### ISSUE TITLE
Add `nock`-like "expectations" to mocks

### ISSUE THREAD

**Issue by SimenB** [nodejs/undici#1002]
## This would solve...

Currently migrating from `nock` based tests to using `undici`'s built-in mocks (thank you for including those!). Our tests currently assert that no mocks that were set up was not called. We do this via checking `nock.isDone()` and sometimes `nock.activeMocks().length === 0`. `nock` ships with a few of these they call "expectations", see https://github.com/nock/nock/blob/main/README.md#expectations.

I like being able to verify we have called all the mocks we set up, and nothing is dangling. Extra useful if using `times()` to ensure we've actually hit the endpoint the number of times expected

## The implementation should look like...

Not sure which of them makes sense to add, but `pendingMocks` and `activeMocks` would be nice (as `isDone()` is basically `pendingMocks().length === 0`).

I don't really have an opinion if it should be added to a `MockScope` or to `MockAgent` or something else.

## I have also considered...

Deleting the assertions when migrating, or trying to count in `headers` callback or some such.

## Additional context

N/A

**Comment by mcollina** [comment]
This is actually a good feature to add. Would you like to send a PR?

**Comment by SimenB** [comment]
Cool! I'll see if I can find the time this weekend or next week 🙂 But just to make sure the design is _somewhat_ ready:

This is nock's implementation:
https://github.com/nock/nock/blob/83131b796e2e1ca16bc9563c1aea4555d7da5162/lib/scope.js#L138-L170

Their docs says that "You probably don't need to use this" about `activeMocks()` and the `isDone` and `done` is just `pending().length === 0` with an `assert` for `done`, so I guess we just need `pendingMocks()`?

And `pendingMocks()` would then return any interceptors not used (or used up in the `times` case), plus any persisted ones? Or should we skip persisted as longs as they're called at least once (like `nock` does)?

In addition, some way of removing and interceptor would be nice - that way if we we can make sure one test doesn't affect any other by clearing any interceptors between tests. For `nock` we used `nock.cleanAll()` - I guess here it makes sense for an `Interceptable` (`MockAgent` & `MockPool`) to clear any? Or should that be on `MockAgent` which is where `enableNetConnect` is etc.?

**Comment by SimenB** [comment]
Cool, I'll go for some exploratory approach then and see where we land 👍
