### ISSUE TITLE
Prioritize `host` header

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#1006]
https://www.rfc-editor.org/rfc/rfc7230.html#section-5.4

>    Since the Host field-value is critical information for handling a
>    request, a user agent SHOULD generate Host as the first header field
>    following the request-line.

Should we do this?

**Comment by mcollina** [comment]
I _thought_ we were doing this already.

**Comment by szmarczak** [comment]
`connection` is actually first

https://github.com/nodejs/undici/blob/d8b3f35b8e46d3eb471e06ddcf1727b6aa01eefa/lib/client.js#L1416-L1426

**Comment by ronag** [comment]
SGTM

**Comment by szmarczak** [comment]
Will send a PR.
