### ISSUE TITLE
Support incorrect deflate content encoding that browser is supporting

### ISSUE THREAD

**Issue by heroboy** [nodejs/undici#1019]
Look at the code. 
1. Use the `deflateRawSync` is not conform to the http standard. But most browser can correctly open it.
2. The error `AboutError` is not clearly. 
3. I have a question. Why `undici.request` not support `deflate` encoding?

```js
const zlib = require('zlib');
const http = require('http');
const undici = require('undici');
let server = http.createServer((req, res) =>
{
	console.log('request');
	res.writeHead(200, { 'Content-Type': 'text/plain', 'content-encoding': 'deflate' });
	res.end(zlib.deflateRawSync('abc'));
	//res.end(zlib.deflateSync('abc'));
});
server.listen(8989, '0.0.0.0', async function ()
{
	try
	{
		let resp = await undici.fetch('http://127.0.0.1:8989');
		let text = await resp.text();
		console.log(text);
	}
	catch (e)
	{
                //AbortError: The operation was aborted
		console.log('request error');
		console.log(e);
	}
});
```

**Comment by ronag** [comment]
PR welcome

**Comment by ronag** [comment]
The `AbortError` seems like a bug. Should probably be another error.

**Comment by heroboy** [comment]
chrome code that inflecting the data:

https://source.chromium.org/chromium/chromium/src/+/main:net/filter/gzip_source_stream.cc;l=134

**Comment by szmarczak** [comment]
I'm -1 on this one. https://datatracker.ietf.org/doc/html/rfc7230#section-4.2.2

> The "deflate" coding is a "zlib" data format
> [...]
> Note: Some non-conformant implementations send the "deflate"
> compressed data without the zlib wrapper.

**Comment by heroboy** [comment]
But can we just add a flag, just like the `strictContentLength`.

**Comment by ronag** [comment]
@mcollina wdyt? node-fetch has support for this https://github.com/node-fetch/node-fetch/blob/8b54ab4509b541dadcd2d66aa5cf0995ad54ac15/src/index.js#L258-L270

**Comment by mcollina** [comment]
I think those http servers are still around, so we should unfortunately support it.

I would mark this as "good first issue", so if somebody needs this they know they can implement it.

**Comment by edward0414** [comment]
This issue is the same as the one linked below.
https://github.com/nodejs/undici/issues/2128

**Comment by Uzlopak** [comment]
This can be closed. I had a wrong issue linked with my PR #2650
