### ISSUE TITLE
Abort request with dispatch()

### ISSUE THREAD

**Issue by RuralDependencies** [nodejs/undici#1028]
It seems that Dispatch does not support a field signal (In order to use new AbortController()), any plan to implement it?
Thanks everyone.

**Comment by mcollina** [comment]
I don't see why now.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ronag** [comment]
I'd prefer to keep dispatch simple...

**Comment by RuralDependencies** [comment]
I don't have the actual talent to implement it so I'll pass, thank you anyway. I'll find a different way to cancel using dispatch
