### ISSUE TITLE
missing dependency `stream` ?

### ISSUE THREAD

**Issue by simone-sanfratello** [nodejs/undici#1029]
More a question than an actual bug, looks like "stream" library is needed consuming streams, but it's not listed in dependencies

https://github.com/nodejs/undici/search?q=stream%2Fweb

Should be added to deps?

**Comment by ronag** [comment]
stream is a core node library

**Comment by simone-sanfratello** [comment]
why `require('stream/web').ReadableStream` instead of `require('stream').ReadableStream` ?

**Comment by ronag** [comment]
Because `ReadableStream` lives under `stream/web`.

**Comment by simone-sanfratello** [comment]
I think the issue is that 'stream/web' is available only on v.16

**Comment by ronag** [comment]
https://github.com/nodejs/undici#undicifetchinput-init-promise

> Only supported on Node 16+.
