### ISSUE TITLE
highWaterMark adjustment for dispatch

### ISSUE THREAD

**Issue by RuralDependencies** [nodejs/undici#1037]
Good evening,

It seems that adding the property highWaterMark when doing a .dispatch doesn't change anything.

**Comment by ronag** [comment]
What do you expect that would do?

**Comment by RuralDependencies** [comment]
On HTTP (node) it can be specified
https://github.com/nodejs/node/issues/30107 - it has been implemented following this issue and chunks can be received in a different way.

**Comment by ronag** [comment]
Doing that on a request basis would not be possible anyway. What you can do is to provide a `connect` option that creates connection with your preferred highwaterMark.

**Comment by RuralDependencies** [comment]
Ok thank you @ronag
