### ISSUE TITLE
Improve `FormData` constructor error message

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#1043]
From https://github.com/nodejs/undici/pull/1042#discussion_r713430349

https://github.com/nodejs/undici/blob/b0ec94d1a4b679b212e441ef332eb1337ad92dbd/lib/fetch/formdata.js#L9-L17

https://github.com/nodejs/undici/blob/b0ec94d1a4b679b212e441ef332eb1337ad92dbd/lib/fetch/util.js#L287

There might be a use case where [`jsdom`](https://github.com/jsdom/jsdom) can be used 🤔
Should we change the error message to something like below to prevent confusion?

```
Failed to constructor 'FormData': parameter 'form' is unsupported
```

**Comment by ronag** [comment]
I was just trying to make it so that the errors are exactly the same as in chrome

**Comment by szmarczak** [comment]
Sure, but that might be confusing for jsdom users. I don't mind waiting to gather more feedback though.

**Comment by ronag** [comment]
Can we detect if it’s a jsdom html form object?
