### ISSUE TITLE
Fetch streaming zip file

### ISSUE THREAD

**Issue by ruslan-khomiak** [nodejs/undici#1046]
## Bug Description

I have a request to get a file as a zip stream
But when using undici-fetch, I get a success response, but there is no stream in the body

## Reproducible By

You need to try to get the file as a zip stream

## Expected Behavior

Get stream without undefined

## Logs & Screenshots

https://prnt.sc/1t8iszd

## Environment

Node 16.9.1, macOS Catalina

**Comment by ronag** [comment]
Do you have a repro?

**Comment by ruslan-khomiak** [comment]
> Do you have a repro?

Unfortunately, I can't provide a reproduction example because this is not a public request.
Here is the [documentation](https://developer.walmart.com/api/us/mp/reports#operation/getReconReport) for the request

**Comment by ronag** [comment]
Sorry. It's difficult to help here without more information.

**Comment by KhafraDev** [comment]
This is just an issue with how the Response is inspected:

```ts
import { fetch } from 'undici';
import AdmZip from 'adm-zip';

const res = await fetch('https://eternallybored.org/misc/wget/releases/wget-1.21.1-1-win64.zip');
const buffer = await res.arrayBuffer();

console.log(res)

const zip = new AdmZip(Buffer.from(buffer));
const files = zip.getEntries();

for (const file of files) {
    console.log(file.entryName);
}
```
![image](https://user-images.githubusercontent.com/42794878/134375529-96d80a2f-c670-4928-86d6-63468f01fe7b.png)
Even though it shows as undefined, everything works correctly

**Comment by ronag** [comment]
We could probably add a custom inspect m.

**Comment by ronag** [comment]
I'm closing this. Feel free to open a PR with custom inspect.
