### ISSUE TITLE
Document: showcase for how to custom mock response

### ISSUE THREAD

**Issue by atian25** [nodejs/undici#1049]
How to access original request and headers at a mock interceptor ?

like nock:

```js
const scope = nock('http://www.google.com')
  .get('/cat-poems')
  .reply(function (uri, requestBody) {
    console.log('path:', this.req.path)
    console.log('headers:', this.req.headers)
    // ...
  })
```

**Comment by mcollina** [comment]
I think we really need better docs for the mock support. I think these should be easily covered in our docs and they are no there.

cc @jonnydgreen

**Comment by jonnydgreen** [comment]
Agreed! I'm available to help out with this next week if that works :)

**Comment by mandaputtra** [comment]
I can help with this, do you want to place it on best practice or just extend the [MockAgent](https://github.com/nodejs/undici/blob/main/docs/api/MockAgent.md), MockClient, etc?

**Comment by mcollina** [comment]
up to you!

**Comment by rubiagatra** [comment]
I think this issue should be solved 🙌  @mcollina , Good job @mandaputtra
