### ISSUE TITLE
Test errors with Node.js 17

### ISSUE THREAD

**Issue by targos** [nodejs/undici#1061]
See CITGM result: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2778/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/undici_v4_7_2/

**Comment by targos** [comment]
Some are also due to the OpenSSL update:

```
 # Subtest: Client using valid client certificate
         1..5
         not ok 1 - error:0A00018E:SSL routines::ca md too weak
           ---
           origin:
             at:
               line: 65
               column: 13
               file: node:internal/tls/secure-context
```

**Comment by mcollina** [comment]
I cannot reproduce that locally using -rc.1.

**Comment by mcollina** [comment]
The OpenSSL error looks suspicious and to be investigated. It does not reproduce on the two machines I have available (Mac and Linux)
