### ISSUE TITLE
Cannot destructure `new undici.Client()`

### ISSUE THREAD

**Issue by trevh3** [nodejs/undici#1096]
## Bug Description
```
const { request } = new undici.Client('http......');
request({...})
```

fails with `UnresolvedPromiseWarning: Cannot read property 'dispatch' of undefined. `

## Expected Behavior

I expected to be able to destructure Client.

## Environment
macOS 11.6, Intel Mac, nodeJS 12.22.7 & nodeJS 16.11.1

**Comment by ronag** [comment]
That's expected. You cannot destructure like that in javascript.
