### ISSUE TITLE
Potentially incorrect validation of 204 response body?

### ISSUE THREAD

**Issue by vlovich** [nodejs/undici#1102]
## Bug Description

If returning a 204 Response object, undici will throw an exception if body is the empty string rather than null. I'm not 100% clear on if this is the correct behavior.

## Reproducible By

```
> npm i -D undici
> npx node
const undici = await import('undici')
new undici.Response('', {status: 204})
```

## Expected Behavior

No exception is thrown.

## Logs & Screenshots

```
Uncaught TypeError: Response with null body status cannot have body
    at new Response (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/undici/lib/fetch/response.js:160:15)
```

## Environment

Node 16.11.1 on Arch.

**Comment by szmarczak** [comment]
This works as expected. `204` is no content, therefore you need to provide `null` instead of an empty string.

**Comment by ronag** [comment]
![Screenshot 2021-11-19 at 18 44 51](https://user-images.githubusercontent.com/3065230/142667747-4f32ede5-9d0c-49d3-a648-ee2898d8332f.png)

Yep, same failure in Chrome.

**Comment by thw0rted** [comment]
Under Node 18, `new Response('', {status: 204})` throws

> Invalid response status code 204

This isn't a great error message -- the problem isn't that 204 is an "invalid code", it's that you can't provide a body when using it, like the helpful message from this Chrome screenshot says.

Should I open a new issue for this?
