### ISSUE TITLE
some kind of dump helper?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1117]
This is a common helper function we use when we don't care about the content body. I'm thinking it would be nice to somehow integrate with out API?

```js
async function dump (res) {
  let limit = 1e6
  try {
    for await (const chunk of res.body) {
      limit -= Buffer.byteLength(chunk)
      if (limit < 0) {
        return
      }
    }
  } catch {
    // Do nothing
  }
}
```

This is better than `res.on('error', () => {}).destroy()` since it lets the socket stay alive.

**Comment by ronag** [comment]
Another way to achieve similar behavior with `res.on('error', () => {}).destroy()` would be that undici internally tries to read more of the response before closing the socket in order to try and detach the socket from the response body before destroy.

**Comment by mcollina** [comment]
This will be helpful, yes!

**Comment by ronag** [comment]
@mcollina How do you think it should look? Another method `BodyReadable`, i.e. `BodyReadable.dump`?

**Comment by mcollina** [comment]
Yes exactly. I would make the limit configurable.
