### ISSUE TITLE
Incompatibility between undici fetch and MockAgent

### ISSUE THREAD

**Issue by bienzaaron** [nodejs/undici#1121]
## Bug Description

When using fetch and attempting to intercept requests via the MockAgent, the object passed to the body request matcher is an async generator rather than a string as documented [here](https://undici.nodejs.org/#/docs/api/MockPool?id=parameter-mockpoolinterceptoptions). When using request, the behavior is as documented.

### Code
```
import { request, fetch, MockAgent, setGlobalDispatcher } from "undici";

export const mockAgent = new MockAgent();
setGlobalDispatcher(mockAgent);

const mockPool = mockAgent.get("http://localhost:3000");

mockPool.intercept({
    path: "/test", method: "POST", body: (value) => {
        console.log(value);
        return value === "request body";
    }
}).reply(200, { success: true }).persist();

(async () => {
    try {
    await fetch("http://localhost:3000/test", { method: "POST", body: "request body" });
    console.error('fetch succeeded');
    } catch(err) {
        console.error('fetch failed');
        console.error(err);
    }
})().then(async () => {
    try {
        await request("http://localhost:3000/test", { method: "POST", body: "request body" });
        console.error('request succeeded');
        } catch(err) {
            console.error('request failed');
            console.error(err);
        }
});

```

## Expected Behavior

MockAgent should behave identically in both request and fetch.

### Console output from above code
```
Object [AsyncGenerator] {}
(node:47299) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
fetch failed
TypeError: fetch failed
    at Object.processResponse (/Users/me/undici-bug/node_modules/undici/lib/fetch/index.js:176:23)
    at fetchFinale (/Users/me/undici-bug/node_modules/undici/lib/fetch/index.js:720:17)
    at EventEmitter.mainFetch (/Users/me/undici-bug/node_modules/undici/lib/fetch/index.js:695:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
request body
request succeeded
```
## Environment

mac OS 10.15.7
Node 16.13.1

**Comment by mcollina** [comment]
Thanks for reporting. In theory this should work :/

@ronag have you got any hint on how fetch could be hitting the dispatcher with different parameters than request?

**Comment by ronag** [comment]
fetch converts it to a async iterable in order to follow the spec.

**Comment by mcollina** [comment]
The routing to the mock happens before the body even exists, it's likely something in the arguments passed to dispatch.

**Comment by ronag** [comment]
> The routing to the mock happens before the body even exists, it's likely something in the arguments passed to dispatch.

I don't follow. 

The body is created:

https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L1450-L1503

and then dispatched to the mock agent https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L1618

**Comment by ronag** [comment]
@mcollina this looks more like a bug in the mock code... which I unfortunately don't fully understand atm.
