### ISSUE TITLE
Add `web-streams-polyfill`, so node14 can use `undici.fetch`

### ISSUE THREAD

**Issue by loynoir** [nodejs/undici#1136]
## This would solve...

node14
```js
> require('undici').fetch
undefined
```
node16
```js
> require('undici').fetch
[AsyncFunction: fetch]
```

## The implementation should look like...

```js
import { ReadableStream } from "web-streams-polyfill/ponyfill";
const readable = new ReadableStream();
```

**Comment by mcollina** [comment]
would you like to work on this? It  might be quite an endeavor considering certain edge cases of fetch.

**Comment by loynoir** [comment]
<details>
  <summary>require hook</summary>
  <p>
 
```js
const { addHook } = require('pirates')

try {
  require('stream/web')
} catch {
  const revert = addHook(
    (code, _filename) => (
      `var {AbortController} = require('node-abort-controller')\n`
      + code.replace(/stream\/web/g, 'web-streams-polyfill/ponyfill')
    ),
    {
      exts: ['.js'],
      ignoreNodeModules: false,
      matcher: filename => filename.includes('undici')
    }
  );
}
```
  </p>
</details>

Just try a require hook using `node-abort-controller` and `web-streams-polyfill/ponyfill`, got

```txt
cause: TypeError: context.dispatcher.dispatch is not a function
```

No idea what is going on. 😔

---

My use case is constructing a `Response` from `ReadableStream`. This require hook works.

**Comment by Kikobeats** [comment]
It's a bit strange to me that undici requires Node.js => 12 but in case you use Node < 16 then `Response`, `Request`, `fetch`, etc are undefined.

@mcollina do you will accept a PR to leverage into `web-streams-polyfill/ponyfill` instead to `node:web/stream` ?

In that way, the library will be ready to be used at Node 12 & Node 14 as well.

**Comment by mcollina** [comment]
I'm opposed to that, it would make maintaining this harder. If you want to use fetch, you'd have to use Node v16. It's LTS.

**Comment by jimmywarting** [comment]
What if we could provide our own streaming library?

```js
class Undici extends Map {}
module.exports = new Undici()

// later:
undici.set('ReadableStream', ReadableStream)
undici.set('WritableStream', WritableStream)
undici.get('ReadableStream')
```

**Comment by mcollina** [comment]
Unfortunately we discovered that in order to implement fetch() you need access to certain details of WHATWG Streams that are not public (disturbed, GC, etc). Making the stream lib pluggable would result in a significant increase in maintenance burden: we need folks to focus on features, spec compliancy and docs.

**Comment by jimmywarting** [comment]
Roger that
