### ISSUE TITLE
Can't use the ProxyAgent with proxy on HTTP calling HTTPS url

### ISSUE THREAD

**Issue by ra100** [nodejs/undici#1148]
## This would solve support for proxies using only HTTP

In the company, we have proxy that needs to be called with http://ourproxy.company.com:1234, but if you request a url with https, it needs to be sent as https request. But here, with the ProxyAgent, I can't force the protocol to be used.
Loading (using Undici.request) http://something.xyz/img.png is fine, but when loading https://whatever, I get an error from proxy about mismatching hosts actually:

> RuleName: (HTTPS) Block Mismatched hosts in HTTPS Tunnel

## I have also considered...

I've tried to modify this part of `proxy-agent.js` and removed the `opts.origin +`, and proxy started to work. I'm 100% sure it's not right, and it's more of a hack.

```js
  dispatch (opts, handler) {
    const { host } = url.parse(opts.origin)
    return this[kAgent].dispatch(
      {
        ...opts,
        origin: this[kProxy].uri,
        path: opts.path, // removed the opts.origin + opts.path
        headers: {
          ...opts.headers,
          host
        }
      },
      handler
    )
  }
```

## Additional context

Is it possible to specify, the dispatcher to use HTTPS protocol even when calling http://.... url?
And I've noticed, that in the `buildProxyOptions` is `protocol: opts.protocol || 'https'` but didn't see it being used anywhere. And `protocol` is not in the opts type of ProxyAgent.

**Comment by mcollina** [comment]
I've never encountered such a weird setup. Anyway, I don't think why this can't be supported. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ra100** [comment]
I'd gladly do a PR, I just need to figure out the proper way to make this work.
And also how to simulate this weird setup in tests :)

**Comment by mcollina** [comment]
go for it!

**Comment by ra100** [comment]
So I have been so slow, that many changes happened, and this issue is not occuring again. Thanks to whomever changed how ProxyAgent works ❤️
