### ISSUE TITLE
HTTP Proxy with undici and HTTPDataSource

### ISSUE THREAD

**Issue by lordjim1985** [nodejs/undici#1153]
Hi,

I'm using HTTPDataSource that uses undici. 
I'm trying to make it work through a proxy.

I've tried to use:

`const proxyAgent = new ProxyAgent({ 
    uri: '0.0.0.0:3128',
    protocol: 'http',
    }
);
setGlobalDispatcher(proxyAgent);`

The problem is, it does not seem to work. Could You provide any suggestions?

I'm using HTTPDataSource the recommended way based on the manual provided here:
https://github.com/StarpTech/apollo-datasource-http

**Comment by mcollina** [comment]
cc @starpttech - I'm unsure how to proceed as it is your module.

**Comment by lordjim1985** [comment]
I'm attempting to use a proxy for a Pool that I'm creating and pass the ProxyAgent in options. Maybe this will help.
`const pool = new Pool(url);
const requestOptions = { ...someOptions };
pool.request(requstOptions);
`

**Comment by suil** [comment]
I confirm this is a bug. when Pool is used, it's not picking up `{ ..., dispatcher: new ProxyAgent("...")}`, or `setGlobalDispatcher(proxyAgent)`

**Comment by RafaelGSS** [comment]
I think this is the same discussion as in https://github.com/nodejs/undici/issues/1270 or I'm missing something?

**Comment by umakanth-fmr** [comment]
I can confirm the bug. It does not work when Pool is used.
