### ISSUE TITLE
Fetch's request.integrity is coerced to the string "undefined" when undefined is explicitly passed

### ISSUE THREAD

**Issue by jimsimon** [nodejs/undici#1176]
## Bug Description

The following code in `makeRequest` coerces `undefined` to the string `"undefined"` when it's explicitly passed to the fetch options:
```
    // 23. If init["integrity"] exists, then set request’s integrity metadata to it.
    if ('integrity' in init) {
      request.integrity = String(init.integrity)
    }
```

## Reproducible By

```
fetch('https://github.com', { integrity: undefined })
```

## Expected Behavior

Undefined is not coerced to a string

## Environment

Arch Linux, Node 16, server-side call (not coming from a browser)

### Additional context

I ran into this while implementing a custom `fetcher` function for Apollo Client. Because the typings for browser/native fetch don't match unidci's fetch, I had to manually map some parameters over. It's pretty easy to workaround this by testing for a falsy value and passing an empty string if needed (`{ integrity: req.integrity || ''}`), but it did result in a pretty cryptic error message:
```
Unknown server error    Error: fetch failed
```

In my case, I believe my need to map stuff manually between the two implementations is actually related to https://github.com/nodejs/undici/issues/1172.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jimsimon** [comment]
Sure, I'll whip something up!
