### ISSUE TITLE
Body mixins throw `TypeError: unusable`

### ISSUE THREAD

**Issue by shellscape** [nodejs/undici#1208]
## Bug Description

Calling `await body.text()` immediately following `await body.json()` throws `TypeError: unusable`.

I'm not entirely sure this is a bug. I tried to navigate the fetch spec on this, but maybe I'm just foggy today and didn't grok.

## Reproducible By

When using `request` and making a successful request with `200` response, I'm performing an `await body.json()`. If for some reason the resulting object is falsy or doesn't contain properties I expect, I'm attempting to call `await body.text()` so I can get an unfettered raw body to pump out to logs for later examination.

## Expected Behavior

I was expecting the body in plain text. 

## Logs & Screenshots

Here's the code I've been trying to run, of course missing additional context from the encompassing file (which I cannot share).

```
      const registryUrl = `https://skimdb.npmjs.com/registry/${encodeURIComponent(change.id)}`;
      const { body, statusCode } = await request(registryUrl, options as any);

      if (statusCode !== 200 && statusCode !== 404) {
        throw new AssertionError({
          message: `Registry Request Error → url: ${registryUrl}, statusCode: ${statusCode}`
        });
      }

      const pkg = (await body.json()) as NpmPackage;

      if (!pkg || !pkg.name) {
        const text = await body.text();
        log.warn('Package or Package Name empty. Skipping. Message body:', text);
        continue;
      }
```

## Environment

MacOS/AWS Linux
Node 14@latest

**Comment by ronag** [comment]
This is expected behavior. You cannot consume the body twice.

**Comment by shellscape** [comment]
@mcollina a bit quick on the trigger there. for the uninitiated, I would have enjoyed some more conversation about this before closing.

@ronag what's the preferred method here in order to enable that? is there a reset? should we pipe into another stream? should we not rely on the JSON mixin and only use the text mixin?

there are a lot of folks out there that are not intimately familiar with the spec and how things should work, additionally that's not documented at all in this repository. so that's leaving people in the dark, and some thorough discussion around that would absolutely help the community

**Comment by mcollina** [comment]
> @mcollina a bit quick on the trigger there. for the uninitiated, I would have enjoyed some more conversation about this before closing.

You are right, sorry about this. We should document it better.

> @ronag what's the preferred method here in order to enable that? is there a reset? should we pipe into another stream? should we not rely on the JSON mixin and only use the text mixin?

I would call .text() and the call JSON.parse() on it.
