### ISSUE TITLE
Raw Header support

### ISSUE THREAD

**Issue by chasetec** [nodejs/undici#1213]
Can we get raw header support in the high level client APIs? The node http(s) clients support it and migrating to undici isn't practical if there is a dependency on having raw header support. Some origins incorrectly depend on header case. If there is a header that I need to return to the origin on subsequent requests I can't know what case the origin used right now.

Not picky on how its supported. A new rawHeaders property in the promised responses....

````
    const {
        statusCode,
        headers,
        rawHeaders,
        trailers,
        body
    } = await undici.request('http://url');
````

Or an option in DispatchOptions that would change the existing headers value.

````
    const {
        statusCode,
        headers,
        trailers,
        body
    } = await undici.request('http://url', {'headersPreserveCase': true});
````

The rawHeaders route might be easier since it could be an array with duplicates.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by MoLow** [comment]
@chasetec @mcollina I'l take a look into this
