### ISSUE TITLE
Fetch options do not allow explicit `undefined`

### ISSUE THREAD

**Issue by chlonel** [nodejs/undici#1225]
## Bug Description

It's hard to say for sure that this is a bug, but it feels like unintended behavior, so I'm reporting it as a bug.

Passing `redirect: undefined` as an option of `fetch` will throw an error.
At the time of executing the following code, `init.redirect` may be assigned `undefined`, which will be considered as an invalid value.
This does not only happen with `redirect`, but also with other options such as `method` and `cache`.

```javascript
// 22. If init["redirect"] exists, then set request’s redirect mode to it.
if ('redirect' in init) {
  request.redirect = init.redirect
  if (!requestRedirect.includes(request.redirect)) {
    throw new TypeError(
      `Failed to construct 'Request': The provided value '${request.redirect}' is not a valid enum value of type RequestRedirect.`
    )
  }
}
```

## Reproducible By

```javascript
fetch("https://github.com", { redirect: undefined });
// TypeError: Failed to construct 'Request': The provided value 'undefined' is not a valid enum value of type RequestRedirect.
```

## Expected Behavior

If `undefined` is passed, it will simply be ignored and the default value will be assigned.
Although `undefined` should not be passed by right, it is useful if it works as well, since Google Chrome and node-fetch implementations do not throw errors.
## Environment

Manjaro 21.2.1
Node.js v16.13.2

**Comment by ronag** [comment]
What does chrome do?

**Comment by ronag** [comment]
Good spot. I think we should replace `x in init` with `init[x] != null` everywhere. Feel free to open a PR.

**Comment by chlonel** [comment]
There is a difference between Chrome and node-fetch.
Chrome does not allow `redirect: null`, while node-fetch ignores it as well as `undefined`.
I think we should only allow `undefined` if we want to be compatible with Chrome, but which one is better?

**Comment by mcollina** [comment]
What does the spec says?

**Comment by mcollina** [comment]
I would treat a field with undefined value and no field in the same way.

**Comment by ronag** [comment]
Also I think Chrome treats `null` the same way as well...

**Comment by chlonel** [comment]
When I run the following code in the console, it throws an error.
Unfortunately, I don't think it is treated the same way.
```javascript
fetch('https://github.com', { redirect: null })
// Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to read the 'redirect' property from 'RequestInit': The provided value 'null' is not a valid enum value of type RequestRedirect.
//     at <anonymous>:1:1
```

I understand that "chrome" is the Google Chrome browser, am I correct?

**Comment by ronag** [comment]
As an unofficial rule we try to match Chrome's behavior, including the actual error message.

**Comment by chlonel** [comment]
I see.
I'll fix it to only allow `undefined`.
