### ISSUE TITLE
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by hansott** [nodejs/undici#1235]
## Bug Description

When using undici 4.14.1 in jest 27.5.1

`import { request } from "undici";`

(not directly imported in test file)

at lazyllhttp (node_modules/undici/lib/client.js:421:49)

`mod = await WebAssembly.compile(Buffer.from(require('./llhttp/llhttp.wasm.js'), 'base64'))`

and code is transpiled with `ts-jest`

## Expected Behavior

The error is not logged.

## Logs & Screenshots

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
  at lazyllhttp (node_modules/undici/lib/client.js:421:49)
```

## Environment

macOS Big Sur 11.6.2
Node.js v16.0.0

**Comment by mcollina** [comment]
Would you like to send a PR that moves the requires to the top of the file and states that we have to double the amount of memory that is loaded on the process because of Jest?

On a side note, I would actually recommend not to use Jest in any Node project.

**Comment by hansott** [comment]
@mcollina A bit swamped with work right now but I might do it a bit later this week, fine for you?

Jest has been treating us good :)

Why's that, got a link to a blogpost or tweet? Curious. What's the alternative?

**Comment by shalvah** [comment]
> Why's that, got a link to a blogpost or tweet? Curious. What's the alternative?

@mcollina has [tweeted a lot](https://twitter.com/search?q=from%3Amatteocollina%20exclude%3Areplies%20Jest&t=sfiCJl_uI5pYnmZyaG2aYA&s=09) about this, but here are a few summary links:

Performance: https://github.com/covidatlas/coronadatascraper/pull/481

Redefining Node.js globals, creating a whole new environment: https://github.com/facebook/jest/issues/2549

And more:  https://github.com/serverless/serverless/pull/6517


Jest is generally very convenient to use...until it's not.

**Comment by hansott** [comment]
Thanks! Looking forward to Node's builtin test runner. ❤️
