### ISSUE TITLE
undici.fetch does not append url fragments (url.hash)

### ISSUE THREAD

**Issue by jennyEckstein** [nodejs/undici#1245]
## Bug Description

At the moment undici.fetch does not support GET requests with fragments

## Reproducible By

See repository to reproduce [here](https://github.com/jennyEckstein/undici.fetch-url-hash)

## Expected Behavior

undici.fetch should be able to handle fragments in url.
Fix: add `url.hash` [here](https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L1811)

## Logs & Screenshots

See repo ☝️

## Environment

macOS Catalina 10.15.7
Node v16.10.0

### Additional context
I would be happy to open PR.

**Comment by ronag** [comment]
PR welcome

**Comment by ronag** [comment]
I think we have the same problem in all undici api's

**Comment by targos** [comment]
I thought that the fragment should not be sent to the remote server?

**Comment by MoLow** [comment]
taking a look

**Comment by ronag** [comment]
> I thought that the fragment should not be sent to the remote server?

I actually don't know. Anyone know what the spec says?

**Comment by jennyEckstein** [comment]
> I thought that the fragment should not be sent to the remote server?

@targos I think you are right, I found this in wiki.
> Clients are not supposed to send URI fragments to servers when they retrieve a document, and without help from a local application (see below) fragments do not participate in [HTTP](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) redirections.
I am testing another approach I can take.

**Comment by jennyEckstein** [comment]
Upon further investigation, I can confirm that undici.fetch works correctly. Server receives path with no fragment (as it is supposed to). The issue is strictly related to the use of MockAgent and the way it stores and compares intercepted path [here](https://github.com/nodejs/undici/blob/main/lib/mock/mock-utils.js#L16). The values must be strictly equal and do not account for stripping fragments or query strings. This function needs to be modified to behave just like it would with real server.

**Comment by galvez** [comment]
I think this interpretation is somewhat dubious. In the Fetch standard, it says it should with a work a URL as per its definition, and its definitions [includes fragments](https://url.spec.whatwg.org/#concept-url). So maybe the URI spec is outdated in relation to the Fetch spec? cc @ronag

**Comment by ronag** [comment]
What does Chrome do?

**Comment by galvez** [comment]
Chrome's fetch() doesn't send #hash indeed. I think we can safely close this then.

**Comment by mcollina** [comment]
I think a better solution to this problem is to remove the hash from the `intercept` call, e.g. make behave https://github.com/jennyEckstein/undici.fetch-url-hash/blob/996b50f06ad6a2fc7e2e65f4e4eaaab814914300/index.js#L15 like  `mockPool.intercept({ method: "GET", path: "/test?foo=bar"` or possibly make it throw if there is an hash specified.

**Comment by killroy42** [comment]
Not sure if this is related, but I was chasing my tail for a while until I realized that undici stripped the hash from a redirect request, unlike node-fetch. So, for example retrying a tinyurl redirect target location with hash, will return the url with the hash stripped from the fetch call.
