### ISSUE TITLE
Normalize BalancedPool addUpstream / removeUpstream

### ISSUE THREAD

**Issue by mnutt** [nodejs/undici#1250]
## This would solve...

If I call `pool.addUpstream("http://localhost:80")`, I'd expect to later be able to call `pool.removeUpstream("http://localhost:80")` using the same URL but it silently fails and the upstream continues to exist.

The issue is that `addUpstream` passes the URL through to the Pool constructor which uses `parseOrigin` to normalize it, while `removeUpstream` just looks up the pool directly using the origin URL passed in. In the above case, the passed string is `http://localhost:80` while the normalized string is `http://localhost`.

Additionally, while `addUpstream` has a [check to ensure we don't add the same backend twice](https://github.com/nodejs/undici/blob/main/lib/balanced-pool.js#L52), this check is bypassed when the  passed URL and normalized origin do not match.

## The implementation should look like...

We might consider having `addUpstream` and `removeUpstream` call `parseOrigin` to normalize the URL.

## I have also considered...

One potential downside to this approach would be if someone was setting a `kFactory` that expected non-normalized origin URLs. I can't think of a great way to mitigate that, though I also think undici doesn't intend to have factories modify origins given the implementation. One (probably undesirable) way might be to store the `rawOrigin` property on the Pool and use that for upstream deduplication/removal.

This issue isn't blocking my use case; knowing how `addUpstream` and `removeUpstream` are implemented, I can call `parseOrigin` myself as a workaround. It was just unexpected that the nodes were not removed and no warnings/errors were returned.

## Additional context

I was running into this issue while trying to pair an undici BalancedPool with service discovery using the Consul node client. This involves keeping a list of upstreams, periodically polling Consul for upstreams added/removed, calculating the delta, and calling `addUpstream`/`removeUpstream`. This initially appeared to be working as expected but testing showed that upstreams were not removed properly.

If this change sounds acceptable I would be happy to open a PR.

**Comment by mcollina** [comment]
Send the PR over!
