### ISSUE TITLE
Add Kerberos support for `request`

### ISSUE THREAD

**Issue by Lonli-Lokli** [nodejs/undici#1261]
Add Kerberos support for `request`

## The implementation should look like...

similar to `fetch`

**Comment by mcollina** [comment]
I don't think we will ever implement something so
specific here. However you could easily build this on top of undici dispatch API.

**Comment by Lonli-Lokli** [comment]
@mcollina can you point to any sample please?

**Comment by mcollina** [comment]
Check out our fetch implementation or the old undici-fetch project
