### ISSUE TITLE
Drop esbuild as a devDep as it's not supported on AIX

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#1267]
## Bug Description

Currently undici fails at CITGM because it can't run esbuild on AIX:

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2862/nodes=aix72-ppc64/testReport/junit/(root)/citgm/undici_v4_15_0/

cc @targos - we added this to support bundling for Node.js, right? Maybe we can fall back to webpack or browserify?

**Comment by targos** [comment]
Can we move it to optionalDependencies instead? I don't think we need to support bundling on AIX

**Comment by mcollina** [comment]
Well it's not even an optionalDependency, because nom will try to install optionalDependencies alongside dependencies.

How about just using npx for running those build scripts?
