### ISSUE TITLE
Mocks should allow to match headers that are meant to be missing

### ISSUE THREAD

**Issue by panva** [nodejs/undici#1269]
## This would solve...

Being able to match only when a given header is not present.

## The implementation should look like...

I dunno, ...
- prefix the header name with a unique symbol outside the range of allowed header names to indicate it's meant to be missing in a to be matched request?
- special symbol instead of a string|regex|function as a matcher to be provided
- function matcher would get undefined passed as a value?

## I have also considered...

I've tried to match the missing header with a function that checks that the value is undefined but the matcher doesn't even run because the header is not in the request.

**Comment by mcollina** [comment]
Testing for absence is a tricky beast. Would you like to send a PR for this?

I'd more leaning to 

> special symbol instead of a string|regex|function as a matcher to be provided


but I'm good with whatever you'd like to propose.

**Comment by panva** [comment]
> Would you like to send a PR for this?

If noone else picks it up in a week or so I will.
