### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by minas90** [nodejs/undici#1271]
## Bug Description

Fetch fails with some URLs (after redirect?).

## Reproducible By

`let res = await fetch('https://www.luzernerzeitung.ch/kultur/literatur-im-pool-ld.2260742');`

## Expected Behavior

It should get the URL without any exception. The same code works just fine with 'node-fetch'.

## Logs & Screenshots

```
    at Object.processResponse (node:internal/deps/undici/undici:7081:34)
    at Fetch.fetchFinale (node:internal/deps/undici/undici:7411:21)
    at Fetch.mainFetch (node:internal/deps/undici/undici:7305:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: Error: incorrect header check
      at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
    errno: -3,
    code: 'Z_DATA_ERROR'
  }
}
```

## Environment

macOS 11.6.4, Node v17.6.0

### Additional context

The provided URL redirects and adds `?reduced=true` at the end of the URL:
`https://www.luzernerzeitung.ch/kultur/literatur-im-pool-ld.2260742?reduced=true`
When I run the same code with this redirected URL, it works fine.

I guess a little tweak with the gzip code or redirect logic should fix this.

**Comment by KhafraDev** [comment]
The error occurs at https://github.com/nodejs/undici/blob/d94dc15b089c3093cde1993241ca78830dec8fbd/lib/fetch/index.js#L1868 because we get a `content-encoding` header that is `gzip`.

**Comment by mcollina** [comment]
It seems the actual content is not gzipped.

**Comment by minas90** [comment]
Yeah, before redirect the content size is `142 bytes` and the gzipped size is 2x more. So maybe the server has a check to send the original content if the size is smaller. I think fetch should not get the content before redirect, it's waste of recourses. 

```
➜  ~ curl "https://www.luzernerzeitung.ch/kultur/literatur-im-pool-ld.2260742" --silent --write-out "%{size_download}\n" --output /dev/null                                         
142
➜  ~ curl "https://www.luzernerzeitung.ch/kultur/literatur-im-pool-ld.2260742" --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null 
142
```
```
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
```


After redirect it is gzipped, you can check with `curl`. 

```➜  ~ curl "https://www.luzernerzeitung.ch/kultur/literatur-im-pool-ld.2260742?reduced=true" --silent --write-out "%{size_download}\n" --output /dev/null
323859
➜  ~ curl "https://www.luzernerzeitung.ch/kultur/literatur-im-pool-ld.2260742?reduced=true" --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
66129```

**Comment by mcollina** [comment]
Ah, I understand now. Basically we need to avoid parsing the body for the redirect. Would you like to send a PR?

**Comment by ronag** [comment]
I’m not sure it’s spec compliant to not read the body?

**Comment by targos** [comment]
Chrome, Firefox and Safari all have no issue with the reproduction code and follow the redirection.
Example in Chrome:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2352663/158014903-c5fc9a63-caa2-4519-98a8-213ac4506b13.png">

**Comment by minas90** [comment]
@mcollina I'm still not familiar with the codebase, if you can fix it quickly please go ahead. Otherwise I will push a PR in a few days when I will have some free time.

@ronag It seems like browsers ignore the body when status is 302. It's not even mandatory, maybe only needed for browsers which can't handle redirect?

[https://stackoverflow.com/questions/8059662/http-302-redirect-is-a-message-body-needed](https://stackoverflow.com/questions/8059662/http-302-redirect-is-a-message-body-needed)

**Comment by ronag** [comment]
I think we should read the body but just ignore the content so that we can keep the connection alive.

**Comment by minas90** [comment]
Btw, it's an unlikely scenario, but it's possible to have the same issue with gzip handling, when body size is small and the server has some logic to avoid gzip for small body. For example responses from API calls, such as simply `ok`

**Comment by ronag** [comment]
For non-fetch undici ignores the body. Not sure yet where it goes in fetch.

**Comment by ronag** [comment]
This is actually quite tricky to fix.

**Comment by ronag** [comment]
Going back to the spec:

For e.g. HEAD and CONNECT the spec says:

>   19. If response is not a network error and either request’s method is
>   `HEAD` or `CONNECT`, or internalResponse’s status is a null body status,
>   set internalResponse’s body to null and disregard any enqueuing toward
>   it (if any).

But there is nothing along those lines for redirects. Is this a spec bug? Since Chrome does seem to disregard the body in thise case. @annevk

**Comment by annevk** [comment]
Redirects can have a response body. I don't think it ever ends up being exposed though.
