### ISSUE TITLE
Missing Interceptable type in export ?

### ISSUE THREAD

**Issue by fraxken** [nodejs/undici#1306]
## Bug Description

While working on UT (with TypeScript) for one of our project we were unable to found the `Interceptable` type in the undici export. 

https://github.com/nodejs/undici/blob/main/types/mock-interceptor.d.ts#L88

## Reproducible By

//

## Expected Behavior

Export the Interceptable type.

## Environment

Node.js 16.13.x on Windows 10.

**Comment by fraxken** [comment]
I'm ok to send a PR if maintainer confirm this should be exported :)

**Comment by Uzlopak** [comment]
@nodejs/undici 

I guess we can close this as solved.
