### ISSUE TITLE
[types] `Response.body` does not extend `ReadableStream`

### ISSUE THREAD

**Issue by AlttiRi** [nodejs/undici#1308]
The browser's  [`Response.body`](https://developer.mozilla.org/en-US/docs/Web/API/Response/body) is [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream).

Based on `fetch.d.ts` `Response.body` of `undici` is just  `ControlledAsyncIterable`.

---

The code below is valid and workable.
However, because of `fetch.d.ts` I see the warning in my IDE (IntelliJ IDEA).

```js
const response = await fetch(url);

/** @type {ReadableStream} */
const body = response.body; // Warning: "Initializer type ControlledAsyncIterable is not assignable to variable type ReadableStream"
body.getReader();
```

```js
const response = await fetch(url);

const body = response.body;
body.getReader(); // Warning: "Unresolved function or method getReader()"
```

**Comment by ronag** [comment]
Sounds like a bug in the type definitions. PR welcome.

**Comment by fraxken** [comment]
I will work on it and make a PR

**Comment by dheeraj1997** [comment]
Can I contribute to it?

**Comment by mcollina** [comment]
sure, go ahead!

**Comment by mcollina** [comment]
Ah your PR did it! It was just not tagged with "closes #issue" so this would get closed automatically.
