### ISSUE TITLE
[experimental fetch] Header parser is very strict and doesn't handle strange characters in HTTP header

### ISSUE THREAD

**Issue by bwalding** [nodejs/undici#1319]
### Version

v17.8.0

### Platform

Darwin xxx 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

### Subsystem

fetch

### What steps will reproduce the bug?

```console
$ node --experimental-fetch -e 'fetch("https://www.mirantis.com/software/mirantis-kubernetes-engine/");'
```

### How often does it reproduce? Is there a required condition?

I imagine this will reproduce until Mirantis changes their server response / removes the typo in their Google config (as that is the cookie being impacted).

I raise this not because Mirantis has an arguably broken response - but because I can't use the fetch due to the failure.  

### What is the expected behavior?

I would *like* to fetch to download the URL as normal - and process the headers "appropriately".  But whether that is correct or not is another thing.  In general - on the internet - you don't always get what you want!

Primarily flagging this for review and pondering.

### What do you see instead?

Fetch throws an exception.

```console
$ node --experimental-fetch -e 'fetch("https://www.mirantis.com/software/mirantis-kubernetes-engine/");'
(node:88027) ExperimentalWarning: Fetch is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:7156
          p.reject(Object.assign(new TypeError("fetch failed"), { cause: response.error }));
                                 ^

TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:7156:34)
    at Fetch.fetchFinale (node:internal/deps/undici/undici:7486:21)
    at Fetch.mainFetch (node:internal/deps/undici/undici:7380:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: HTTPParserError: Invalid header value char
      at Parser.execute (node:internal/deps/undici/undici:1832:19)
      at Parser.readMore (node:internal/deps/undici/undici:1791:16)
      at TLSSocket.onSocketReadable (node:internal/deps/undici/undici:2122:14)
      at TLSSocket.emit (node:events:527:28)
      at emitReadable_ (node:internal/streams/readable:601:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'HPE_INVALID_HEADER_TOKEN',
    data: '\x01KuIR; path=/; Max-Age=900; Secure; SameSite=None\r\n' +
      'Set-Cookie: ___utmvbiPuicBO=EZc\r\n' +
      '    XfzOtale: stZ; path=/; Max-Age=900; Secure; SameSite=None\r\n' +
      'X-CDN: Imperva\r\n' +
      'Content-Encoding: gzip\r\n' +
      'X-Iinfo: 11-140504429-140504431 NNYN CT(206 419 0) RT(1648936173815 47) q(0 0 6 -1) r(9 9) U5\r\n' +
      '\r\n'
  }
}

Node.js v17.8.0
```

### Additional information

I confirmed there is an extra byte in their header using curl:

```console
$ curl -v https://www.mirantis.com/software/mirantis-kubernetes-engine/ > /dev/null 2> headers.txt
$ grep ___utm headers.txt | less
< Set-Cookie: ___utmvmiPuicBO=zUzimBnWQYi; path=/; Max-Age=900; Secure; SameSite=None
< Set-Cookie: ___utmvaiPuicBO=kJX^AGWTa; path=/; Max-Age=900; Secure; SameSite=None
< Set-Cookie: ___utmvbiPuicBO=lZo
```
(you can see the ^A on the 2nd of the Set-Cookie lines).

I would not be that surprised to see this ticket closed as 'not a bug'.

**Comment by mcollina** [comment]
Overall a lenient patate is the source of many security issues. I'm inclined to not fix this, as the risks outweigh the benefits.

I don't know if llhttp has a lenient flag for this and if we expose it.

Would you like to take a look and see how this could be in implemented?
