### ISSUE TITLE
Mocks: mocking `undici.fetch` leads to undefined `response.statusText`

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1321]
## Bug Description

When using mocks with `undici.fetch`, the Response object returned has a `statusText` property that is undefined.

## Reproducible By

```js
import { fetch, MockAgent, setGlobalDispatcher } from 'undici';

const mockAgent = new MockAgent();
mockAgent.disableNetConnect();
setGlobalDispatcher(mockAgent);

const mockPool = mockAgent.get('http://localhost:3000');

mockPool.intercept({
	path: '/test',
	method: 'GET'
}).reply(200, 'Hello!');

const r = await fetch('http://localhost:3000/test', {
	method: 'GET'
});

console.log(r.statusText); // undefined
```

## Expected Behavior

`statusText` should be assigned a value

## Environment

windows 10 node v17.7.1

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
