### ISSUE TITLE
types(MockResponseCallbackOptions): body is not always a string

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1322]
## Bug Description

When mocking `undici.fetch`, and supplying a function to `.intercept`, the parameter's `body` can be an object (tested with FormData, maybe it falls back to not parsing on unsupported types?).

## Reproducible By

```js
import { fetch, FormData, MockAgent, setGlobalDispatcher } from 'undici';
import { Blob } from 'buffer';

const mockAgent = new MockAgent();
mockAgent.disableNetConnect();
setGlobalDispatcher(mockAgent);

const mockPool = mockAgent.get('http://localhost:3000');

mockPool.intercept({
	path: '/test',
	method: 'POST'
}).reply((t) => {
	console.log({ b: t.body }); // FormData 🤯

	return {
		data: 'Hello!',
		statusCode: 200
	}
});

const fd = new FormData();
fd.append('a', new Blob(['key']), 'and_name');

const r = await fetch('http://localhost:3000/test', {
	method: 'POST',
	body: fd
});
```

## Expected Behavior

It would be very helpful to get a stringified version of the FormData (ie. the value actually sent to a server) 🙏 

## Logs & Screenshots
![image](https://user-images.githubusercontent.com/42794878/161677414-5333eda2-d886-4591-87ec-6b20affdd66a.png)

## Environment

windows 10 node v17.7.1

### Additional context

I wasn't sure if you guys preferred separate issues or for me to cram them all into 1, sorry if you preferred the latter ❤️

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by KhafraDev** [comment]
I'll be looking into all 3, hopefully I can fix them all 👍

**Comment by KhafraDev** [comment]
Fixing the types only isn't a solution either because the body is stringified automatically which causes the infamous `[object FormData]` output...

**Comment by mcollina** [comment]
I don't think we can make the mocking system aware of formdata, that information is lost at that point.

**Comment by KhafraDev** [comment]
I've found a very bad work around for now where I simply add the tests to the callback function...

Returning the `FormData` object without it being stringified would also be a useful solution IMO, and I'd be willing to submit a PR to allow this if this solution sounds good to you?

**Comment by mcollina** [comment]
If that's possible that'd be great.

**Comment by KhafraDev** [comment]
The potential solution I mentioned earlier is either not possible or way too difficult for me to figure out, `fetch` (and likely `request`) expect strings and stuff breaks otherwise. My best attempt was assigning a property to each `MockPool` instance of the last body received, which isn't great either as different scopes could share a single `MockPool` instance. 

I also discovered that `<callback param>.body` can be any value really, as long as the value can be passed as a `body` option. Therefore the param can be one of `Buffer | Uint8Array | internal.Readable | string | FormData`...

**Comment by mcollina** [comment]
Attaching something to `MockPool` might not be correct in case of multiple concurrent requests.

**Comment by KhafraDev** [comment]
Attaching to each MockScope does not seem to be possible because as soon as the interceptor is used, it's deleted. It would be nice to be able to receive the body sent to the interceptor, but I can't think of a decent way of doing so.
