### ISSUE TITLE
How To: Reusing `body` mixin streams

### ISSUE THREAD

**Issue by shellscape** [nodejs/undici#1326]
This is being left here to make it searchable:

If the scenario arises where you absolutely must have a copy of the result stream, [`.clone`](https://fetch.spec.whatwg.org/#dom-request-clone) can be used _before_ using a `body` mixin, or [`body.pipeThrough`](https://streams.spec.whatwg.org/#readablestream-pipe-through) with a user-defined stream [§](https://web.dev/fetch-upload-streaming), such as [`TransformStream`]https://nodejs.org/api/stream.html#duplex-and-transform-streams.

**Comment by restfulhead** [comment]
@shellscape I don't think `pipeThrough` works. It still marks the body as consumed.

```ts
console.log(request.bodyUsed)
request.body.pipeThrough(new TextDecoderStream())
console.log(request.bodyUsed)
```

This prints out `false`, then `true`. How can we copy/clone the stream without causing `bodyUsed` to become true?
