### ISSUE TITLE
Strange result with `set-cookie` header of `undici.fetch`

### ISSUE THREAD

**Issue by cjh980402** [nodejs/undici#1328]
## Bug Description
Result of set-cookie, Set-cookie, and sEt-CoOkIe header value should be same, but undici.fetch has different result.

## Reproducible By

```js
const { fetch } = require('undici');

const response = await fetch('https://maple.gg');

console.log(response.headers); // has set-cookie
console.log(response.headers.get('set-cookie')); // undefined
console.log(response.headers.get('Set-cookie')); // some cookie key and value
console.log(response.headers.get('sEt-CoOkIe')); // some cookie key and value
```

## Expected Behavior
I think all result of get should be same.

## Environment

Ubuntu 20.04
Node v16.14.2

**Comment by RafaelGSS** [comment]
@cjh980402 which `undici` version are you using?

**Comment by cjh980402** [comment]
I use undici 5.0.0.

**Comment by KhafraDev** [comment]
`set-cookie` is a forbidden header-name so it should be removed entirely (this is similar behavior with browser)

however `getting` a non-existent header should return null, not undefined.

**Comment by aeharding** [comment]
`set-cookie is a forbidden header-name so it should be removed entirely (this is similar behavior with browser)`

@KhafraDev if this is true, it seems like a case of a spec being written in the context of the browser, and not node.

Is there any chance of this being reverted? This change makes the fetch API not usable for me.

**Comment by KhafraDev** [comment]
Reverted? Probably not. However I'm willing to make a PR once a decision has been made on how to handle cookies in undici/node.
