### ISSUE TITLE
feature request: allow sending FormData in `undici.request`?

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1330]
## This would solve...

In a codebase I am working on, it is a requirement to be able to send FormDatas to the server (to upload files, etc.). It is preferable to use `request` because it is currently much faster than `fetch`.

## The implementation should look like...

Undici's fetch currently parses the FormData to a stringified version:
https://github.com/nodejs/undici/blob/c0961f4c7ef5dd6e64dbb7ffbd3f6cb1f78f106a/lib/fetch/body.js#L75-L124

## I have also considered...

Currently I have an implementation identical to this that just removed the async generator and manually sets the body & header properly. This is very tedious, but it does work.

## Additional context

This is basically all that is missing from making a seamless transition from `node-fetch` to `undici.fetch` to `undici.request`.

**Comment by ronag** [comment]
Or welcome!

**Comment by KhafraDev** [comment]
Got it working but I decided to throw an error on node <16 which makes the code much cleaner.

```js
{
  args: {},
  data: '',
  files: {},
  form: { a: 'b', c: 'd' },
  headers: {
    'Content-Type': 'multipart/form-data; boundary=----formdata-undici-0.8881790692261458',
    Host: 'httpbin.org',
    'Transfer-Encoding': 'chunked',
    'X-Amzn-Trace-Id': 'Root=1-6255b46c-247824d473dbe01c3ca0aa3f'
  },
  json: null,
  origin: '204.44.124.233', // vpn IP
  url: 'http://httpbin.org/post'
}
```
