### ISSUE TITLE
Make the global dispatcher truly global

### ISSUE THREAD

**Issue by delvedor** [nodejs/undici#1331]
The current implementation of the global dispatcher is that it stores within the library the global agent. This works well when the user is directly using `undici`. Still, suppose the user is using a library that internally uses `undici` and the user didn't install the exact same version of the library. In that case, the global dispatcher API won't work as the user would expect.

To clarify what I think a typical user expects: it should work in the same way as `nock`.
`nock` does not suffer from this problem because it will always use the same version of Node.js, while for `undici` this is not true (yet).

Even if it's kinda ugly, I would suggest attaching the global dispatcher to the Node.js's [`global`](https://nodejs.org/api/globals.html#global) object, so different versions (withing the major possibly) of `undici` can use the same global dispatcher.

If this solution is fine for you (or you have a better idea), I can work on it.

**Comment by ronag** [comment]
@mcollina I think this is more your area. Wdyt?

**Comment by mcollina** [comment]
This could solve it https://github.com/nodejs/node/issues/42814.

**Comment by ronag** [comment]
> @ronag do you think it would be possible to use the Agent from one version of undici in the one inside node core?

Yes. But then we can't break the interface. Ever

**Comment by mcollina** [comment]
Pretty much. Are we reading for it?

**Comment by delvedor** [comment]
> Yes. But then we can't break the interface. Ever

Yes and no IMHO. This problem could be solved similarly to what we are doing with [Fastify plugins](https://github.com/fastify/fastify-plugin#fastify-version).
