### ISSUE TITLE
Fetch returns body on null-body statuses

### ISSUE THREAD

**Issue by wmertens** [nodejs/undici#1339]
## Bug Description

When doing a request that returns status 204, the Response will have a defined `body`. Trying to create a wrapped Response based on this will fail due to [this check](https://github.com/nodejs/undici/blob/f5d9a94e8771708a2d3654e412cb82404bf7cf4f/lib/fetch/response.js#L161-L163).

## Reproducible By

```
$ node --experimental-fetch
(node:778928) ExperimentalWarning: Fetch is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Welcome to Node.js v17.7.2.
Type ".help" for more information.
> r=await fetch('https://httpstat.us/204')
Response { ... }
> new Response(r.body, r)
Uncaught TypeError: Response with null body status cannot have body
    at new Response (node:internal/deps/undici/undici:6134:19)
```

## Expected Behavior

How about: give the Response a null body and ignore anything the server sends after the headers.

## Environment

Node 17.7.2 and Chrome stable

**Comment by ronag** [comment]
I think this is mandated by the spec and not something we can change.

**Comment by wmertens** [comment]
I'm having a hard time reading the spec - it does [specify the null body statuses](https://fetch.spec.whatwg.org/#:~:text=null%20body%20status%20is%20a%20status%20that%20is%20101%2C%20103%2C%20204%2C%20205%2C%20or%20304) but I don't find where it mandates that noll-body status responses should have a body.

In any case I can imagine that bad servers do send a body on 204 so indeed better to leave as-is.

So what would be the best approach to wrap a response? I see that fetch creates a Response without arguments and then adds the state later, which circumvents the check.

Given that I'd like to have a null body on my wrapped response in this case, I can just provide a null body but I'll have to consume the body stream, right?
