### ISSUE TITLE
Set proxy for some fetch request (not all)

### ISSUE THREAD

**Issue by tamaina** [nodejs/undici#1350]
I apologize if this has already been implemented or issue created, but I could not find this usage in the documentation.

## This would solve...

I would like to specify a proxy for each fetch run.

## The implementation should look like...

Deno implements as follows PR:  
https://github.com/denoland/deno/pull/10907

In undici, it would become as follows...?

```js
import { ProxyAgent } from 'undici';

const client = new ProxyAgent('localhost:3000');
const response = await fetch("https://myserver.com", { client });
```

(Is ProxyAgent better than Client?)

**Comment by mcollina** [comment]
cc @ronag

**Comment by KhafraDev** [comment]
```js
import { ProxyAgent } from 'undici';

const client = new ProxyAgent('localhost:3000');
const response = await fetch("https://myserver.com", {
    dispatcher: client
});
```

If you are using node v18.2.0 or above, this will work using node's fetch. Otherwise, you need to import `fetch` from undici on v5.2.0 or above.

**Comment by 1999** [comment]
@KhafraDev sorry for reviving this thread, but is this a standard thing? I couldn't find any "dispatcher" in Fetch API docs. It also [isn't listed](https://github.com/microsoft/TypeScript/blob/e6edc567a3946d203436265c5b525817fe2f708d/src/lib/dom.generated.d.ts#L18404) in Typescript "lib" types for "RequestInit":

<img width="529" alt="image" src="https://github.com/user-attachments/assets/3b0d0c24-04dc-449c-a0d6-c140903c650d">

**Comment by KhafraDev** [comment]
It's a node-specific extension. I wouldn't recommend using the dom types in node; @types/node will be more correct.

https://github.com/nodejs/undici?tab=readme-ov-file#undicifetchinput-init-promise
