### ISSUE TITLE
Fetch garbles headers when used with a proxy global dispatcher

### ISSUE THREAD

**Issue by pimterry** [nodejs/undici#1355]
## Bug Description

When a ProxyAgent is set as the global dispatcher, the headers sent in fetch requests are completely broken: they're transformed from `header-name: header-value` into `1: header-name`, `2: header-value`, basically flattening them into an array and using the indexes as the header names.

## Reproducible By

Use any proxy, for quick testing I'd suggest launching tinyproxy on port 8888 locally via Docker:

```
docker run -it --rm -p 8888:8888 monokal/tinyproxy ANY
```

Then use Undici with that proxy:

```javascript
let Undici = require('undici');

// Use the proxy as the global dispatcher:
Undici.setGlobalDispatcher(new Undici.ProxyAgent('http://localhost:8888'))

// Send a fetch request to httpbin, which echoes the incoming headers:
Undici.fetch('http://httpbin.org/get', {
  headers: { 'Test-header': 'value' }
}).then(r => r.text()).then(console.log)
```

This prints:

```json
{
  "args": {}, 
  "headers": {
    "0": "accept", 
    "1": "*/*", 
    "10": "user-agent", 
    "11": "undici", 
    "2": "accept-encoding", 
    "3": "gzip, deflate", 
    "4": "accept-language", 
    "5": "*", 
    "6": "sec-fetch-mode", 
    "7": "cors", 
    "8": "test-header", 
    "9": "value",
    "Host": "httpbin.org", 
    "X-Amzn-Trace-Id": "Root=1-6170a3-4c398f08ae255c83"
  }, 
  "origin": "ip.ip.ip.ip", 
  "url": "http://httpbin.org/get"
}
```

I've tested this with a couple of different proxies and looked at the traffic in wireshark. This isn't being broken on the proxy site - those are the real headers that Undici is sending to the proxy itself.

## Expected Behavior

The headers should be sent in their original format. `Undici.request` does have the correct behaviour:

```javascript
// (after setting the global dispatcher as above)
Undici.request('http://httpbin.org/get', {
  headers: { 'Test-header': 'value' }
}).then(r => r.body.pipe(process.stdout))
```

That correct prints:

```json
{
  "args": {}, 
  "headers": {
    "Host": "httpbin.org", 
    "Test-Header": "value", 
    "X-Amzn-Trace-Id": "Root=1-62624e-c8afe258cd33244f8"
  }, 
  "origin": "ip.ip.ip.ip", 
  "url": "http://httpbin.org/get"
}
```

Using `Undici.fetch` without a proxy also works correctly, it's only when a global dispatcher is configured that this breaks.

## Environment

Ubuntu 20.04.4, Node 16.14.2, Undici v5.0.0

**Comment by ronag** [comment]
Do you think you could make a test that does not depend on external urls?

**Comment by pimterry** [comment]
Sure:

```javascript
// Run a server on port 9000 that echoes all headers
require('http').createServer((req, res) => console.log('Got request', req.headers)).listen(9000)

let Undici = require('undici');

// Use the proxy as the global dispatcher:
Undici.setGlobalDispatcher(new Undici.ProxyAgent('http://localhost:8888'))

// Send a fetch request to the above local server via the proxy:
Undici.fetch('http://172.17.0.1:9000', {
  headers: { 'Test-header': 'value' }
}).then(r => r.text()).then(console.log)
```

`172.17.0.1` is the local Docker host address (i.e. the node server's address from the POV of the Docker-hosted proxy) if you're running on Linux. On Windows/Mac `host.docker.internal` should work instead. Or you can set up a proxy outside Docker and use `localhost` directly.

When you make the request after a couple of seconds delay (tinyproxy seems slow, don't think it's relevant) it logs:

```
Got request {
  '0': 'accept',
  '1': '*/*',
  '2': 'accept-encoding',
  '3': 'gzip, deflate',
  '4': 'accept-language',
  '5': '*',
  '6': 'sec-fetch-mode',
  '7': 'cors',
  '8': 'test-header',
  '9': 'value',
  '10': 'user-agent',
  '11': 'undici',
  host: '172.17.0.1:9000',
  connection: 'close',
  via: '1.1 tinyproxy (tinyproxy/1.10.0)'
}
```

**Comment by ronag** [comment]
I can't run this as a self contained test. Amongst other you don't have :8888. Do you think you could make it fully self contained so that we can easily make a test of it and fix it.

**Comment by ronag** [comment]
@RafaelGSS I suspect our recent headers changes might have regressed somewhere with an incorrect spread operator.

**Comment by pimterry** [comment]
> I can't run this as a self contained test (no docker).

You can use any HTTP proxy you like, e.g. using [buildProxy](https://github.com/nodejs/undici/blob/f70ac7f57ae1b95b8140bcbe408274961fc1ac92/test/proxy.js#L127-L132) from the Undici tests.

In the code above, you'll just need to replace `http://localhost:8888` with the proxy's address and `http://172.17.0.1:9000` with the server's address from the proxy's POV (so `http://localhost:9000` if the proxy is running locally without docker)

**Comment by KhafraDev** [comment]
I'll have a pr fixing this in a few hours

**Comment by KhafraDev** [comment]
It's exactly that, noticed it pretty quickly 😄
https://github.com/nodejs/undici/blob/1dc2977c94583efbecd5b6791b5a091d18a2ceeb/lib/proxy-agent.js#L26
