### ISSUE TITLE
Release new version (node.js compat < v16)

### ISSUE THREAD

**Issue by dnalborczyk** [nodejs/undici#1372]
I was wondering if a new release could be published.

this PR https://github.com/nodejs/undici/pull/1318 fixed an issue with `logical assignment` syntax not being supported for `node.js < v16`.

the `elasticsearch client` adopted `undici v5.0` https://github.com/elastic/elastic-transport-js/blob/fabe5f42d6e69aa99cb0a77dda76e7369800d896/package.json#L66 and therefore makes it incompatible with any version below v16.

I must admit that it is a bit surprising that neither the `undici` tests nor the `elasticsearch` tests discovered the incompatibility in their tests.

**Comment by matthewlilley** [comment]
Please, this is blocking numerous apps from being deployed into production at the moment.

**Comment by matthewlilley** [comment]
Looks like it was released.

**Comment by mcollina** [comment]
This is done.
