### ISSUE TITLE
Request timeout vs fetch failed

### ISSUE THREAD

**Issue by kyrylkov** [nodejs/undici#1385]
Right now when fetch fails due to timeout generic `Fetch failed` error produced.  It literally took us months to figure it out.

It would be great to replace generic `Fetch failed` with specific timeout error message.

**Comment by ronag** [comment]
There should be a timeout in the "cause" for "fetch failed". If not then that's a bug. Do you think you could open a PR with unit test for that?

**Comment by kyrylkov** [comment]
Here is an example of stack trace for timeout: https://github.com/nodejs/undici/issues/1248#issuecomment-1109691167

Cause: undefined

**Comment by ronag** [comment]
I suspect that hs been fixed in master.

**Comment by kyrylkov** [comment]
I confirm
