### ISSUE TITLE
Use Proxy with Fetch

### ISSUE THREAD

**Issue by Electrite** [nodejs/undici#1388]
## Problem
I'm unsure about how to use a proxy with fetch. I've found very little documentation about how to integrate a proxy and I seek to use separate proxies for any fetch request with username and password authentication if applicable.

## Solution
As for a good solution I'd hope for a code example to perform a simple get request to a site (e.g. to ifconfig.me) using a proxy and instructions on how to include a username and password with that proxy.

**Comment by KhafraDev** [comment]
Possible with #1411, but if you are using `fetch` from node directly, you may need to wait for https://github.com/nodejs/node/issues/43187 (if a decision to expose it is ever made).

```js
import { fetch, ProxyAgent } from 'undici'

const agent = new ProxyAgent('localhost:8888')

const response = await fetch('https://example.com', {
    dispatcher: agent
})
```

**Comment by sxzz** [comment]
TIPs: `const agent = new ProxyAgent('localhost:8888')` is not working (for me), remember to add `http://` protocol.
