### ISSUE TITLE
Node's fetch implementation does not allow changing headers on request object

### ISSUE THREAD

**Issue by evert** [nodejs/undici#1433]
### Version

v18.1.0

### Platform

Linux evertbook6 5.15.0-27-generic nodejs/node#28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Node will lose headers that were added to the request after constructing the Request object, but_only_ if a custom Headers object was also passed in. This reproduces the issue 

```javascript
const headers = new Headers();
const request = new Request('http://localhost:8080', { headers });
request.headers.set('X-Foo', 'bar');

await fetch(request);
```

This does not happen when a headers object was not passed in:

```javascript
const request = new Request('http://localhost:8080');
request.headers.set('X-Foo', 'bar');

await fetch(request);
```

Oof this took a lot of experimentation to get to :S

I *think* this was introduced with Node 18.1.0, because I have a feeling my my tests passed with 18.0.0

### What is the expected behavior?

The following headers on the server:

```javascript
{
  host: 'localhost:8080',
  connection: 'keep-alive',
  'x-foo': 'bar',
  accept: '*/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'undici',
  'accept-encoding': 'gzip, deflate'
}
```

### What do you see instead?

```javascript
{
  host: 'localhost:8080',
  connection: 'keep-alive',
  accept: '*/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'undici',
  'accept-encoding': 'gzip, deflate'
}
```
@jasnell

**Comment by ronag** [comment]
I think this was fixed in https://github.com/nodejs/undici/pull/1401

**Comment by evert** [comment]
I'm not fully certain if #1401 tests for the the exact same issue. One thing that's at least different is that I'm changing a header after constructing the `Request` object.  I don't think there's a test there that covers that case, _but_ it does seem related to very possible that this is _also_ fixed.

**Comment by mcollina** [comment]
Could you verify if this still applies to undici v5.2.0?

**Comment by evert** [comment]
I imported Undici in my project directly, overwrite `global.fetch()` and family and can confirm it's fixed!
