### ISSUE TITLE
Provide a way to access raw headers

### ISSUE THREAD

**Issue by blittle** [nodejs/undici#1437]
## This would solve...

As outlined at [WHATWG/fetch](https://github.com/whatwg/fetch/issues/973) there is often the need in a server environment to access cookie headers.

For example editing Cookie headers:

```ts
const h = new Headers;
h.append("Set-Cookie", "a=1; Expires=Wed, 21 Oct 2015 07:28:00 GMT");
h.append("Set-Cookie", "b=1; Expires=Wed, 21 Oct 2015 07:28:00 GMT");

h.get("Set-Cookie")
// a=1; Expires=Wed, 21 Oct 2015 07:28:00 GMT, b=1; Expires=Wed, 21 Oct 2015 07:28:00 GMT
```

Splitting the combined header value by , will give an invalid result. Instead getAll could be used to retrieve the individual headers.

## The implementation should look like...

There are two solutions currently proposed:

1. Node-fetch provides a non-standard `Headers.prototype.raw` method that returns entries for each (including duplicate) header.
2. Re-introduce `Headers.prototype.getAll` to return multiple header values.

## I have also considered...

1. Not use undici primitives within NodeJS.
2. Attempt to [monkey patch undici](https://github.com/sveltejs/kit/issues/4375#issuecomment-1071995207)

## Additional context

1. Cloudflare implemented [.getAll()](https://github.com/whatwg/fetch/issues/973#issuecomment-902784363).
3. Node-fetch [`.raw()` implementation](https://github.com/node-fetch/node-fetch/blob/main/src/headers.js#L202)
4. Tracking at [WinterCG](https://github.com/wintercg/fetch-standard/issues/4)

**Comment by KhafraDev** [comment]
The current headers implementation would need an overhaul to support this. It stores headers as strings, rather than arrays (which I believe goes against the spec) and doesn't concat values when using `.get()` (as, well, they're already strings).

I can see adding `.getAll()`, and like cloudflare, making it only work on set-cookie headers.

**Comment by ksmithut** [comment]
Some more additional context, it looks like Deno's implementation is also a bit different:

Deno:
```
Deno 1.22.2
> Array.from(new Headers([['set-cookie', 'a=b'], ['set-cookie', 'b=c']]))
[ [ "set-cookie", "a=b" ], [ "set-cookie", "b=c" ] ]
```

Node:
```
Welcome to Node.js v18.3.0.
> Array.from(new Headers([['set-cookie', 'a=b'], ['set-cookie', 'b=c']]))
[ [ 'set-cookie', 'a=b, b=c' ] ]
```

Not sure what the "right" thing to do is, just pointing out an implementation detail.

**Comment by KhafraDev** [comment]
Undici is the spec-compliant way, Deno purposefully doesn't concatenate `set-cookie` headers.

https://github.com/denoland/deno/blob/bb3387de17953ea1f0558f5f9863b0cd6c59d48c/ext/fetch/20_headers.js#L212-L215

**Comment by ksmithut** [comment]
Right, they seem to do that because they reuse the Request and Response classes in a server context, not just for usage with fetch. If that's not a goal of undici, then it should probably just stick with the spec.

**Comment by KhafraDev** [comment]
[`Headers.prototype.getSetCookie`](https://github.com/whatwg/fetch/pull/1346) will solve this use case. I don't think another solution would be accepted unless something is decided in the wintercg fetch group.

**Comment by sbellone** [comment]
I think this can be closed now that `.getSetCookie()` has been introduced: https://github.com/nodejs/undici/pull/1915
