### ISSUE TITLE
Body close event not emitted when the connection is lost

### ISSUE THREAD

**Issue by S222em** [nodejs/undici#1442]
## Bug Description

The **close** event of the body is not emitted when the connection is lost.

## Reproducible By

```ts
const { body } = await request(SOME_URL, {
	method: 'GET',
	headers: {
		Accept: 'text/event-stream',
	},
	bodyTimeout: 0,
	dispatcher: SOME_DISPATCHER,
});

// Never emitted
body.on('close', () => console.log('Closed'));
```
The connection that was established here works correctly and is supposed to be able to run forever (which it does). When the connection is lost e.g. wifi connection is lost, nothing happens.

- Make a request that will run forever until closed manually (text/event-stream for example).
- Ensure the connection is working.
- Turn off your wifi.
- Observe that nothing happens.

## Expected Behavior

The **close** event should be emitted when the connection is lost.

## Environment

WSL2, Ubuntu 20.04.4LTS
NodeJS v16.14.2

**Comment by mcollina** [comment]
Could you create a test to reproduce that will not require the wifi to be turned off? It'd be difficult to fix otherwise.

**Comment by S222em** [comment]
It seems like I am unable to reproduce this. I have tried creating a simple express HTTP server, which I can't repro. I will continue looking into this. It's supposed to throw an error or emit `closed` right?

**Comment by S222em** [comment]
> Okay, so I managed to reproduce it with a local raspberry pi running the same express server. After turning the wifi off, simply nothing happens. What I did observe, is that after turning the wifi on again, it reconnected and caught up with all delayed/not received packets. I am quickly going to make sure the same happens in practice, if so I can just close this issue.

So I just quickly tested this, and it does actually reconnect and catch up. The only thing is that I would like to know when this occurs, so I can change the state of the connection to actually tell the end-user it is "disconnected". Not sure if that is an issue on undici's side.

**Comment by mcollina** [comment]
Awesome thanks for confirming! I don't think there is anything to do on our part... you are disabling the `bodyTimeout`.
