### ISSUE TITLE
Improve diagnostics request/response/trailers types

### ISSUE THREAD

**Issue by stefee** [nodejs/undici#1443]
## This would solve...

Implementing diagnostics channels subscription using TypeScript e.g. for https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1021

## The implementation should look like...

Export types for the request/response/trailers provided as message to diagnostics channel. 

## I have also considered...

Using `any` as the diagnostics message and custom type definitions as a temporary workaround.

## Additional context

~Worth bearing in mind this `@types/node` bug as well - but these are only tangentially related. https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59005 fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56618~ Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59796

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by stefee** [comment]
I can take a look. Some guidance on the structure and naming of the exports would be appreciated, because the `Request` type presumably already exists or it might mean something ambiguous at least. Is the request provided to diagnostics a specific type of request object?

**Comment by stefee** [comment]
It looks like the Request and Response types refer to the fetch variants currently.

**Comment by stefee** [comment]
I'm thinking something like `UndiciRequest` or `UndiciClientRequest` would make sense.

**Comment by stefee** [comment]
Hmm, so the `response` passed into the channel is just an object-literal sent purely for diagnostics purposes. https://cs.github.com/nodejs/undici/blob/b6a72620a67236ea84160a0ae3d505b3d77a2214/lib/core/request.js#L194

With this in mind, I think a minimal type definition would be best. How does this sound?
- DiagnosticsChannelRequest is a subset of the core Request object - we probably just need to expose some properties and the `addHeader` for now?
- DiagnosticsChannelResponse - a simple object with properties
- DiagnosticsChannelTrailers - an array of Buffers

If later we want to export the core request more generically to support another use case then we can, but it seems like a bad idea to export the whole Request class from core?

**Comment by mcollina** [comment]
Sounds fair, go for it!
