### ISSUE TITLE
Remove `readonly` from `RequestInit` typings

### ISSUE THREAD

**Issue by NMinhNguyen** [nodejs/undici#1445]
## Bug Description

It'd be good to remove `readonly` modifier from `RequestInit` typings to match https://github.com/microsoft/TypeScript/blob/95731f03979985609c9fd662f179be5b9cea3470/lib/lib.dom.d.ts#L1470. This would allow for `RequestInit` objects to be conditionally mutated like so https://github.com/ferdikoomen/openapi-typescript-codegen/blob/0f11ea84a9ca9867bb72700f468fa21d8085ce86/src/templates/core/fetch/sendRequest.hbs#L20

I'm happy to raise a PR for this if there are no objections.

## Reproducible By

If you try to mutate a `RequestInit` object, TypeScript will say something like:

> Cannot assign to 'credentials' because it is a read-only property. ts(2540)

## Expected Behavior

No error.

**Comment by KhafraDev** [comment]
PR welcome, make sure to include tests. We use tsd for testing types.

**Comment by KhafraDev** [comment]
PR welcome, make sure to include tests. We use tsd for testing types.

**Comment by NMinhNguyen** [comment]
Thanks @KhafraDev, let me know if the test in #1446 isn't enough and I'll see what I can do
