### ISSUE TITLE
Support for query params

### ISSUE THREAD

**Issue by kibertoad** [nodejs/undici#1448]
## This would solve...

Supporting query params would decrease amount of boilerplate code that developers need to write

## The implementation should look like...

```
    const { statusCode, headers, trailers, body } = await request("localhost:8080/", {
      method: 'GET',
      params: {
        pageNum: 1,
        pageSize: 10
    }
    })
```

## I have also considered...

Embedding query params directly into the URL, but it is very cumbersome or requires writing a wrapper in every project.

## Additional context

If this is approved, I can contribute a PR.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
go for it!

**Comment by ronag** [comment]
There is also already the following option:

```js
const url = new URL('http://localhost:8080')
url.searchParams = new URLSearchParams({
    pageNum: 1,
    pageSize: 10
})
const { statusCode, headers, trailers, body } = await undici.request(url)

```

**Comment by kibertoad** [comment]
@ronag Yes, but it is fairly verbose for a very common use-case. My idea is to basically add this under-the-hood, should be very simple change.

**Comment by ronag** [comment]
I don't mind it as long as it doesn't add too much complexity and edge cases.

**Comment by kapouer** [comment]
Really ? I thought undici wouldn't fall for that joke ! Now you're on the "implementation details" road.
