### ISSUE TITLE
Implicit import of `URL`?

### ISSUE THREAD

**Issue by Fdawgs** [nodejs/undici#1450]
The `URL` class was made part of the global object in node 10, however it is imported regularly throughout this repo:

https://github.com/nodejs/undici/blob/55d39a355c83dfeb52720d1085495f9b5d3a3a95/lib/proxy-agent.js#L4

Was this a stylistic choice, or can it potentially be removed?
Happy to open a PR if wanted.

**Comment by ronag** [comment]
@mcollina wdyt?

**Comment by mcollina** [comment]
I think it was done before we `URL` became a global. I'm ok in using a global.
