### ISSUE TITLE
Correct way to identify empty response body

### ISSUE THREAD

**Issue by kibertoad** [nodejs/undici#1480]
## This would solve...

Even if there is no response body, undici handles it by returning a stream with 0 length. Currently the only way to tell if you should be trying to parse the body is `response.body._readableState.length`, which feels a lot like delving deep into internals.

## The implementation should look like...

Additional getter on response would allow to solve this problem without performance overhead:

```
response.isBodyPresent // getter that checks _readableState.length
```

## I have also considered...

This can also be addressed via documentation, if it is recommended to resolve this in a different way, e. g. by trusting statusCode === 204.

**Comment by KhafraDev** [comment]
https://datatracker.ietf.org/doc/html/rfc7230#section-3.3

I think documentation would be helpful but adding these checks doesn't seem necessary.

**Comment by kibertoad** [comment]
@KhafraDev "All other responses do include a message body, although the body might be of zero length"

This doesn't seem conclusive. Realistically speaking this means that it is not safe to always invoke response.body.json() on all 200 answers, because according to spec they may have zero length, which will crash, and undici provides no public API for checking body length.

**Comment by kibertoad** [comment]
Another alternative would be returning null for zero-length body on .json()
wdyt?

**Comment by mcollina** [comment]
A few notes:

1. a JSON is at least 2 bytes
2. a body can be zero length
3. a content-type of "application/json" guarantees at least two bytes

What I did in the past in those cases is to check the content-type header.

**Comment by kibertoad** [comment]
@mcollina Does undici lower-case headers it received in responses? If not, should we introduce case-insensitive way to check?

**Comment by mcollina** [comment]
> Does undici lower-case headers it received in responses?

Yes it does.
