### ISSUE TITLE
Undici throws a ConnectTimeoutError when there is no connection

### ISSUE THREAD

**Issue by mdmitry01** [nodejs/undici#1484]
## Bug Description

If you try to send an HTTP request, but the DNS lookup for the requested domain name fails, Undici may throw a `ConnectTimeoutError`.

## Reproducible By

I wrote a simple script which reproduces the issue

```js
const { Pool } = require('undici')

const agent = new Pool('http://foobar.bar')

for (let i = 0; i < 500; i++) {
  agent.request({ method: 'GET', path: '/foobar' })
    .then(async ({ body }) => {
      for await (const data of body) {
        console.log('data', data.toString('utf8'))
      }
    })
    .catch(console.error)
}
```

I used undici@5.4.0

## Expected Behavior

I'd expect to get only errors which indicate that the DNS lookup has failed.

## Logs & Screenshots

[Video](https://user-images.githubusercontent.com/69001428/172602292-44b429bc-029e-4bc4-bbf8-b82edb98930c.mp4)

## Environment

Ubuntu 20.04.4 LTS, Node v16.13.0

**Comment by mcollina** [comment]
I cannot reproduce the error at all on Linux or Mac.

@ronag could you take a look too?

**Comment by jodevsa** [comment]
@mcollina  I can reproduce it with

`
const { Pool } = require('undici')

const agent = new Pool('http://foobar.bar')

for (let i = 0; i < 50000; i++) {
  agent.request({ method: 'GET', path: '/foobar' })
    .then(async ({ body }) => {
      for await (const data of body) {
        console.log('data', data.toString('utf8'))
      }
    })
    .catch(console.error)
}
`


then try to write the output on a file and search for TO. something like

`node a.js 2> a.txt`


I think the problem here is that the call stack blocks the event loop from executing stuff in the callback queue until the for loop is done executing and as soon as the callbacks are executed we reached TO

**Comment by jodevsa** [comment]
Seems like the for loop execution is blocking the event loop from picking executing callbacks from the callback queue and for some reason the TO callback comes before the error callback.

using process.nextTick for the setTimeout fixes it 

`let timeoutId = null
    socket
      .setNoDelay(true)
      .once(protocol === 'https:' ? 'secureConnect' : 'connect', function () {
        clearTimeout(timeoutId)

        if (callback) {
          const cb = callback
          callback = null
          cb(null, this)
        }
      })
      .on('error', function (err) {
        clearTimeout(timeoutId)

        if (callback) {
          const cb = callback
          callback = null
          cb(err)
        }
      })

      process.nextTick(()=>{
      timeoutId = timeout
      ? setTimeout(onConnectTimeout, timeout, socket)
      : null
      })`

**Comment by jodevsa** [comment]
sure, I'll prepare a PR ASAP

**Comment by jodevsa** [comment]
created the following PR: https://github.com/nodejs/undici/pull/1551

**Comment by jodevsa** [comment]
reproduce script:
```
const { Pool } = require('undici')
const assert = require('assert')
const agent = new Pool('http://foobar.bar')

for (let i = 0; i < 50000; i++) {
  agent.request({ method: 'GET', path: '/foobar' })
    .then(async ({ body }) => {
      for await (const data of body) {
        console.log('data', data.toString('utf8'))
      }
    })
    .catch((e)=>assert.equal(e.code,'ENOTFOUND'))
}

```
