### ISSUE TITLE
v5: somehow abort signal is retained between invocations?

### ISSUE THREAD

**Issue by wmertens** [nodejs/undici#1485]
## Bug Description

We maintain a fetch wrapper that adds timeouts, retries and concurrency control at https://github.com/StratoKit/fetch-extra

Upgrading to undici v5 causes the validation tests to break. What happens in the test is that a first request gets aborted due to request status, and then retried (resulting in a different status), and somehow undici immediately aborts the second fetch, seemingly as part of the first fetch.

## Reproducible By

1. clone https://github.com/StratoKit/fetch-extra and `npm install`
2. `npm test` works
3. `npm i undici@5`
4. `npm test` now fails

## Environment

Node 16

### Additional context

you can set `DEBUG=*` to get extra debugging information

**Comment by KhafraDev** [comment]
Does it happen when you're not using jest?

**Comment by KhafraDev** [comment]
If you are using the same AbortController for both requests, and it gets aborted, both requests will abort (if either of them haven't been aborted). This is expected behavior, see #1389.

**Comment by Dzieni** [comment]
I managed to make a minimal reproduction and it does seem to be a problem of Jest. Running the same code in clean Node environment seems to do the job well.

Here's what I reported in Jest's repo: https://github.com/facebook/jest/issues/13029
