### ISSUE TITLE
TypeError: disturbed

### ISSUE THREAD

**Issue by kyrylkov** [nodejs/undici#1499]
## Bug Description
Undici fetch get results in `TypeError: disturbed`

## Reproducible By
N/A

## Expected Behavior
Proper response or specific error message

## Logs & Screenshots
N/A

## Environment
Ubuntu 22.04 LTS, Node v18.4.0

### Additional context
N/A

**Comment by ronag** [comment]
This can be normal. You need to provide more context and a reproducible example.

**Comment by kyrylkov** [comment]
> This can be normal.

What does it mean if it's normal?

> You need to provide more context and a reproducible example.

We'll try

**Comment by KhafraDev** [comment]
> What does it mean if it's normal?

The body has already been consumed.

```js
import { fetch } from 'undici'

const response = await fetch('https://example.com')

await response.text()
await response.text() // fails
```

**Comment by kyrylkov** [comment]
> The body has already been consumed.

I see.  It cannot be the case.  Because it's coming from the code path that 99% of the cases generate proper responses.  The only different thing from call to call are authentication and request params.

**Comment by mcollina** [comment]
Then we'll really need a reproduction

**Comment by renhiyama** [comment]
Why cant we use response.text() multiple times? sounds bad to me :(

**Comment by mcollina** [comment]
> Why cant we use response.text() multiple times? sounds bad to me :(

That's how the spec works.

**Comment by jimmywarting** [comment]
use `clone` if you intend to use it multiple times.

```js
res1 = new Response('foo')
res2 = res1.clone()

// best if both are being consumed at the same time...
res1.text()
res2.text()
```

**Comment by fresheneesz** [comment]
Sorry, did someone actually thing just "disturbed" is an acceptable error message? First thing I thought was that Zalgo got its hooks into my code.
