### ISSUE TITLE
Fetch + proxy

### ISSUE THREAD

**Issue by sosoba** [nodejs/undici#1504]
May I have a please an example code of a connection via the global "fetch" method with using https proxy?

**Comment by protometa** [comment]
The [proxy](https://github.com/nodejs/undici/blob/main/test/proxy.js) and [proxy agent](https://github.com/nodejs/undici/blob/main/test/proxy-agent.js) tests probably have the most throughout examples, but there's also some basic ones in [examples](https://github.com/nodejs/undici/tree/main/examples).
