### ISSUE TITLE
GC example could be improved

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#1505]
if you are only after the headers then it might be better to just use `HEAD` request.
```js
// Do
const headers = await fetch(url)
  .then(async res => {
    for await (const chunk of res.body) {
      // force consumption of body
    }
    return res.headers
  })

// Do not
const headers = await fetch(url)
  .then(res => res.headers)
```
alternative is to just cancel it with abort signal and abort the request
but i also understand if it's just for explaining how GC works. but many ppl just blindly copy code in readme's that isn't always the best

**Comment by mrkldshv** [comment]
Hey! I was thinking to take this issue. Do we just want to add the example with `HEAD` request below and note that this is the better way to do it?

**Comment by mcollina** [comment]
Go for it! We'll be happy to review!
