### ISSUE TITLE
Unknown cause error when fetch fails due to a redirect

### ISSUE THREAD

**Issue by ImRodry** [nodejs/undici#1509]
## Bug Description

When you make a fetch request with the `redirect` option set to "error", upon receiving a redirect, fetch will throw an error with an undefined cause and simply saying "fetch failed"

## Reproducible By

```js
fetch("https://i.imgur.com/BLUyAX0.png", { redirect: "error" })
```

## Expected Behavior

The error is thrown with a more explicit reason such as "Unexpected redirect"

## Logs & Screenshots

![image](https://user-images.githubusercontent.com/38259440/175096046-477322f4-df85-4280-8ae0-6444801a870d.png)

## Environment

Windows 11, Node.js v18.4.0

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ImRodry** [comment]
Sure, the fix seems to be quite easy. Where should I place the tests for this?

**Comment by mcollina** [comment]
https://github.com/nodejs/undici/tree/main/test/fetch
