### ISSUE TITLE
Getting warnings

### ISSUE THREAD

**Issue by parasop** [nodejs/undici#1524]
why getting this warnings 

(node:3542) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time

**Comment by KhafraDev** [comment]
In node v16.x, [Blob](https://nodejs.org/dist/latest-v16.x/docs/api/buffer.html#class-blob) is marked as experimental.

When consuming a response's body after using `fetch`, undici converts the body to a Blob (causing the warning), and then to its respective form. This allows us to re-use blob's prototype methods instead of re-implementing methods of converting the response body.

```js
import { fetch } from 'undici'

const response = await fetch('...') // no warning
await response.blob() // warning
await response.text() // warning
await response.json() // warning
// etc...
```

**Comment by jimmywarting** [comment]
> When consuming a response's body after using `fetch`, undici converts the body to a Blob (causing the warning), and then to its respective form. This allows us to re-use blob's prototype methods instead of re-implementing methods of converting the response body.

This kind of solution is a memory hog. first it has to assembly all the uint8array chunks into one large array of `chunks[uint8array]` 
then it needs to create a Blob `new Blob(chunks, ...`) and the Blob requires it to be immutable so it needs to copy each and every uint8array chunk (at that point you have 2x the amount of memory) then it will use `blob.text()` that has a other [flaw](https://github.com/nodejs/node/issues/42265) (in that it can't process strings larger than 500MB)
cuz that `blob.text()` method uses:
```js
    const dec = new TextDecoder();
    return dec.decode(await this.arrayBuffer());
```
so again you need to allocate memory for both a ArrayBuffer and a string at the same time so 2x as much memory are being used there as well.

---

I have been thinking if it isn't better to just do:
```js
  async blob() {
    const blobs = []
    for await (const chunk of stream) blobs.push(new Blob(chunk))
    return new Blob(blobs, { ... })
  }
```
at least then it have the option to GC and offload data to the disk and not copy all data at once to make it immutable.
I know that you can get into trouble in chrome if you are creating one large or many small blob chunks too fast. but create many small blob chunks successively and then concatinate them using `new Blob(blobs)` then chrome can simply handle it more gracefully. Have been thinking of doing it this way in node-fetch but haven't gotten around at doing it yet...

---

Either way this blob reading methods should perhaps best be avoided to avoid some unnecessary overhead.
i think a better solution would be to simply just use 
```js
async function text() {
  const rs = this.body.pipeThrough(new TextDecoderStream())
  let str = '' 
  for await (const chunk of rs) str += chunk
  return str
}
```
or using `streamConsumers.text(stream)` or something more lower level and more cross version comp:

```js
  async text () {
    // More optimized than using this.arrayBuffer()
    // that requires twice as much ram
    const decoder = new TextDecoder()
    let str = ''
    for await (const part of this.body) str += decoder.decode(part, { stream: true })
    // Remaining
    str += decoder.decode()
    return str
  }
```

**Comment by mcollina** [comment]
A PR would be amazing as well.
