### ISSUE TITLE
`fetch` no longer respects `Request` object as a parameter

### ISSUE THREAD

**Issue by ardatan** [nodejs/undici#1527]
## Bug Description

Until 5.6.0, you could use `Request` objects as an input for `fetch`. But now it doesn't respect and ignores the parameters already given with previously created `Request`.

## Reproducible By
It can be easily reproduced like below. You will get an error that says it is not possible to have a `body` for HTTP `GET` and `HEAD` requests.
```ts
  const body = JSON.stringify({ foo: "bar" });
  const request = new undici.Request("https://www.google.com", {
        method: "POST",
        body,
    });

  await undici.fetch(request);
```

Also see https://github.com/nodejs/undici/pull/1528

## Expected Behavior

Like other `fetch` implementations, it should be expected to use `Request` objects as an input.

Related part of the spec;
https://fetch.spec.whatwg.org/#requestinfo

## Environment

Ubuntu 18.04 LTS,
Node v16.13

**Comment by ronag** [comment]
@KhafraDev

**Comment by KhafraDev** [comment]
Might not have time to make a PR to fix this today, but I've found the issue.

When using a `Request` object as the first parameter, the `init` parameters (options) should default to the Request's options, which it does not. This causes init to be assigned a default value of `{ method: 'GET' }` which will throw an error.
