### ISSUE TITLE
object.hasOwn is not a function

### ISSUE THREAD

**Issue by parasop** [nodejs/undici#1538]
![Screenshot](https://user-images.githubusercontent.com/63485824/178218351-21e4d9a8-d566-4160-921d-693f9dc29ba8.png)

whenever i am fetching i am getting error like object.hasOwn is not function

**Comment by mcollina** [comment]
What version of Node.js are you using?

**Comment by parasop** [comment]
> What version of Node.js are you using?

v16.5

**Comment by KhafraDev** [comment]
Node v16.5 support in fetch was dropped in aa8782cfcc24fe116cf27c34e65a057fbcbac3ba due to a magnitude of bugs existing in it for quite some time.
