### ISSUE TITLE
Issues While Importing Via CommonJS

### ISSUE THREAD

**Issue by siklr** [nodejs/undici#1553]
I'm trying to work with the Undici package, and while I see that the documentation uses ```import { request } from 'undici'```, I'm using ```const { request } = require('undici');```, which from my understanding should work.

However, if I use:

```
const { request } = require('undici');

const result = await request('https://aws.random.cat/meow');
```

I receive the following error:

```
const result = await request('https://aws.random.cat/meow');
               ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
```

To be clear, request is an async function as defined in the package.

I'm confused as to why this doesn't work? I've seen a few tutorials that use what I'm attempting to use with no issue, so I'm not sure what I'm doing wrong.

**Comment by mcollina** [comment]
Top-level await is not available in commonjs, it's specific to modules: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await https://dev.to/raviojha/node-v14-8-top-level-async-await-2i2b.

You must wrap your `await` inside an async function:

```js
const { request } = require('undici');

async function run () {
  return await request('https://aws.random.cat/meow');
}

run().then(console.log)
```
