### ISSUE TITLE
undici does not resolve `*.localhost` domains correctly

### ISSUE THREAD

**Issue by TheKnarf** [nodejs/undici#1571]
## Bug Description

In my local development env I got Hasura running and responding on `hasura.localhost`. This works fine in Chrome, I can open the web UI and do stuff from there. However this does not seem to work when trying to query the api using `undici` (see `reproducible by` below).

This seems to break [RFC-6761](https://www.rfc-editor.org/rfc/rfc6761#section-6.3):

>Name resolution APIs and libraries SHOULD recognize localhost names as special and SHOULD always return the IP loopback address for address queries and negative responses for all other query types. Name resolution APIs SHOULD NOT send queries for localhost names to their configured caching DNS server(s).

So it seems that Chrome resolves `hasura.localhost` as the localhost loopback, while `undici` does not.

## Reproducible By

`test.mjs`:
```
#!/usr/bin/env node

import { request } from 'undici'

const {
  statusCode,
  headers,
  trailers,
  body
} = await request('http://hasura.localhost/v1/graphql')

console.log('response received', statusCode)
console.log('headers', headers)
```

Then run it:

```
$ chmod +x ./test.mjs
$ ./test.mjs
```

## Expected Behavior

For it to resolve `hasura.localhost` as the local loopback IP (aka `127.0.0.1`).

## Environment

```
$ uname -a
Darwin Mbp13arm.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
```

### Additional context

Version: `undici@npm:5.5.1`

**Comment by mcollina** [comment]
I have reported this upstream: https://github.com/c-ares/c-ares/issues/477
