### ISSUE TITLE
Release Schedule or CD

### ISSUE THREAD

**Issue by shellscape** [nodejs/undici#1586]
## This would solve...

Fixes that may be mission critical but delayed for release. There are currently 9 fixes, 1 chore, and 1 docs update merged to master but unpublished.

## The implementation should look like...

I would personally love to see a release schedule, or a doc that states expectations for releases following merges of fix/feat to master. Alternatively a CD workflow that published on merge would be helpful, automatic, and not burdensome to maintainers.

## I have also considered...

That there may be good reasons for not having a CD workflow. And in that case I think setting expectations for publish/release 

## Additional context

Big fan of the project, want to make sure our apps are on the latest hotness.

**Comment by mcollina** [comment]
I don't think we trust any of the tools for _completely automatic releases_, as there are often a few nuances and timing.

We usually release every 2 weeks but that's not the formal schedule and more when we are available to do it.
