### ISSUE TITLE
Mock cannot intercept an array query parameter if the native `fetch` is used.

### ISSUE THREAD

**Issue by mmktomato** [nodejs/undici#1592]
## Bug Description

I found I can't intercept a http request with an array query parameter if I use native `fetch`.

## Reproducible By

```
const mockAgent = new MockAgent()
setGlobalDispatcher(mockAgent)

const mockPool = mockAgent.get('http://localhost:3001')

mockPool.intercept({
  path: '/foo',
  method: 'GET',
  query: {
    arr: ["a","b"],
  },
}).reply(200, 'foo')

// This fails because `fetch` tries to make a real http request.
await fetch('http://localhost:3001/foo?arr%5B%5D=a&arr%5B%5D=b');

// This also fails.
// await fetch('http://localhost:3001/foo?arr%5B0%5D=a&arr%5B1%5D=b');
```

If the query parameter is a string or number, the interception works.

```
mockPool.intercept({
  // ...(snip)...

  query: {
    // arr: ["a","b"],
    a: "a"
  },
}).reply(200, 'foo')

// This works.
await fetch('http://localhost:3001/foo?a=a');
```

## Expected Behavior

The interception works fine if:
- a query parameter is an array.
- the native `fetch` is used.

## Environment

macOS: 12.5
Node.js: 18.7.0
undici: 5.8.1

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by KhafraDev** [comment]
Your example is incorrect as far as I can tell.

The query params use brackets to denote an 'array' or duplicated keys, which changes the key from 'arr' to 'arr[]'. Therefore, to fix your answer:

```diff
mockPool.intercept({
  path: '/foo',
  method: 'GET',
  query: {
-    arr: ["a","b"],
+   'arr[]': ["a","b"],
  },
}).reply(200, 'foo')
```

---

You can read a much better answer than I could write out [here](https://stackoverflow.com/a/39294315/15299271).

TL:DR; [RFC 1866 8.2.4](https://www.rfc-editor.org/rfc/rfc1866#section-8.2) gives an example of setting duplicate keys (no bracket notation), but the WHATWG URL spec has essentially superseded this and used bracket notation. So to match multiple keys, you can manually add in the brackets to the `query` option.
