### ISSUE TITLE
The line where fetch is called doesn't show in the stack trace

### ISSUE THREAD

**Issue by icetbr** [nodejs/undici#1599]
### Version

v18.7.0

### Platform

Linux 98a94d978874 5.4.0-122-generic nodejs/node#138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 Linux

### Subsystem

fetch

### What steps will reproduce the bug?

```js
async function a() {
    await fetch('http://a.com')
}

(async function() {
    await a()
    // → 🎉
}());
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

At some point in the stack frame:
```console
 at a (/home/user/projectA/a.js:8:11)
```

### What do you see instead?

```console
TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:7175:34)
    at Fetch.fetchFinale (node:internal/deps/undici/undici:7505:21)
    at Fetch.mainFetch (node:internal/deps/undici/undici:7399:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: Error: getaddrinfo ENOTFOUND a.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:82:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'a.com'
  }
}
```

### Additional information

Maybe undici issue @mcollina ?

**Comment by mcollina** [comment]
Yes, it's a undici issue, I moved it there.

**Comment by mcollina** [comment]
@KhafraDev @ronag have you got some ideas? This would be a true benefit for the ecosystem.

**Comment by ronag** [comment]
Doesn't this require some async hook magic?

**Comment by mcollina** [comment]
I don't think it would. This will get us there:

```diff
diff --git a/index.js b/index.js
index 8099f5a..0b9a2e5 100644
--- a/index.js
+++ b/index.js
@@ -92,7 +92,12 @@ if (nodeMajor > 16 || (nodeMajor === 16 && nodeMinor >= 8)) {
       fetchImpl = require('./lib/fetch')
     }
     const dispatcher = (arguments[1] && arguments[1].dispatcher) || getGlobalDispatcher()
-    return fetchImpl.apply(dispatcher, arguments)
+    try {
+      await fetchImpl.apply(dispatcher, arguments)
+    } catch (err) {
+      Error.captureStackTrace(err)
+      throw err
+    }
   }
   module.exports.Headers = require('./lib/fetch/headers').Headers
   module.exports.Response = require('./lib/fetch/response').Response
```

I'm not sure the exact implications of this.

cc @benjamingr

**Comment by mcollina** [comment]
This practically adds 2 microticks.

**Comment by sosoba** [comment]
It is worth paying attention to the second parameter of `captureStackTrace`. By specifying the scope function (ex. this), you can trim the stack trace from internals.
```js
Error.captureStackTrace(err, this)
```

**Comment by mcollina** [comment]
@sosoba  would you like to send a PR to implement this?
