### ISSUE TITLE
Query assertions on MockAgent intercept have ordering significance

### ISSUE THREAD

**Issue by James1x0** [nodejs/undici#1600]
## Bug Description
Query parameter assertions have ordering significance. Objects do have key ordering significance, however query parameters should not.

## Reproducible By

Consider this example:

```typescript
 mockAgent = new MockAgent();
 mockAgent.disableNetConnect();
 setGlobalDispatcher(mockAgent);

mockAgent.get('someHost').intercept({
    path: '/some/path',
    method: 'get',
    query: {
        somevalue: ['abc'], // note key ordering here.
        key: 'test',
    },
}).reply(200, 'yay');

const response = await request('someHost/some/path', {
    query: {
        key: 'test', // keys in different order
        somevalue: ['abc'],
    }
});
// ^ ❌ miss

const response = await request('someHost/some/path', {
    query: {
        somevalue: 'test', // keys in same order
        key: ['abc'],
    }
});
// ^ ✅ hit
```

## Expected Behavior
Request `query` key ordering should have no significance on assertions.

## Logs & Screenshots
N/A

## Environment
macOS 12.3.1, Node v16.13.2

### Additional context
I'm happy to submit a PR fixing this if the contributors agree with the expected behavior. Thanks!

**Comment by mateonunez** [comment]
When the `getMockDispatch` method resolves the path, the **mockDispatches** are filtered by `consumed` props and the result of `matchValue` method, checking the following variables:

```js
path: "/foo?foo=bar&key=get";
resolvedPath: "/foo?key=get&foo=bar"
```

https://github.com/nodejs/undici/blob/deed6284ad97df01df92cee7576384bff7da1ad9/lib/mock/mock-utils.js#L110

**Comment by mcollina** [comment]
I think the behavior is fundamentally correct. We cannot test or verify all permutations.
Having said that, I think we should provide better diagnostics to let people know where things got stuck.

**Comment by James1x0** [comment]
> I think the behavior is fundamentally correct. We cannot test or verify all permutations.
> 
> Having said that, I think we should provide better diagnostics to let people know where things got stuck.

Hm, makes sense if for some reason it's not advisable to deserialize the query parameters.

How would you imagine diagnostics? Logging mismatched requests?

**Comment by mcollina** [comment]
> How would you imagine diagnostics? Logging mismatched requests?

Having a callback in MockAgent that produce some kind of reporting object saying _why_ a request was not matched. Folks could then add a `console.log()` there if they want to.
