### ISSUE TITLE
Expected `ENOTFOUND` but got `UND_ERR_CONNECT_TIMEOUT`

### ISSUE THREAD

**Issue by mateonunez** [nodejs/undici#1603]
## Bug Description

Running the tests, the `connect-timeout` fails. The test `priotorise socket errors over timeouts` checks the error code that should match with `ENOTFOUND`, but got `UND_ERR_CONNECT_TIMEOUT`.

## Reproducible By

```sh
> git clone https://github.com/nodejs/undici
> npm|yarn|pnpm install
> npm|yarn|pnpm test
```

## Expected Behavior

The test should check the **type** instead the code, as the other tests do.

## Logs & Screenshots

```sh
 FAIL ​ test/connect-timeout.js
 ✖ should be equal

  test/connect-timeout.js
  14 |     .then(() => t.fail())
  15 |     .catch((err) => {
> 16 |       t.equal(err.code, 'ENOTFOUND')
     | --------^
  17 |     })
  18 |
  19 |   // block for 1001ms which is enough for the dns lookup to complete and TO to fire  

  --- expected
  +++ actual
  @@ -1,1 +1,1 @@
  -ENOTFOUND
  +UND_ERR_CONNECT_TIMEOUT 

  test: test/connect-timeout.js priotorise socket errors over timeouts
  stack: |
    test/connect-timeout.js:16:9
```

## Environment

- OS: **Windows 11 21H2**
- Node: **v18.6.0**

### Additional context

The error occurs only on Windows environments.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mateonunez** [comment]
I tried to create a reproducible example, but when the CI was completed on Windows environment, all tests passed correctly: [summary here](https://github.com/mateonunez/undici/runs/7876719769).
I'm gonna close this issue as a falsy.

Thank you for the quick feedback!

**Comment by mcollina** [comment]
No worries
