### ISSUE TITLE
Undici crashes on node compiled without crypto

### ISSUE THREAD

**Issue by aduh95** [nodejs/undici#1612]
@nodejs/undici this seems to break with a container/machine without OpenSSL:
https://ci.nodejs.org/job/node-test-commit-linux-containered/33340/nodes=ubuntu1804_sharedlibs_withoutssl_x64/
```
17:44:45     [UNEXPECTED_FAILURE][FAIL] Importing an i32 global with an incorrectly-typed value: ""
17:44:45     Node.js is not compiled with OpenSSL crypto support
17:44:45     Error [ERR_NO_CRYPTO]: Node.js is not compiled with OpenSSL crypto support
```

_Originally posted by @MoLow in https://github.com/nodejs/node/issues/44319#issuecomment-1221580468_

**Comment by aduh95** [comment]
It looks like the change was introduced by https://github.com/nodejs/undici/pull/1596.

**Comment by KhafraDev** [comment]
I'm going to work on this (and a few other issues I had with #1596)
