### ISSUE TITLE
responseHeaders['set-cookie'] better stores in an array?

### ISSUE THREAD

**Issue by OKFred** [nodejs/undici#1616]
https://github.com/nodejs/undici/blob/6a87bfb38b3f4a28be81d2cc44a80083a0e4f798/lib/fetch/index.js#L1952

When it comes to response headers: **'set-cookie'**, the value stores as a string as well.
The problem is that there may be multiple 'set-cookie' headers in various of formats sent from the server. 
Hard to split when joined in a string. (Or, do you have any better ideas defining the splitter? Coz I am a newbie)

It would be easier to handle as an array. 
Reasons/References are as follows:

- In older ways, it stores as an array. Quotes: **set-cookie is always an array. Duplicates are added to the array.**
[https://nodejs.org/api/http.html#messageheaders](https://nodejs.org/api/http.html#messageheaders)

- And node-fetch package implemented this way as well, which you may have referred.
[https://github.com/node-fetch/node-fetch/blob/main/src/index.js#L65](https://github.com/node-fetch/node-fetch/blob/main/src/index.js#L65)

Thx & B/R
Fred

**Comment by ronag** [comment]
This is how the fetch spec defines the behavior and is not something I believe we can change.

**Comment by mcollina** [comment]
See https://github.com/wintercg/fetch/issues/6.
As soon as a spec-compatible API is available, we'll implement it.

**Comment by OKFred** [comment]
@ronag Are you referring to the Fetch Standard? [https://fetch.spec.whatwg.org/#headers-class](https://fetch.spec.whatwg.org/#headers-class)
The following quote could be quite informative: 
Unlike a [header list](https://fetch.spec.whatwg.org/#concept-header-list), a [Headers](https://fetch.spec.whatwg.org/#headers) object cannot represent more than one `Set-Cookie` [header](https://fetch.spec.whatwg.org/#concept-header). In a way this is problematic as unlike all other headers `Set-Cookie` headers cannot be combined, but since `Set-Cookie` headers are not exposed to client-side JavaScript this is deemed an acceptable compromise. **Implementations could choose the more efficient [Headers](https://fetch.spec.whatwg.org/#headers) object representation even for a [header list](https://fetch.spec.whatwg.org/#concept-header-list), as long as they also support an associated data structure for `Set-Cookie` headers.**

Anyway, glad to hear if we can move on one day. @mcollina 

Thx & B/R
Fred
