### ISSUE TITLE
Circular dependencies in code

### ISSUE THREAD

**Issue by benmccann** [nodejs/undici#1629]
## Bug Description

There's a circular dependency in Undici's code, which causes build warnings when building a project using Undici with Rollup

## Reproducible By

You can see this by simply reading the code and looking at the imports from the console warning below

To reproduce the build warning, import Undici and build a project with Rollup. You can also do:
```
git clone git@github.com:sveltejs/kit.git
cd kit
pnpm install
pnpm build
```

## Expected Behavior

I'd expect not to get build warnings about circular dependencies just because I'm using Undici

## Logs & Screenshots

```
@sveltejs/adapter-node:build: (!) Circular dependencies
@sveltejs/adapter-node:build: ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/util.js -> ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/file.js -> ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/util.js
@sveltejs/adapter-node:build: ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/util.js -> ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/file.js -> ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/webidl.js -> ../../node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/util.js
```

## Environment

```
		"undici": "^5.10.0",
		"rollup": "^2.78.1",
		"vite": "^3.1.0-beta.1"
```

**Comment by ronag** [comment]
@KhafraDev
