### ISSUE TITLE
ProxyAgent does not send any request

### ISSUE THREAD

**Issue by pikokr** [nodejs/undici#1639]
## Bug Description

I made a simple server to use with discord.js proxy, but it didn't receive any request.  
The 'connect' event works, but 'request' events never fires.  
However, it works when I just connect by web browser.

## Reproducible By

server:
```ts
import { createServer } from 'http'

const server = createServer((req, res) => {
  console.log(req.url) // never fires
  res.end()
})

server.listen(3000, () => console.log('Listening'))
```

client:
```ts
import { ProxyAgent, fetch } from 'undici'

;(async () => {
  const dispatcher = new ProxyAgent('http://127.0.0.1:3000')
  
  const { text } = await fetch('some url', { dispatcher }) // times out here

  console.log(await text())
})()
```

## Expected Behavior

The server should handle the request

## Logs & Screenshots

![image](https://user-images.githubusercontent.com/68010770/188559571-698655be-5cec-4636-b9e2-ccf6c59644a0.png)

## Environment

Ubuntu 22.04 LTS, Node v18.8.0

### Additional context

\-

**Comment by mcollina** [comment]
cc @RafaelGSS

**Comment by RafaelGSS** [comment]
That's expected. Your proxy server is not a proxy server. Consider using https://www.npmjs.com/package/proxy in your HTTP server.
