### ISSUE TITLE
docs: MockAgent.get() documentation is missing required options for MockPool.intercept()

### ISSUE THREAD

**Issue by bnb** [nodejs/undici#1642]
## Bug Description

Currently, the [`MockAgent.get()` documentation](https://undici.nodejs.org/#/docs/api/MockAgent?id=mockagentgetorigin) shows using an implementation of `MockPool.intercept()` _without_ the (seemingly, both in my own testing and based on what [`MockPool.intercept()`](https://undici.nodejs.org/#/docs/api/MockPool?id=parameter-mockpoolinterceptoptions) docs say) **required** `method` property.

## Reproducible By

Trying to run any of the examples in [`MockAgent.get()` documentation](https://undici.nodejs.org/#/docs/api/MockAgent?id=mockagentgetorigin) that use a ``MockPool.intercept()` implementation without the `method` property.

## Expected Behavior

Examples should be functioning properly.

## Logs & Screenshots

![screenshot of my own code where an error occurred](https://user-images.githubusercontent.com/502396/189469774-e77fd35a-c3c4-4ff5-a20f-e63650d543ea.png)
![nearly identical code on the undici docs](https://user-images.githubusercontent.com/502396/189469792-93c15220-6a2e-4367-aa7c-6e4d94ccd331.png)

## Environment

N/A

### Additional context

Should be fixable by just adding the `method` property to every options object where `includes` is used.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by kibertoad** [comment]
@bnb Looks like TS types need to be updated too: https://github.com/nodejs/undici/blob/main/types/mock-interceptor.d.ts
it's marked as optional there as well

**Comment by KhafraDev** [comment]
It says in the types that it defaults to get, which makes more sense than throwing an error imo.

**Comment by bnb** [comment]
@mcollina I'm not sure I'll have time immediately to submit a PR. Lots of travel both currently and in the next few weeks :P

I'd be happy to try eventually, but if someone else can nail that beforehand that'd be great.

**Comment by KhafraDev** [comment]
This was changed in 48c326f0. You probably just need to update undici?

**Comment by bnb** [comment]
Ah yes, I'm on 5.8.2. That doesn't change the need to update docs inconsistency, though 😊
