### ISSUE TITLE
Node.js 12 support?

### ISSUE THREAD

**Issue by dominykas** [nodejs/undici#1645]
It seems as part of https://github.com/nodejs/undici/pull/1604, Node.js 12 was removed from the support matrix - not sure if that was intentional?

https://github.com/nodejs/undici/blob/88eca8d967897d68e9ce31b452e573c6eac1d278/.github/workflows/nodejs.yml#L23-L26

If Node.js 12 is no longer supported - then probably the `engines` field needs to be updated (incl. a major version release) - but quite possibly that was a typo and the matrix needs to be adjusted?

**Comment by mcollina** [comment]
this should still support Node v12. I didn't spot this in that PR, I thought we were just skipping it on Windows.

Would you mind sending a PR?

**Comment by dominykas** [comment]
Seems there's a test failing (`test/request-timeout.js`) - I can take a look later.

**Comment by dominykas** [comment]
OK, I think I don't have enough context, TBH. But that test is failing due to https://github.com/nodejs/undici/pull/1604/files#diff-ca407d959d33ce92a7f7efee354a5ea5e6e61fcd797d32c04205e429a074ed54R892 - seems that timeout happens in node 14+ due to `socket.writableNeedDrain` - which actually makes 14.17.0+ a requirement for the _test_, but I'd probably need significantly more time to figure out whether the implementation is the right one 😅 

Happy to follow any pointers, though...

**Comment by mcollina** [comment]
I think that's the best outcome. Just make that test run on Node v14.17+.

**Comment by dominykas** [comment]
Updated the PR, also had to disable `jest` for Node 12 - seems that it's accumulating the disabled tests - not sure if that's becoming problematic or not just yet?
