### ISSUE TITLE
Provide a hint how to solve a `disturbed` exception

### ISSUE THREAD

**Issue by reknih** [nodejs/undici#1653]
I was using Node to fetch some JSON off a server and ran into an `disturbed` Exception after trying to call the `.json` method twice on the server response. At first, I could not locate what caused that in my application. Eventually, I found #1499 and realized my mistake. However, the error message could provide a hint towards what to fix to improve developer experience.

## This would solve...

Developer confusion when confronted with the `disturbed` exception from a package that is not even included in their `package-lock.json` 🤯

## The implementation should look like...

Here is an example error message:

```js
if (util.isDisturbed(object)) {
  throw new TypeError("Object is disturbed.\n\n" +
    "You may have already tried to consume this response. " +
    "At most one method that can consume a body may be called on a response."
  )
}
```

[This function](https://github.com/nodejs/undici/blob/dcd4e81b83c709f78ad2b28c844e9dac67f9078f/lib/fetch/body.js#L220) may currently be the culprit, but I'm not sure.

## I have also considered...

An alternative could be to clarify the concept of "disturbed" bodies within the documentation, a FAQ section, etc. However, placing helpful messages right inside the exception IMHO places them in front of the programmer when they need it.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
