### ISSUE TITLE
UND_ERR_SOCKET thrown when fetching certain endpoints of the GitHub API

### ISSUE THREAD

**Issue by rijkvanzanten** [nodejs/undici#1670]
## Bug Description

When requesting certain endpoints of the GitHub API, `undici` crashes with `SocketError: closed`

<details><summary>Full Error</summary>

```
/path/to/node_modules/undici/lib/client.js:967
  const err = this[kError] || new SocketError('closed', util.getSocketInfo(this))
                              ^

SocketError: closed
    at TLSSocket.onSocketClose (/path/to/node_modules/undici/lib/client.js:967:31)
    at TLSSocket.emit (node:events:525:35)
    at node:net:757:14
    at TCP.done (node:_tls_wrap:584:7)
Emitted 'error' event on BodyReadable instance at:
    return super.emit(ev, ...args)
                 ^

Error
    at Object.emit (/path/to/node_modules/undici/lib/api/readable.js:66:18)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'UND_ERR_SOCKET',
  socket: {
    localAddress: undefined,
    localPort: undefined,
    remoteAddress: undefined,
    remotePort: undefined,
    remoteFamily: undefined,
    timeout: undefined,
    bytesWritten: 75,
    bytesRead: 556
  }
}
```

</details>

I'm assuming there's a certain header or combination of response headers that's causing this behavior, but I don't know enough about the Undici codebase or http headers to flag the problem. I've copied the full raw response this endpoint gives using other API debugging tools

<details><summary>Response headers from aforementioned endpoint</summary>

```
HTTP/1.1 401 Unauthorized
Server: GitHub.com
Date: Wed, 28 Sep 2022 16:02:23 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 152
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 55
X-RateLimit-Reset: 1664384459
X-RateLimit-Resource: core
X-RateLimit-Used: 5
X-GitHub-Request-Id: F68E:1A6C:47DAE65:925FC3C:63347011
connection: close

{"message":"Requires authentication","documentation_url":"https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user"}
```  

</details>

## Reproducible By

```js
import { request } from 'undici';

const { body } = await request('https://api.github.com/user/emails');

console.log(await body.json());
```

on the latest version at time of writing `5.10.0`.

Minimal repro repo: https://github.com/rijkvanzanten/undici-socket-err

## Expected Behavior

The above code snippet should console.log the JSON output of the endpoint. 

## Environment

macOS 12.6, Node v16.17.0

**Comment by rijkvanzanten** [comment]
It's similar to the following, but I don't think this is a duplicate of:

- https://github.com/nodejs/undici/issues/1414 
  In this case, the response does have an explicit content-length, which seems to be correct. 
- https://github.com/nodejs/undici/issues/1412
  This problem happens with both `fetch` and `request` and the endpoint isn't an http2 endpoint

**Comment by mcollina** [comment]
I know why this is happening: the socket is getting closed before we have time to complete parsing the response. It's a timing issue. We should defer this error if we expect the socket to be closed.

**Comment by rijkvanzanten** [comment]
@mcollina Happy to try my hand at a PR if you have some pointers on where to tackle this in the codebase 🙂

**Comment by mcollina** [comment]
I think deferring https://github.com/nodejs/undici/blob/7c93a8d88233d58a7c1db89ed3b311533404cd96/lib/client.js#L961-L995 by a setImmedidate and adding some checks that we parsed the complete message would do the trick.

**Comment by jamesmenera** [comment]
Hey, any update on this issue?

**Comment by 5821036299** [comment]
Also running into this issue.

**Comment by jaafarskafi1** [comment]
Also running into this issue

**Comment by jaafarskafi1** [comment]
Running into this issue as well
