### ISSUE TITLE
How to handle body timeout error?

### ISSUE THREAD

**Issue by paymog** [nodejs/undici#1671]
## Bug Description

I have a fastify server which uses `undici`. I'm seeing the following errors intermittently:

```
BodyTimeoutError: Body Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/app/node_modules/undici/lib/client.js:896:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on BodyReadable instance at:
    at BodyReadable.emit (/app/node_modules/undici/lib/api/readable.js:66:18)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'UND_ERR_BODY_TIMEOUT'
}
```

Unfortunately, this stack trace doesn't indicate where I should put a try/catch to swallow this error.

I have a `reply.From` which has looks like so

```
    reply.from(pathname || '/', {
      getUpstream: () => origin,
      onError: (rep, err) => {
        // ...
      },
      onResponse: async (_, rep, res) => {
          // ...
        });
      },
    });
```

It seems that the body timeout error is either happening elsewhere in my server or is not triggering the `onError` handler.

## Expected Behavior

I'd expect this stack trace to give more information on where this error is originating so that I can put a try/catch around it

## Environment

a docker container based on `node:17-alpine`

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by paymog** [comment]
Turns out this stemmed from running an x86 docker image on my M1 mac - I guess it was something weird going on with the emulator. After building the container on my M1, the issue resolved.
