### ISSUE TITLE
Improve buildURL performance

### ISSUE THREAD

**Issue by anonrig** [nodejs/undici#1672]
## This would solve...

The current implementation is quite slow. I recommend using [fast-querystring](https://github.com/anonrig/fast-querystring) and replacing the existing querystring builder.

## The implementation should look like...

Replacing buildURL function with [fast-querystring](https://github.com/anonrig/fast-querystring) and improve the performance (with a proper benchmark)
 https://github.com/nodejs/undici/blob/0d1419ce8980e8c0f289e876448bf1e6eb755a8d/lib/core/util.js#L39

## I have also considered...

Just copying the code of [fast-querystring](https://github.com/anonrig/fast-querystring) and putting inside the undici, but I believe it will bloat the codebase.

## Additional context

I'm the author of [fast-querystring](https://github.com/anonrig/fast-querystring) which makes me biased towards this decision. That's why I wanted to open an issue before a pull request.

**Comment by kibertoad** [comment]
This is a hot path for the large number of GET requests, so having this would be nice.

**Comment by ronag** [comment]
PR welcome

**Comment by anonrig** [comment]
I created a pull request and added a comment regarding the benchmarks @ronag https://github.com/nodejs/undici/pull/1673
