### ISSUE TITLE
MAX_RESPONSE_BODY_SIZE is missing

### ISSUE THREAD

**Issue by nosovk** [nodejs/undici#1692]
## This would solve...

Sometimes we have to fetch user provided URL. In that case some users can provide a link to something big, like 4k video.
In that cases we would like to limit body size accepted by fetch.
In `node-fetch` there was option [`size`: maximum response body size in bytes. 0 to disable](https://github.com/node-fetch/node-fetch/blob/main/README.md#options). It would be nice to have a similar option in `undici`, because fetching user provided URLs without limitations seems to be a bad idea.

## The implementation should look like...

Add additional parameter to options, implementation in `node-fetch` seems to be clear to understand.

## I have also considered...

We can go to more low level implementation, but having option in fetch implementations seems to be a good idea.

**Comment by KhafraDev** [comment]
This would be better suited as an Agent option, as a counterpart to maxHeaderSize & bodyTimeout.

Fetch is a [web spec](https://fetch.spec.whatwg.org/) which means we should fundamentally keep modifications to it at a minimum.

**Comment by mcollina** [comment]
I'm +1 to add it to `Client`. Would you like to send a PR?

**Comment by nosovk** [comment]
Unfortunately won't fix now. This issue blocks migration from `node-fetch` to `undici`, but till node-fetch is not deprecated it could be postponed.

**Comment by jodevsa** [comment]
Hi @mcollina, can this issue be closed now?
