### ISSUE TITLE
ProxyAgent can only use basic authentication

### ISSUE THREAD

**Issue by oooshima** [nodejs/undici#1704]
## This would solve...
Basic authentication is hard coded at 
https://github.com/nodejs/undici/blob/8d6ddb7e2e2d0c22a3814c33b08edf1480c1e586/lib/proxy-agent.js#L59

Sometimes we have to use other authentication. (Bearer etc..)

## The implementation should look like...
Add additional parameter to options, which is type of authentication.
Can I like to send a PR to fix this?

## I have also considered...
I think it is better to add an option because erasing the hard code is breaking changes.

**Comment by cola119** [comment]
How about adding a new option like `opts.token` and set it directly to `this[kProxyHeaders]['proxy-authorization']`?

```js
if (opts.token) {
  this[kProxyHeaders]['proxy-authorization'] = opts.token
}
```
```js
// user land
const agent = new ProxyAgent({
  url: 'my.proxy.com',
  token: 'Bearer xxxx'
})
```

**Comment by ronag** [comment]
PR welcome

**Comment by oooshima** [comment]
Thanks for the answer!
I have created a PR and would appreciate a review.
https://github.com/nodejs/undici/pull/1705
