### ISSUE TITLE
Add AVX support to complete the simd supportiveness for llhttp

### ISSUE THREAD

**Issue by lucshi** [nodejs/undici#1709]
## This would solve...

Complete the simd supportiveness for llhttp.

## The implementation should look like...

Currently llhttp only support SSE which has been a quite old instruction set. I plan to work on this to add AVX, AVX2 and AVX512 support to llhttp to make simd supportiveness complete. I'm not sure if any objections for this idea.

## I have also considered...

May only add AVX512 to build out a peak performance version.

**Comment by ronag** [comment]
WASM doesn't support AVX instruction yet as far as I know...

**Comment by mcollina** [comment]
@lucshi you might want to open this issue to llhttp iself.
