### ISSUE TITLE
Update llhttp

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#1710]
We should update llhttp to the latest version.

**Comment by mcollina** [comment]
1. download the latest tagged release, e.g. https://github.com/nodejs/llhttp/releases/tag/release%2Fv8.1.0
2. unpack the file in `deps/llhttp`
3. `npm run prebuild:wasm`
4. `npm run build:wasm`

Can you also add those instructions to CONTRIBUTING.md?

**Comment by HassanBahati** [comment]
> 

Okay let me do so

**Comment by HassanBahati** [comment]
> 

@mcollina  for instruction 2 (unpack the file in `deps/llhttp` ) , does that mean all files from the llhttp v8.1.0 should be extracted into `deps/llhttp` or I should only replace the `src` and `includes` folders as it currently appears ?

**Comment by mcollina** [comment]
You can copy all files, it should work anyway.

**Comment by HassanBahati** [comment]
> You can copy all files, it should work anyway.

alright let me copy all files

**Comment by kibertoad** [comment]
@mcollina Should this be closed? I believe this was done
