### ISSUE TITLE
Node 19 CI Failures

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1733]
Seems we have CI failures on node 19 related to balanced pool. Took a quick look, but I'm not that familiar with these parts. @mcollina do you have a good ping?

**Comment by mcollina** [comment]
This is a good topic for my stream ;).

**Comment by KhafraDev** [comment]
there's also an issue with the WPT runner in v19, see https://github.com/nodejs/node/issues/45419

**Comment by mcollina** [comment]
I thought I had more time than expected.

**Comment by mcollina** [comment]
Closing. Node.js v19 is out of support.
