### ISSUE TITLE
TypeError: Cannot find name DOMException 

### ISSUE THREAD

**Issue by Tarrowren** [nodejs/undici#1740]
## Bug Description

Missing `DOMException`, `Event` and other types

## Reproducible By

```jsonc
// tsconfrig.json
{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "Node",
    "target": "ES2020",
    "lib": ["ES2020"],
    "rootDir": "src",
    "outDir": "out",
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true
  },
  "include": ["src"]
}

```
run
```sh
tsc -p ./
```

## Expected Behavior

Compilation passed

## Logs & Screenshots
```sh
node_modules/undici/types/filereader.d.ts:5:41 - error TS2304: Cannot find name 'EventTarget'.

5 export declare class FileReader extends EventTarget {
                                          ~~~~~~~~~~~

node_modules/undici/types/filereader.d.ts:27:19 - error TS2304: Cannot find name 'DOMException'.

27   readonly error: DOMException | null
                     ~~~~~~~~~~~~

node_modules/undici/types/filereader.d.ts:37:44 - error TS2304: Cannot find name 'EventInit'.   

37 export interface ProgressEventInit extends EventInit {
                                              ~~~~~~~~~

node_modules/undici/types/filereader.d.ts:43:44 - error TS2304: Cannot find name 'Event'.       

43 export declare class ProgressEvent extends Event {
                                              ~~~~~

[11:46:51] Found 4 errors. Watching for file changes.

```
## Environment

Node v16.18.0

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Tarrowren** [comment]
# example:
run:
```sh
npm init -y
npm i -D typescript
npm i undici
```
create file: tsconfig.json
```jsonc
{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "Node",
    "target": "ES2020",
    "lib": ["ES2020"],
    "rootDir": "src",
    "outDir": "out",
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true
  },
  "include": ["src"]
}
```
create file: src/index.ts
```ts
import { request } from "undici";
console.log(request);
```
run:
```sh
node_modules/.bin/tsc -p ./
```

**Comment by climba03003** [comment]
Shouldn't `Node` is required inside `lib` when you are in `Node` environment?

**Comment by Tarrowren** [comment]
thanks for the reminder, I've revised the comment.
this is node project and I will not add "DOM" in "lib".

**Comment by mcollina** [comment]
I think you need `@types/node@18` to use this library. All of fetch requires Node v18 and I don't know how we can make that optional for TS users on Node v16.

**Comment by mcollina** [comment]
I don't know how to make these optional. fetch() is a DOM API and we need those definitions.

**Comment by Tarrowren** [comment]
`@types/node@18` is still missing some types

```sh
[21:29:33] Starting compilation in watch mode...

node_modules/undici/types/filereader.d.ts:27:19 - error TS2304: Cannot find name 'DOMException'.

27   readonly error: DOMException | null
                     ~~~~~~~~~~~~

node_modules/undici/types/filereader.d.ts:37:44 - error TS2304: Cannot find name 'EventInit'.

37 export interface ProgressEventInit extends EventInit {
                                              ~~~~~~~~~

[21:29:35] Found 2 errors. Watching for file changes.
```

**Comment by KhafraDev** [comment]
You could set [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) to true in your tsconfig which would solve the problem. Otherwise this seems like an issue with @types/node (which are seemingly more and more common).

**Comment by Tarrowren** [comment]
Now that's what I do, but apparently this way isn't perfect😂

**Comment by Tarrowren** [comment]
I found that on node16, `DOMException` is not defined
may need to export this class
![image](https://user-images.githubusercontent.com/35626141/198919592-b4b9d506-adc4-4e06-b782-cd23a16064ad.png)

**Comment by KhafraDev** [comment]
DOMException wasn't exposed until v17 (probably) so we use a hack to get it in node 16. You can get it by doing:
https://github.com/nodejs/undici/blob/bc1ee0cf768a8a18228807960ab050cefd8c273f/lib/fetch/constants.js#L66-L74

or you could use [node-domexception](https://www.npmjs.com/package/node-domexception), which uses a different hack, but it's in the form of an npm package instead

**Comment by climba03003** [comment]
> DOMException wasn't exposed until v17 so we use a hack to get it in node 16

Then, shouldn't it be a breaking change and need to be update the support `engine`?

https://github.com/nodejs/undici/blob/bc1ee0cf768a8a18228807960ab050cefd8c273f/package.json#L100-L102

**Comment by KhafraDev** [comment]
This is something that we should fix, considering this is causing issues for other people.

We need to add `EventInit` (this is easy), `DOMException`, `Event`, and `EventTarget` while not conflicting with node v16 types, which don't have these.

OR, we could `any` the types if not available... something like

```ts
export type DOMException = typeof globalThis extends { DOMException: infer T }
  ? T
  : any
```

This way is so much easier but might still cause issues.
