### ISSUE TITLE
undici doesnt support keep-alive connection header?

### ISSUE THREAD

**Issue by Automized** [nodejs/undici#1746]
I am trying to use the keep-alive connection header but it returns this error (see below)

```
(node:65464) UnhandledPromiseRejectionWarning: InvalidArgumentError: invalid connection header
```

Not sure if I am doing something wrong, maybe the keep-alive is called something different in undici or that it is not supported.

Please let me know, thank you!

**Comment by ronag** [comment]
You should not be setting the keep-alive header yourself. undici already does this for you.

**Comment by Automized** [comment]
> You should not be setting the keep-alive header yourself. undici already does this for you.

okay great, thank you for the quick response :)
