### ISSUE TITLE
undici.stream ignores throwOnError

### ISSUE THREAD

**Issue by mdashlw** [nodejs/undici#1753]
## Bug Description

`undici.stream`/`Dispatcher.stream` accepts [`RequestOptions`](https://undici.nodejs.org/#/docs/api/Dispatcher?id=parameter-requestoptions) which extends [`DispatchOptions`](https://undici.nodejs.org/#/docs/api/Dispatcher?id=parameter-dispatchoptions) which includes `throwOnError` to throw on 4xx and 5xx HTTP errors, but completely ignores it and calls the factory regardless of the status code.

## Reproducible By

```js
import fs from "node:fs";
import undici from "undici";

await undici.stream(
  "https://httpbin.org/status/502",
  { throwOnError: true },
  () => fs.createWriteStream("httpbin_502.txt")
);
```

Successfully creates an empty `httpbin_502.txt` (because httpbin.org sends empty body on `/status`)

## Expected Behavior

```
ResponseStatusCodeError: Response status code 502: BAD GATEWAY
```

### Additional context

* `throwOnError` was introduced in https://github.com/nodejs/undici/pull/1453
* the current code for `request`: https://github.com/nodejs/undici/blob/0a7ba7226ce8cdd6bc67527bcd3427665ff7edd2/lib/api/api-request.js#L95
* `stream` lacks that code: https://github.com/nodejs/undici/blob/0a7ba7226ce8cdd6bc67527bcd3427665ff7edd2/lib/api/api-stream.js#L92

**Comment by ronag** [comment]
PR welcome!

**Comment by ronag** [comment]
Should do the same on undici.pipeline

**Comment by MattBidewell** [comment]
If no one else is looking, I've started to take a look at this. :) Have a WIP draft PR here, not finished yet. 

https://github.com/nodejs/undici/pull/1766

**Comment by assalielmehdi** [comment]
Hi, I implemented a [fix](https://github.com/nodejs/undici/pull/1767). Can you take a look?
