### ISSUE TITLE
Allow async callbacks in `reply`

### ISSUE THREAD

**Issue by robertcepa** [nodejs/undici#1757]
## This would solve...

I am using a library that proxies `undici` in an unintended way, changing the type of `opts.body` to `AsyncGenerator`. I would like to read the generator and reply with the result, but it's not possible because reply callback isn't awaited. This was discussed more in-depth here https://github.com/nodejs/undici/issues/1756.

This capability would also allow awaiting other async functions in the callback 

## The implementation should look like...

In my specific use-case, I'd be able to read `AsyncGenerator` and return the body string:

```
.reply(200, async (opts) => {
  const buffers = [];
  for await (const data of opts.body) {
    buffers.push(data);
  }
  const body = Buffer.concat(buffers).toString('utf8');
    
  return body;
});
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
