### ISSUE TITLE
Have `stream` expose the final URL

### ISSUE THREAD

**Issue by fb55** [nodejs/undici#1761]
## This would solve...

I am trying to use undici's `stream` method to fetch a website. I am unable to find a way to retrieve the final URL (after redirects) from the exposed API surface.

## The implementation should look like...

The URL could be a member of the stream factory data that's passed to the callback. It might also make sense to have it be a part of the context — URLs that were redirected from are already a part of the context's `history` property.

## I have also considered...

Digging into other methods. `stream` seems otherwise ideal for my use-case, so I'd like to stick with it.

## Additional context

This is for the upcoming release of the `cheerio` module.

**Comment by mcollina** [comment]
This would be amazing to add. Would you like to send a PR?

**Comment by fb55** [comment]
While attempting to implement this, I realised that the `history` array in the context will have the final location as an entry. My workaround looks like this:

```js
undici.stream(url, requestOptions, (res) => {
	/*
     * If we allow redirects and aren't using a client, we will have entries in the history.
     * The last entry will be the final URL.
     * 
     * If we don't allow redirects, we can use the original URL.
     */
    const history = res.context?.history
    const finalURL = history ? history[history.length - 1] : url
})
```

Note that this will _not_ work with clients (`(new Client(...)).stream(...)`), as they don't add to the history[^1]. The redirect logic seems broken for clients anyhow[^2], so I'm ignoring this for my use-case.

It would still be nice to have the final URL more easily available, but I can't come up with an approach that wouldn't touch many different files, making this more work than I was looking for 😄 

[^1]:  As `opts.origin` is undefined [in the `RedirectHandler`](https://github.com/nodejs/undici/blob/7b4114de5b884224fc54cd8724a57ffba80203e3/lib/handler/RedirectHandler.js#L94-L96) when using a client.
[^2]: This line will throw for a relative redirect if `opts.origin` is undefined: https://github.com/nodejs/undici/blob/7b4114de5b884224fc54cd8724a57ffba80203e3/lib/handler/RedirectHandler.js#L102

**Comment by mcollina** [comment]
That seems pretty ok as an API.

**Comment by fb55** [comment]
> That seems pretty ok as an API.

It's alright, just took me a while to realise how it's done. Closing this issue then!
