### ISSUE TITLE
Documentation website is gone.

### ISSUE THREAD

**Issue by Dbuggerx** [nodejs/undici#1763]
## Bug Description

The documentation website is gone. It apparently redirects to Node's homepage.

## Reproducible By

Go to https://undici.nodejs.org/

## Expected Behavior

The documentation website is accessible, as [it was previously
](http://web.archive.org/web/20221024213003/https://undici.nodejs.org/#/)

**Comment by mcollina** [comment]
cc @mhdawson @Trott

**Comment by Trott** [comment]
https://nodejs.github.io/undici works and redirects to https://undici.nodejs.org/#/ which also works. I'm guessing #mhdawson or someone on #nodejs/build fixed this, or maybe something was wrong with our Cloudflare stuff for undici for a while and now it's fixed? I don't know. Or maybe GitHub pages was down? But I *think* this can be closed?

**Comment by KhafraDev** [comment]
This seems to be working again
