### ISSUE TITLE
content-length never sent

### ISSUE THREAD

**Issue by JamesKyburz** [nodejs/undici#1783]
Are there any plans to optionally send the content-length header?

Some API's reject requests that are missing the header, for example sending FormData to AWS S3 returns 411.

**Comment by JamesKyburz** [comment]
Example is using the shipped version in node 18, but using the latest code here gives the same result. Validation exists to check the bytes written match the content-length header if present in the arguments to fetch, however for multipart the `content-length` might be different for each request because of the boundary data.

```sh
/tmp/undici ᐅ cat a.out
text
```

```javascript
// server.mjs
import http from 'node:http'

http
  .createServer(async function onRequest (req, res) {
    console.log('got %s:%s', req.url, req.method)
    console.log('headers %s', JSON.stringify(req.headers, null, 2))
    for await (const chunk of req) {
      process.stdout.write(chunk)
    }
    res.end()
  })
  .listen(1234)
```

```javascript
// upload.mjs
import { readFile } from 'node:fs/promises'

const file = new Blob([await readFile('./a.out')], { type: 'text/plain' })

const form = new FormData()
form.append('file', file)

const res = await fetch('http://127.0.0.1:1234', {
  method: 'POST',
  body: form
})
```

```sh
node server.mjs &
curl -F file=@./a.out http://localhost:1234
got /:POST
headers {
  "host": "localhost:1234",
  "user-agent": "curl/7.84.0",
  "accept": "*/*",
  "content-length": "202",
  "content-type": "multipart/form-data; boundary=------------------------d0bb9893ded475fd"
}
--------------------------d0bb9893ded475fd
Content-Disposition: form-data; name="file"; filename="a.out"
Content-Type: application/octet-stream

text

--------------------------d0bb9893ded475fd--

node upload.mjs
got /:POST
headers {
  "host": "127.0.0.1:1234",
  "connection": "keep-alive",
  "content-type": "multipart/form-data; boundary=----formdata-undici-0.4263000856730006",
  "accept": "*/*",
  "accept-language": "*",
  "sec-fetch-mode": "cors",
  "user-agent": "undici",
  "accept-encoding": "gzip, deflate",
  "transfer-encoding": "chunked"
}
------formdata-undici-0.4263000856730006
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: text/plain

text

------formdata-undici-0.4263000856730006--
```

**Comment by JamesKyburz** [comment]
It's the same code that S3 rejects with 411 because of the lacking `content-length` header.

**Comment by mcollina** [comment]
A few notes:

1. `transfer-encoding: chunked' encoding is a valid way to transfer data without setting a `content-length`.
2. Given `FormData` API, I _think_ we have all the data to calculate and set `content-length` correctly.
3. Do browsers send `content-length` in the very same scenario?

**Comment by mcollina** [comment]
@KhafraDev

**Comment by KhafraDev** [comment]
The issue is that we don't currently set a length for FormData bodies,
https://github.com/nodejs/undici/blob/b3447abca2464739c00dffda96a8513687985481/lib/fetch/body.js#L144-L145

**Comment by JamesKyburz** [comment]
> A few notes:
> 
> 1. `transfer-encoding: chunked' encoding is a valid way to transfer data without setting a `content-length`.
> 2. Given `FormData` API, I _think_ we have all the data to calculate and set `content-length` correctly.
> 3. Do browsers send `content-length` in the very same scenario?

Agreed, omitting content-length isn't wrong here, I thought I would raise the question to see what options we have.

Chrome sends the content-length with fetch when body is an instance of FormData.
