### ISSUE TITLE
docs: File class is not explicitly documented

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1799]
Looks like it's not explicitly documented, so I'd be a little hesitant to use it. But maybe that's just a docs fix for undici

_Originally posted by @ThisIsMissEm in https://github.com/nodejs/node/issues/45763#issuecomment-1340252100_
      
---

In general, the documentation around fetch could massively be improved. We don't seem to document Headers, Request, Response, FormData, or File.

**Comment by KhafraDev** [comment]
IMO at the very least we should document that they exist and link to MDN. Wdyt?

The main issue in the above comment is that they didn't know File was an undici export because it isn't documented anywhere.

**Comment by ThisIsMissEm** [comment]
Yeah, just documenting that they exists as exports from `import { ... } from "undici";` or `require("undici")` would make sense, even if that documentation just points to MDN, that'd be good enough for me.

**Comment by mcollina** [comment]
Yes it is! Just linking to MDN would be fine.

**Comment by KhafraDev** [comment]
You would need to create a new Fetch.md file https://github.com/nodejs/undici/tree/main/docs/api and update the sidebar https://github.com/nodejs/undici/blob/main/docsify/sidebar.md

- File: https://developer.mozilla.org/en-US/docs/Web/API/File
- FormData: https://developer.mozilla.org/en-US/docs/Web/API/FormData
- Response: https://developer.mozilla.org/en-US/docs/Web/API/Response
- Request: https://developer.mozilla.org/en-US/docs/Web/API/Request
- Headers: https://developer.mozilla.org/en-US/docs/Web/API/Headers

**Comment by ThisIsMissEm** [comment]
@VedanthB you might want to do a subheading for each, with the text "This API is implemented as per the standard, you can find documentation on the [Mozilla Developer Network].”, given each of them are classes that can be instantiated.

**Comment by VedanthB** [comment]
I have raised a PR, please review it.
