### ISSUE TITLE
bug(types) missing timeout in ProxyAgent Options 

### ISSUE THREAD

**Issue by sosoba** [nodejs/undici#1800]
## Bug Description

`ProxyAgent` constructor support `timeout` attribute which are not exposed in types.

## Reproducible By

```ts
new ProxyAgent({
  uri: 'http://proxy.example.com',
  proxyTls: {
    timeout: 1000, // Object literal may only specify known properties, and 'timeout' does not exist in type 'TlsOptions & { servername?: string; }'.ts(2322)
  }
});
```

## Expected Behavior

No errors

### Additional context

`ProxyAgent` constructor pass options to `buildConnector` function which allow to pass `timeout` parameter: 
https://github.com/nodejs/undici/blob/cd1387a30f671e65ed3d2d0fffe360f14577fccf/lib/proxy-agent.js#L37-L38
https://github.com/nodejs/undici/blob/cd1387a30f671e65ed3d2d0fffe360f14577fccf/lib/proxy-agent.js#L70-L71
https://github.com/nodejs/undici/blob/cd1387a30f671e65ed3d2d0fffe360f14577fccf/lib/core/connect.js#L14

Unfortunately type definition do not mention this attribute:
https://github.com/nodejs/undici/blob/cd1387a30f671e65ed3d2d0fffe360f14577fccf/types/proxy-agent.d.ts#L22-L23

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
