### ISSUE TITLE
Could not open '/lib64/ld-linux-x86-64.so.2'

### ISSUE THREAD

**Issue by jd-carroll** [nodejs/undici#1808]
When I encountered [this error](https://github.com/nodejs/llhttp/issues/208) when building `llhttp` I believed it could be an issue, maybe I was the first M1 mac to attempt to build the project. Now that I am encountering the same issue with `undici` I am much more skeptical and believe I am doing something wrong.

### Recap
If you're looking at this issue, it likely means you are on an M1 architecture (or at least not x86-64).

The problem is that the `prebuild-wasm` script defined in the `package.json` _is not_ platform agnostic.  The default (presumably from Docker) is to use an x86-64 architecture.  Meaning, if you are not on an x86-64 architecture you'll likely end up with an error like this:

```shell
> undici@5.14.0 build:wasm
> node build/wasm.js --docker

qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
node:child_process:903
    throw err;
    ^

Error: Command failed: /home/node/wasi-sdk-14.0/bin/clang  --sysroot=/home/node/wasi-sdk-14.0/share/wasi-sysroot  -target wasm32-unknown-wasi  -Ofast  -fno-exceptions  -fvisibility=hidden  -mexec-model=reactor  -Wl,-error-limit=0  -Wl,-O3  -Wl,--lto-O3  -Wl,--strip-all  -Wl,--allow-undefined  -Wl,--export-dynamic  -Wl,--export-table  -Wl,--export=malloc  -Wl,--export=free  /home/node/undici/deps/llhttp/src/*.c  -I/home/node/undici/deps/llhttp/include  -o /home/node/undici/lib/llhttp/llhttp.wasm
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.<anonymous> (/home/node/undici/build/wasm.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    ...
```

### Solution
For me on an M1 mac, the solution was to change the `package.json`
from:
`    "prebuild:wasm": "docker build -t llhttp_wasm_builder -f build/Dockerfile .",`
to:
`    "prebuild:wasm": "docker build --platform=linux/amd64 -t llhttp_wasm_builder -f build/Dockerfile .",`

If you are not on an M1 mac and still encountering this issue, **you'll need to specify the correct architecture for yourself**

**Comment by Uzlopak** [comment]
@mcollina 

This seems to be fixed as now there is wasm.js build script which handles the platform detection.
