### ISSUE TITLE
some unnecessary code?

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#1813]
isn't this:
https://github.com/nodejs/undici/blob/f38fbdc0f03d5c19d74d09bc0bee32c58a5afd6f/lib/fetch/body.js#L195-L199

already covered by this thing above: 
https://github.com/nodejs/undici/blob/f38fbdc0f03d5c19d74d09bc0bee32c58a5afd6f/lib/fetch/body.js#L94-L98

looks like 195-199 never happens? or am i wrong?

**Comment by KhafraDev** [comment]
It appears so. Would you like to submit a pr?

**Comment by jimmywarting** [comment]
seem like 195-199 also do not slice a copy to make it immutable
