### ISSUE TITLE
Request fails when Array.prototype['pipe'] is defined

### ISSUE THREAD

**Issue by pen-carpinelli** [nodejs/undici#1825]
## Bug Description

`undici\lib\api\api-request.js` line 54 throws an error if a custom pipe prototype for array is defined.

## Reproducible By

1. Define a custom pipe prototype for array:
`Array.prototype['pipe'] = function () { }`

2. Create a undici request with body being an array.

## Expected Behavior

The request succeeds.

## Logs & Screenshots

The request fails; the error `body.on is not a function` is thrown.

## Environment

Windows 11

**Comment by ronag** [comment]
> Create a undici request with body being an array.

An array is not a valid body. So while the error might be better this should still fail.
