### ISSUE TITLE
Low Code Coverage

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1826]
- [ ] fileapi
- [x] websocket

**Comment by ronag** [comment]
@KhafraDev

**Comment by KhafraDev** [comment]
Unfortunately WPTs aren't contributing to codecov. I tried and couldn't get it to work, #1734

**Comment by ronag** [comment]
@mcollina do you know anyone that might be willing to assist on making WPT contribute to coverage?

**Comment by KhafraDev** [comment]
I'll take another shot at it
