### ISSUE TITLE
How to set the original timeout param in http.request(url[, options][, callback])

### ISSUE THREAD

**Issue by jiajianrong** [nodejs/undici#1841]
In native nodejs api, there is a timeout config:

> timeout [<number>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type): A number specifying the socket timeout in milliseconds. This will set the timeout before the socket is connected.

https://nodejs.org/docs/latest-v12.x/api/http.html#http_http_request_url_options_callback

Want to know how to set this timeout param in undici? I think it's neither headersTimeout nor bodyTimeout. Thanks.

**Comment by jimmywarting** [comment]
Setting timeout isn't so web spec ish. IMO i think it better to write code that is more cross env friendly. And that means using `signal` to abort the request.
```js
fetch(url, { signal: AbortSignal.timeout(5000) })
```
https://stackoverflow.com/questions/46946380/fetch-api-request-timeout/50101022#50101022

**Comment by jiajianrong** [comment]
> Setting timeout isn't so web spec ish. IMO i think it better to write code that is more cross env friendly. And that means using `signal` to abort the request.
> 
> ```js
> fetch(url, { signal: AbortSignal.timeout(5000) })
> ```
> 
> https://stackoverflow.com/questions/46946380/fetch-api-request-timeout/50101022#50101022
> 
> it might not be the same thing as socket timeout but you can create a own AbortController also and abort it yourself.

Since the native http.request has already provided a timeout for socket connect timeout, why bother adding a new AbortController and setTimeout to do the same thing?

Is there a quick way to specify the native nodejs http.request's timeout?

**Comment by jiajianrong** [comment]
> > why bother adding a new AbortController and setTimeout to do the same thing?
> 
> So that your code can work as equally good as on any other platform. may it be Deno, browser, web workers or bun.js and even NodeJS itself ...or even some other developer that depends on your package and wants to run it in another env.

My app is pure Node.js. So I want to verify is if the ConnectOptions' timeout is the identical to http.request's timeout? I see [Parameter: ClientOptions](https://undici.nodejs.org/#/docs/api/Client?id=parameter-clientoptions) has a param called connect, which has a timeout param. Thanks.
![image](https://user-images.githubusercontent.com/17488218/209557776-067c43bd-8e9d-4972-8388-191e094a96de.png)


https://undici.nodejs.org/#/docs/api/Client?id=parameter-connectoptions

**Comment by jimmywarting** [comment]
maybe you can do something with `Agent`? haven't had a look in that for a long while.

**Comment by jiajianrong** [comment]
Thank you jimmy.

> maybe you can do something with `Agent`? haven't had a look in that for a long while.
