### ISSUE TITLE
`Response.url` doesn't provide hash (#)

### ISSUE THREAD

**Issue by AngeloCore** [nodejs/undici#1844]
## Bug Description

`Response.url` of the `fetch` method doesn't provide the url hash (#), but if i use the new nodejs native `fetch` method it works

## Reproducible By

Http response url

## Expected Behavior

The url should include the hash too (string after **#**), right now returns `https://example.com/ok` and it should return `https://example.com/ok#iscool=yes`

## Environment

Undici - `5.14.0`
Node - `18.8.0`

### Additional context

Thanks for the nice library

**Comment by mcollina** [comment]
cc @KhafraDev

**Comment by KhafraDev** [comment]
This is expected, https://fetch.spec.whatwg.org/#dom-response-url:
> otherwise [this](https://webidl.spec.whatwg.org/#this)’s [response](https://fetch.spec.whatwg.org/#concept-response-response)’s [URL](https://fetch.spec.whatwg.org/#concept-response-url), [serialized](https://url.spec.whatwg.org/#concept-url-serializer) with [exclude fragment](https://url.spec.whatwg.org/#url-serializer-exclude-fragment) set to true.

We are required to remove the url's hash.

**Comment by KhafraDev** [comment]
fetch should also be removing the hash, that is a bug

**Comment by AngeloCore** [comment]
> This bug is fixed in the latest version of undici, the node version you're using doesn't include the patch.

Which node version shall i use?

**Comment by KhafraDev** [comment]
> Which node version shall i use?

Only available in node v19 (either .1 or .2) unfortunately. Rather than using the global fetch, you can use undici's exported fetch instead (`const { fetch } = require('undici')`).

> Also is there any way to get the url hash?

No there isn't

**Comment by AngeloCore** [comment]
> No there isn't

I don't understand, what's the point of removing this feature?

**Comment by KhafraDev** [comment]
https://www.rfc-editor.org/rfc/rfc2396#section-4.1
```
   When a URI reference is used to perform a retrieval action on the
   identified resource, the optional fragment identifier, separated from
   the URI by a crosshatch ("#") character, consists of additional
   reference information to be interpreted by the user agent after the
   retrieval action has been successfully completed.  As such, it is not
   part of a URI, but is often used in conjunction with a URI.
```
