### ISSUE TITLE
Fetch fails when response body is empty

### ISSUE THREAD

**Issue by dreitzner** [nodejs/undici#1855]
## Bug Description
When I send json to an api and the response body is empty (content-length = 0), the response still tries to serialize the body (which will fail)
Stack trace: 
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (C:\projects\work\TUW\community-map\node_modules\@sveltejs\kit\node_modules\undici\lib\fetch\body.js:572:15)
    at successSteps (C:\projects\work\TUW\community-map\node_modules\@sveltejs\kit\node_modules\undici\lib\fetch\body.js:512:23)
    at C:\projects\work\TUW\community-map\node_modules\@sveltejs\kit\node_modules\undici\lib\fetch\util.js:814:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Reproducible By

- call any post api with json body
- return an empty body from 
Example Postman response:
![image](https://user-images.githubusercontent.com/30938967/212286391-855630e2-0fcc-4e91-8d41-95eff5cc1d1f.png)
As the API is not open to the public I can't share it here, sorry.

## Expected Behavior
JSON.parse is not executed on a body with content length header of 0

## Environment
- Win10
- node 18.12.1
- undici version 5.14.0 & 5.15.0

**Comment by ronag** [comment]
Can you please provide a repro? i.e. how are you calling undici?

**Comment by naftalimurgor** [comment]
Hey @dreitzner , @ronag 

This is probably caused by calling `JSON.parse([jsonObject])` on an invalid JSON object and would most probably be determined by how `undici` is called within the code that causes the above exhibited behavior.

**Comment by ronag** [comment]
Looks like old version undici. can you ry with latest

**Comment by ronag** [comment]
What happens in chrome? I suspect this might be correct. If the server sends content-type json then an empty body is invalid.

**Comment by dreitzner** [comment]
> Looks like old version undici. can you ry with latest

I tried with two latest versions of undici

**Comment by dreitzner** [comment]
> Can you please provide a repro? i.e. how are you calling undici?

I'm using undici through Sveltekit (uses it as fetch polyfill)

I can't really share the project repo, as it is a client project. 
I'll try to abstract the basics into a public repo on Monday.

**Comment by dreitzner** [comment]
> What happens in chrome? I suspect this might be correct. If the server sends content-type json then an empty body is invalid.

If I call the API in chrome (with native fetch through swagger), i get a success response. I'll post screenshots on Monday.

**Comment by KhafraDev** [comment]
The error is expected. Without a repro there's nothing we can do.

**Comment by jimmywarting** [comment]
> If I call the API in chrome (with native fetch through swagger), i get a success response

I doubt so, 
```js
new Response(null).json()
new Response("").json()
```
both of this fails in chrome. It's by design

**Comment by dreitzner** [comment]
Ok, I think I found the issue with the headers I was sending differently to swagger (accept: */*)
