### ISSUE TITLE
More strict isFormDataLike

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1872]
`isFormDataLike` currently only checks that the `constructor.name` is `'FormData'`. We should also check the interface as there are npm packages that have the correct name but wrong interface causing confusion where it's read as a FOrmData instead of a async generator..

**Comment by jimmywarting** [comment]
> there are npm packages that have the correct name but wrong interface

hmm, which one?

**Comment by ronag** [comment]
https://www.npmjs.com/package/form-data

**Comment by mateonunez** [comment]
Hey @ronag, what about the following check?

```js
function isFormDataLike (chunk) {
  return (
    (chunk &&
      chunk.constructor && chunk.constructor.name === 'FormData' &&
      /^(FormData)$/.test(chunk[Symbol.toStringTag])
    )
  )
}
```

Could this control be sufficient in your opinion? It checks if the instance of `chunk` contains the `Symbol.toStringTag`. It's extendible with other thirds parts (ex: formdata-node) and prevents confusion between packages like: `form-data`.

**Comment by ronag** [comment]
I'm not sure that is sufficient

**Comment by ronag** [comment]
That has the problem in the other direction. Third party module that as FormData like might not work.
