### ISSUE TITLE
Allow setting custom kProxyHeaders

### ISSUE THREAD

**Issue by Sebmaster** [nodejs/undici#1876]
## This would solve...

ProxyAgent currently only allows configuring the `Authorization` header for its CONNECT request to the proxy. I'd like to add different custom headers (e.g. User-Agent) as well. This header should only be sent in the CONNECT request, not in the tunneled requests to the target URL.

## The implementation should look like...

I think providing a way to add more headers to `kProxyHeaders` - possibly just an arbitrary headers object in the options param?

**Comment by KhafraDev** [comment]
cc @RafaelGSS

**Comment by RafaelGSS** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Sebmaster** [comment]
Done: #1877.
