### ISSUE TITLE
can't run unit tests with jest when using esm modules, typescript and undici v5.16.0

### ISSUE THREAD

**Issue by marinrusu1997** [nodejs/undici#1878]
## Bug Description

When trying to run unit tests with jest for files which use undici an error is thrown.

## Reproducible By

You can reproduce this error by cloning [this repo](https://github.com/marinrusu1997/jest-undici-esm-bug). [README](https://github.com/marinrusu1997/jest-undici-esm-bug/blob/master/README.md) contains steps to reproduce the bug.

## Expected Behavior

Unit tests should complete successfully.

## Logs & Screenshots
This is the error shown by jest:
```
 Must use import to load ES Module: /Users/marin/Development/jest-undici-esm-bug/node_modules/undici/lib/llhttp/llhttp.wasm

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:817:21)
          at async Promise.all (index 0)
          at async Promise.all (index 0)
```

Also notice that if you lower the undici version, let's say to v5.15.0, a different issue will be thrown
```
/Users/marin/Development/jest-undici-esm-bug/node_modules/undici/lib/client.js:1184
        if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                            ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/Users/marin/Development/jest-undici-esm-bug/node_modules/undici/lib/client.js:1184:29)
    at resume (/Users/marin/Development/jest-undici-esm-bug/node_modules/undici/lib/client.js:1148:3)
    at connect (/Users/marin/Development/jest-undici-esm-bug/node_modules/undici/lib/client.js:1133:3)
```

## Environment

MacOS Monterey
Node v16.14.2
Undici v5.16.0

**Comment by KhafraDev** [comment]
This is an issue with `jest.config.cjs`:

```diff
diff --git a/jest.config.cjs b/jest.config.cjs
index 3841fe0..cb6e7d5 100644
--- a/jest.config.cjs
+++ b/jest.config.cjs
@@ -8,7 +8,7 @@ module.exports = {
                },
        },
        moduleNameMapper: {
-               '^(\\.{1,2}/.*)\\.js$': '$1',
+               '^(\\.{1,2}/.*)\\.js$': '$1.js',
        },
        testMatch: ["**/test/**/*.spec.ts"]
-};
\ No newline at end of file
+};
diff --git a/test/index.spec.ts b/test/index.spec.ts
index 87d3dbb..9068d1f 100644
--- a/test/index.spec.ts
+++ b/test/index.spec.ts
@@ -7,7 +7,7 @@ describe('get request', function () {
     afterAll(stopServer);

     it('makes get request', async () => {
-        const result = await get(BASE_URL);
+        const result = await (await get(BASE_URL)).body.text();
         expect(result).toBe('Hello World');
     });
 })
```

I would experiment with `moduleNameMapper` more as it might conflict with other requires/imports/whatever it's used for. The issue is that it would change `'./llhttp/llhttp.wasm.js'` to `'./llhttp/llhttp.wasm'`, which caused the require to fail, for whatever reason. Who knows with jest?

**Comment by KhafraDev** [comment]
Okay, it seems like ts-jest is at [fault](https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/) for suggesting a bad default for moduleNameWrapper.

**Comment by cwilso03** [comment]
Yeah, ts-jest's suggestion is to just drop the `.js` suffix on imports so Jest doesn't complain about the ESM import syntax.

To fix this in my project, I changed my `jest.config.js` file to specifically exclude `llhttp.wasm.js` from that modification, like so:
```
  moduleNameMapper: {
    '^(\\.{1,2}/.*\\llhttp\\.wasm\\.js)$': '$1',
    '^(\\.{1,2}/.*)\\.js$': '$1'
  },
```
It's a bit of a hack, but until Jest has full ESM support, it gets the job done.
