### ISSUE TITLE
"blocking" missing from dispatcher type definition

### ISSUE THREAD

**Issue by xconverge** [nodejs/undici#1885]
## Bug Description

a blocking flag was added in https://github.com/nodejs/undici/pull/1034/files but was not added to https://github.com/nodejs/undici/blob/main/types/dispatcher.d.ts

I am not super clear on what this flag does/prevents/changes but wanted to try it for a long running request I am having issues with

## Reproducible By

Examination

## Expected Behavior

Type should exist

**Comment by xconverge** [comment]
I can open a PR if its just adding the one line to the file? But I was also wondering if I could get a sentence on what this is doing

**Comment by mcollina** [comment]
the comment on the doc is accurate
