### ISSUE TITLE
tests don't seem to be running in the ci

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1890]
https://github.com/nodejs/undici/pull/1889
47f574d1ac97afa3b1f17c0f8610b73b16cba9b9

None of the tests seem to be running:
```

The workflow is not valid. .github/workflows/nodejs.yml (Line: 13, Col: 5): Unexpected value 'uses' .github/workflows/nodejs.yml (Line: 14, Col: 5): Unexpected value 'with'

```

**Comment by mcollina** [comment]
I configured timeout-minutes but it's incompatible with the action we use: https://github.com/pkgjs/action/issues/53
