### ISSUE TITLE
exposing the content-type parser?

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1891]
Since undici's parser consistently outperforms node's, should we consider exposing it? It already passes the entirety of the [mimesniff](https://mimesniff.spec.whatwg.org/) [tests](https://github.com/web-platform-tests/wpt/tree/master/mimesniff).

_Originally posted by @KhafraDev in https://github.com/nodejs/performance/issues/38#issuecomment-1407118885_

**Comment by KhafraDev** [comment]
... and unlike FileReader, is actually relevant to an http client. It's low maintenance and isn't affected by node's release schedule (it's much easier to update undici to a newer version than a newer node version if a bug appears in either parser).

**Comment by metcoder95** [comment]
It is also important to highlight that some adjustments can be made to Node compared to Undici's implementation. As, e.g., the `collectASequenceOfCodePoints` can be totally optimized only to be used by the MIME class, outcoming even better results.
This can also be achieved at `Undici` if scoping the same function only to MIME class, but yeah worth it to draw that out 🙂

**Comment by KhafraDev** [comment]
collectASequenceOfCodePoints could probably be replaced with indexOf and slice

**Comment by mcollina** [comment]
I think replacing node mime parser with undici's is a decision better taken in the Node.js repo.

**Comment by KhafraDev** [comment]
I don't think it needs to be replaced, I'm wondering if undici should export it as an alternative to node's.

**Comment by mcollina** [comment]
Definitely!!

**Comment by metcoder95** [comment]
>collectASequenceOfCodePoints could probably be replaced with indexOf and slice, unsure if it would be faster

As shared in your PR, it definitely is. Didn't make that comparison within Undici but was able to come to the same conclusion by running external benchmarks comparing `indexOf`, `search`, and the `Regex#test` method. So far showed similar results, but the former always taking the lead.

Biggest step forward exposing the util 🚀
