### ISSUE TITLE
logging feature: how could i see detailed logging of the requests that are being done for the purpose of debugging

### ISSUE THREAD

**Issue by andreidiaconescu** [nodejs/undici#1912]
## This would solve...

Now when i mage fetch from node 18, i get an error: "fetch failed" without any details

## The implementation should look like...

Maybe a flag could be used to enable detailed logging

**Comment by KhafraDev** [comment]
Each error will have a [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) attached which is the actual reason the request failed.

**Comment by andreidiaconescu** [comment]
i found a way to debug : https://github.com/nodejs/undici/blob/main/docs/api/DiagnosticsChannel.md
