### ISSUE TITLE
fetch: cache headers are wronly added to conditional requests

### ISSUE THREAD

**Issue by sbellone** [nodejs/undici#1930]
## Bug Description

Conditional requests (`If-None-Match`, `If-Modified-Since`...) are not working properly with `fetch`, because some extra cache headers are added:
- When a conditional request header is set, the cache mode is [set to `no-store`](https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L1354).
- And when the cache more is `no-store`, the following headers [are added](https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L1382):
  - `Pragma: no-cache`
  - `Cache-Control: no-cache`

I didn't dig in the specs, but at least Node's reference server Express serves a non cached response and replies with a `200` instead of a `304` when those headers are present.

## Reproducible By

```js
const express = require('express');
const undici = require('undici');

const app = express();
const port = 3000;
const URL = `http://localhost:${port}/`;

app.get('/', (req, res) => {
  res.send('Hello World!');
});
const serv = app.listen(port);

(async () => {
  const res = await undici.fetch(URL);
  const etag = res.headers.get('ETag');
  console.log(`ETag: ${etag}`);

  const res2 = await undici.fetch(URL, {
    headers: {
      'If-None-Match': etag,
    },
  });
  console.log(res2.status); // 200

  const res3 = await undici.fetch(URL, {
    headers: {
      'If-None-Match': etag,
      'Cache-Control': 'no-store',
    },
  });
  console.log(res3.status); // 304

  serv.close();
})();
```

## Expected Behavior

I would expect the second request to replies with a 304 without the need to manually override the cache-control header.

Actually I would see two fixes:
- Don't add any cache headers for conditional requests, i.e. don't set the cache mode to `'no-store'` in the first place -> remove [step 15](https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L1354).
- When the cache mode is set to `no-store`, I don't get why it is transformed in a `Cache-Control: no-cache` header. Would it make sense to set it to `Cache-Control: no-store`?
  - I would also remove the deprecated `Pragma` header.

Wdyt? Thanks in advance!

## Logs & Screenshots

```
ETag: W/"c-Lve95gjOVATpfV8EL5X4nxwjKHE"
200
304
```

## Environment

Node v18.14.0
Undici v5.19.1

**Comment by ronag** [comment]
As far as I can see, we are following the spec... so it's IMO a no fix unless WinterCG says otherwise... @jasnell @KhafraDev

**Comment by ronag** [comment]
What does Deno, Bun and/or Cloudworkers do?

**Comment by sbellone** [comment]
Thanks for your answer (sorry for the tags), and good point to look in the spec!
It indeed seems to be the behaviour described in the steps listed here: https://fetch.spec.whatwg.org/#http-network-or-cache-fetch

So it would be up to the servers to ignore the `Cache-Control: no-cache` header in case of conditional request?

Or is it expected that developers have to pass both conditional and `Cache-Control` headers?
As a user perspective it's very counter-intuitive to have a no-cache header automatically added in a conditional request :thinking:

**Comment by ronag** [comment]
> So it would be up to the servers to ignore the `Cache-Control: no-cache` header in case of conditional request?
> 
> Or is it expected that developers have to pass both conditional and `Cache-Control` headers? As a user perspective it's very counter-intuitive to have a no-cache header automatically added in a conditional request 🤔

I have no idea. I think that might be a question better suited to the fetch spec repo.

**Comment by alxndrsn** [comment]
> I didn't dig in the specs, but at least Node's reference server Express serves a non cached response and replies with a `200` instead of a `304` when those headers are present.

Just a note on this: I think `express`'s behaviour is implemented in the `fresh` module at https://github.com/jshttp/fresh/blob/master/index.js#L43-L49 (via https://github.com/expressjs/express/blob/4.x/lib/request.js#L467-L484, https://github.com/expressjs/express/blob/4.x/lib/response.js#L210).
