### ISSUE TITLE
size attribute should be optional when creating multipart requests from a readable stream

### ISSUE THREAD

**Issue by HeikoTheissen** [nodejs/undici#1934]
## This would solve...

I was excited to [learn](https://stackoverflow.com/a/75338068/16462950) that `FormData` is able to create `multipart/form-data` requests from a readable stream like this:
```
var formData = new FormData();
formData.set("filedata", {
  [Symbol.toStringTag]: "File",
  name: "<filename.ext>",
  type: "<mime/type>",
  size: <file size>,
  stream: () => fs.createReadStream("<path/to/file.ext>")
});
fetch("<url>", {
  method: "POST",
  body: formData
});
```
However, this requires me to know the size in advance. Without the `size` attribute, I get the error
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: InvalidArgumentError: invalid content-length header
```
This is caused by the length computation in
https://github.com/nodejs/undici/blob/d13781b3e1ed700d68e765af7602d611383ae685/lib/fetch/body.js#L141
where `value.size = undefined` leads to `length = NaN`.

While the size is known when I stream a file, this does not work for all readable streams, for example, incoming HTTP chunked requests or responses.

## The implementation should look like...

I can work around this restriction if I replace the `fetch` statement in the code above with
```
var r = new Request("<url>", {
  method: "POST",
  body: formData
});
fetch(r.url, {
  method: r.method,
  headers: r.headers,
  duplex: "half",
  body: r.body
});
```

But then it should also work without this workaround.

## I have also considered...

n/a

## Additional context

Node v18.14.0

**Comment by KhafraDev** [comment]
This seems like a misuse of FormData due to lax restrictions to support third party File/Blobs

**Comment by mcollina** [comment]
I don't think it's possible to achieve this. _However_, once we land https://github.com/nodejs/node/pull/45258 in Node.js, you'd be able to do that with the new API.
