### ISSUE TITLE
TypeScript Type Fixes (for *.d.ts files)

### ISSUE THREAD

**Issue by joshxyzhimself** [nodejs/undici#1949]
Hi, thought of submitting a couple type fixes for the *.d.types to improve some VSCode IntelliSense.

For example, `Client.Options.socketPath` type is missing when the following lines use it:

https://github.com/nodejs/undici/blob/d04ec2b1b4145f9068fb97a43ea35f0bb3197d15/lib/client.js#L103

https://github.com/nodejs/undici/blob/d04ec2b1b4145f9068fb97a43ea35f0bb3197d15/benchmarks/benchmark.js#L27

A question before I proceed, am I correct that the types below:

https://github.com/nodejs/undici/blob/d04ec2b1b4145f9068fb97a43ea35f0bb3197d15/types/client.d.ts#L20-L52

..are intended for the constructor below?

https://github.com/nodejs/undici/blob/d04ec2b1b4145f9068fb97a43ea35f0bb3197d15/lib/client.js#L88-L115

I'm thinking of adding types for `options.socketPath`, but also noticed missing types for other parameters like `options.socketTimeout`, is it alright to include those?

Thanks.

**Comment by mcollina** [comment]
Go ahead!
