### ISSUE TITLE
fetch: Referer header is almost never being set

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1958]
I'll get around to fixing it, but it could be a good first issue for someone who wants to dive into the code but doesn't know where to start. Here's why the bug occurs:

The referrerPolicy is being set to undefined here
https://github.com/nodejs/undici/blob/bc8e2b801b0e93d7d5b8482beb8ab33967162dd0/lib/fetch/index.js#L557-L559
because we don't implement policyContainers:
https://github.com/nodejs/undici/blob/bc8e2b801b0e93d7d5b8482beb8ab33967162dd0/lib/fetch/util.js#L328-L338
which causes this condition to trigger
https://github.com/nodejs/undici/blob/bc8e2b801b0e93d7d5b8482beb8ab33967162dd0/lib/fetch/util.js#L346-L348
which means the header is never appended here
https://github.com/nodejs/undici/blob/bc8e2b801b0e93d7d5b8482beb8ab33967162dd0/lib/fetch/index.js#L1333-L1335

The easiest fix is to implement `makePolicyContainer` and `clonePolicyContainer` (both are used). Follow the steps in the links above the methods (and include the steps as comments). A "list" is an array.

**Comment by Aditya-A-G** [comment]
hey, @KhafraDev I would like to work on this issue. can you please assign this issue to me

**Comment by Aditya-A-G** [comment]
sorry due to some reason I will not be able to solve this issue
