### ISSUE TITLE
Make ProxyAgent take another Agent as an option

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#1962]
In https://github.com/nodejs/undici/blob/0beedf9911a6104aec33ef6b84b54e48f0716e95/lib/proxy-agent.js#L41, we create a new `Agent` for every `ProxyAgent`. I think we should make `ProxyAgent` take an instance of `Agent` as an option, making something like the following possible:

```ts
import { ProxyAgent, request, setGlobalDispatcher } from "undici"
import { CookieAgent } from "http-cookie-agent/undici"
import { CookieJar } from "tough-cookie"


async function test() {
  const proxyAgent = new ProxyAgent("http://127.0.0.1:10810")
  setGlobalDispatcher(proxyAgent)
  const jar = new CookieJar()
  const agent = new CookieAgent({ cookies: { jar } })
  await request("https://test.com", {
    dispatcher: agent,
  })
}
```
Help would be greatly appreciated! 🙏

_Originally posted by @tgioer in https://github.com/nodejs/undici/discussions/1957_

**Comment by RishabhKodes** [comment]
Hey @mcollina, I'm taking up this issue.

**Comment by jabali2004** [comment]
Hey @mcollina 👋🏼
Can we close that one? Since #2003 has been merged.
