### ISSUE TITLE
duplex option is required when sending a body.

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1963]
https://github.com/nodejs/undici/actions/runs/4241282379/jobs/7371309085

```
Error: or [Error]: RequestInit: duplex option is required when sending a body.
    at fetch (/home/runner/work/undici/undici/index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by ronag** [comment]
@KhafraDev

**Comment by KhafraDev** [comment]
unfortunately the same issue from https://github.com/web-platform-tests/wpt/pull/36268

**Comment by KhafraDev** [comment]
There's no way to disable a single test (at least to my knowledge, they're not supposed to crash the runner if they fail), so the alternative is to disable the file altogether (disables many tests) or to patch it. I patched it previously, but the change was undone in #1954. I'll look for a way to fix it in the runner, or patch it again if I can't figure anything out
