### ISSUE TITLE
feat: can we mention 🍊 `tangerine` in the README?

### ISSUE THREAD

**Issue by titanism** [nodejs/undici#1971]
We released 🍊 [Tangerine](https://github.com/forwardemail/tangerine), which is a DNS over HTTPS ("DoH") API that is a 1:1 drop-in replacement with native Node.js DNS module `dns.promises.Resolver`.  It's actually _faster_ ⚡ than the built-in Node dns module.  This project uses `undici` under the hood, and also has support for caching, AbortController, and more.  If the authors of `undici` deemed this to be a good fit for the README, we welcome them to add it.

cc @mcollina @ronag @ethan-arrowood

**Comment by mcollina** [comment]
Oh we did not respond in time I guess. I don't think we should list Tangering here, as Node.js tends not to pick winners in the ecosystem.

Note that undici.request() is several times faster than fetch(), so any minimal difference in the algorithm will count. I've never analyzed/optmized POST requests specifically so it's technically possible that there might be some difference but I would not expect to be huge. I would not recommend using fetch for your use case.

**Comment by mcollina** [comment]
Feel free to open issue if you find performance glitches or similar, we'd be happy to take a look.

**Comment by mcollina** [comment]
From my understanding of the source code, `undici.request` should handle `bodyTimeout` per request. Could you create a new issue with a reproducible example?
