### ISSUE TITLE
Undici does not set the Content-Type when sending data zipped with zlib

### ISSUE THREAD

**Issue by ImRodry** [nodejs/undici#1972]
## Bug Description

When sending data zipped by node's zlib (in the form of a Buffer, the type returned by gzipSync) in the body of a fetch request, undici does not set the Content-Type at all, when it should set it to application/gzip

## Reproducible By

1. Define the string you want to send zipped
2. Import gzipSync from node:zlib
3. Zip the string defined earlier with gzipSync(stringVar)
4. send it through the body of a request fetch("http://localhost", { method: "POST", body: zippeddata })
5. Check the content-type sent is undefined either through the response or the receiving API.

## Expected Behavior

Undici should set the content-type to application/gzip

## Logs & Screenshots

I think the issue is easily reproducible, not sure what logs to include here

## Environment

Happens regardless of OS on Node.js v18.14.1

### Additional context

I read through the code and I understand this isn't explicitly defined in the spec, I just thought it could be integrated since zlib is a library built-in to node, so it would make sense that buffers produced by it would get their content-type automatically inferred. If there's a way to get undici to do this that I'm not aware of, please let me know

**Comment by mcollina** [comment]
Thanks for reporting. This is a missing feature by choice. There needs to be a safe way to handle this generically, but I don't know about it.

Maybe @KhafraDev can help, but I don't feel this is something we can support.

**Comment by KhafraDev** [comment]
We could detect if a body has been gzipped pretty easily, but the issue above still remains.

According to https://datatracker.ietf.org/doc/html/rfc1952
```
These have the fixed values ID1 = 31 (0x1f, \037), ID2 = 139
            (0x8b, \213), to identify the file as being in gzip format.
```
so we *could* check if a body has been gzipped via something like
```js
const gzd = zlib.gzipSync('abc')

if (Buffer.isBuffer(gzd) && gzd[0] === 0x1f && gzd[1] === 0x8b) {
  // set content-type header here
}
```

it would be easier to set the content-type header on your end

**Comment by ImRodry** [comment]
Yeah I know it would, but I didn't know undici wasn't setting this and just lost a good few hours trying to debug this. I feel like if I'm zipping a file it would be logical for the content-type to be application/gzip without me having to repeat it. If that's something you can add to the library I would highly appreciate it. It also makes sense given that undici is made by node and zlib is a library within node itself, so compatibility between the two would be logical IMO. I believe zlib itself also checks for those same headers when unzipping so that would be a safe check

**Comment by mcollina** [comment]
@KhafraDev do you know if this is covered by WPTs?

**Comment by KhafraDev** [comment]
no, it's not

**Comment by mcollina** [comment]
Then I would not implement it.

**Comment by ronag** [comment]
I think this is a can't fix.

**Comment by ImRodry** [comment]
Yeah understandable
