### ISSUE TITLE
Request Body as Iterable/Iterator

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#198]
Current flow is to just use `Readable.from(i)`. Which is fine. But we could make this faster.

**Comment by mcollina** [comment]
Note that strings and buffer should not be iterated upon.

**Comment by Ethan-Arrowood** [comment]
Whats status of this? I'd like to take a shot at it if possible 😄

**Comment by ronag** [comment]
Go for it

**Comment by Ethan-Arrowood** [comment]
@ronag can you provide any more info on the intended solution here? Any pointers are appreciated, thank you 😄

**Comment by ronag** [comment]
Easiest way to do it is to detect whether it is a generator and convert it into a stream.

**Comment by Ethan-Arrowood** [comment]
So in this part: https://github.com/nodejs/undici/blob/c17ae444963a112aa3bbbb4c06ad77e98aec6212/lib/core/request.js#L67 ?

**Comment by Ethan-Arrowood** [comment]
Since its been a while since I made any progress on this I'm going to self-mark this as **stale**. If someone else wants to take a stab at implementing iterators please do so ❤️
