### ISSUE TITLE
Request headers may potentially not have a proper ending (`\r\n\r\n`). 

### ISSUE THREAD

**Issue by webcarrot** [nodejs/undici#1981]
## Bug Description

It's possible that proper ending of request headers (`\r\n\r\n`) will be not send immediately together with headers chunk due to:

👉🏻 https://github.com/nodejs/undici/blob/main/lib/client.js#L1677
```js
socket.write(`${header}transfer-encoding: chunked\r\n`, 'ascii')
```

### Potential fix:

```js
    if (bytesWritten === 0) {
      if (!expectsPayload) {
        socket[kReset] = true
      }

      if (contentLength === null) {
        socket.write(`${header}transfer-encoding: chunked\r\n\r\n`, 'ascii')
        socket.write(`${len.toString(16)}\r\n`, 'ascii')
      } else {
        socket.write(`${header}content-length: ${contentLength}\r\n\r\n`, 'ascii')
      }

    } else if (contentLength === null) {
        socket.write(`\r\n${len.toString(16)}\r\n`, 'ascii')
    }

```

## Reproducible By

It's quite random and depends on Socket/system behaviours - "Sometimes" 😉 

👀 👉🏻 Additional context

## Expected Behavior

Chunk containing request headers always contains proper headers ending - `\r\n\r\n`.

### Additional context

Related issue: https://github.com/uNetworking/uWebSockets.js/issues/879 

In this issue I have tried to emulate behaviour of `undici` - especially: https://github.com/uNetworking/uWebSockets.js/issues/879#issuecomment-1451560911

**Comment by ronag** [comment]
undici does the right thing here, but I guess it wouldn't hurt to send them at the same time.
