### ISSUE TITLE
SyntaxError on valid response (apparently)

### ISSUE THREAD

**Issue by rozzilla** [nodejs/undici#2012]
## Bug Description

Doing a call to `https://nominatim.openstreetmap.org/search?format=json&q=milan` using `request` method from `undici` results in `SyntaxError: Unexpected token < in JSON at position 0`. The same, with `fetch` from Node.js, works fine.

## Reproducible By

Code for Node.js (working correctly):
```
(async () => {
  const response = await fetch(
    "https://nominatim.openstreetmap.org/search?format=json&q=milan"
  );

  const data = await response.json();
  console.log("the data", data);
})();

```

Code for `undici`:
```
const { request } = require("undici");

(async () => {
  const { body } = await request(
    "https://nominatim.openstreetmap.org/search?format=json&q=milan"
  );

  const data = await body.json();
  console.log("the data", data);
})();
```

## Expected Behavior

Since the API mentioned returns a valid JSON, `undici` shouldn't throw.

## Logs & Screenshots

![image](https://user-images.githubusercontent.com/3996291/225661915-7d2adb62-700d-4eb2-a23b-bc5e75719d57.png)

## Environment

MacOS 13.2.1 (22D68) - Node.js v18.15.0

### Additional context

Replacing the call to another URL (f.e. `https://jsonplaceholder.typicode.com/todos/1`) the same code works on `undici` too. Available to provide more info if needed.

**Comment by KhafraDev** [comment]
The request is returning html.
