### ISSUE TITLE
When Content-Length is specified, fetch() raises RequestContentLengthMismatchError on redirection

### ISSUE THREAD

**Issue by geryogam** [nodejs/undici#2021]
## Bug Description

When the `Content-Length` request header field is manually specified (instead of automatically generated), `fetch()` raises a `RequestContentLengthMismatchError` in case of redirection.

## Reproducible By

We send a `POST` request to the `/sirene/public/recherche` target URI to search for a non-existing company whose name `foobarbaz` is provided in the request body:

```javascript
const uri = 'https://www.sirene.fr/sirene/public/recherche';
const method = 'POST';
const body = 'recherche.sirenSiret=&recherche.raisonSociale=foobarbaz&recherche.adresse=&recherche.commune=&recherche.excludeClosed=true&__checkbox_recherche.excludeClosed=true&recherche.captcha=';
const headers = {'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(body)};
const response = await fetch(uri, {method, headers, body});
```

The target URI `/sirene/public/recherche` replies with a `302` response with a `Location: /sirene/error/autre.action` header field. So `fetch` automatically (by default) redirects the original request to the target URI `/sirene/error/autre.action` and raises a `RequestContentLengthMismatchError`:

```
Uncaught TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at async REPL5:1:47 {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (node:internal/deps/undici/undici:9907:41)
      at _resume (node:internal/deps/undici/undici:9885:33)
      at resume (node:internal/deps/undici/undici:9787:7)
      at connect (node:internal/deps/undici/undici:9776:7) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

## Expected Behavior

The specified `Content-Length` request header field is correct in the original request so I don’t expect a `RequestContentLengthMismatchError` after automatic redirection.

## Logs & Screenshots

I assume that during redirection, `fetch()` resends the original request but with the following modifications:

- the target URI is changed from `/sirene/public/recherche` to `/sirene/error/autre.action`;
- the `POST` request method is changed to `GET`;
- the request body is removed.

But it doesn’t remove the content-specific header fields (`Content-Type` and `Content-Length` here), contrary to what the latest HTTP specification [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#section-15.4-6.5.1) recommends:

> When automatically following a redirected request, the user agent SHOULD resend the original request message with the following modifications:
> 
> 1. Replace the target URI with the URI referenced by the redirection response's Location header field value after resolving it relative to the original request's target URI.
> 2. […]
> 3. […]
> 4. Change the request method according to the redirecting status code's semantics, if applicable.
> 5. **If the request method has been changed to GET or HEAD, remove content-specific header fields, including (but not limited to) Content-Encoding, Content-Language, Content-Location, Content-Type, Content-Length, Digest, Last-Modified.**

This non-compliance to point 5 of Undici likely causes the `RequestContentLengthMismatchError`. Indeed, sending a `GET` request without a body but with a `Content-Length` header field raises the same `RequestContentLengthMismatchError`:

```javascript
fetch('http://example.com/', {headers: {'Content-Length': 0}})
```

Output:

```
Uncaught TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (node:internal/deps/undici/undici:9907:41)
      at _resume (node:internal/deps/undici/undici:9885:33)
      at resume (node:internal/deps/undici/undici:9787:7)
      at connect (node:internal/deps/undici/undici:9776:7) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

## Environment

MacOS 11.6.7, Node 19.7.0.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that. In this case we need  both the server and the client.

A PR with a fix would also be highly appreciated!

**Comment by ronag** [comment]
@KhafraDev did we or the fetch spec miss a step in the redirection logic?

**Comment by KhafraDev** [comment]
No, the `content-length` header is a forbidden header, but we don't filter headers.

**Comment by geryogam** [comment]
> Can you provide steps to reproduce?

@mcollina The code to reproduce the issue is already in the ‘Reproducible By’ section.

**Comment by ronag** [comment]
> No, the content-length header is a forbidden header, but we don't filter headers.

What does the spec say? Do we need to filter or throw an error?

**Comment by KhafraDev** [comment]
The RFC mentioned in the OP recommends removing some headers on redirect, that's likely what we should do.

**Comment by mcollina** [comment]
> @mcollina The code to reproduce the issue is already in the ‘Reproducible By’ section.

As I said in https://github.com/nodejs/undici/issues/2021#issuecomment-1480718584, we need both the client and server.

**Comment by KhafraDev** [comment]
Here's a small repro

```mjs
import { once } from 'events'
import { createServer } from 'http'
import { fetch } from './index.js'

const server = createServer((req, res) => {
  if (req.url === '/redirect') {
    res.writeHead(302, { Location: '/redirect2' })
    res.end()
    return
  }

  console.log('hello', req.url)
}).listen(0)

await once(server, 'listening')

await fetch(`http://localhost:${server.address().port}/redirect`, {
  method: 'POST',
  body: 'a+b+c',
  headers: {
    'content-length': Buffer.byteLength('a+b+c')
  }
})
```

**Comment by ronag** [comment]
@KhafraDev 

```
To validate a [header](https://fetch.spec.whatwg.org/#concept-header) (name, value) for a [Headers](https://fetch.spec.whatwg.org/#headers) object headers:

If name is not a [header name](https://fetch.spec.whatwg.org/#header-name) or value is not a [header value](https://fetch.spec.whatwg.org/#header-value), then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

If headers’s [guard](https://fetch.spec.whatwg.org/#concept-headers-guard) is "immutable", then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

If headers’s [guard](https://fetch.spec.whatwg.org/#concept-headers-guard) is "request" and (name, value) is a [forbidden request-header](https://fetch.spec.whatwg.org/#forbidden-request-header), then return false.

If headers’s [guard](https://fetch.spec.whatwg.org/#concept-headers-guard) is "response" and name is a [forbidden response-header name](https://fetch.spec.whatwg.org/#forbidden-response-header-name), then return false.

Return true.
```

The header validation should fail with content-length and therefore it should just be thrown away as far as I can see?

**Comment by ronag** [comment]
I don't think our code any longer corresponds with https://fetch.spec.whatwg.org/#headers-class. Maybe time to have another iteration?

**Comment by KhafraDev** [comment]
The headers are being removed in fetch, this is a bug elsewhere:
https://github.com/nodejs/undici/blob/e6fc80f809d1217814c044f52ed40ef13f21e43c/lib/fetch/index.js#L1177-L1195

**Comment by KhafraDev** [comment]
Oh nvm, adding `content-length` to that list fixes it lol

**Comment by ronag** [comment]
I think it's in the header append guard logic where it should be removed.

**Comment by ronag** [comment]
> > Maybe time to have another iteration?
> 
> I've purposefully kept it close to Rafael's version, as it makes headers faster by tenfold (using a map instead of an array). Unfortunately that decision snowballed to where the implementation is completely different from what the spec says to do.

I have mixed feelings on this... Not sure what to think.

**Comment by geryogam** [comment]
> I don't think we should filter any headers in fetch. Adding content-length to requestBodyHeader fixes the issue in a spec-compliant & rfc compliant way.

Yes, currently the list is (https://github.com/nodejs/undici/blob/v5.21.0/lib/fetch/constants.js#L51-L56):

```javascript
const requestBodyHeader = [
  'content-encoding',
  'content-language',
  'content-location',
  'content-type'
]
```

To be RFC 9110 compliant, we should remove the following header fields (https://www.rfc-editor.org/rfc/rfc9110#section-15.4-6.5.1):

> 5. If the request method has been changed to GET or HEAD, remove content-specific header fields, including (but not limited to) Content-Encoding, Content-Language, Content-Location, Content-Type, Content-Length, Digest, Last-Modified.

So:

```javascript
const requestBodyHeader = [
  'content-encoding',
  'content-language',
  'content-location',
  'content-type',
+ 'content-length',
+ 'digest',
+ 'last-modified'
]
```

**Comment by geryogam** [comment]
Thank you for solving this issue guys.
