### ISSUE TITLE
MockPool interceptor body is AsyncGenerator instead of string

### ISSUE THREAD

**Issue by DASPRiD** [nodejs/undici#2024]
## Bug Description

When trying to intercept a request based on its body, I noticed that those intercepts always fail. I was initially using this with NodeJS 18's native fetch, but thinking that it might be an incompatibility, I switched to using Undici directly. I still experience the same issue there though.

Basically the body for the intercept call is `AsyncGenerator` instead of a `string`.

This does sound similar to https://github.com/nodejs/undici/issues/1447 (which was resolved) but happens with Undici's fetch client as well.

## Reproducible By

```js
import { fetch } from "undici";
import { MockAgent, setGlobalDispatcher } from "undici";

const mockAgent = new MockAgent();
mockAgent.disableNetConnect();
const mockPool = mockAgent.get("https://localhost");
setGlobalDispatcher(mockPool);

mockPool
  .intercept({
    path: "/test",
    method: "POST",
    body: (body) => {
      console.log(body);
      return true;
    },
  })
  .reply(204);

const response = await fetch("http://localhost/test", {
  method: "POST",
  body: "test",
});
console.log(response.status);
```

## Expected Behavior

The intercept should work when matching against a given string body.

## Environment

- Node v18.15.0
- Undici v5.21.0

**Comment by KhafraDev** [comment]
There are 2 bugs in your example:
1. You create a mock for **https**://localhost, but fetch **http**://localhost
2. You set the global dispatcher to the mockPool, when it should be mockAgent.

Once those 2 issues were fixed the example should work!
