### ISSUE TITLE
More informative error when connecting to unsupported HTTP/2 end-point

### ISSUE THREAD

**Issue by Songkeys** [nodejs/undici#2043]
## Bug Description

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HTTPParserError: Expected HTTP/
    at Parser.execute (/Users/songkeys/GitHub/playground/node_modules/undici/lib/client.js:572:15)
    at Parser.readMore (/Users/songkeys/GitHub/playground/node_modules/undici/lib/client.js:516:12)
    at TLSSocket.onSocketReadable (/Users/songkeys/GitHub/playground/node_modules/undici/lib/client.js:940:10)
    at TLSSocket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'HPE_INVALID_CONSTANT',
  data: '\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x01\x00\x00\x10\x00\x00\x03\x00\x00\x00\x01\x00\x05\x00\x00@\x00\x00\x06\x00\x00\x1F@'
}

Node.js v19.3.0
```

## Reproducible By

```js
import { request } from "undici";

request("https://api.push.apple.com");
```

## Environment

Node.js v19.3.0

undici@5.21.0

### Additional context

This error only occurs on this specific endpoint.

**Comment by Songkeys** [comment]
Oh I just realized the API is HTTP/2 and `undici` only supports HTTP/1.1 so far. You were right. The issue might be the uninformative error message then.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Songkeys** [comment]
@mcollina Yes. I'm interested. Give me some time :)

**Comment by Songkeys** [comment]
@mcollina This looks more tough than I thought.

I tried to compare the first chunk read from the socket with http2 preface:

```js
const HTTP2_PREFACE = 'PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n';
const http2PrefaceBuffer = Buffer.from(HTTP2_PREFACE, 'utf8');
return chunk.slice(0, http2PrefaceBuffer.length).equals(http2PrefaceBuffer);
```

but the chunk doesn't seem to make any sense. Take the API response in this issue as an example, it's: `"\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x01\x00\x00\x10\x00\x00\x03\x00\x00\x00\x01\x00\x05\x00\x00@\x00\x00\x06\x00\x00\x1F@"`.

I also tried to use `socket.alpnProtocol` to tell if the server is h2. but it always returns false.

Any instruction?

**Comment by mcollina** [comment]
I think we can just mention that we expected HTTP/1.1 and we didn't get it (leaving to the reader to figure out what protocol was on the wire).
