### ISSUE TITLE
Sending a DELETE request with "Content-Length: 0" fails with a RequestContentLengthMismatchError

### ISSUE THREAD

**Issue by ouuan** [nodejs/undici#2046]
## Bug Description

Sending a DELETE request with "content-length: 0" fails with a RequestContentLengthMismatchError.

The specification says "A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body", but according to [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119), "SHOULD NOT" means "NOT RECOMMENDED", so it's not reasonable to fail a request for this reason.

Even if the Content-Length header "MUST NOT" be sent, the current implementation would still be problematic:

1. A better behavior could be removing the header instead of failing the request.
2. The request only fails when Content-Length is set to zero, but not when it is not zero and matches the length of the body. Note that the DELETE method does not anticipate a body.
3. The error message is unhelpful. It says "Request body length does not match content-length header" instead of "Content-Length should not be set for the DELETE method".

## Reproducible By

```javascript
fetch('https://example.com', { method: 'DELETE', headers: { 'content-length': '0' } })
```

## Expected Behavior

The request succeeds, either as it is or with the Content-Length header removed.

## Logs & Screenshots

```
> Uncaught TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (node:internal/deps/undici/undici:9907:41)
      at _resume (node:internal/deps/undici/undici:9885:33)
      at resume (node:internal/deps/undici/undici:9787:7)
      at connect (node:internal/deps/undici/undici:9776:7) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

## Environment

Reproducible on both Node v18.15.0 and v19.8.1

## Additional Context

Related codes:

https://github.com/nodejs/undici/blob/5f3b8e16a9aa33fe72d640fe271d8e7a5748321a/lib/client.js#L1333-L1366

**Comment by KhafraDev** [comment]
RFC 2119 also says about "SHOULD NOT":
```
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.
````

Do you have a use case that justifies this?

**Comment by ronag** [comment]
PR welcome

**Comment by ronag** [comment]
FYI I'm not sure atm what I think is right or wrong here. What is the realistic scenario where this is a problem? @KhafraDev shouldn't content-length be removed by fetch anyway? Why isn't it?

**Comment by ouuan** [comment]
> What is the realistic scenario where this is a problem?

I'm using Nuxt, which is using Nitro, whose proxy is based on `node-http-proxy`. And the problem comes from this code:

https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy/passes/web-incoming.js#L34-L40

`node-http-proxy` is not actively maintained, and it cost me a few hours to find where the bug was. It's certainly a bug of `node-http-proxy` in my case, but I just think it doesn't worth the effort to fix the bug when the Content-Length header is mistakenly added somewhere.

**Comment by ronag** [comment]
> content-length is removed on redirect in fetch, this bug would also affect undici.request

I'm aware it affects undici.request, however I wouldn't consider it a bug per se in that context.

**Comment by KhafraDev** [comment]
I think failing the request is fine in fetch too.

**Comment by ronag** [comment]
@ouuan If you want to make a PR to change this behavior, we'd consider merging it.

**Comment by kaloyanBozhkov** [comment]
I encountered this error as well

**Comment by kmvan** [comment]
Should the server ignore `content-length` when it receives a `DELETE` request?

**Comment by metcoder95** [comment]
Servers most likely can decline the request if a `content-length` and/or body of the request is received. It is highly recommended to not do it at all at the client side. From [RFC-9110](https://www.rfc-editor.org/rfc/rfc9110#DELETE):

> Although request message framing is independent of the method used, content received in a DELETE request has no generally defined semantics, cannot alter the meaning or target of the request, and might lead some implementations to reject the request and close the connection because of its potential as a request smuggling attack ([Section 11.2](https://www.rfc-editor.org/rfc/rfc9112#section-11.2) of [[HTTP/1.1](https://www.rfc-editor.org/rfc/rfc9110#HTTP11)]). A client SHOULD NOT generate content in a DELETE request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported

**Comment by pxue** [comment]
Well just spent the entire day to dig through this issue, and also just realized all of our users couldn't DELETE things in the app for a good few months.

The discrepancy is where undici expects content length to be 'null' https://github.com/nodejs/undici/blob/5f3b8e16a9aa33fe72d640fe271d8e7a5748321a/lib/client.js#L1356 and not zero

**Comment by KhafraDev** [comment]
I think we should allow this. If anyone wants to send in a PR, that would be great.

**Comment by pxue** [comment]
> I think we should allow this. If anyone wants to send in a PR, that would be great.

@KhafraDev is the fix here to allow 0-ish values in client.js? If so I can open a PR and write some tests

**Comment by KhafraDev** [comment]
I would only expect it to be set to 0 (outside of where it's already being done) if the method is DELETE and content-length is 0, and definitely a comment linking to this issue.

**Comment by pxue** [comment]
Ok got it, just to confirm, would I have to check for both integer 0 and string '0'?

For example, the source of the issue comes from node-http-proxy where the content-length is being forced to '0'
https://github.com/http-party/node-http-proxy/blob/9b96cd725127a024dabebec6c7ea8c807272223d/lib/http-proxy/passes/web-incoming.js#L37

**Comment by KhafraDev** [comment]
no, it's an integer (the code in the linked issue only checks for 0)

**Comment by pxue** [comment]
PR opened, let me know if that's a passable fix @KhafraDev

**Comment by sahanxdissanayake** [comment]
Getting this same error when calling a python/flask service hosted on vercel from a server action with fetch

```
{
  error: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11457:11) {
    cause: RequestContentLengthMismatchError: Request body length does not match content-length header
        at AsyncWriter.end (/Users/sahan/dashboard/node_modules/next/dist/compiled/undici/index.js:1:82040)
        at writeIterable (/Users/sahan/dashboard/node_modules/next/dist/compiled/undici/index.js:1:80712) {
      code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
    }
  }
}
```

**Comment by sahanxdissanayake** [comment]
Moved to axios and the request seems to be working now. Will report back if there are further issues.
