### ISSUE TITLE
HeadersList.clear() does not clear .cookies

### ISSUE THREAD

**Issue by smilingthax** [nodejs/undici#2050]
Since `.getSetCookie()` was introduced, `HeaderList` has an additional `.cookies` field, which is not updated on `.clear()`:

https://github.com/nodejs/undici/blob/816dcaa5bb39c477a66b8abb497b5cddcd9cdda4/lib/fetch/headers.js#L95-L98

This is observable:
```
const req1 = new undici.Request('http://localhost', {
  headers: {
    'set-cookie': 'a=1'
  }
});
console.log([...req1.headers]);   // --> [ [ 'set-cookie', 'a=1' ] ]
const req2 = new undici.Request(req1, {
  headers: {}
});
console.log([...req2.headers]);    // --> []
console.log(req2.headers.getSetCookie());   // --> [ 'a=1' ]   - unexpected!
```

**Comment by KhafraDev** [comment]
Can you provide a code sample that uses undici.fetch & a server?
