### ISSUE TITLE
put `ErrorEvent` and `CloseEvent` on global scope

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#2084]
I think this is more targeted to the nodejs/node repo.
but since they both are implemented here in undici i will instead post it here.

CloseEvent and ErrorEvent exist globally in Deno, but not in NodeJS. 
I guess Deno has it b/c of WebSocket and FileReader, Workers and globalThis.onerror.

Any way... my feature request is to make those two accessible on the globalThis...

I tried last weak to build a more spec compatible Worker last week and wanted to use ErrorEvent but was a tiny bit surprised that it where not introduced earlier. 

related to: https://github.com/nodejs/node/issues/47587

**Comment by KhafraDev** [comment]
Adding globals is out of scope for undici. Once undici exports WebSocket in its "fetch" bundle (which node is using), I can see the errors also being exported.

**Comment by mcollina** [comment]
We are happy to update the fetch bundle with whatever API Node.js needs, but it's not up to us to decide.
