### ISSUE TITLE
tap can't run tests because node option --experimental-wasm-simd doesn't exist in v20

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2086]
Refs: https://github.com/nodejs/undici/actions/runs/4775514329/jobs/8489868744

https://github.com/nodejs/undici/blob/eeaa0735e1c51dd09706dff97ba06e63ae9fc72b/.taprc#L8

It might be safe to remove the option for lower versions but I'm not sure.

**Comment by targos** [comment]
The flag was removed in https://chromium-review.googlesource.com/c/v8/v8/+/3957636
They say it was enabled by default in Chrome 91. This corresponds to Node.js v16.4.0.

**Comment by KhafraDev** [comment]
thanks, I couldn't find info on it :) thinking it over I doubt removing the flag will cause issues in v14. Ill test it tomorrow if no one else does so before me
