### ISSUE TITLE
docs: Errors documentation is missing 6 errors from table list

### ISSUE THREAD

**Issue by titanism** [nodejs/undici#2090]
The following errors are not documented at <https://github.com/nodejs/undici/blob/main/docs/api/Errors.md>:

- `UND_ERR`
- `UND_ERR_CONNECT_TIMEOUT`
- `UND_ERR_HEADERS_TIMEOUT`
- `UND_ERR_HEADERS_OVERFLOW`
- `UND_ERR_BODY_TIMEOUT`
- `UND_ERR_RESPONSE_STATUS_CODE`

**Comment by ronag** [comment]
I don't know about `UND_ERR`? I don't think we ever throw that.
