### ISSUE TITLE
Is there a Discrepency between Fetch Specs and RFC 7231? - "Request with GET/HEAD method cannot have body"

### ISSUE THREAD

**Issue by nickwelp** [nodejs/undici#2098]
## Bug Description
"Request with GET/HEAD method cannot have body." is not true, at least not according to https://www.rfc-editor.org/rfc/rfc7231#page-24

"A payload within a GET request message has no defined semantics." Which is to say it is allowed to exist.

I read the Fetch Specs and it seemed like it didn't explicitly forbid GET BODY; however I may have overlooked something. 
So why is this a feature of Fetch in node? "Request with GET/HEAD method cannot have body." is no longer valid.

Did I overlook something in the Fetch Spec?

**Comment by KhafraDev** [comment]
The next sentence in the RFC: "...sending a payload body on a GET request might cause some existing
   implementations to reject the request."

**Comment by KhafraDev** [comment]
Fetch also doesn't support GET requests with bodies

https://github.com/whatwg/fetch/issues/551 / https://github.com/whatwg/fetch/issues/83

**Comment by nickwelp** [comment]
Are you saying Fetch is an Antiquated Implementation? They left that caveat for implementations made before 2014.
