### ISSUE TITLE
RequestContentLengthMismatchError with undici 5.22.0 when sending FormData body with stream

### ISSUE THREAD

**Issue by asciidisco** [nodejs/undici#2104]
## Bug Description

Since version 5.22.0 sending a stream using FormData body fails with error ` RequestContentLengthMismatchError: Request body length does not match content-length header` `UND_ERR_REQ_CONTENT_LENGTH_MISMATCH` when no `size` property has been set while appending form data.

## Reproducible By

Execute this code in order to reporduce the issue (server url doesn't matter, as the request will never be send):

```js
const fs = require('node:fs')
const { Client, FormData, Response } = require('undici')

const client = new Client('http://some.example')
const formData = new FormData()

formData.append('map', JSON.stringify({
  0: [`variables.image`] 
}))

formData.append('0', {
  type: 'image/jpeg',
  name: 'avatar.jpg',
  stream() { return fs.createReadStream('./some_random_image.jpg') },
  [Symbol.toStringTag]: 'File'
})

async function main() {
  await client.request({
    path: `/graphql`,
    method: 'POST',
    headers: { 
      ...(new Response(formData)).headers,
      accept: 'text/plain',
    },
    body: formData
  })
}

main()
```

## Expected Behavior

With Undici version lower  and equal `5.21.2` this works, not that it also works if you set the `size` property of the form data like  so:

```js
formData.append('0', {
  size: fs.statSync('./some_random_image.jpg').size,
  type: 'image/jpeg',
  name: 'avatar.jpg',
  stream() { return fs.createReadStream('./some_random_image.jpg') },
  [Symbol.toStringTag]: 'File'
})
```

While this might work with files being read from the file system, as you can stat them

## Logs & Screenshots

```
 errorRequest(client, request, new RequestContentLengthMismatchError())
                                    ^

RequestContentLengthMismatchError: Request body length does not match content-length header
    at write (/Users/asciidisco/Desktop/file-upload/node_modules/undici/lib/client.js:1373:37)
    at _resume (/Users/asciidisco/Desktop/file-upload/node_modules/undici/lib/client.js:1325:29)
    at resume (/Users/asciidisco/Desktop/file-upload/node_modules/undici/lib/client.js:1183:3)
    at connect (/Users/asciidisco/Desktop/file-upload/node_modules/undici/lib/client.js:1168:3) {
  code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
}

Node.js v20.0.0
```

## Environment

OS: macOS 13.4 Beta,
Node: Node v20.0.0

### Additional context

I believe this issue was introduced by @KhafraDev with [this commit](https://github.com/nodejs/undici/pull/2066/commits/a5487ec81b4e9b9fbfb7cba1e825e50979f33683) as in the scenario I described the `content-length` won't be able to be calculated & as @fengmk2 mentioned leads to `bodyStream.length` to be evaluated to `NaN` therefore triggering the error

**Comment by KhafraDev** [comment]
fixed in 8ffad9d782146d5dd405b81eeb2cbfe97c6a03b1
