### ISSUE TITLE
nullish coalescing assignment(??=) is not support in node 14

### ISSUE THREAD

**Issue by quanru** [nodejs/undici#2117]
## Bug Description

nullish coalescing assignment(??=) is not support in node 14, but undici require a node version >= 14

## Reproducible By

![image](https://github.com/nodejs/undici/assets/11739753/8a7059d5-b2d8-4b36-bb6f-59bed48de76f)

## Expected Behavior

not throw error in node 14

## Logs & Screenshots

![image](https://github.com/nodejs/undici/assets/11739753/1b3a03c8-6467-46b8-84b5-3a49bd3360bf)

## Environment

Node v14.21.3
MacOS 13.3.1 (a) (22E772610a)

### Additional context

no

**Comment by ronag** [comment]
Node 14 is EOL. We have dropped support.
