### ISSUE TITLE
fetch: set body with byte reading support

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2122]
Currently this throws an error:
```js
const response = await fetch('https://www.google.com')
response.body.getReader({ mode: 'byob' })
```
when it shouldn't. IIRC there was an issue with using structuredClone on a readable byte stream that was fixed, so nothing should hold this back I think.

Refs: https://github.com/whatwg/fetch/pull/1593

**Comment by KhafraDev** [comment]
The fix is to add `type: 'bytes'` in the ReadableStream constructor options. Of course we don't want to set it on versions where cloning it is broken, since that would break response.clone.

**Comment by jimmywarting** [comment]
dupl: #1873

**Comment by KhafraDev** [comment]
I... made a duplicate bug report for a bug I already reported? 😂

**Comment by jimmywarting** [comment]
I was going to work on something regarding Byob to try and use less RAM and doing less garbage collection. But was not supported. So i searched för this

**Comment by KhafraDev** [comment]
if you want a hard challenge make fetch a lower level api and skip the node stream -> web stream conversion, it would probably have a significant effect on ram/gc usage

**Comment by jimmywarting** [comment]
> if you want a hard challenge make fetch a lower level api and skip the node stream -> web stream conversion, it would probably have a significant effect on ram/gc usage

Not gonna work... The thing i'm building is not meant to only run in NodeJS...
