### ISSUE TITLE
support slightly invalid gzip response

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#2123]
Here is one test we have in node-fetch, and i run it on undici fetch but it failed...
our test:
```js
	it.only('should decompress slightly invalid gzip response', async () => {
		const url = `${base}gzip-truncated`;
		const res = await fetch(url);
		expect(res.headers.get('content-type')).to.equal('text/plain');
		const result = await res.text();
		expect(result).to.be.a('string');
		expect(result).to.equal('hello world');
	});
```
```js
// our response

		if (p === '/gzip-truncated') {
			res.statusCode = 200;
			res.setHeader('Content-Type', 'text/plain');
			res.setHeader('Content-Encoding', 'gzip');
			zlib.gzip('hello world', (err, buffer) => {
				if (err) {
					throw err;
				}

				// Truncate the CRC checksum and size check at the end of the stream
				res.end(buffer.slice(0, -8)); // Buffer.from('H4sIAAAAAAAAE8tIzcnJVyjPL8pJAQA=')
			});
		}
```

this works fine in browsers and some server ignore this CRC checksum and size at the end

**Comment by mcollina** [comment]
I'm not sure how we could, this might be something to bring up inside Node.js iteself.

**Comment by jimmywarting** [comment]
We solved it with some zlibOptions options in node-fetch
```js
const buf = Buffer.from('H4sIAAAAAAAAE8tIzcnJVyjPL8pJAQA=', 'base64')
const readable = stream.Readable.from(buf)

// For Node v6+
// Be less strict when decoding compressed responses, since sometimes
// servers send slightly invalid responses that are still accepted
// by common browsers.
// Always using Z_SYNC_FLUSH is what cURL does.
const zlibOptions = {
  flush: zlib.Z_SYNC_FLUSH,
  finishFlush: zlib.Z_SYNC_FLUSH
}

const ts = zlib.createGunzip(zlibOptions)

  // For gzip
  if (codings === 'gzip' || codings === 'x-gzip') {
    new Response(readable.pipe(ts)).text().then(console.log)
```

**Comment by jimmywarting** [comment]
just tested this and it seems to work okey

**Comment by KhafraDev** [comment]
Relevant part of fetch:
https://github.com/nodejs/undici/blob/f5f7c18698b2b373d04867a07b1e59af9e284714/lib/fetch/index.js#L2010

Want to send in a PR adding the options? That test could be added to the node-fetch suite.

**Comment by jimmywarting** [comment]
Now that NodeJS v16 is the current LTS and having web streams built in i was thinking about actually kind of delete everything (including all the test and so forth) and just bring in a dependency on Undici instead and simply just re-export everything. kind of like an alias for Undici. and piggy back on you to fix all our issues we have :P

kind of have this in the pipe-line:
```js
import * as undici from 'undici'

const fetch = globalThis.fetch || undici.fetch
const FormData = globalThis.FormData || undici.FormData
const Headers = globalThis.Headers || undici.Headers
const Request = globalThis.Request || undici.Request
const Response = globalThis.Response || undici.Response

export default fetch
export {
	fetch,
	FormData,
	Headers,
	Request,
	Response
}

export * from 'fetch-blob/from.js'
```

just tough i would first share a few of our test cases that fails with undici before thinking of actually replacing it with undici.

ref: https://github.com/node-fetch/node-fetch/issues/1742

but sure i could maybe add a PR
