### ISSUE TITLE
Benchmarks fail on Node 20.1.0

### ISSUE THREAD

**Issue by ida613** [nodejs/undici#2129]
## Bug Description

Running benchmarks on Node v20.1.0 fails. 

## Reproducible By

Upgrade Node.js to 20.1.0 if haven't already
Run `npm run bench` inside the undici repo

## Expected Behavior

Benchmarks run successfully

## Logs & Screenshots

> undici@5.20.0 bench
> PORT=3042 concurrently -k -s first npm:bench:server npm:bench:run

[bench:run] 
[bench:run] > undici@5.20.0 prebench:run /Users/ida.liu/Projects/undici
[bench:run] > node benchmarks/wait.js
[bench:run] 
[bench:server] 
[bench:server] > undici@5.20.0 bench:server /Users/ida.liu/Projects/undici
[bench:server] > node benchmarks/server.js
[bench:server] 
[bench:run] 
[bench:run] > undici@5.20.0 bench:run /Users/ida.liu/Projects/undici
[bench:run] > CONNECTIONS=1 node --experimental-wasm-simd benchmarks/benchmark.js; CONNECTIONS=50 node --experimental-wasm-simd benchmarks/benchmark.js
[bench:run] 
[bench:run] node: bad option: --experimental-wasm-simd
[bench:run] node: bad option: --experimental-wasm-simd
[bench:run] 
[bench:run] npm ERR! Darwin 22.4.0
npm ERR! argv "/Users/ida.liu/.nvm/versions/node/v20.1.0/bin/node" "/Users/ida.liu/node_modules/.bin/npm" "run" "bench:run"
npm ERR! node v20.1.0
[bench:run] npm ERR! npm  v2.15.12
[bench:run] npm ERR! code ELIFECYCLE
[bench:run] npm ERR! undici@5.20.0 bench:run: `CONNECTIONS=1 node --experimental-wasm-simd benchmarks/benchmark.js; CONNECTIONS=50 node --experimental-wasm-simd benchmarks/benchmark.js`
npm ERR! Exit status 9
[bench:run] npm ERR! 
[bench:run] npm ERR! Failed at the undici@5.20.0 bench:run script 'CONNECTIONS=1 node --experimental-wasm-simd benchmarks/benchmark.js; CONNECTIONS=50 node --experimental-wasm-simd benchmarks/benchmark.js'.
[bench:run] npm ERR! This is most likely a problem with the undici package,
[bench:run] npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
[bench:run] npm ERR!     CONNECTIONS=1 node --experimental-wasm-simd benchmarks/benchmark.js; CONNECTIONS=50 node --experimental-wasm-simd benchmarks/benchmark.js
[bench:run] npm ERR! You can get information on how to open an issue for this project with:
[bench:run] npm ERR!     npm bugs undici
[bench:run] npm ERR! Or if that isn't available, you can get their info via:
[bench:run] npm ERR! 
[bench:run] npm ERR!     npm owner ls undici
[bench:run] npm ERR! There is likely additional logging output above.
[bench:run] 
[bench:run] npm ERR! Please include the following file with any support request:
[bench:run] npm ERR!     /Users/ida.liu/Projects/undici/npm-debug.log
[bench:run] npm run bench:run exited with code 1
--> Sending SIGTERM to other processes..
[bench:server] npm run bench:server exited with code SIGTERM

## Environment

Node v20.1.0

**Comment by Uzlopak** [comment]
@mcollina

Can we close this? This is not reproducable. Not on latest node, not on node 20.1.0, not with latest undici and not with latest v5.
