### ISSUE TITLE
Incorrect order of response body decompression when there are multiple content encodings in undici.fetch (?)

### ISSUE THREAD

**Issue by rychkog** [nodejs/undici#2158]
## Bug Description

I might misunderstood the spec, but

According to [specification](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.4) the `Content-Encoding`
 might have multiple encodings:

```
If one or more encodings have been applied to a representation, the sender that applied the encodings MUST generate a Content-Encoding header field that lists the content codings in the order in which they were applied
```

And based on the implementation it is not the case:
https://github.com/nodejs/undici/blob/main/lib/fetch/index.js#L2007

## Reproducible By

Run following server

```js
const express = require('express');
const zlib = require('zlib');
const { pipeline, Readable } = require('stream');

const app = express();

app.get('/data', (req, res) => {
  const data = {
    message: 'Hello, world!',
    date: new Date()
  };

  const jsonData = JSON.stringify(data);

  // Enable compression for both gzip and deflate
  const gzip = zlib.createGzip();
  const deflate = zlib.createDeflate();

  // Set the appropriate response headers
  res.setHeader('Content-Type', 'application/json');
  // In order the coders were applied
  res.setHeader('Content-Encoding', 'deflate, gzip');

  pipeline(Readable.from([jsonData]), deflate, gzip, res, () => {})
});

const port = 3000;
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```

Try to fetch the data:

```js
  const undici = require('undici');
  const res = await undici.fetch('http://localhost:3000/data')
  console.log(await res.text());
```

## Expected Behavior

When there is a payload with following `Content-Encoding: deflate, gzip` we need to decode it with `gzip` first and then with `deflate`

The code above crashes right now, but should return properly decoded text.

## Logs & Screenshots

N/A

## Environment

Ubuntu 22.04 LTS, Node v16.20.0

### Additional context

N/A

**Comment by ronag** [comment]
It seems like the codings are applied in the wrong order. PR welcome.

**Comment by KhafraDev** [comment]
The specification states that the *sender* must set the header properly. If the body is being decompressed incorrectly, this doesn't seem to be an issue with undici?

**Comment by KhafraDev** [comment]
that doesn't seem to match the code though https://github.com/nodejs/undici/blob/2032e8997695f569c3bfdf975cdd8c7289478f83/lib/fetch/index.js#L2007-L2036

**Comment by rychkog** [comment]
@KhafraDev As I've pointed in the issue description

> When there is a payload with following `Content-Encoding: deflate, gzip` we need to decode it with `gzip` first and then with `deflate`

So I believe the loops from your comment should iterate over `codings.reverse()`

**Comment by KhafraDev** [comment]
would you like to send in a PR?

**Comment by rychkog** [comment]
> would you like to send in a PR?

Sure, will send
