### ISSUE TITLE
Fetch returns 404 when URL resource passed as parameter 

### ISSUE THREAD

**Issue by gplusdotgr** [nodejs/undici#2160]
## Bug Description

When creating a new [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) object and passing it to fetch, the fetch returns 404. The Response is:
```js
Response {
  [Symbol(realm)]: null,
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: true,
    requestIncludesCredentials: true,
    type: 'default',
    status: 404,
    timingInfo: {
      startTime: 1204498.5030000005,
      redirectStartTime: 0,
      redirectEndTime: 0,
      postRedirectStartTime: 1204498.5030000005,
      finalServiceWorkerStartTime: 0,
      finalNetworkResponseStartTime: 0,
      finalNetworkRequestStartTime: 0,
      endTime: 0,
      encodedBodySize: 431,
      decodedBodySize: 431,
      finalConnectionTimingInfo: null
    },
    cacheState: '',
    statusText: '',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    body: { stream: undefined }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(5) {
      'date' => [Object],
      'content-type' => [Object],
      'content-length' => [Object],
      'connection' => [Object],
      'content-language' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}
```

## Reproducible By

```js
import { to } from "await-to-js"

export const getTrafficSource = async () => {
  const url = new URL(
    '/traffic-source',
    import.meta.env.EXPLORE_INTERNAL_API ||
      "https://some-base-url"
  )
  const [err, res] = await to(fetch(url))

  if (err) {
    console.error(err)
    return
  }
  const data = await res.json()
  return data
```

When I actually make the same call using a plain string, it works:

```js
// this works
  const [err, res] = await to(fetch('https://some-base-url/traffic-source'))
```

## Expected Behavior

JSON should be returned and parsed

## Environment

node v16.19.0

### Additional context

Astro Framework

**Comment by ronag** [comment]
Please make a minimal repro.

**Comment by KhafraDev** [comment]
this is unlikely to be a bug in undici, I'm going to close this until/unless a minimal repro is provided

**Comment by gkatsanos** [comment]
Sorry for not following up. I'm not sure if this will help, but, we solved it.. and this is how: 
I moved the `/` from the path to the `base` url , and the call worked. I wasn't able to find any specification that says whether the base should include a trailing slash or not.. If someone can think of something please ping me : )

**Comment by gkatsanos** [comment]
Hi, we realized that when you pass a url with a path and without a trailing slash as a base , the URL constructor removes the last part of the url.
e.g. 
```js
const url = new URL("/some/path", "https://www.example.com/api")
```
will actually generate https://www.example.com/some/path : 

![image](https://github.com/nodejs/undici/assets/1768834/b1da43dd-68c8-4e30-8488-dca0cfbedc27)
 
 that's not a fetch / undici issue!
