### ISSUE TITLE
AbortSignal.timeout inconsistently leads to TimeoutError or AbortError

### ISSUE THREAD

**Issue by cancan101** [nodejs/undici#2171]
## Bug Description

If `fetch` is passed a `AbortSignal.timeout(timeout)` as the signal and the timeout occurs, a `TimeoutError` is raised in certain cases whereas in other cases a `AbortError` is raised. The `TimeoutError` occurs when the fetch itself times out whereas the `AbortError` is raised if the timeout occurs while streaming the response.

## Reproducible By

```ts
export async function fetchWithTimeout(
  resource: RequestInfo,
  options: RequestInit & { timeout?: number } = {}
) {
  const { timeout = 8000 } = options;

  const response = await fetch(resource, {
    ...options,
    signal: AbortSignal.timeout(timeout),
  });
  return response;
}

async function main() {
  const response = await fetchWithTimeout("https://google.com/", {
    timeout: 1000,
  });

  if (!response.body) {
    return null;
  }

  const saver = new WritableStream<string>({
    async write(data, controller) {
      await new Promise((r) => setTimeout(r, 1000));
    },
  });

  return await response.body.pipeThrough(new TextDecoderStream()).pipeTo(saver);
}

main().catch((x) => console.error(x));
```

## Expected Behavior

An error of the format:
```
DOMException [TimeoutError]: The operation was aborted due to timeout
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
...
```

## Logs & Screenshots

Instead we get:
```
DOMException [AbortError]: The operation was aborted.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at Fetch.abort (node:internal/deps/undici/undici:10586:19)
    at EventTarget.requestObject.signal.addEventListener.once (node:internal/deps/undici/undici:10620:22)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
    at EventTarget.dispatchEvent (node:internal/event_target:703:26)
    at abortSignal (node:internal/abort_controller:314:10)
    at AbortController.abort (node:internal/abort_controller:332:5)
    at EventTarget.abort (node:internal/deps/undici/undici:7174:18)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
    at EventTarget.dispatchEvent (node:internal/event_target:703:26)
```

## Environment

MacOS: 12.6
Node: v19.9.0

**Comment by ronag** [comment]
I'm not sure I see a problem here? The current behavior makes sense to me.

**Comment by ronag** [comment]
I'm pretty sure this is spec compliant.  `AbortSignal.timeout` is supposed to cause an abort error.

**Comment by ronag** [comment]
Ah, you might be right https://dom.spec.whatwg.org/#ref-for-dom-abortsignal-timeout%E2%91%A0. @KhafraDev

**Comment by KhafraDev** [comment]
fetch is expected to only throw an AbortError (previous discussion about this starts [here](https://github.com/nodejs/undici/pull/1511#issuecomment-1166488396)).

**Comment by cancan101** [comment]
That is definitely not the case right now. As mentioned above fetch will throw `TimeoutError` in certain circumstances. I think this was a new feature as of node 19. Prior versions did throw just `AbortError`. That being said, I don't follow why you would not want to have a differentiated `TimeoutError` for timeouts, consistent with the linked spec above.

**Comment by cancan101** [comment]
Also the linked comment refers to user supplied reasons which isn't the issue that I have here.

**Comment by KhafraDev** [comment]
I'm inclined to think that is a bug in Firefox, the [spec](https://fetch.spec.whatwg.org/) doesn't mention TimeoutError at all. It mentions AbortError for timeouts.

**Comment by cancan101** [comment]
The [DOM spec](https://dom.spec.whatwg.org/#ref-for-dom-abortsignal-timeout%E2%91%A0) does mention it, however:
![image](https://github.com/nodejs/undici/assets/51059/49a3655a-b227-465a-9e38-f3d739376c56)

**Comment by cancan101** [comment]
and the fetch spec seems to indicate that AbortError is used as the _fallbackError_:
![image](https://github.com/nodejs/undici/assets/51059/15ff26c7-5cb4-46a5-93ae-9d9ca00d0e67)

**Comment by ronag** [comment]
> I'm inclined to think that is a bug in Firefox, the [spec](https://fetch.spec.whatwg.org/) doesn't mention TimeoutError at all. It mentions AbortError for timeouts.

I'm leaning towards that you might be wrong here...

**Comment by KhafraDev** [comment]
Yeah I was, we weren't forwarding the reason. Will have a PR up soon.

**Comment by Dzieni** [comment]
Great to see that it's fixed. Can't wait to have it oficially released. Is there any release schedule?
