### ISSUE TITLE
Windows Deno WebSocket timeout

### ISSUE THREAD

**Issue by 7xa5h** [nodejs/undici#2187]
## Bug Description
Undici always timing out specifically on Windows when being used with Deno, and not on other systems.

## Reproducible By
There aren't any direct snippets or code that could reproduce the bug but for an example using npm:discord.js alongside Deno will always result in a AbortError on `client.login()`

## Expected Behavior
Again not 1 direct expected behavior but it should basically just go through like it does on other operating systems like MacOS and most Linux Distros 

## Environment

Windows 11
Deno 1.35
### Additional context

So far I've tested this on MacOS and it seems to be running just fine, the issue is Windows-only.
Related issues: https://github.com/discordjs/discord.js/issues/9663 https://github.com/denoland/deno/issues/19766

**Comment by 7xa5h** [comment]
> Is this a problem on Node? I don't think we officially support Deno.

Not Node but Deno, I was told many times that it was a Undici specific issue so i thought id open an issue here too, i also feel like itd be great if also support for Deno was or is going to be worked on as it just widens the range of usage and makes programming just easier imo

**Comment by ronag** [comment]
Even if this is a bug in undici. It needs to be debugging in Deno and none of the maintainers work with Deno. PR is welcome though.

**Comment by KhafraDev** [comment]
Since the code you provided in the Deno issue works in node, this is an issue with Deno. More specifically: this is an issue with Deno's node compatibility.
