### ISSUE TITLE
Unidici not compatible with AWS Xray 

### ISSUE THREAD

**Issue by mmazurowski** [nodejs/undici#2190]
Hello there 👋 

I've spent some time trying to get this working but unfortunately I can't. Normally AWS Xray wraps native node packages `https` and `http`. Creating segments on each HTTP request. That is not the case for unidici nor clients using it as dependency for example being elastic search client. 

What is correct way of capturing http requests in a way to manually instrument requests for tracing services?

Kind regards,
Martin

**Comment by ronag** [comment]
https://undici.nodejs.org/#/docs/api/DiagnosticsChannel
