### ISSUE TITLE
Enhance the document of ProxyAgent options params

### ISSUE THREAD

**Issue by monjer** [nodejs/undici#2192]
The`ProxyAgentOptions` params of [ProxyAgent](https://github.com/nodejs/undici/blob/main/lib/proxy-agent.js#L42) class need enhance. 

Actually  the `ProxyAgentOptions` has some other options like `requestTls` , `proxyTls`, which not included in [document ](https://undici.nodejs.org/#/docs/api/ProxyAgent?id=parameter-proxyagentoptions). It's really appreciate it if enhance the document.

#1489

**Comment by metcoder95** [comment]
Hey! Thanks for the heads up, would you like to send a PR for it? 🙂
