### ISSUE TITLE
Use llhttp through wasm

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#22]
Would it be possible and make sense to use https://github.com/nodejs/llhttp instead of http-parser-js? Maybe as an opt-in?

**Comment by ronag** [comment]
The [performance of http-parser-js](https://github.com/creationix/http-parser-js/issues/70) came up as part of a discussion regarding this library. Hence this issue.

**Comment by mcollina** [comment]
I’d be happy to, however llhttp is not part of the public API, and I would prefer not to use a binary addon.

Wasm could be cool, but I do not know how it would perform. On top of of that, all of this _inlines_ and it avoids one or more jump between the http parser (C) and client (JS). Tbh, I don’t expect a bump in speed, but I would be happy to be surprised.

**Comment by szmarczak** [comment]
I have to say I'm impressed. Even with `http-parser-js` it's still faster than the native Node.js `http`.

```
undici x 20,826 ops/sec ±1.70% (87 runs sampled)
Fastest is undici
```

<details>
<summary>Benchmark source code</summary>

```js
'use strict';
const Benchmark = require('benchmark');
const {Client} = require('undici');

const suite = new Benchmark.Suite();

const client = new Client('https://localhost:8081', {
    tls: {
rejectUnauthorized: false
    }
});

const options = {
    path: '/',
    method: 'GET'
};

// Benchmarking
suite.add('undici', {
    defer: true,
    fn: async deferred => {
        const {body} = await client.request(options);
        body.resume();

        body.once('end', () => {
            deferred.resolve();
        });
    }
}).on('cycle', event => {
    console.log(String(event.target));
}).on('complete', function () {
    console.log(`Fastest is ${this.filter('fastest').map('name')}`);
}).run();
```


</details>

The fun fact is that it's even [faster than the HTTP2 implementation](https://github.com/szmarczak/http2-wrapper#benchmarks):

> ```
> http2 x 16,172 ops/sec ±1.21% (85 runs sampled)
> https - keepalive x 13,158 ops/sec ±2.88% (78 runs sampled)
> ```

**Comment by ronag** [comment]
Anyone of you know of anyone that might be interested in creating or helping out with a wasm build of llhttp that can be used as an alternative to http-parser-js? I hope it would not be too difficult if one is familiar with the wasm build flow.

**Comment by mcollina** [comment]
In would recommend to open an issue on https://github.com/nodejs/llhttp, there is also https://www.npmjs.com/package/llhttp which might be usable somehow?

**Comment by ronag** [comment]
@szmarczak Would you mind running those benchmarks again against master? I'm curious how much of a difference recent improvements have made.

**Comment by szmarczak** [comment]
master: `undici x 21,168 ops/sec ±2.00% (88 runs sampled)`

**Comment by szmarczak** [comment]
#109 `undici x 20,131 ops/sec ±1.81% (85 runs sampled)`

but it very often goes below 20k: `undici x 19,812 ops/sec ±2.01% (85 runs sampled)`

**Comment by szmarczak** [comment]
ah wait I didn't use the newer API, lemme check it out

**Comment by szmarczak** [comment]
```js
        client.stream(options, () => {
            const obj = {
                on: () => obj,
                write: () => {},
                end: () => deferred.resolve()
            };

            return obj;
        });
```

```
undici x 24,184 ops/sec ±1.64% (85 runs sampled)
```

```js
        client.stream(options, () => {
            let buffered = '';

            const obj = {
                on: () => obj,
                write: chunk => {
                    buffered += chunk;
                },
                end: () => deferred.resolve()
            };

            return obj;
        });
```

```
undici x 23,080 ops/sec ±1.50% (83 runs sampled)
```

That's a big improvement!

**Comment by dnlup** [comment]
I did a quick test and the package https://www.npmjs.com/package/llhttp can be used directly.
A lot of tests fail, I would like to dig deeper to check if it is something that can be solved by just refactoring or there are some major incompatibilities.

**client-base**
```js
...
const { HTTP: HTTParser } = require('llhttp')
...
```

Note: I don't know how much this task would take atm

**Comment by dnlup** [comment]
After some research I found [this issue](https://github.com/nodejs/llhttp/issues/44) which seems to suggest a way to use this parser through Node directly, which I think it could be better.

**Comment by mcollina** [comment]
I think using `process.bindings()` is highly unsupported from the Node.js team. It could work but it would require more maintainance.

**Comment by ronag** [comment]
> I think using process.bindings() is highly unsupported from the Node.js team. 

Yes.

> It could work but it would require more maintainance.

Yes, though I don't see anyway good alternative at the moment.

I think it might be worth it. We would need to keep an eye on major releases of Node though to make sure it doesn't break.

**Comment by mcollina** [comment]
I'm good with the approach.

**Comment by ronag** [comment]
Fixed in https://github.com/mcollina/undici/commit/2240cb09488a409b65e40fc99ef3c89a50de3ca8 (although not using wasm).

**Comment by szmarczak** [comment]
So `llhttp` is a no?

**Comment by szmarczak** [comment]
Any idea how would wasm improve the performance? Would it be a significant one or not?

**Comment by ronag** [comment]
> Any idea how would wasm improve the performance?

Maybe if the js<->wasm overhead is lower than js<->c++.

**Comment by mcollina** [comment]
Given https://github.com/devsnek/llhttp/tree/wasm, I think we could try vendoring llhttp and the http parser.

**Comment by ronag** [comment]
I think I can do this

**Comment by mcollina** [comment]
That would be a good experiment! I tried to get a build done and I keep getting errors :D.

If you have a good tutorial /some docs I would love to read up.

cc @devsnek

**Comment by devsnek** [comment]
It was built using https://github.com/WebAssembly/wasi-sdk. After you build it with `build_wasm.sh`, `wasm.js` should "just work".

**Comment by devsnek** [comment]
I think technically you could built it without the wasi by manually including libc headers since it doesn't use any system apis, but imo its easier just to use the sdk anyway.

**Comment by mcollina** [comment]
Thanks!

**Comment by mcollina** [comment]
I did some experiments... using the wasi-sdk works like magic, thanks @devsnek!

From the point of view of Undici, we are missing some key things that are provided by https://github.com/nodejs/node/blob/master/src/node_http_parser.cc, hooks into the parsing flow:

https://github.com/nodejs/node/blob/76a073b67ed94a38ab3efa9cf9b2030962cb4d08/src/node_http_parser.cc#L966-L979.

This is doable with much more work apparently.

**Comment by dnlup** [comment]
> I did some experiments... using the wasi-sdk works like magic, thanks @devsnek!
> 
> From the point of view of Undici, we are missing some key things that are provided by https://github.com/nodejs/node/blob/master/src/node_http_parser.cc, hooks into the parsing flow:
> 
> https://github.com/nodejs/node/blob/76a073b67ed94a38ab3efa9cf9b2030962cb4d08/src/node_http_parser.cc#L966-L979.
> 
> This is doable with much more work apparently.

Is it, hopefully,  a matter of copy/paste the bits of Node into llhttp?

**Comment by devsnek** [comment]
@mcollina you can add them in here: https://github.com/devsnek/llhttp/blob/69d4405f2dd492164a236c7bdb76902c8d46d7d4/src/native/api.c#L29-L45

**Comment by ronag** [comment]
I'm blocked. No idea how to build https://github.com/devsnek/llhttp/tree/wasm with https://github.com/WebAssembly/wasi-sdk

Tried everything I can think of to make clang find the correct include path without success:

```
/build/c/llhttp.c:7574:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.
./src/native/api.c:1:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.
./src/native/http.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

I guess UNIX tooling is not my strongest skill.

**Comment by dnlup** [comment]
Just thinking out loud here:

to define `kOnMessageBegin` we should add a `wasm_on_message_begin` in the parser settings in `src/native/api.c`. That would be similar to what is done in Node `http_parser.cc` with `on_message_begin`. The hook using `kOnMessageBegin` would then be finalized/implemented in the `JS` implementation of the Parser. This implementation will substitute the `HTTP_Parser` we are currently using in `core` here. 

I am trying to play with it using the @devsnek branch (thank you). I apologize if this is stuff known already, I am new to wasi.

**Comment by dnlup** [comment]
> I'm blocked. No idea how to build https://github.com/devsnek/llhttp/tree/wasm with https://github.com/WebAssembly/wasi-sdk
> 
> Tried everything I can think of to make clang find the correct include path without success:
> 
> ```shell
> /build/c/llhttp.c:7574:10: fatal error: 'stdlib.h' file not found
> #include <stdlib.h>
>          ^~~~~~~~~~
> 1 error generated.
> ./src/native/api.c:1:10: fatal error: 'stdlib.h' file not found
> #include <stdlib.h>
>          ^~~~~~~~~~
> 1 error generated.
> ./src/native/http.c:1:10: fatal error: 'stdio.h' file not found
> #include <stdio.h>
>          ^~~~~~~~~
> 1 error generated.
> ```
> 
> I guess UNIX tooling is not my strongest skill.
> 
> e.g.
> 
> ```shell
> /Users/ronagy/GitHub/public/devsnek-llhttp/wasi-sdk-12.0/bin/clang -I /Users/ronagy/GitHub/public/devsnek-llhttp/wasi-sdk-12.0/lib/clang/11.0.0/include     --sysroot=$WASI_ROOT/share/wasi-sysroot   -target wasm32-unknown-wasi   -Ofast   -fno-exceptions   -fvisibility=hidden   -mexec-model=reactor   -Wl,-error-limit=0   -Wl,-O3   -Wl,--lto-O3   -Wl,--strip-all   -Wl,--allow-undefined   -Wl,--export-dynamic   -Wl,--export-table   -Wl,--export=malloc   -Wl,--export=free   ./build/c/*.c   ./src/native/*.c   -I./build   -o ./build/llhttp.wasm
> ```

@ronag The that works for me is downloading a `tar.gz` [release](https://github.com/WebAssembly/wasi-sdk/releases), extract it somewhere, then launch `WASI_ROOT=<path-to-wasm-sdk> ./build_wasm.sh`.

**Comment by dnlup** [comment]
Also, [`consume/uncosume`](https://github.com/nodejs/node/blob/76a073b67ed94a38ab3efa9cf9b2030962cb4d08/src/node_http_parser.cc#L604)  would have to be implemented using streams on the `JS` side, right?

**Comment by ronag** [comment]
> Also, [`consume/uncosume`](https://github.com/nodejs/node/blob/76a073b67ed94a38ab3efa9cf9b2030962cb4d08/src/node_http_parser.cc#L604) would have to be implemented using streams on the `JS` side, right?

Yea. We need to remove consume/unconsume and just use `socket.on('data', buf => parser.execute(buf))`

**Comment by dnlup** [comment]
> > Also, [`consume/uncosume`](https://github.com/nodejs/node/blob/76a073b67ed94a38ab3efa9cf9b2030962cb4d08/src/node_http_parser.cc#L604) would have to be implemented using streams on the `JS` side, right?
> 
> Yea. We need to remove consume/unconsume and just use `socket.on('data', buf => parser.execute(buf))`
> 
> So we go from:
> 
> `cpp (socket + parser) -> js (undici)`
> 
> to:
> 
> `cpp (socket) -> js (undici) -> wasm (parser) -> js (undici)`

Does that mean that [`kOnExecute`](https://github.com/nodejs/undici/blob/master/lib/core/client.js#L442)  is no longer necessary?

**Comment by ronag** [comment]
> Does that mean that kOnExecute is no longer necessary?

Correct. That logic should live after `const ret = parser->execute(buf)`

**Comment by dnlup** [comment]
I managed to put together a small experiment for a parser in https://github.com/dnlup/llhttp/blob/undici_wasm/wasm.js. Besides the things we already mentioned. like: 
* `kOnExecute` not being necessary anymore
* we will handle the stream logic in js

One other thing I am seeing is the headers timeout, the headers max size & number. Do we need all of them implemented in the base parser?

What strategy do you think is best for embedding the parser in `undici`? Should it live in a separate repo? Or should we include it here?

**Comment by ronag** [comment]
headersTimeout not necessary

**Comment by ronag** [comment]
@dnlup at you working on this with intention to open PR?

**Comment by mcollina** [comment]
> What strategy do you think is best for embedding the parser in undici? Should it live in a separate repo? Or should we include it here?

it would be best if undici kept having no runtime dependencies. A contribution in the form of a script that generates the relative javascript and wasm files and populate a folder in this repo would be rad.

(Bonus point if the script is run within a docker image, so the toolchain to generate those files is super easy).

**Comment by dnlup** [comment]
> @dnlup at you working on this with intention to open PR?

Yes. There's a lot of new stuff for me here, so I might not be fast, but I hope to complete it.  Anyway, I'd be happy to help with this issue.

**Comment by dnlup** [comment]
> > What strategy do you think is best for embedding the parser in undici? Should it live in a separate repo? Or should we include it here?
> 
> it would be best if undici kept having no runtime dependencies. A contribution in the form of a script that generates the relative javascript and wasm files and populate a folder in this repo would be rad.
> 
> (Bonus point if the script is run within a docker image, so the toolchain to generate those files is super easy).

Ok, just to check I understand correctly, the best approach would be:

* setting up a docker container
* from the container, we clone/download the llhttp project (do we use a custom repo or branch?)
* launch the script to generate the wasm build
* copy the build assets into undici

This script would also have to work locally. Otherwise, there would be no way to tun undici

**Comment by mcollina** [comment]
> from the container, we clone/download the llhttp project (do we use a custom repo or branch?)

I would just clone master and add our own files on top (if we need them)

> This script would also have to work locally. Otherwise, there would be no way to tun undici

I don't understand this.

**Comment by dnlup** [comment]
> I don't understand this.

Sorry.

I thought that the script should have to run on the CI and locally (while working on your machine). But now that I think about it, maybe the easiest solution, for now, would be just to run it locally. We need to be able to build the parser to use undici.

**Comment by mcollina** [comment]
> I thought that the script should have to run on the CI and locally (while working on your machine). But now that I think about it, maybe the easiest solution, for now, would be just to run it locally. We need to be able to build the parser to use undici.

A local run (via docker) would be fine... we'll commit the output to this repo.

**Comment by mcollina** [comment]
This was done
