### ISSUE TITLE
expose WebSocket to fetch bundle

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2216]
is it time to expose our WebSocket in node?

**Comment by ronag** [comment]
SGTM

**Comment by metcoder95** [comment]
Is there any possible gotcha to be aware of?

**Comment by KhafraDev** [comment]
adding globals is a semver major change and potentially breaking change. I assume that there will also be some dissent to adding WebSocket, like there has been to adding basically any web spec in node.

it probably also needs discussions and the like
