### ISSUE TITLE
Request is getting timed out from lambda

### ISSUE THREAD

**Issue by cnrahulrkr** [nodejs/undici#2222]
## Bug Description

We are using this undici package for our web scrapper project, we are experiencing an issue, not sure what we missing. We are getting a timeout error while executing the below code from AWS lambda. We have increased the timeout of lambda to 2 min, still it's getting timed out. And there is no VPC or security group attached with lambda.

But the same code base is working as expected from local system, getting response as 200.

## Reproducible By

```js
  const {
    statusCode,
    headers,
    trailers,
    body
  } = await request(
    'https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1576869304/406994_BLM00_1000_001_100_0000_Light-Gucci-Jordaan-leather-loafer.jpg',
    {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
      }
    })
  
  console.log('response received', statusCode)
  console.log('headers', headers)
```

## Expected Behavior

Status code should be 200

**Comment by ronag** [comment]
Try adding `await body.dump()`.

**Comment by cnrahulrkr** [comment]
Nope, still the same error.

**Comment by ronag** [comment]
not much more we can help with based on the information you have provided...

**Comment by rghv404** [comment]
@cnrahulrkr  were you able to figure out what was causing this?
