### ISSUE TITLE
cryptic error message for already aborted signals

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#2242]
Undici have the most crypting error message when sending in an already aborted signal.

example:
```js
fetch('http://localhost', { signal: AbortSignal.abort('Already aborted') })
  .catch(e => console.log({ctor: e.constructor.name, code: e.code, message: e.message}))
```

undici:
```js
{ ctor: 'TypeError', code: undefined, message: 'invalid_argument' }
```
Chrome:
```js
{ ctor: 'DOMException', code: 20, message: "Failed to execute 'fetch' on 'Window': The user aborted a request."}
```
Safari:
```js
{ ctor: "DOMException", code: 20, message: "Request signal is aborted"}
```
Firefox & Deno:
```js
{ ctor: "String", code: undefined, message: undefined }
// returns the abort reason, so the result is "Already aborted"

// With an undefined reason it throw
{ ctor: "DOMException", code: 20, message: "The operation was aborted. " }
```

i tough i sent in something really wrong type when i was calling fetch when i received a TypeError.
but it's of a correct "type".

`{ signal: "foo" }` is an TypeError and a invalid argument.

**Comment by ronag** [comment]
@KhafraDev

**Comment by KhafraDev** [comment]
the error comes from https://github.com/nodejs/undici/blob/68e22750f90af164fa83b502a4d315f838b2d59e/index.js#L109 but I think would undici be in the right here by throwing the signal's reason "Already aborted" because of the first 4 steps of https://fetch.spec.whatwg.org/#dom-global-fetch. Idk

**Comment by jimmywarting** [comment]
I guess firefox and Deno's behavior is also right. 
It have more value by rejecting with the signals own reason... so that you know why it got aborted. 

reason why you get a DOMException when undefined is passed is b/c:
`AbortSignal.abort().reason.constructor === DOMException`

**Comment by KhafraDev** [comment]
it was the correct behavior but there was a spec change a while ago that they haven't updated to
