### ISSUE TITLE
Move from tap to the node core test runner

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#2267]
As titled

This could be part of the next semver major that drops old nodes.

**Comment by ashutoshdhande** [comment]
Will give a shot at this

**Comment by anurag-roy** [comment]
@mcollina There are a lot of test files using `tap` (around 150).

Are we looking to migrate all of them in one PR or migrating part by part is fine?

**Comment by pmarchini** [comment]
Hey!

Given the large number of tests and the need to meticulously avoid false positives, would it be more effective to split the test suites into separate PRs?

For instance, `test:cookies` appears to be easily portable independently of other suites.

How about we create a list of these suites to distribute the workload and more effectively monitor the outcomes?

**Comment by Uzlopak** [comment]
Is there something like t.plan in node:test?

**Comment by anurag-roy** [comment]
@Uzlopak There isn't, we are using `@matteo.collina/tspl` package instead of t.plan

Example usage [here](https://github.com/nodejs/undici/blob/main/test/node-test/abort-controller.js#L25).

**Comment by Uzlopak** [comment]
I am on this now. 

I opened a PR #2719 for an example transformation. 
Also I will split the necessary work into smaller PRs to reduce the review work.

**Comment by Uzlopak** [comment]
Opened #2720 and #2721 to incrementally prepare the following PR.

**Comment by Uzlopak** [comment]
LOL. I created basically 6 batches and lost the following stuff, which I stashed in git. 

So please review and merge the open PRs. Then I can continue to migrate it.

**Comment by Uzlopak** [comment]
Nice.
