### ISSUE TITLE
Can we remove `npm run test` from pre-commit hook? 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/undici#2274]
As titled. 

I'm finding it extremely annoying that all of the tests run every time I commit. We should enforce commit squashing anyways when we merge PRs so that not every commit has to be valid. 

I currently pass `-n` every time I commit simply because I don't want to wait for the tests to run, but then when I use `npm version` and it commits a tag, that hook still runs and there's no way for me to disable it. 

Maintainers, WDYT?

**Comment by Ethan-Arrowood** [comment]
I actually sorta remember that discussion - and I may have been on the other side. But now I'm definitely for removing it lol. When other tools trigger the pre-commit hook (`npm version`) and I can't disable the hook, that's really bothersome.

**Comment by metcoder95** [comment]
I've personally never been a fan of git-hooks running as it makes the experience quite annoying when having to commit a change or something; but as well, I tend to use `-n` or `--no-verify` (I even make a git alias for it 😅).

If asked, I'm more into removing it but I do not have a problem keeping it with the ability to bypass it 👍

**Comment by mcollina** [comment]
I'm happy to follow whatever you prefer.

**Comment by ronag** [comment]
I'm fine with removing it as long as it runs in CI with PR

**Comment by anonrig** [comment]
I agree 100%

**Comment by metcoder95** [comment]
Closed on by #2296
