### ISSUE TITLE
NPM release 5.25.1 has no GitHub release

### ISSUE THREAD

**Issue by meyfa** [nodejs/undici#2277]
For purposes of retrieving the changelog, as well as general consistency, I would expect Undici's NPM releases and GitHub releases to have a 1:1 association. The newest release on NPM, 5.25.1, is missing from GitHub.

**Comment by meyfa** [comment]
As an aside, I would highly recommend publishing via GitHub Actions, which would prevent such differences in the future. The setup is very simple. Google's release-please action can be used to generate automated version bump PRs, and when merged, create a GitHub release + push to NPM. Example workflow from one of my projects: https://github.com/meyfa/group-items/blob/2bc57df1c264d7680d6e0788ce678ca9897aaa82/.github/workflows/release-please.yml

From a software security standpoint, this greatly increases trust in the supply chain, as the NPM `--provenance` flag can be used. Provenance links a release to a specific commit and GitHub Actions run cryptographically, so that the package origin can easily be traced and verified.

It also generates this nice badge on npmjs.com:

![image](https://github.com/nodejs/undici/assets/3982806/802cba2e-e32c-416e-9518-47da62952a4d)

More information: https://docs.npmjs.com/generating-provenance-statements

By the way, to everyone involved, thanks for all your hard work on maintaining this awesome package! ❤️

**Comment by Ethan-Arrowood** [comment]
That is my bad. I pushed the git tag, but didn't create a GitHub release for it. 

Looks like @mcollina did: https://github.com/nodejs/undici/releases/tag/v5.25.1

I do want to automate our release process completely. Thank you for the actions recommendation.

**Comment by meyfa** [comment]
Sounds great! Since #2280 now exists, and my original request seems solved I'll go ahead and close this :)
