### ISSUE TITLE
Not getting the full type when parsing multipart/form-data

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#2283]
## Bug Description

Not getting the full type when parsing multipart/form-data

## Reproducible By

```js
var b = new Blob(['123'], { type: 'text/plain;charset=utf-8'})
var fd = new FormData()
fd.set('x', b)
var res = new Response(fd)
res.clone().text().then(body => 
  // Just making sure that it contains ;charset=utf-8 (which it dose)
  console.log(body.includes('utf-8'))
)

new Response(fd).formData().then(fd => {
  // returns just 'text/plain'
  console.log(fd.get('x').type)
})
```

## Expected Behavior

To get the full type, `text/plain;charset=utf-8`

## Logs & Screenshots

Screenshot of chrome:
<img width="626" alt="image" src="https://github.com/nodejs/undici/assets/1148376/f92e118b-1fd3-467e-8a54-b4b75f2af436">

Screenshot of NodeJS
<img width="293" alt="image" src="https://github.com/nodejs/undici/assets/1148376/0a3ff6d4-42fd-4e92-84d2-5a7ac8f7753b">

## Environment

Not using undici directly - using Node.js v20.6.1 built in fetch

### Additional context

presumable this revolves around the usage around Busboy...
Maybe the type should be extracted from the headers instead...? to get the raw content-type.

**Comment by KhafraDev** [comment]
would you like to send in a PR?

**Comment by jimmywarting** [comment]
> would you like to send in a PR?

not this time... this time i think i will pass. 
Have plenty of other things to do.

**Comment by barronw** [comment]
Hi @jimmywarting and @KhafraDev. Can I work on this issue?

**Comment by jimmywarting** [comment]
fine by me

**Comment by barronw** [comment]
The fix seems to require a change to `busboy`, and there is a pull request (https://github.com/nodejs/undici/pull/2211) to replace `busboy` with `@fastify/busboy`. I'll wait to see if that lands before submitting a fix.

**Comment by IlyasShabi** [comment]
@barronw Indeed, it comes from `busboy`, and even `@fastify/busboy` returns `text/plain` as the mimeType

**Comment by KhafraDev** [comment]
@fastify/busboy is a fork of busboy, the options are probably the same

**Comment by IlyasShabi** [comment]
@KhafraDev @barronw I think that we can emit charset also [ boy.emit('file', fieldname, file, filename, encoding, contype, charset)](https://github.com/fastify/busboy/blob/master/lib/types/multipart.js#L193) and then handle the logic from in undici like:
`busboy.on('file', (name, value, filename, encoding, mimeType, charset)`
to avoid breaking changes

**Comment by jimmywarting** [comment]
@IlyasShabi 
`charset` should not be the only thing we should worry about...

if i would like then i could just send this
```js
var otherFormData = new Blob(['123'], { type: 'application/form-data; boundary=eu293yre972yrr283r'})
var fd = new FormData()
fd.set('embeded-formdata', otherFormData)

// later
fd = await request.formData()
fd.get('embeded-formdata').type === otherFormData.type
```

i should be able to put in a file that have completely nonsense type
```js
new Blob(data, { type: 'x/y; foo=bar; fuz=123' })
```
and get back exactly the same thing.
