### ISSUE TITLE
Fetch API giving error UNABLE_TO_GET_ISSUER_CERT_LOCALLY for nodejs vesrion 18.15.0

### ISSUE THREAD

**Issue by ajaygera** [nodejs/undici#2293]
## Bug Description

I am getting UNABLE_TO_GET_ISSUER_CERT_LOCALLY error while making HTTPS (REST API) call using typescript  with node js version 18.15.0.
There was no error with 16.17.1 . 
Basically I was using vscode version 1.81.1 which has nodejs version 16.17.1  
I upgraded vscode to 1.82.2 and it has nodejs version 18.15.0.
After upgrade, on making HTTPS request (REST API call)  I started to get error UNABLE_TO_GET_ISSUER_CERT_LOCALLY
What is changed in nodejs 18.15.0 for SSL certification validation? which is causing this issue
## Environment
Windows 11 enterprise , nodejs version 18.15.0

**Comment by mcollina** [comment]
How did you install Node.js? Can you share a script to reproduce your problem?

**Comment by ajaygera** [comment]
I have downloaded nodeJs from https://nodejs.org/en/download. I installed this around few months back. I started to get issue after I upgraded vscode to 1.82.2 . I  have not made any code changes. If I downgrade vscode to 1.81.1 then I don't see any issue with fetch API.  Just two days back, I upgraded to vscode 1.82.2

**Comment by mcollina** [comment]
Unfortunately I can't help you, I recommend to contact Microsoft support, looks like a VSCode issue.
