### ISSUE TITLE
Change default "user-agent" from `undici`

### ISSUE THREAD

**Issue by balazsorban44** [nodejs/undici#2306]
### What is the problem this feature will solve?

Currently, Node.js uses `undici` for its `fetch` implementation. This sets `undici` as the default user agent.

From Node.js' perspective, `undici` is an implementation detail and so it should have its own user agent header.

**For context** at Next.js, we stopped polyfilling `globalThis.fetch` in favor of the platform-provided alternative (previously using `node-fetch`), and started getting reports where users did not know where the requests with the `undici` user agent were coming from.

I've tested the current behavior in different runtimes, here is Node.js, Bun and Deno for comparison:

- Node.js `node node.mjs` prints: undici:
```js
// node.mjs
import { createServer } from 'http'
const server = createServer((req, res) => {
  console.log(req.headers['user-agent'])
  res.end()
}).listen(3000)
await fetch('http://localhost:3000')
server.close()
process.exit(0)
```

- Bun `bun bun.js` prints: Bun/1.0.2:
```js
// bun.js
const server = Bun.serve({
  port: 3000,
  fetch: (req) => console.log(req.headers.get('user-agent')),
})
await fetch('http://localhost:3000')
server.stop()
```

- Deno `deno run --allow-net deno.js` prints: Deno/1.37.1:
```js
// deno.js
Deno.serve({ port: 3000 }, (request) => {
  console.log(request.headers.get('user-agent'))
  return new Response()
})
await fetch('http://localhost:3000')
Deno.exit(0)
```

### What is the feature you are proposing to solve the problem?

I propose that the default user agent in Node.js changes to the format used by Deno, and Bun for consistency.

Example: `Node/18.18.0`

### What alternatives have you considered?

Related: https://github.com/nodejs/node/pull/43852 https://github.com/nodejs/node/issues/43851

**Comment by mcollina** [comment]
I would rather not have one, but the spec mandate us. `node` is better than `undici` because it's 3 bytes less.

Who wants to do the honors?
