### ISSUE TITLE
bug: fetch causes http2 server to hang

### ISSUE THREAD

**Issue by vegerot** [nodejs/undici#2311]
## Bug Description

Reading the `body` of an http2 POST call causes `node:http2` to hang when called from this `fetch`, but not from Deno's fetch or curl.

## Reproducible By

```js
import http2 from "node:http2";
import assert from "node:assert";
import { exec } from "node:child_process";

import { Client, fetch } from "undici";
import devcert from "devcert";

const ssl = await devcert.certificateFor("localhost");
const server = http2.createSecureServer(ssl, async (req, res) => {
  assert.equal(req.method, "POST");
  console.log("beginning to read body...");
  let body = [];
  for await (const chunk of req) {
    console.log({ chunk });
    body.push(chunk);
  }
  let buffer = Buffer.concat(body);
  console.log("end of reading body");
  res.end(buffer);
}).listen(3000);

const METHOD = "fetch";
const h2Client = new Client("https://localhost:3000", {
  connect: {
    rejectUnauthorized: false,
  },
  allowH2: true,
});

server.on("listening", async () => {
  console.log("listening on 3000");
  if (METHOD === "fetch") {
    const response = await fetch("https://localhost:3000", {
      dispatcher: h2Client,
      method: "POST",
      body: "12",
      headers: {
        "content-type": "text/plain",
        "content-length": "2",
      },
    });
    console.log("DONE", { response });
  } else if (METHOD === "curl") {
    const curl =
      `curl --no-progress-meter -k -X POST -H "content-type: text/plain" -H "content-length: 2" -d "12" https://localhost:3000`;
    exec(curl, (err, stdout, stderr) => {
      if (err) {
        console.error("DONE", err);
        return;
      }
      console.log("DONE", stdout);
    });
  } else {
    throw new Error();
  }
});
```

Play around with the value of `METHOD` to see what I'm talking about

## Expected Behavior

both `curl` and `fetch` should receive a response quickly.

Instead, `curl` gets a response immediately but `fetch` never returns.

## Logs & Screenshots
```js
// with curl
beginning to read body...
{ chunk: <Buffer 31 32> }
end of reading body
DONE 12
```

```js
// with fetch
beginning to read body...
{ chunk: <Buffer 31 32> }
// never gets passed here
```

## Environment

node v20.3.1
Linux maxs-pc 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Additional context

I have tested this code with
- node's builtin fetch ❌
- undici fetch ❌
- undici `Client#request` ❌
- curl ✅
- Deno fetch ✅

**Comment by vegerot** [comment]
`fetch` will work if you read the body like 

```js
const server = http2.createSecureServer(ssl, async (req, res) => {
  assert.equal(req.method, "POST");
  console.log("beginning to read body...");
  let body = [];
  req.on("data", (chunk) => {
    body.push(chunk);
  });
  let buffer = Buffer.concat(body);
  console.log("end of reading body");
  res.end(buffer);
}).listen(3000);
```

Why is `for await...of` different?

**Comment by vegerot** [comment]
Of course, that's just because I'm only responding with the first `chunk`.  The bug is back if I do

```js
const server = http2.createSecureServer(ssl, async (req, res) => {
  assert.equal(req.method, "POST");
  console.log("beginning to read body...");
  let body = [];
  req.on("data", (chunk) => {
    body.push(chunk);
  });
  req.on("end", () => {
    let buffer = Buffer.concat(body);
    console.log("end of reading body");
    res.end(buffer);
  })
}).listen(3000);
```

**Comment by vegerot** [comment]
Failing test https://github.com/vegerot/undici/commit/f2519dcf5e2ff9bbf01c062b620c59796f8adb40

**Comment by vegerot** [comment]
@strager found that Node `fetch` is sending a "partial entity body" while curl and Deno's `fetch` do not
![image](https://github.com/nodejs/undici/assets/5297725/a2375d1d-60be-4f9b-8043-38fb33f5a5c3) 
![image](https://github.com/nodejs/undici/assets/5297725/3a2cc83a-1dcf-4466-8508-2a6494955eb4)

I don't know what "partial entity body" means, but our hypothesis is that Node `fetch` isn't sending the "whole body", so the server waits forever to get the rest of the body.

**Comment by metcoder95** [comment]
Does it fail if you only use `Client#request` instead?

**Comment by vegerot** [comment]
thanks @metcoder95 

`client.request` also hangs.

I'm using `latest`, aka 5.24.4.

Would you please take a look at the [failing test](https://github.com/nodejs/undici/issues/2311#issuecomment-1747910269)?
