### ISSUE TITLE
test: Flaky test for Fetch + HTTP/2

### ISSUE THREAD

**Issue by metcoder95** [nodejs/undici#2321]
## Bug Description

The following test is unstable and fails from time to time; it requires further research on how to handle it better. An initial guest is a possible race condition but it requires further investigation.

https://github.com/nodejs/undici/blob/e5c9d703e63cd5ad691b8ce26e3f9a81c598f2e3/test/fetch/http2.js#L177

## Reproducible By

- Any PR, often on v20 tests

## Logs & Screenshots

```shell
    # Subtest: [Fetch] Should handle h2 request with body (stream)
        1..8
        ok 1 - should be equal
        ok 2 - should be equal
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equal
        ok 6 - should be equal
        ok 7 - should be equal
        not ok 8 - should be equal
```

## Environment

- Often v20.

**Comment by KhafraDev** [comment]
maybe moving the stream.end() to after the for await?

**Comment by metcoder95** [comment]
Yeah, most likely that might be the scenario as there's race condition between consuming the request's body, and start doing the assertions
