### ISSUE TITLE
`NODE_V8_COVERAGE` leads to different behavior, `dispatcher.on is not a function`

### ISSUE THREAD

**Issue by loynoir** [nodejs/undici#2328]
### Version

v20.8.0

### Platform

Docker ArchLinux 6.1.55-1-lts

### What steps will reproduce the bug?

```sh
$ cat reproduce.mjs 
import { fetch as $fetch, Agent } from "undici";

const controller = new AbortController();

await $fetch("http://127.0.0.1:1234", {
  signal: controller.signal,
});
$ 
$ node reproduce.mjs 
$ 
$ env NODE_V8_COVERAGE='./coverage/tmp' node ./reproduce.mjs
/tmp/tmp.UqQMFN5Qmf/node_modules/undici/index.js:110
        Error.captureStackTrace(err, this)
              ^

TypeError: dispatcher.on is not a function
    at fetch (/tmp/tmp.UqQMFN5Qmf/node_modules/undici/index.js:110:15)
    at async file:///tmp/tmp.UqQMFN5Qmf/reproduce.mjs:5:1

Node.js v20.8.0
```

### What is the expected behavior? Why is that the expected behavior?

`NODE_V8_COVERAGE` does not leads to different behavior.

```sh
$ node reproduce.mjs 
$ 
$ env NODE_V8_COVERAGE='./coverage/tmp' node ./reproduce.mjs
$
```

### What do you see instead?

`NODE_V8_COVERAGE` leads to different behavior.

```sh
$ node reproduce.mjs 
$ 
$ env NODE_V8_COVERAGE='./coverage/tmp' node ./reproduce.mjs
/tmp/tmp.UqQMFN5Qmf/node_modules/undici/index.js:110
        Error.captureStackTrace(err, this)
              ^

TypeError: dispatcher.on is not a function
    at fetch (/tmp/tmp.UqQMFN5Qmf/node_modules/undici/index.js:110:15)
    at async file:///tmp/tmp.UqQMFN5Qmf/reproduce.mjs:5:1

Node.js v20.8.0
```

**Comment by loynoir** [comment]
I created issue in `nodejs/node` https://github.com/nodejs/node/issues/50129.

I don't know why this issue transfer from `nodejs/node` to `nodejs/undici`

---

Quote @KhafraDev

> FinalizationRegister gets disabled with coverage -> use undici's compat one -> attempt to use .on with an AbortController -> error. idk what the expected behavior here is.

---

> FinalizationRegister gets disabled with coverage

@KhafraDev @mcollina

- seems related to https://github.com/nodejs/node/issues/49344

- maybe should revert https://github.com/nodejs/undici/pull/2330

---

> use undici's compat one

- What is a undici's compat one?

- Is there a way not to use compat one?

---

> attempt to use .on with an AbortController -> error

- Is there a manually cleanup way, `undici.addSignal`, `undici.removeSignal`?

```js
    const SUGGESTION_A = "undici.addSignal(signal)";
    const SUGGESTION_B = "undici.removeSignal(signal)";

    if (dispatcher.on) {
      dispatcher.on("disconnect", () => {
        this.finalizer(key);
        if (dispatcher[kConnected] === 0 && dispatcher[kSize] === 0) {
        }
        this.finalizer(key);
      });
    } else {
      // https://github.com/nodejs/node/issues/49344
      if (registedSignal.get(signal)) {
        console.debug(`should call ${SUGGESTION_B} after fetch`)
      } else {
        throw new Error(
          `should call ${SUGGESTION_A} before fetch, and call ${SUGGESTION_B} after fetch`
        );
      }
    }
```

**Comment by meyfa** [comment]
Right, it seems to me that this issue was caused by #2298, which is a workaround for a bug in Node.js. Maybe it's not such a good idea to fix this issue, which was introduced by a workaround, with yet another workaround. I don't have time to come up with a reproduction, but it feels like #2330 would probably break stuff in unexpected ways. These failures will be hard to track down as well, since they depend on the execution environment, and not only the code. Please do not branch the execution based on whether coverage is enabled or not.

@loynoir 

> I don't know why this issue transfer from nodejs/node to nodejs/undici

Well, you are importing from the `undici` package in your reproduction. This is the repository for that.

**Comment by loynoir** [comment]
@meyfa 

Thanks for the link.

Now, I understand the situation.

- `undici` already workaround `node` bug.

- but that workaround not cover `controller.signal`.
