### ISSUE TITLE
content-type always text/plain; charset=utf-8

### ISSUE THREAD

**Issue by vanodevium** [nodejs/undici#2356]
## Bug Description

When I make HEAD requests, **content-type** header is always `text/plain; charset=utf-8`

## Reproducible By

```js
const fetchResponse = await undici.request('https://www.devium.me/functional/', {method: "HEAD"});
const contentType = fetchResponse.headers["content-type"] || "";
console.log({url, contentType});
```

> For another URLs content-type is `text/plain; charset=utf-8` also. See logs.

## Expected Behavior

I think it have to be correct **content-type** header.

## Logs & Screenshots

```
{
  url: 'https://devium.me/functional/',
  contentType: 'text/plain; charset=utf-8'
}

{
  url: 'https://devium.me/css/style.min.492160a6a70449f4e53039777c9b360d07a38b491891aa12cb6681e410b3ffa1.css',
  contentType: 'text/plain; charset=utf-8'
}

{
  url: 'https://devium.me/js/main.min.f2d1aadf04481dae22a434c69fca8b4fd96e4bd859d040e2a8c117a32cd22248.js',
  contentType: 'text/plain; charset=utf-8'
}
```

## Environment

Linux x86_64
node v20.8.1
undici 5.26.3

**Comment by vanodevium** [comment]
There is output with system curl
```
➜ curl -I https://www.devium.me/functional/
HTTP/2 200 
accept-ranges: bytes
age: 115
cache-control: public,max-age=0,must-revalidate
content-type: text/html; charset=UTF-8
date: Wed, 18 Oct 2023 08:54:13 GMT
etag: "b48e55d43f20e758c315f5862a85892b-ssl"
server: Netlify
strict-transport-security: max-age=31536000
x-nf-request-id: 01HD0ZW5T5PEXXA9CV69NH1F00
content-length: 8332
```

**Comment by metcoder95** [comment]
For the second and third example, there's a redirect; which is the cause of the `text/plain` content type; this seems to not be an issue with `undici` at all

**Comment by vanodevium** [comment]
@metcoder95 
Oh, I see. Thank you for response.

My problem is that I did not know that the **maxRedirections** should be specified in the **request()** options in general, now I will know. (Actually, I can't control the URLs that reach me, so redirects are an inherent part of my functionality)

But this is not the main problem. 

The thing is that the native fetch is very slow and I'm looking for a fast alternative.

Maybe you can give me some quick response util?

**Comment by metcoder95** [comment]
Native fetch has some drawbacks, especially with `WebStreams` and other gotchas. If you are not looking for isomorphic code, its better to use `undici` rather than `fetch`. It will fulfill most of the backend-related needs, as well as give you more control over the request/response when doing HTTP calls (also we recently added support for H2, feedback is welcomed)

**Comment by vanodevium** [comment]
@metcoder95 

Thanx!
