### ISSUE TITLE
breaking change - class names got prefixed with _

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/undici#2365]
## Reproducible By

```js
Response.name === 'Response' // false
```

## Expected Behavior

```js
Response.name === 'Response' // true
```
it instead returns `"_Response"`

## Environment

Somewhere between NodeJS v20.6 and v20.8.1 the constructor name got changed.
this broke detection...

## Additional information

Same applies to `FormData`, `Headers` and `Request` - all are prefixed with _ when it shouldn't

**Comment by jimmywarting** [comment]
Same applies to `FormData` and `Request`

**Comment by KhafraDev** [comment]
this was fixed in https://github.com/nodejs/undici/commit/0681760ef1b24a9ddcb257b1a6a121d1825a67c0

**Comment by jimmywarting** [comment]
dupl of #2358
