### ISSUE TITLE
Node 18.18.2 Incorrectly copies headers onto fetches

### ISSUE THREAD

**Issue by bbowman** [nodejs/undici#2374]
## Bug Description

Noticed that in our product using Node 18 that we encountered a slew of issues when moving forward to 18.18.2 that included a CVE fix for undici. Debugging into the issue it appears that in the CVE fix a class name was changed resulting in incorrect behavior. See the screenshot below and I believe it should be a simple fix. The headers copying logic fell down the wrong path when it failed to recognize that the passed in Object was already a Headers object.

## Reproducible By

I dont have a minimal repro handy but it should be just creating a new Request with both an existing request with headers to copy and an init param.

## Expected Behavior

When creating a new request with both a Request object to copy and an init set of options, the headers from the request are preserved.

## Logs & Screenshots

![image](https://github.com/nodejs/undici/assets/15642573/9af65f9c-099e-46e5-b275-6719f0e9d7f7)

## Environment

Node v18.18.2

**Comment by metcoder95** [comment]
cc: @KhafraDev @mcollina

**Comment by KhafraDev** [comment]
duplicate of https://github.com/nodejs/node/issues/50263

**Comment by bbowman** [comment]
@KhafraDev thank you for the quick fix and sorry for not looking for dupes first! Do we have any plan worked out for if / when Node would take this for a 18.18.3? We are avoid taking 18.18x in the meantime but would love the latest security fixes once this is integrated.

**Comment by bbowman** [comment]
https://github.com/nodejs/node/pull/50274 might have that info for others looking.

**Comment by MajorTanya** [comment]
Not sure if that's exactly what you asked, but I can confirm it was fixed in Node v21.1.0 (released yesterday), which included the update to undici 5.26.4, so I'd assume that backporting that update would fix it for v18.x and v20.x as well
