### ISSUE TITLE
Protocol from proxy url is ignored when building proxy Agent

### ISSUE THREAD

**Issue by cheenamalhotra** [nodejs/undici#2390]
## Bug Description
Imagine proxy URL in format:
`http://123.123.1.1:8080`

Code here:
https://github.com/nodejs/undici/blob/3a77cbb471b76175898d8b094beb9b40ceadd671/lib/proxy-agent.js#L33

Doesn't respect 'http' protocol if specified in proxy Url.

## Environment
Node 18

**Comment by metcoder95** [comment]
It somehow relates to #2278, would be better if we fully support the `URL` object instead

**Comment by rossilor95** [comment]
Hey @metcoder95, I think this can be closed

**Comment by metcoder95** [comment]
Closed by #2810
