### ISSUE TITLE
`TypeError: fetch failed` - `SocketError: other side closed` - `UND_ERR_SOCKET`

### ISSUE THREAD

**Issue by ifeltsweet** [nodejs/undici#2400]
## Bug Description

A GET request to [image served by Nginx](https://blog.cheewid.com/wp-content/uploads/2023/11/Cheewit-Nov2-banner.jpg) fails with `fetch` but works with `request`. 

When I serve the same image with another server (Next.js) the `fetch` works without issues.

## Reproducible By

```
import { request, fetch } from 'undici';

// Works.
await request("https://blog.cheewid.com/wp-content/uploads/2023/11/Cheewit-Nov2-banner.jpg");

// Does not work.
await fetch("https://blog.cheewid.com/wp-content/uploads/2023/11/Cheewit-Nov2-banner.jpg");
```

## Expected Behavior

Should work.

## Logs & Screenshots

```
/Users/denisp/Work/cheewid/cheewid-website/node_modules/undici/index.js:110
        Error.captureStackTrace(err, this)
              ^

TypeError: fetch failed
    at fetch (/Users/denisp/Work/cheewid/cheewid-website/node_modules/undici/index.js:110:15)
    at async file:///Users/denisp/Work/cheewid/cheewid-website/test.mjs:7:1 {
  cause: SocketError: other side closed
      at TLSSocket.onSocketEnd (/Users/denisp/Work/cheewid/cheewid-website/node_modules/undici/lib/client.js:1129:22)
      at TLSSocket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '192.168.2.142',
      localPort: 54903,
      remoteAddress: '147.50.231.20',
      remotePort: 443,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 227,
      bytesRead: 0
    }
  }
}
```

## Environment

macOS 13.1
Node 18.17.1
undici 5.27.2

### Additional context

I tried creating a client with `allowH2: true`, but this time the process crashes without producing any error logs.

```
import { Client, fetch } from 'undici';

const client = new Client('https://blog.cheewid.com', {
  allowH2: true,
});

await fetch("https://blog.cheewid.com/wp-content/uploads/2023/11/Cheewit-Nov2-banner.jpg", {
  dispatcher: client,
});
```

**Comment by metcoder95** [comment]
👋 
It can be related to the network settings at your `nginx` instance. Can you provide 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so we can help you in a better way?

I tried reproducing your example, and it just worked.

**Comment by ifeltsweet** [comment]
@metcoder95 Unfortunately, I don't have access to the Nginx settings. But here is are two sandboxes that may help you to reproduce the example:

- https://stackblitz.com/edit/node-zwkmc8?file=index.mjs,package.json
- https://codesandbox.io/p/sandbox/pedantic-wood-zk29pp?file=%2Findex.mjs%3A6%2C1

> I tried reproducing your example, and it just worked.

Thank you for trying! I wonder if this has anything to do with the network you are on. My colleagues and I are located in Thailand, and the provided image URL fails on all the machines and networks we tried with.

Both of the sandboxes above cannot fetch the image as well.

**Comment by metcoder95** [comment]
Hmm, this is interesting. It seems that `client.request` works, can you verify that?

Chrome seems to fetch them well, on most of the reproduction what I'm seeing is that something is causing a remote termination from the server, not the client. Not sure this really a problem with `undici` but rather the `nginx` settings. Would you like to move this into a discussion to help you further?

**Comment by andrewizbatista** [comment]
I'm having the same exact issue, while using `undici` inside the `connect` from `@planetscale/database`.

**Comment by andrewizbatista** [comment]
Ok I found the issue _(which was in my face all the time, too early here)_, `hostname: 'undefined'`

I'm sorry for polluting the issue, my bad.

**Comment by metcoder95** [comment]
No worries, it happens 😉 
When in this case, feel free to open a GH discussion first and later we can make it issue if we found there's something to do at `undici` 👍

**Comment by ifeltsweet** [comment]
@metcoder95 can you please reopen this issue because it was not fixed.

> It seems that client.request works, can you verify that? 

Yes `request` and `client.request` work, but `fetch` does not.

> Not sure this really a problem with undici but rather the nginx settings

Yes, the Nginx settings may be having some play here but why is `client.request` not affected by it while `fetch` is?

**Comment by metcoder95** [comment]
Oh, sorry, I closed by mistake. Confused myself with the previous comment.

Ok, now I was able to reproduce it, and so far the issue stills seems directly related with the server setup. For some reason, this is only reproducible if we append the following headers to the request:
```js
{
    accept: '*/*',
    'accept-language': '*',
    'sec-fetch-mode': 'cors',
    'user-agent': 'undici',
    'accept-encoding': 'br, gzip, deflate'
}
```

Reproducing the same call that `fech` attempts, but removing those headers, the issue is gone completely, meaning the connection is maintained.
I'm not sure what might be happening, but it could be an encoding issue or similar.

```js
getGlobalDispatcher().dispatch(
  {
    path: '/wp-content/uploads/2023/11/Cheewit-Nov2-banner.jpg',
    origin: 'https://blog.cheewid.com',
    method: 'GET',
    body: null,
    // headers: { uncomment them and it fails
    //   accept: '*/*',
    //   'accept-language': '*',
    //   'sec-fetch-mode': 'cors',
    //   'user-agent': 'undici',
    //   'accept-encoding': 'br, gzip, deflate'
    // },
    maxRedirections: 0,
    upgrade: undefined
  },
  {
    abort: null,
    onError (err) {
      console.log(err) // gone
    },
    onHeaders (status) {
      console.log('headers', status) // 200
      return true
    },
    onData (chunk) {
      return true
    },
    onConnect (abort) {
      console.log('connected')
      this.abort = abort
    },
    onComplete () {
      console.log('completed')
    }
  }
)
```

**Comment by metcoder95** [comment]
Narrowed even more, it closes it as soon as it sees the `user-agent` is set to `undici`. Maybe is not within an allow list?
