### ISSUE TITLE
Request body of type `ReadableStream` omitted when `MockAgent["disableNetConnect"]` enabled

### ISSUE THREAD

**Issue by mpint** [nodejs/undici#2418]
## Bug Description

Request bodies of type `ReadableStream` are omitted when `MockAgent["disableNetConnect"]` (or `enableNetConnect(url)`) is enabled.

This bug was originally filed under `miniflare`/`workers-sdk`, but was subsequently diagnosed as an `undici` issue.

## Reproducible By

Please see [this issue](https://github.com/cloudflare/workers-sdk/issues/4356) for a reproduction within a Cloudflare. A diagnosis of the root cause is included in the OP in the "Diagnosis" section.

[Courtesy of](https://github.com/cloudflare/workers-sdk/issues/4356#issuecomment-1803577678) @mrbbot 
```
import http from "node:http";
import { MockAgent, setGlobalDispatcher, fetch } from "undici";

function startServer() {
  const server = http.createServer((req, res) => {
    res.write(`${req.method} `);
    req.pipe(res);
  });
  
  return new Promise((resolve) => {
    server.listen(0, () => {
      resolve(new URL(`http://127.0.0.1:${server.address().port}`));
    });
  });
}

const url = await startServer();

const fetchMock = new MockAgent();
fetchMock.enableNetConnect(url.host);
setGlobalDispatcher(fetchMock);

const res1 = await fetch(url, {
  method: "POST",
  body: "hello"
});
console.log({ res1: await res1.text() }); // "POST hello"

const res2 = await fetch(url, {
  method: "POST",
  body: new Blob(["hello"]).stream(),
  duplex: "half"
});
console.log({ res2: await res2.text() }); // "POST" (no body)
```

## Expected Behavior

Body should be sent in `res2`

## Environment

Node 18x, OSX 13.6

**Comment by tsctx** [comment]
Hi @mpint,
This issue will be fixed in #2425.
