### ISSUE TITLE
Node crash on second fetch call to caused by parseJSONFromBytes

### ISSUE THREAD

**Issue by stephan-bosch** [nodejs/undici#2442]
## Bug Description

Greetings,

EDIT:

Right after i  posted here i noticed something. before the explained API call is made a different Fetch Call is made and that is the actual cause of the JSON parse error.

![create destination bad request](https://github.com/nodejs/undici/assets/85499114/2e1c4f0d-f9c4-4df5-9104-3ece6a25f505)

The code continues on calling the explained situation below and only after that the server is crashing. 

-----------------

I am the following Fetch call to an api endpoint that is part of a class as an async function call where the class is exported and the function is called outside from a node express endpoint. Also same information using postman works fine.

`const response = await fetch(
			this.xsuaaEnv.credentials.apiurl +
				"/sap/rest/authorization/v2/rolecollections",
			{
				method: "POST",
				headers: {
					"Content-type": "application/json",
					Authorization: "Bearer " + params.token.access_token,
				},
				body: JSON.stringify({
					"name": params.name,
					"description": params.description,
					"roleReferences": params.roleReferences,
				}),
			}
		);`

When the server sends the response back these are the headers:

![server response headers](https://github.com/nodejs/undici/assets/85499114/a8466f92-fe39-4dce-85ef-4999f35d2c7c)

Not that the response is OK and the actual task is verified being done.
But for some reason the following error occurs:

![fetch parse error](https://github.com/nodejs/undici/assets/85499114/8b870fdb-e47e-4940-bdd6-6fca2685b41d)

After going deep into the debug i managed to verify the data it is trying to parse and that is B is the start of Bad Request in plain text.

Now here is the odd behaviour:

i can still parse the body using .text() even after the error had occurred as shown by the header property bodyUsed false

When using try catch this error is never caught, it is only displayed in console.

Surrounding the fetch in try catch block or using .catch((err) => { console.log(err) }) is never triggered!
Instead it is treated as a succesfull request and in fairness it is cause the API call did successfully do what it needed to do.

At this point the server has not yet yet crashed.
Now without creating a class instance we call the same method again to the same endpoint

![node crash](https://github.com/nodejs/undici/assets/85499114/980d0ac4-c0b6-4c81-b23a-9018b1b1e99e)

The main problem is i have no clue where that "bad request" is coming from since the server and the body does not contain it.
But it could be related to [socket closed](https://github.com/nodejs/undici/issues/2412)

i did see this occurring on the second time the fetch call was made.

## Environment

Windows 11, 
visual studio code,
Node v18.12.0 (also happened on latest node LTS 20 version)

### Additional context

i am at a loss the odd thing is that it was working fine till a few days ago, i have no clue what changed.
I hope this is enough information and any help is appreciated.

## Summery

Async method containing a post fetch call where the async method is awaited. This call fails due to json parse exception and a different async await method is called that succeeds once and on the second call server is crashing.

It took me to write this post to relize what i had to change, but i leave it up to someone else to decide if the behavior explained is something that needs to be addressed.

kind regards,

stephan

**Comment by metcoder95** [comment]
👋 
The `Bad Request` is a plain text response provided by the server. When trying to parse it as JSON it fails as it is not a valid JSON string.

On the other hand, the error swallowing is normal as you are forking the promise chain.
Check your server requirements and validate how are you sending the request to verify why the server is returning 200 with a `Bad Request` as response's body

**Comment by stephan-bosch** [comment]
> 👋 The `Bad Request` is a plain text response provided by the server. When trying to parse it as JSON it fails as it is not a valid JSON string.
> 
> On the other hand, the error swallowing is normal as you are forking the promise chain. Check your server requirements and validate how are you sending the request to verify why the server is returning 200 with a `Bad Request` as response's body

Thank you for your responds.

i just updated my post, i found the actual issue after i wrote the post... but i leave it to someone else to decide if the behavior described of server crash is something to look into . 

Its one of those cases where i just had to write out the issue to find what my issue was.

kind reagrds,

stephan
