### ISSUE TITLE
Error: ReferenceError: ReadableStream is not defined

### ISSUE THREAD

**Issue by ehuelsmann** [nodejs/undici#2512]
After updating the version of the "[undici](https://github.com/nodejs/undici)" lib version to 6.0.1 we started receiving the error "ReferenceError: ReadableStream is not Define", has anyone experienced this?

_Originally posted by @hygormartins10 in https://github.com/nodejs/undici/discussions/2508_

Turned into an issue on request of @ronag.

**Comment by ehuelsmann** [comment]
We use GitHub Actions with `actions/setup-node@v4` and node version `latest` (which is definitely newer than the minimum node version of 18 referenced in the discussion), but we're experiencing the same problem as the reporter. See ledgersmb/LedgerSMB#7780 (more specifically: https://github.com/ledgersmb/LedgerSMB/actions/runs/7138005066/job/19438901209?pr=7780#step:8:113 )

**Comment by ehuelsmann** [comment]
Yes. No idea about the original reporter's case, but this is the full error - on Node 21.4.0:

```plain
$ /home/runner/work/LedgerSMB/LedgerSMB/UI/node_modules/.bin/jest --coverage
FAIL tests/specs/openapi/API-invoices.spec.js
  ● Test suite failed to run

    ReferenceError: ReadableStream is not defined



      at Object.<anonymous> (node_modules/undici/lib/fetch/response.js:506:3)
      at Object.<anonymous> (node_modules/undici/index.js:118:27)
      at Object.<anonymous> (tests/common/jest.polyfills.js:32:5)
```

**Comment by ronag** [comment]
Can you make a minimal repro I can run? It works just fine for me. I would guess this is a jest issue.

**Comment by ronag** [comment]
We are not big jest fans and are not very keen on spending time on jest-related issues. However, if you open a PR with a fix we are likely to accept it.

**Comment by ehuelsmann** [comment]
> Can you make a minimal repro I can run? It works just fine for me. I would guess this is a jest issue.

Have truckloads of development experience, but 99.9% of it outside of the JS world. Can you enlighten me what it is that makes you say this and "we're not big jest fans"? Does Jest have issues intervening with the libraries it uses that other test frameworks don't have?

**Comment by mcollina** [comment]
@ehuelsmann basically `ReadableStream` is a global in Node.js v18+ that jest is not exposing.
This is an issue about `jest`, not undici.

**Comment by nicole0707** [comment]
You could add this into jest environment file
```ts
import { ReadableStream } from "node:stream/web";
this.global.ReadableStream = ReadableStream;
```

**Comment by Mxnet-do-it-yourself** [comment]
> Can you make a minimal repro I can run? It works just fine for me. I would guess this is a jest issue.





https://profiler5.github.io/53_xNdYUaV4m904E8w/
