### ISSUE TITLE
Importing in Node.js < 18

### ISSUE THREAD

**Issue by char0n** [nodejs/undici#2521]
## Bug Description

After importing the `undici@6` on Node.js 16.16.0, we see the following error. I know `unidici@6` now supports only Node.js >= 18.

```
Uncaught ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/node_modules/undici/lib/fetch/response.js:506:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

## Reproducible By

Node.js 16.16.0

```
import { fetch } from 'undici';
```

## Expected Behavior

Import would work, but imported `fetch` symbol will be `undefined`. This is how it worked on for `undici@5` and allows us to fallback to different `fetch` implementation.

## Environment

Node.js 16.16.0

**Comment by char0n** [comment]
Hi, 

I'm not sure if this is fixable or now, but it would be great for `undici@6` to work as `undici@5` as this behavior (returning undefined) allowed for a lot of flexibility.

**Comment by ribeaud** [comment]
I do not know whether this is relevant here but I am getting this error as well and we are using **Node** _20_.

**Comment by mcollina** [comment]
> I do not know whether this is relevant here but I am getting this error as well and we are using Node 20.

Please provide a reproduction, this should not happen Node 20.

---

I'm not sure what the ask is. Node.js v16 is _deliberately_ not supported anymore, it's out of maintenance and you should likely migrate off from it.

**Comment by char0n** [comment]
> I'm not sure what the ask is. Node.js v16 is deliberately not supported anymore, it's out of maintenance and you should likely migrate off from it.

It's about detection and polyfilling. `undici@5` worked from Node.js >= 16.8 (fetch part). In Node.js <16.8, we could still do 

```js
import { fetch } from 'undici';
```

...and it didn't throw any error. Instead imported `fetch` function was `undefined`. This allowed us to fallback to `node-fetch` on older Node.js versions:

```js
import { fetch as fetchU } from 'undici';
import { fetch as fetchN } from 'node-fetch';

const fetchFn = fetchU | fetchN;
```

This is no longer possibly with `undici@6`, as it throws errors directly during the import.

**Comment by ribeaud** [comment]
And if the error is thrown, then it would be `ReferenceError: ReadableStream is not defined`?

I am not sure I will be able to provide a simple reproduction step (the project is huge!). But I can start to explain, and maybe this will ring a bell on your side?

This is about [this](https://gitlab.com/biomedit/portal/-/tree/main/frontend) project. We introduced **undici** because of **msw** last move/version. In our **Jest** tests suite, we load a [jest.polyfills.js](https://gitlab.com/biomedit/portal/-/blob/da8a2d9afb48d091648c5f158507ca0426c0ac0b/frontend/src/jest/jest.polyfills.js). This used to work pretty well until [undici@6](https://gitlab.com/biomedit/portal/-/merge_requests/1011).

**Comment by Ethan-Arrowood** [comment]
I believe a solution is to load a ReadableStream implementation of your own and make it apart of the global scope _before_ importing Undici.

**Comment by char0n** [comment]
@Ethan-Arrowood yeah thanks for the suggestion.

```js
import { ReadableStream } from 'node:stream/web';

globalThis.ReadableStream = ReadableStream;
```

The issue is that I don't want to run `undici@6` on Node.js versions that are officially unsupported. I'd really want it to be able to import but check the `fetch` imported symbol as I described in https://github.com/nodejs/undici/issues/2521#issuecomment-1857523871. But if this `undici@6` is not going to be aligned with `undici@5` behavior, I guess I can do it myself by using `ReadableStream` and `process.version` as semaphores.

**Comment by ribeaud** [comment]
I tried the suggested solution. It helped but unfortunately not for all my tests (I'm still having a lot of them failing). Thanks anyway though.
