### ISSUE TITLE
Jest throws TLSWRAP error while using fetch

### ISSUE THREAD

**Issue by slim-hmidi1** [nodejs/undici#2522]
## Bug Description

I created a function wrapper that uses fetch api in Node 18, the function works well when I did some api calls but there is some log errors thrown by jest after executing the tests.

## Reproducible By
```ts
function client<T>({
  url,
  data,
  config,
}: Props) {
  const method = config?.method ?? 'GET';
  const requestInit: Partial<NodeJS.fetch.RequestInit> = {
    method,
    body: data ? JSON.stringify(data) : undefined,
    ...config,
  };


  const request = new Request(url, requestInit);

  const response = await fetch(request);
  const responseData = await response.json();
  if (!response.ok) {
    throw new CustomError('....');
  }

  return responseData as T;
}
```

Then I created this test:
```ts
describe('client', () => {
   test('Should retun an error while deleting a non exiting item', async () => {
    const itemId= 'item_id';

    await expect(client({ endpoint: `items/${itemId}`, config: { method: 'Delete' } })).rejects.toThrow(`Error occurs while executing /DELETE items/${itemId}: Not Found`);

  });
  });
 ```
 The test passed correctly but I got this error after that:
 ```ts
 Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  TLSWRAP

      27 |   const request = new Request(url, requestInit);
      28 |
    > 29 |   const response = await fetch(request);
         |                          ^
 ```
 

## Expected Behavior

No  log erros should be thrown after the test pass.
## Environment

MacOs: 14.1.2 
Node: v18.18.0

**Comment by ronag** [comment]
We don't support Jest. Sorry.

**Comment by slim-hmidi1** [comment]
@ronag I think the issue here that connection executed by fetch api stays open even the promise is resolved and that's what jest is complaining about.

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) without TS for easier reproduction?

I'd recommend to try first adding a custom `agent/client` with `pipeline: 0` to disable keep-alive and start from there.

**Comment by KhafraDev** [comment]
to be clear this is an issue with jest, if disabling pipelining works we should include that in the docs somewhere

**Comment by ronag** [comment]
If we are sure this is a jest issue then I'm closing this.
