### ISSUE TITLE
Dispatcher.connect doesn't include `origin` field

### ISSUE THREAD

**Issue by dvoytenko** [nodejs/undici#2531]
## Bug Description

[`ConnectOptions`](https://github.com/nodejs/undici/blob/871baa74ec326518a3de3ee4591459e25617402e/types/dispatcher.d.ts#L123) interface doesn't include an `origin` field that's required for the [HTTP CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT).

Furthermore, it appears that the `agent.connect({})` currently fails to execute without the `origin` field.

## Reproducible By

```
const agent = new Agent();
agent.connect({
  origin: "https://example.com",
  path: "/robots.txt"
 });
```

This gives a TypeScript error for unknown "origin" field.

## Expected Behavior

Origin is accepted.

## Environment

Any

**Comment by metcoder95** [comment]
Would you like to send a PR?

**Comment by dvoytenko** [comment]
@metcoder95 I took a stub at it in https://github.com/nodejs/undici/pull/2532. But not sure what to do with backward compat, so I left it an optional field.

**Comment by KhafraDev** [comment]
Type changes are always considered minor changes, it's fine to make the field required (especially since it doesn't work without it).
