### ISSUE TITLE
TypeError: Invalid state: Writer has been released

### ISSUE THREAD

**Issue by FishOrBear** [nodejs/undici#2540]
ref:https://github.com/cloudflare/miniflare/issues/147

in vscode debugging, using will trigger an error.

![image](https://github.com/nodejs/undici/assets/19372111/df9d8344-6574-4c98-80d6-9622a5449ba1)

```
     let res = await fetch("https://api.64clouds.com/v1/");
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by FishOrBear** [comment]
thank you for your reply

https://github.com/FishOrBear/fetch_ts_error_demo

npm i
Open /src/test.ts using vscode
Turn on uncaught exceptions
Start debugging run ts

![image](https://github.com/nodejs/undici/assets/19372111/7ffc4000-1a37-4e2d-bc4e-8106ffa15f47)

**Comment by metcoder95** [comment]
Tried to reproduce it with a different node version and sadly I couldn't.
The `promise`s resolves as expected; including a body with an error within.

**Comment by mcollina** [comment]
what version of Node are you using?

**Comment by FishOrBear** [comment]
Microsoft Windows [版本 10.0.19044.3803]
nodejs 21.5

**Comment by KhafraDev** [comment]
this is more likely an issue with web streams than with fetch

**Comment by mcollina** [comment]
I cannot reproduce

**Comment by FunctionPoint** [comment]
I also have this error with the following example code:

```
// import fetch from "node-fetch";

function doIt()
{
	fetch( 'http://www.boredapi.com/api' )
	.then( response => response.text() )
	.then( text => console.log( text ) )
	.catch( error => console.log( error ) );
}
doIt();
console.log( "Exiting app, but fetch still running" );
```

Running on VSCode current and NodeJS current on Windows 11 current. 
(But the error occured earlier).
.
Some extra info: 
If you uncomment the first line and import "node-fetch" the error disappears. (my current workaround, BTW)
If you place a breakpoint on the last console.log(...) line, and then resume with F5 after a second, the error also disappears.
.
PS The correct output is: '{  "message": "Bored API" }'

**Comment by FunctionPoint** [comment]
PS here is a screen shot of the call stack for the above.
![stack](https://github.com/nodejs/undici/assets/9684694/c9d31ae0-2dbc-4189-ad8b-b11ae4d15311)

**Comment by metcoder95** [comment]
Tried to reproduce the issue with the provided code and didn't have any success.

```js
function doIt () {
  undici.fetch('http://www.boredapi.com/api')
    .then(response => response.text())
    .then(text => console.log(text))
    .catch(error => console.log(error))
}
doIt()
console.log('Exiting app, but fetch still running')
```

Tried on different Node versions as well without luck:

<img width="273" alt="image" src="https://github.com/nodejs/undici/assets/10200776/4468651e-8dc6-4824-bb10-591242a67408">

**Comment by FunctionPoint** [comment]
Did you use VSCode and in "Breakpoints" check the "Uncaught Exceptions" option?
![Uncaugt exceptions](https://github.com/nodejs/undici/assets/9684694/f3b52b73-1f8d-4f45-b456-f3f665a801bc)
The error occurs in some finalization (cleanup) function that is not needed to produce the correct output.
So if you do not "break" on that, the program will seem to function normally.
I suspect the exiting of Node.JS cleans something up that Undici still needs when handling the subsequent fetch callback.
(Closes the writer steam)
.
When debugging a program, the option op catching uncaugth exceptions is very handy in finding bugs.

**Comment by FunctionPoint** [comment]
Looking at the callstack, the last called Undici function is `fetchFinale`.
The error occurs on this line of the function:
`response.body = { stream: response.body.stream.pipeThrough(transformStream) };`
Maybe there cloud be some check built in there to see if the streams are still valid?

**Comment by Uzlopak** [comment]
I also faced this bug while implementing eventsource.

**Comment by mcollina** [comment]
@Uzlopak can you reduce it to simple reproduction?

**Comment by yemreak** [comment]
To ignore this, you can use:

`error.message !== "Invalid state: Writer has been released"` (set it for both of the two)

<img width="343" alt="image" src="https://github.com/nodejs/undici/assets/49655146/bf141817-fb1b-4d35-852a-25b06b3c8067">
<img width="346" alt="image" src="https://github.com/nodejs/undici/assets/49655146/24f59656-1b4e-49c1-802d-bfc3c9598ec3">

**Comment by FunctionPoint** [comment]
Thanks, this does indeed prevent a debugger break on this error.
But still needs to be solved, I should think.
@mcollina : Did you try using VSCode already? 
The reproduction sequence is quite minimal and deterministic..

**Comment by yemreak** [comment]
I found **solution**. If you dont use `node-fetch` library and use `vscode` default `fetch` functions this error occurs.

Import `node-fetch`

```ts
// npm install node-fetch
import fetch from "node-fetch"

export async function getPublicIP(): Promise<string> {
	const response = await fetch("https://httpbin.org/ip")
	const data = (await response.json()) as { origin: string }
	return data.origin
}
```

## Vs Code Fetch API

- if you ⌘ Click on your `fetch` function u will see it's reference

<img width="1079" alt="image" src="https://github.com/nodejs/undici/assets/49655146/30a3dff3-95d4-4fb2-b52b-538bdf4afd3e">


@FunctionPoint

**Comment by KhafraDev** [comment]
This isn't an issue with fetch, there isn't much we can do here. I'd recommend reporting this in the node repo. Here's a repro that doesn't use fetch (put a breakpoint on the `return ''` and the same error occurs):

```js
async function run () {
  const transform = new TransformStream({
    start () {},
    transform (chunk, controller) {
      controller.enqueue(chunk)
    },
    flush () {}
  })

  const readable = new ReadableStream({
    async start (controller) {
      controller.close()
    }
  })

  const piped = readable.pipeThrough(transform)
  const reader = piped.getReader()

  while (true) {
    const { done } = await reader.read()

    if (done) break
  }

  return ''
}

run()

```

**Comment by FunctionPoint** [comment]
@yemreak 
Yes, when using "node-fetch", this error does not occur.
This is my current workaround.  (as stated above)

**Comment by mchapman** [comment]
I am getting this coming up in 20.11.0 (current LTS).  Using the node-fetch workaround.  Very difficult for me to isolate to a minimal case (and there seems to be no appetite for fixing anyway).

**Comment by KhafraDev** [comment]
As I mentioned, this is an issue with webstreams or vscode debugging, there is nothing to fix in undici.

**Comment by FunctionPoint** [comment]
Hah, as GitHub autoamtically did above:
The current version of node (23.6) seems to have solved this bug.
It no longer occurs in my software.
So I'm removing the workaround; use of the 3rd pary module node-fetch.
