### ISSUE TITLE
Non-GET http2 requests without a body hang indefninitely

### ISSUE THREAD

**Issue by ktaekwon000** [nodejs/undici#2589]
## Bug Description

When using fetch to make non-GET/HEAD http2 requests, the function call hangs indefinitely. Passing in an empty string in place of the body fixes this issue.

## Reproducible By

The following js script triggers the issue on undici v6.2.1
```javascript
'use strict'

const { fetch, Client } = require('undici')

async function main () {
    const client = new Client("https://google.com", { allowH2: true });
    const res = await fetch("https://google.com", {
        dispatcher: client,
        baseURL: 'https://google.com',
        url: 'https://google.com/',
        method: "POST",
    })

    const data = await res.text()
    console.log('response received', res.status)
    console.log('headers', res.headers)
    console.log('data', data)
}
main()
```

## Expected Behavior

The function call should send the request with an empty body.

## Environment

macOS 14.0, node v20.8.1, undici v6.2.1

### Additional context

I believe the issue is closely related to #2258 , but while this PR had only fixed GET/HEAD requests, this actually affects all kinds of requests.

**Comment by metcoder95** [comment]
Hey! Thanks for the report

I believe this should be scope to validate wether or not there's a body at all being sent.

Would you like to submit a PR?

**Comment by ronag** [comment]
> I believe this should be scope to validate wether or not there's a body at all being sent.

I'm confused. It should be possible to send a fetch without body? Also this sounds like we are missing something in the spec language? @KhafraDev

**Comment by KhafraDev** [comment]
this isn't an issue with fetch afaict

**Comment by timursevimli** [comment]
While I was trying to investigate this problem, I discovered a completely different problem.

When we pass body the following object appears:
```js
{
   finalBody: {
     stream: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
     source: 'helloWorld',
     length: 10
   }
}
```
(For this output I used output a variable called finalBody in undici/lib/fetch/request.js:505)

Well, if we pass an object to body, then we get the following output:
```js
{
   finalBody: {
     stream: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
     source: '[object Object]',
     length: 15
   }
}
```
In this case, regardless of the size of our object, length will always be 15 and source will be incorrect.

**Comment by taekwon-datature** [comment]
@timursevimli I believe the problem you're facing is not a bug, and not related to the problem I've posted in the OP. Try passing in your object as `data` not `body`, or stringifiying the JSON yourself and setting the respective content-type if using `body`.

**Comment by ktaekwon000** [comment]
@timursevimli I believe the problem you're facing is not a bug, and not related to the problem I've posted in the OP. Try passing in your object as `data` not `body`, or stringifiying the JSON yourself and setting the respective content-type if using `body`.

**Comment by timursevimli** [comment]
@ktaekwon000 I agree that the problem is not related to your problem, well, while I was debugging the body that is being transmitted, I noticed such a problem. The fetch specification does not necessarily require us to manually convert objects to strings. The implementation of fetch in undici creates a so-called finalBody object that contains 3 attributes such as stream, source, length. The problem is that here length is subtracted from the length of source. Well, if source was an object, when converted into a string in the wrong way and therefore we get the wrong length.

I repeat, the problem is not related to your problem, and while I don’t quite understand why finalBody is needed, where it is passed and how its attributes are used, well, it is still calculated incorrectly and this is a fact.

Perhaps we should report this with a new issue, if it’s not specifically designed that way, of course

**Comment by Piyush-Kumar-Ghosh** [comment]
### Proposed Solutions:

1. **Enhancing undici Library:**
   - **File to Modify:** `lib/fetch.js`
   - **Approach:** I suggest a tweak in the undici library where we can specifically check for an empty body. This adjustment would involve handling the content-length header appropriately.

2. **Adjusting Fetch Options:**
   - **Resolution Approach:** To address the issue, consider adjusting the `fetch` options. Explicitly include an empty body in the request.
   
   ```javascript
   // Example Code Snippet
   const res = await fetch("https://google.com", {
       dispatcher: client,
       baseURL: 'https://google.com',
       url: 'https://google.com/',
       method: "POST",
       // Include an empty body
       body: ''
   });
   ```

   *This modification ensures that the function call sends the request with an empty body, effectively resolving the hanging behavior.*

**Comment by mcollina** [comment]
Given this works with HTTP/1.1, it's not a bug in `fetch()` but in our HTTP/2 implementation.

**Comment by ktaekwon000** [comment]
I can verify that the script in the OP runs without issues on v6.4.0 of undici. Thanks everyone for the comments and @timursevimli for the PR!
