### ISSUE TITLE
fetch() with parameters causes headers to be lost

### ISSUE THREAD

**Issue by magcius** [nodejs/undici#2602]
## Bug Description

It seems that if I use fetch() with initialization parameters on a request with headers, those headers are lost. This doesn't match the behavior I see in browsers.

## Reproducible By

```ts
var r = new Request("http://example.com");
r.headers.set("Range", "bytes=10-20");
fetch(r); // works fine
fetch(r, { }); // so does this
fetch(r, { signal: null }); // fetch has missing headers
```

## Expected Behavior

I expect the headers from the passed-in request to be retained, even though unrelated parameters were added to the fetch options.

## Environment

I'm using the fetch builtin to node in node v20.9.0

### Additional context

It appears to be an issue in the webidl converter of Request, as I can reproduce it with:

```ts
var r = new Request("http://example.com");
r.headers.set("Range", "bytes=10-20");

new Request(r); // works fine
new Request(r, { }); // also works fine
new Request(r, { signal: null }); // headers are missing
```

**Comment by KhafraDev** [comment]
upgrade to node v20.10.0
