### ISSUE TITLE
Error: incorrect header check Z_DATA_ERROR

### ISSUE THREAD

**Issue by jaschaio** [nodejs/undici#2603]
## Bug Description

I am trying to fetch a URL but it fails. It works just fine when I use `node-fetch`, `curl` or the native browser `fetch`. It's similar to #1271 but there is no redirect happening.

These are the response headers:

```
{
  'cache-control': 'no-cache',
  'content-encoding': 'deflate',
  'content-type': 'text/xml; charset=utf-8',
  date: 'Mon, 08 Jan 2024 06:12:38 GMT',
  server: 'lighttpd/1.4.45',
  'transfer-encoding': 'chunked'
}
```

## Reproducible By

```js
const response = await fetch( 'https://egauge90013.egaug.es/cgi-bin/egauge-show?a&E' );

const text = await response.text();

console.log( text );
```

## Expected Behavior

I would expect the response to log into console

## Logs

Instead I get this error:

```
TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:11279:53)
    at Fetch.emit (node:events:513:28)
    at Fetch.emit (node:domain:489:12)
    at Fetch.terminate (node:internal/deps/undici/undici:10534:14)
    at Fetch.fetchParams.controller.resume (node:internal/deps/undici/undici:11258:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: incorrect header check
      at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {
    errno: -3,
    code: 'Z_DATA_ERROR'
  }
}
```

## Environment

Node v20.7.0 and v18.14.2

**Comment by mcollina** [comment]
Can you please set up a simple node server that reproduce the problem?

**Comment by jaschaio** [comment]
> Can you please set up a simple node server that reproduce the problem?

https://codesandbox.io/p/devbox/fetch-lxhr8s

**Comment by mcollina** [comment]
I don't see a server there, only the fetch client.

**Comment by ronag** [comment]
Probably related https://github.com/node-fetch/node-fetch/blob/8b3320d2a7c07bce4afc6b2bf6c3bbddda85b01f/src/index.js#L315

**Comment by ronag** [comment]
PR welcome

**Comment by jaschaio** [comment]
> I don't see a server there, only the fetch client.

Sorry, I misread your question. I don't control the server so not sure what exactly they are doing in their response that is causing issues with node fetch / unidici.

**Comment by jaschaio** [comment]
> Probably related https://github.com/node-fetch/node-fetch/blob/8b3320d2a7c07bce4afc6b2bf6c3bbddda85b01f/src/index.js#L315

Thanks, do you mean `node-fetch` has some special handling not present in unidici and that's why it works with `node-fetch` but not node native `fetch`?
