### ISSUE TITLE
Can't Ignore SSL Error ERR_SSL_DH_KEY_TOO_SMALL

### ISSUE THREAD

**Issue by Poyoman39** [nodejs/undici#2620]
## Bug Description

I need to request an old website with outdated SSL security leading to an ERR_SSL_DH_KEY_TOO_SMALL error.

I need to ignore this error on this specific request.

- I tried to use `rejectUnauthorized: false` but this is not taken into account
- I tried to use `OPENSSL_CONF=someCustom.cnf` env variable and it's not taken into account either

## Reproducible By
```JavaScript
import { Agent, setGlobalDispatcher, fetch } from 'undici';
setGlobalDispatcher(new Agent({ connect: { rejectUnauthorized: false, } }))

await fetch('https://www.aerocontact.com/entreprise-aeronautique/societe-latecoere-1128/offres-emploi-aeronautique?')
// This throw with ERR_SSL_DH_KEY_TOO_SMALL
```

## Expected Behavior

I want the ssl error to be ignored when i specify `rejectUnauthorized: false`

## Environment

Node.JS v20.10.0
OpenSSL 3.2.0
EndeavourOS (last)

**Comment by metcoder95** [comment]
I've tried to reproduce it without luck. When trying to reproduce it with also another local reproduction still do not have any luck, `fetch` fails if `rejectUnauthorized`  is set to `true` and goes through otherwise.

```js
const server = createServer(pem, (req, res) => {
  res.writeHead(200, { 'content-type': 'text/plain' })
  res.end('hello h1!')
})

setGlobalDispatcher(new Agent({ connect: { rejectUnauthorized: false } }))

server.listen(0, () => {
  const { port, address, family } = server.address()
  const host = family === 'IPv6' ? `[${address}]` : address

  fetch(`https://${host}:${port}`).then(
    res => {
      console.log(res.status, res.statusText)
    },
    err => console.log(err)
  ).then(() => server.close())
})
```

**Comment by Poyoman39** [comment]
Hi @metcoder95 thank you for your quick answer. I made some tests and i did not reproduce on linux with OpenSSL 3.1.x. Maybe the problem come whith OpenSSL 3.2.0 ... I'm searching a bit more to be sure.

**Comment by Poyoman39** [comment]
I made some tests i think  (for reasons i don't know) undici ignores openssl configuration.

I edited /etc/ssl/openssl.cnf file on my system

With Following configuration (low sec level) :
```
[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=1
```
I get this this =>

Curl working :
`curl 'https://www.aerocontact.com/entreprise-aeronautique/societe-latecoere-1128/offres-emploi-aeronautique?'`

node.js fetch throw

With default configuration (normal sec level) :
Curl :
`curl 'https://www.aerocontact.com/entreprise-aeronautique/societe-latecoere-1128/offres-emploi-aeronautique?'`
Output : `> curl: (35) OpenSSL/3.2.0: error:0A00018A:SSL routines::dh key too small`

Node.js Fetch fails but it's normal


I hope this helps

**Comment by Poyoman39** [comment]
It looks like undici with node.js use its own openssl service / configuration file and ignore system configuration and `--openssl-config` argument

**Comment by metcoder95** [comment]
I'm still having some hard times reproducing, most likely might be doing it wrong; though, an `openssl.cnf` example for a customized behaviour should follow a similar format:
```config
nodejs_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv2
CipherString = DEFAULT:@SECLEVEL=2
```

And should be passed down to `node` using its either flag or the environment variable `OPENSSL_CONFIG`.
e.g. **flag**
`node --openssl-config /path/to/config script.js`

or through **env var**
``OPENSSL_CONF=/path/to/config node script.js`

**Comment by Poyoman39** [comment]
Hi @metcoder95 sry for wrong issue report. I tried with your openssl.cnf format and it's working fine. I bet i miss-unerstood the tutorials about how to write this file :face_in_clouds:

**Comment by Poyoman39** [comment]
I guess it was working on some of my servers since openssl changed it's default security levels recently and my servers where just a bit late.

**Comment by Poyoman39** [comment]
@metcoder95 i closed this issue a bit too fast. I succeed to reproduce the bug with previous openssl version. Here is how to proceed : 

This `openssl.cnf` file
```
nodejs_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=2
```
 
 Then `node --openssl-config ./openssl.cnf` and execute
 
 ```
const { Agent, setGlobalDispatcher, fetch } = await import('undici');
setGlobalDispatcher(new Agent({ connect: { rejectUnauthorized: false, } }))

await fetch('https://www.aerocontact.com/entreprise-aeronautique/societe-latecoere-1128/offres-emploi-aeronautique?')
 ```
 
 This will throw `ERR_SSL_DH_KEY_TOO_SMALL`.
 
 
 PS : If you get `UND_ERR_CONNECT_TIMEOUT` error, just run the fetch again (this website is really slow)

**Comment by metcoder95** [comment]
Nice, thanks! I was able to reproduce it; Now, lowering the sec level to 1 did the trick for me; did you try it already?

```txt
nodejs_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=1
```

**Comment by Poyoman39** [comment]
Hi @metcoder95 yes lowering it to 1 do the trick to me too, and that's why i closed the issue a bit quickly first.

Then i remembered my issue was that `setGlobalDispatcher(new Agent({ connect: { rejectUnauthorized: false, } }))` does not make fetch ignore this error ^^

Should't `rejectUnauthorized: false` make the request work even with "bad sec level" ?

**Comment by metcoder95** [comment]
ah, ok sorry, now I got you 👍 
And no, it doesn't work like that; the `rejectUnauthorized` is meant for CAs, as it will mandate whether or not reject requests whose certificate has a valid CA (avoiding self-signed or similar)

**Comment by Poyoman39** [comment]
Good to know 😁.
Do you think it would be possible to have a boolean controling if its possible to disable this security check on one request ? Or does it need to be done at node.js level ?

**Comment by metcoder95** [comment]
You can do it by passing the `cipher` property to the `Agent` under the `connect` scope, e.g.

```js
setGlobalDispatcher(
  new Agent({
    allowH2: true,
    connect: {
      rejectUnauthorized: false,
      ciphers: 'DEFAULT:@SECLEVEL=2',
    }
  })
)```

**Comment by Poyoman39** [comment]
I confirm this is working fine :star_struck: 
The solution working for my case:
```

**Comment by Poyoman39** [comment]
By the way do you think it worse a mention in [the official Agent documentation](https://undici.nodejs.org/#/docs/api/Agent) ? I don't find reference of such ciphers parameter ^^

**Comment by Poyoman39** [comment]
Found the documentation ^^ https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
