### ISSUE TITLE
WPT Tests, which timeout should be shown as failure

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2627]
If a test times out it will only be logged 

https://github.com/nodejs/undici/blob/b82c4905ff94bf1c0c9b1e4494f4bbe52e188be2/test/wpt/runner/runner.mjs#L232

Imho the test case should be marked as failed.

**Comment by rossilor95** [comment]
Hi! Can I work on this issue?

**Comment by Uzlopak** [comment]
I guess so. There is afaik a no cookie licking policy.

**Comment by merojosa** [comment]
@metcoder95 @KhafraDev FYI, this issue should be closed

**Comment by Uzlopak** [comment]
Thanks for the hint. ;)
