### ISSUE TITLE
isTrusted for MessageEvents?

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2631]
Could we write an initializer, which is called in nodejs passing the kTrustEvent or isTrustedSet from `lib/internal/event_target.js` to undici, so that we can instantiate MessageEvents of type trusted?

Maybe it is not secure approach and we can not ensure that it is used by malicious userland code. But that is something I would like to discuss and clarify.

**Comment by mcollina** [comment]
I don't understand the issue ;).

**Comment by KhafraDev** [comment]
Events contain an [`isTrusted` property](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) that we can't set form userland. Causes a WPT for EventSource to fail.

**Comment by KhafraDev** [comment]
I'm going to close this, I don't think it's worth the hassle the fix and there isn't a way for us to fix it.
