### ISSUE TITLE
Add Unix Domain Sockets to benchmarks

### ISSUE THREAD

**Issue by janpio** [nodejs/undici#264]
Now that [UDS is supported](https://github.com/mcollina/undici/pull/238), it would be great if it was added to the benchmarks as well:

https://github.com/mcollina/undici#benchmarks
https://github.com/mcollina/undici/blob/master/benchmarks/index.js

**Comment by ronag** [comment]
PR is welcome!

**Comment by ronag** [comment]
I think this is done.

**Comment by janpio** [comment]
No search results for "unix" or "uds" but 🤷

**Comment by ronag** [comment]
https://github.com/nodejs/undici/blob/main/benchmarks/server.js#L7

**Comment by janpio** [comment]
Ah nice. Are the results interesting enough to be added to the README?
(Tried to run on Windows, but the server can not be started because of the Socket file not being readable or something)

**Comment by ronag** [comment]
Those results are what’s already in the readme.

**Comment by janpio** [comment]
Again, very good point. I'll just be quiet now. 
(Although I was looking for a comparison between socket vs no socket)

**Comment by szmarczak** [comment]
> Tried to run on Windows

Do you mean WSL?

**Comment by janpio** [comment]
No, direct Cmd.exe. WSL would probably be fine.

**Comment by szmarczak** [comment]
AFAIK there are no UNIX sockets on Windows yet. I believe it's still on Windows Insiders, but haven't checked.
