### ISSUE TITLE
how to change the default user-agent?

### ISSUE THREAD

**Issue by fancy45daddy** [nodejs/undici#2641]
i use a lot of fetch in my nodejs program. now i want to change all the useragent to something like that in the chrome browser. adding the useragent to each fetch is pretty cumbersome. any way to change the useragent globally?

**Comment by KhafraDev** [comment]
Yes, it's possible with the dispatcher API.

```js
import { Agent, setGlobalDispatcher } from 'undici'

class AddHeaderAgent extends Agent {
  dispatch (opts, handler) {
    opts.headers['user-agent'] = 'my-user-agent'

    return super.dispatch(opts, handler)
  }
}

setGlobalDispatcher(new AddHeaderAgent())

// any code that uses undici fetch or node's global fetch will now set the user-agent header.
```

Of course this will also apply to any dependencies that use fetch.
