### ISSUE TITLE
is it possible to use undici.Agent in nodejs v21 without npm install undici

### ISSUE THREAD

**Issue by fancy45daddy** [nodejs/undici#2652]
is there something like globalThis[Symbol.for('undici.globalDispatcher.1')] to expose the undici.Agent api in node 21

**Comment by tsctx** [comment]
There are hacks like this.
```js
const getAgent = () => {
  fetch("data:,").catch(() => null);
  return Object.getPrototypeOf(globalThis[Symbol.for('undici.globalDispatcher.1')]).constructor
}

class MyAgent extends getAgent() {
 // ...
}
```

**Comment by fancy45daddy** [comment]
Not working.

globalThis[Symbol.for('undici.globalDispatcher.1' )] return undefined

**Comment by ronag** [comment]
No. Don't do this. Use the package.
