### ISSUE TITLE
The "event" argument must be an instance of Event. Received an instance of Event (WebSocket + ws)

### ISSUE THREAD

**Issue by kettanaito** [nodejs/undici#2663]
## Bug Description

When Undici calls [`fireEvent`](https://github.com/nodejs/undici/blob/b04d65cc7f50e5fc86145a9fddd9952824539397/lib/websocket/util.js#L42) with the `MessageEvent` received from the server constructed via the [`ws`](https://github.com/websockets/ws) package, the following error is thrown by `internals/event_target`:

```
The "event" argument must be an instance of Event. Received an instance of Event
```

## Reproducible By

```js
import { WebSocketServer } from 'ws'
import { WebSocket } from 'undici'

const server = new WebSocketServer({ host: '127.0.0.1', port: 0 })
server.on('connection', (client) => {
  client.send('hello')
})

const ws = new WebSocket(server.address())
ws.addEventListener('message', (event) => {
  console.log('received:', event.data)
})
```

## Expected Behavior

The `MessageEvent` dispatched via `fireEvent` does not throw an error. 

## Logs & Screenshots

<img width="1165" alt="Screenshot 2024-01-29 at 14 25 25" src="https://github.com/nodejs/undici/assets/14984911/cffa8e60-3fa5-43a4-9d64-fcc51fcf4f26">

## Environment

```
os: MacOS 14.2.1 (23C71)
node: v18.17.0
```

### Additional context

Here's the check that Node performs before throwing that error:

https://github.com/nodejs/node/blob/64c6d97463c29bade4d6081683dab2cd7cda298d/lib/internal/event_target.js#L751

I suspect that the `MessageEvent` provided by the `ws` package doesn't extend the global `Event` correctly, and thus fails the `instanceof` check. I still think it's worth opening the issue in Undici for discoverability even if the root cause will end up to be elsewhere.

**Comment by kettanaito** [comment]
Closing because it's the issue in the `ws` package (see https://github.com/websockets/ws/issues/1818#issuecomment-1914702007).

I suspect that due to the Node.js version support they promise, they ended up re-implementing `Event` and `EventTarget`, which leads to the `MessageEvent extends Event` extending _the wrong_ `Event` (their own, not the global one; see https://github.com/websockets/ws/blob/5e42cfdc5fa114659908eaad4d9ead7d5051d740/lib/event-target.js#L17).

**Comment by kettanaito** [comment]
Strangely, even if I modify `ws` to dispatch a global `Event`, its `instanceof` check still returns `false`, even if inlined in Undici's `fireEvent`. Can the two packages be getting different global `Event` object? 🤔

**Comment by lpinca** [comment]
I don't understand. In the example `ws` does not fire any event. The event is fired by `undici`. What `ws` sends to undici is just a WebSocket frame.

**Comment by kettanaito** [comment]
Here's a detailed call stack:

- `ws` implicitly constructs an open `Event` when `this.emit('open')` is called (maps back the emitter interface to the event target call signature): https://github.com/websockets/ws/blob/5e42cfdc5fa114659908eaad4d9ead7d5051d740/lib/event-target.js#L234
- The open event bubbles to `undici`, and undici provides it to `fireEvent`, then to `target.dispatchEvent`. 
- `internal/event_target.js` checks whether the dispatched event is an instance of `Event`. If not, it throws (https://github.com/nodejs/node/blob/64c6d97463c29bade4d6081683dab2cd7cda298d/lib/internal/event_target.js#L751).

**Comment by lpinca** [comment]
There is no listener for the `'open'` event in the example.

**Comment by kettanaito** [comment]
@lpinca there's a listener for the `message` event though. The same thing happens to _all_ events from `ws` since none of them extend the global `Event` in Node.

**Comment by lpinca** [comment]
But you are adding to the the undici `WebSocket` instance, not ws `WebSocket` instance.

**Comment by kettanaito** [comment]
I apologize, I extracted my issue scenario incorrectly 👍 Will update to prevent further confusion.

**Comment by ronag** [comment]
I don't see how this is related to `ws`. If there is an issue it's in undici. @KhafraDev

**Comment by lpinca** [comment]
I think they are doing something like https://github.com/websockets/ws/issues/1818 but I see nothing related to `ws` in the stack trace.

**Comment by kettanaito** [comment]
@KhafraDev, like I suspected, this isn't an issue with Undici. It simply surfaces through it. 

The issue is in the `ws` module (see https://github.com/websockets/ws/issues/1818).

**Comment by lpinca** [comment]
Can you please share a minimal test case? The one in the issue description works correctly.

**Comment by KhafraDev** [comment]
Since ws' Event is similar to the spec one, it should be possible to take the attributes from ws' Event and create a node Event from that.

**Comment by kettanaito** [comment]
## Reproduction case

1. Check out https://github.com/mswjs/interceptors/pull/501.
2. Open `test/modules/WebSocket/exchange/websocket.server.connect.test.ts`. Uncomment any/all server tests.
3. `pnpm test test/modules/WebSocket/exchange/websocket.server.connect.test.ts`

See the following errors during the test run:

```
TypeError: The "event" argument must be an instance of Event. Received an instance of Event
 ❯ new NodeError ../node:internal/errors:405:5
 ❯ WebSocket.dispatchEvent ../node:internal/event_target:678:13
 ❯ fireEvent ../node_modules/.pnpm/undici@6.5.0/node_modules/undici/lib/websocket/util.js:58:10
 ❯ WebSocket.#onConnectionEstablished ../node_modules/.pnpm/undici@6.5.0/node_modules/undici/lib/websocket/websocket.js:537:5
 ❯ ../node_modules/.pnpm/undici@6.5.0/node_modules/undici/lib/websocket/websocket.js:126:50
 ❯ Object.processResponse ../node_modules/.pnpm/undici@6.5.0/node_modules/undici/lib/websocket/connection.js:197:7
 ❯ ../node_modules/.pnpm/undici@6.5.0/node_modules/undici/lib/fetch/index.js:1083:38
 ❯ ../node:internal/process/task_queues:140:7
 ❯ AsyncResource.runInAsyncScope ../node:async_hooks:203:9
 ❯ AsyncResource.runMicrotask ../node:internal/process/task_queues:137:8
```

This reproduction case is a part of the Interceptors library. Note that the interceptor itself doesn't affect `Event`, Undici, or `ws` in any way. I can put up a more isolated repository if you wish but the instructions above will give you the errors I'm experiencing.

## More context

I learned that Undici also implements its own events but they do extend the global `Event` class, which should make individual events correct instances of the global `Event`.

However, that's not the case. Here's when Undici emits _its own_ `MessageEvent`:

https://github.com/nodejs/undici/blob/e30f200b84ff7f862f61fe5c69185aaa816c5b25/lib/websocket/util.js#L96-L102

If I check `event instanceof Event` in `fireEvent()`, I will get `false`:

https://github.com/nodejs/undici/blob/e30f200b84ff7f862f61fe5c69185aaa816c5b25/lib/websocket/util.js#L48

```js
console.log(event instanceof Event)
```

```
false
```

This instance check later on results in the Node.js error during the event validation here:

https://github.com/nodejs/node/blob/8a41d9b636be86350cd32847c3f89d327c4f6ff7/lib/internal/event_target.js#L751

I would be grateful if you point me in the right direction and explain why is that instance check failing.

**Comment by kettanaito** [comment]
## Inline reproduction case

Here's an inline reproduction as well:

```js
// test.js
const { MessageEvent } = require('undici')
console.log(MessageEvent instanceof Event)
```
```
node ./test.js
```
```
false
```

**Comment by kettanaito** [comment]
This is likely an environment problem. Standalone, Undici events pass the instanceof check:

```js
const { MessageEvent } = require('undici/lib/websocket/events.js')
console.log(new MessageEvent('message') instanceof Event)
// true
```

I will try to see if this has anything to do with the test runner I'm using.

**Comment by kettanaito** [comment]
## Root cause

This error was happening due to JSDOM. It's always JSDOM. Looks like the global `Event` integrity is violated when you use Jest+JSDOM. This has cost me almost a week of debugging. 

Thank you everyone for help here. I appreciate it a lot.

**Comment by kzhdev** [comment]
I have the same error when trying to use WebSocket in Angular.

`TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of Event
    at WebSocket.dispatchEvent (node:internal/event_target:757:13)
    at fireEvent (node:internal/deps/undici/undici:11637:14)
    at #onConnectionEstablished (node:internal/deps/undici/undici:12806:9)
    at node:internal/deps/undici/undici:12614:66
    at Object.processResponse (node:internal/deps/undici/undici:11980:11)
    at node:internal/deps/undici/undici:10709:23
    at _ZoneDelegate.invokeTask (D:\repo\coinbase\coinbase\.angular\vite-root\coinbase\node_modules\zone.js\fesm2015\zone-node.js:402:33)
    at ZoneImpl.runTask (D:\repo\coinbase\coinbase\.angular\vite-root\coinbase\node_modules\zone.js\fesm2015\zone-node.js:159:47)
    at drainMicroTaskQueue (D:\repo\coinbase\coinbase\.angular\vite-root\coinbase\node_modules\zone.js\fesm2015\zone-node.js:581:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

@kettanaito How do you resolve the issue?

**Comment by terzurumluoglu** [comment]
> I have the same error when trying to use WebSocket in Angular.
> 
> `TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of Event at WebSocket.dispatchEvent (node:internal/event_target:757:13) at fireEvent (node:internal/deps/undici/undici:11637:14) at #onConnectionEstablished (node:internal/deps/undici/undici:12806:9) at node:internal/deps/undici/undici:12614:66 at Object.processResponse (node:internal/deps/undici/undici:11980:11) at node:internal/deps/undici/undici:10709:23 at _ZoneDelegate.invokeTask (D:\repo\coinbase\coinbase\.angular\vite-root\coinbase\node_modules\zone.js\fesm2015\zone-node.js:402:33) at ZoneImpl.runTask (D:\repo\coinbase\coinbase\.angular\vite-root\coinbase\node_modules\zone.js\fesm2015\zone-node.js:159:47) at drainMicroTaskQueue (D:\repo\coinbase\coinbase\.angular\vite-root\coinbase\node_modules\zone.js\fesm2015\zone-node.js:581:35) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) { code: 'ERR_INVALID_ARG_TYPE' }`
> 
> [@kettanaito](https://github.com/kettanaito) How do you resolve the issue?

I tried more than one projects such as v18, v19, with ssr, no ssr etc. and I dont know why its getting error trying to connect when start. But its relation with angular ssr. You can try remove ssr from your project. It worked for me.
