### ISSUE TITLE
Since 6.4.0 -> 6.5.0 upgrade I keep getting "Can't resolve 'timers/promises' "

### ISSUE THREAD

**Issue by plee-fn** [nodejs/undici#2664]
## Bug Description

I upgrade undici from 6.4.0 to 6.5.0. 
Ran storybook, and I encountered the error: `Module not found: Error: Can't resolve 'timers/promises' in './node_modules/undici/lib/eventsource'`

## Expected Behavior

No error occurred when storybook is run.

## Logs & Screenshots

<img width="1026" alt="Screenshot 2024-01-29 at 12 32 48 PM" src="https://github.com/nodejs/undici/assets/93216113/b6b16142-e572-4f34-94c3-620f27335a62">

## Environment

Node v18.14.2

**Comment by KhafraDev** [comment]
We can provide a workaround, but this looks like an issue in storybook.
