### ISSUE TITLE
Security Update broke test/fetch/pull-dont-push.js?

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2697]
The unit test test/fetch/pull-dont-push.js is broken. I first thought it has something to do within my PR #2696  were I saw this first. But this issue is also on the default branch. I deleted locally my undici repo, cloned again and again the test runner hangs on this specific test. 

I guess it has something to do with the security patches.

**Comment by mcollina** [comment]
That test was added by the security release and it's passing on main. Where is it failing?

**Comment by Uzlopak** [comment]
@mcollina 
Like i said, my pr is failing because if this file. And when i clone this repo fresh and use the main branch and install everything etc.. then this test is never ending?!

**Comment by mcollina** [comment]
The tests seems to be passing on main. Or maybe they are not run at all?

On Mac the test pass on all version.

**Comment by Uzlopak** [comment]
This one PR I created is just adding an .npmrc file and the CI/CD pipeline is broken?!

Maybe one of the commits merged after the security release broke it?

I will investigate in few hours.
