### ISSUE TITLE
Issue with undici.request and Headers Global Object

### ISSUE THREAD

**Issue by JaoodxD** [nodejs/undici#2700]
## Bug Description
Undici's `request` function appears to be skipping headers that are constructed using the `Headers` global object.

## Reproducible By

1. Create an instance of `Headers` class.
2. Add header with set/append.
3. Pass headers instance to request.

```js
const headers = new Headers()
headers.append('random-header', 'hello world')

const res = await request('http://localhost:3001', { headers })
```

Full reproducable example can be found in following [repo](https://github.com/JaoodxD/undici-request-headers)

## Expected Behavior

I expect the `undici.request` function to treat instances of the `Headers` class the same way it handles plain JavaScript objects passed to options.  
Specifically, I anticipate that the headers, when constructed using the `Headers` class, should be seamlessly attached to the HTTP request.

## Logs & Screenshots

```
{
  host: 'localhost:3000',
  connection: 'keep-alive',
  'random-header': 'hello world' // passed as plain object
}
{ host: 'localhost:3001', connection: 'keep-alive' } // as Headers instance
```

## Environment
OS: Windows 10
Nodejs: v20.8.0
undici: v6.6.1

**Comment by JaoodxD** [comment]
> Headers object are not expected to work. Though I wouldn't mind adding support for it. PR welcome.

I would like to implement it.

**Comment by KhafraDev** [comment]
it might be worth it to allow Map-like objects instead (ie. something that implements .get()) instead of only Headers.

**Comment by JaoodxD** [comment]
> it might be worth it to allow Map-like objects instead (ie. something that implements .get()/an iterator) instead of only Headers.

Good idea. Would it be a sufficient option to implement it like it's done in fetch? https://github.com/nodejs/undici/blob/8e1407824ccd55ed5348eb6fd13616975f4f3a25/lib/fetch/headers.js#L573-L576
