### ISSUE TITLE
expose MessageEvent for node core

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2769]
Both node and undici implement MessageEvent. Node's implementation is far from spec compliant, whereas undici's is (we run idl WPTs on MessageEvent). Should we replace the existing MessageEvent with undici's?

On a side note: since I had no idea that node had MessageEvent, it does not work with WebSocket.

**Comment by metcoder95** [comment]
It will most likely mean a major, should we aim for v22?
I'm just not fully aware what's the process on Node.js releases for that 😅

**Comment by KhafraDev** [comment]
Unfortunately error messages do change, but all tests from node core pass.
