### ISSUE TITLE
next branch purged of semver-major changes?

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2771]
@ronag 

Did your force push removed the semver-major changes? E.g. llhttp 9.2.0 is back to v8 in next.

**Comment by ronag** [comment]
What PR did that land in?

**Comment by ronag** [comment]
I did a force push assuming nothing had landed on the next branch. I'm confused.

**Comment by Uzlopak** [comment]
With #2701 llhttp was upgraded to 9.2.0

Also the changes of this PR of yours seems to be removed from next branch #2724

We probably can fix this as we have the commits still in the sync-next branch of @metcoder95 and maybe have to cherrypick them?!

**Comment by ronag** [comment]
I will fix this.

**Comment by Uzlopak** [comment]
Awesome. Thanks
