### ISSUE TITLE
Run wpt tests concurrently

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2792]
Make them run faster

**Comment by KhafraDev** [comment]
they were, but it caused flakiness in the CI.

**Comment by Uzlopak** [comment]
Do you have a PR where we deactivated parallel run?

**Comment by KhafraDev** [comment]
no, it was a while ago. It also wasn't at once:
- all WPTs were run in separate workers (CI was flaky)
- so then I limited it to 10 workers/os.cpus(), don't remember (still was flaky)

there was no combination of parallelism I could find that made these tests pass consistently.
