### ISSUE TITLE
Provide an alternative to interceptors

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#2802]
In `next`, we have removed the interceptors. However, we have not introduced a mechanism that's as easy to achieve the same behavior.

@ronag @metcoder95 could you take a look on adding it? I think @ronag has ideas

**Comment by ronag** [comment]
WIP https://github.com/nodejs/undici/pull/2795

**Comment by ronag** [comment]
I'm still overwhelmed with non-programmer work (it's a pain running a business sometimes). I will hope to spend more thought and time on this in the next few weeks.

**Comment by metcoder95** [comment]
Slightly the same, but we can definitely iterate together, so far we are already cooking something 👍

**Comment by mcollina** [comment]
Implemented in https://github.com/nodejs/undici/pull/2826
