### ISSUE TITLE
Nuxt build error with undici 

### ISSUE THREAD

**Issue by emiltsang-flow** [nodejs/undici#2811]
## Bug Description

Failed to build with nuxt.

## Logs & Screenshots
[fatal] Nuxt build error
  ERROR in ./node_modules/undici/lib/cache/cachestorage.js 13:2
  Module parse failed: Unexpected character '#' (13:2)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  |    * @type {Map<string, import('./cache').requestResponseList}
  |    */
  >   #caches = new Map()
  |
  |   constructor () {
  @ ./node_modules/undici/index.js 128:27-62
  @ ./node_modules/@firebase/auth/dist/node/index.js
  @ ./node_modules/firebase/auth/dist/index.cjs.js
  @ ./plugins/firebase.js
  @ ./.nuxt/index.js
  @ ./.nuxt/server.js
  @ multi ./.nuxt/server.js

## Environment
Binaries:
Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
Yarn: 1.22.1 - ~/.nvm/versions/node/v18.17.1/bin/yarn
npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
npmPackages:
@nuxt/core: ^2.12.2 => 2.17.1
@nuxt/image: ^0.7.1 => 0.7.1
nuxt: 2.17.0 => 2.17.0

**Comment by kylsgl** [comment]
Not an undici issue. `#` is a prefix for private class fields added in ES2022.
