### ISSUE TITLE
non-keep alive connections are not data safe

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#2825]
They are unsafe from corruption. In particular due to the fact that we treat unexpected socket end as a valid end of message, which it not necessarily is...

```We treat all incoming data so far as a valid response.```

**Comment by metcoder95** [comment]
Do you have an example at hand for this?

**Comment by mcollina** [comment]
> In particular due to the fact that we treat unexpected socket end as a valid end of message, which it not necessarily is...

Well, it is for HTTP/1.

**Comment by ronag** [comment]
Ah, I missed the keepAlive check. Nevermind this.
