### ISSUE TITLE
WebSocket: wrong subprotocol choose check (response Sec-WebSocket-Protocol header)

### ISSUE THREAD

**Issue by farwayer** [nodejs/undici#2844]
## Bug Description

1. client sends `Sec-WebSocket-Protocol` header with protocol **list** (separated by ',')
2. server responds with **one** protocol from this list
3. WebSocket client compares request header  (protocol **list**) with response header (**one** protocol) value and fails with the error `Protocol was not set in the opening handshake`

https://github.com/nodejs/undici/blob/c49058b956bda999bc26a1c43c66f1bede2ebc18/lib/web/websocket/connection.js#L179

## Reproducible By

```js
let ws = new WebSocket('ws://server...', ['msgpack', 'json'])
ws.addEventListener('error', e => console.log(e.error))
// server choses json and responds with `Sec-WebSocket-Protocol: json`
// client failed
```

## Expected Behavior

Correct subprotocol check

## Environment

- Node.js v21.6.2
- `--experimental-websocket` flag

**Comment by KhafraDev** [comment]
I will have a fix for this soon.

**Comment by kettanaito** [comment]
@KhafraDev, is there a chance to backport this to Node.js v18? This bug breaks WebSocket connections with multiple protocols.
