### ISSUE TITLE
[Bug] When body response is empty, body.json() returns error

### ISSUE THREAD

**Issue by ValchanOficial** [nodejs/undici#2854]
## Bug Description

I call some API, it returns or not a body
I always call body.json after a request
If body is empty, it throws: Unexpected end of JSON input at JSON
**Line 306: resolve(JSON.parse(chunksDecode(body, length)))**

## Expected Behavior

If body is empty, just return empty too

**Comment by ronag** [comment]
Sorry. This works as expected.

**Comment by ValchanOficial** [comment]
Try: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
console.log(JSON.parse(''));

![307901357-f27add81-6c2c-4a1a-88f8-0bf691a0a29a](https://github.com/nodejs/undici/assets/16228014/594b338e-77c3-4e4c-8c63-f3b876dbefa6)

**Comment by ValchanOficial** [comment]
https://github.com/ValchanOficial/example

**Comment by Uzlopak** [comment]
I investigated this and this is definetly working as expected.

Chrome is also throwing an error when requesting a resource with no body and trying to call .json().
