### ISSUE TITLE
WebSocket: message handler sometimes called with null data (potentially issue in frame processing)

### ISSUE THREAD

**Issue by farwayer** [nodejs/undici#2859]
## Bug Description

I’ll say right away that the bug is floating and I don’t have a ready-made recipe for reproducing it. The bug usually appeared during debugging. Apparently, timings and the sequence of data arrival are important. The server should also send pings to get this effect.

From the screenshot you can see that the `websocketMessageReceived` function is called with `this.#info.originalOpcode=9` (PING frame type), which should not happen.

## Logs & Screenshots

![2024_02_27T05 33 03](https://github.com/nodejs/undici/assets/2343101/80279f6f-fb33-42a9-a909-a4bab15091ee)

## Environment

node v21.6.2

**Comment by KhafraDev** [comment]
does this only occur during debugging?

**Comment by farwayer** [comment]
Yes, I only encountered this error in debugging. But, I assume that the problem is not related to it, but to the timings. Before sending null to the message handler, two breakpoints are triggered. But if you send a ping from the server with a little delay (calling `process.hrtime()` before sending is enough), then everything goes fine.

**Comment by KhafraDev** [comment]
Maybe, I think there's definitely room for improvement in parsing close frames (frames that can't be fragmented). I'll look into it but no promises.

**Comment by LubosD** [comment]
FWIW, I definitely encountered this bug outside of debugging. The WebSocket would receive messages correctly for a while and then it would always give me `null`s.
