### ISSUE TITLE
avoid containing undici internals in error stacktrace in web api

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2869]
I find it highly confusing, that e.g. when I call .body() on a fetch response and it errors I get all the internal functions in the stacktrace.

This is maybe more about convenience but it makes more sense when using fetch in nodejs... there i want to have e.g. less information about the internals.

**Comment by metcoder95** [comment]
I kind of recall we have a chat about this in the past along with @KhafraDev and @Ethan-Arrowood but not sure what was the outcome

**Comment by KhafraDev** [comment]
I don't remember any previous discussion but the stack trace lying to you doesn't seem like a great idea
