### ISSUE TITLE
reduce package size by compressing wasm base64 first via brotli?

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2870]
I think we could save some bytes by compressing the base64 encoded wasm before the base64 encoding via brotli.

**Comment by ronag** [comment]
Do you have any numbers? Just run it though brotli.

**Comment by mcollina** [comment]
compression would trade startup time with disk space, and that's usually a bad trade.

**Comment by metcoder95** [comment]
What problem are we trying to solve exactly?

**Comment by Uzlopak** [comment]
If my assessment is right, than llhttp simd wasm shrinks from 55kb to 14kb.  Thus base64 encoded wasm changes from 74kb to about 18kb. If #2871 removes normal wasm, than we speak of about a sofe of about 50 kb, if the PR does not pass and we still ship both wasm files, we speak a save of 100 kb.

**Comment by ronag** [comment]
Doesn't npm compress the package anyway?

**Comment by Uzlopak** [comment]
We pack undici into node. So node gets bigger.

**Comment by Uzlopak** [comment]
idk. but even if compression doesnt mean a reduction to 0. ;)

**Comment by ronag** [comment]
I mean you get pretty much the same compression if you compress it before the bundle or compress it with the bundle...
