### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#289]
I think making TS type definitions should be possible if anyone wants to put in the effort and maintain it.

**Comment by mcollina** [comment]
I would recommend the use of http://npm.im/tsd for testing them.

**Comment by delvedor** [comment]
I can help with this, but I would wait until the API is stable enough™, otherwise, we should write them twice.

**Comment by Ethan-Arrowood** [comment]
👋 happy to help as well 😄
