### ISSUE TITLE
Fetch fails for responses with http status 407

### ISSUE THREAD

**Issue by bdemann** [nodejs/undici#2896]
## Bug Description

If a server responds with a 407, fetch will fail instead of returning a response with a 407 status.

## Reproducible By
With an express server (for example) with an endpoint like this
```javascript
app.get('/407', (req, res) => {
  res.status(407).send('This is a 407 Proxy Authentication Required response.');
});
```
Being hit with fetch like this
```javascript
async function fetch407Endpoint() {
  try {
    const response = await fetch('http://localhost:3000/407');
    if (response.status === 407) {
      const data = await response.text();
      console.log('407 endpoint response:', data);
    } else {
      console.log('407 endpoint didn\'t return with 407 status');
      console.error('Error:', response.status, response.statusText);
    }
  } catch (error) {
    console.log('407 endpoint failed');
    console.error('Error:', error);
  }
}
```

## Expected Behavior

In the above example I would expect it to print out "407 endpoint response: This is a 407 Proxy Authentication Required response." But instead it throws and it lands in the catch block. cURL and FireFox's implementation of fetch both have the expected behavior.

## Logs & Screenshots

```
Error: TypeError: fetch failed
    at node:internal/deps/undici/undici:12344:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetch407Endpoint (fourZeroSeven/fetch.js:22:22) {
  cause: Error
      at makeNetworkError (node:internal/deps/undici/undici:5585:35)
      at httpNetworkOrCacheFetch (node:internal/deps/undici/undici:10731:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async httpFetch (node:internal/deps/undici/undici:10545:37)
      at async node:internal/deps/undici/undici:10342:20
      at async mainFetch (node:internal/deps/undici/undici:10332:20)
}
```

## Environment

I have tried on the following node versions: v18.18.0, v20.11.0 and v21.6.1
Ubuntu 23.10

### Additional context

Additional information and a full server and client reproduction can be found here https://github.com/demergent-labs/fourZeroSeven

**Comment by KhafraDev** [comment]
node is working as expected. The global object isn't a window so when handling 407 status codes the spec tells us to throw a network error.
