### ISSUE TITLE
Issue importing RetryAgent in TypeScript

### ISSUE THREAD

**Issue by acommodari** [nodejs/undici#2907]
## Bug Description

When I try following the `RetryAgent` example code on the undici docs I get a TypeScript error saying that `RetryAgent` is not export

## Reproducible By

1. Install `undici` in a TypeScript project.

2. Copy the `RetryAgent` code example from the `undici` docs.

3. Import statement will throw an error.

## Expected Behavior

I should be able to import the `RetryAgent` as shown in the docs.

## Logs & Screenshots

```typescript
import { Agent, RetryAgent } from 'undici'

const agent = new RetryAgent(new Agent())

const res = await agent.request('http://example.com')
console.log(res.statuCode)
console.log(await res.body.text())
```

```
Module '"undici"' has no exported member 'RetryAgent'. Did you mean to use 'import RetryAgent from "undici"' instead?ts(2614)
```

## Environment

macOS 13.2.1
node 20.11.1

### Additional context

I was trying to add request retries to my `request` to retry on failure and discovered this issue.

**Comment by tsctx** [comment]
RetryAgent not yet shipped.

**Comment by acommodari** [comment]
Oh! Thank you I thought it was 😅 the docs didn't mention anything. 

I'll close this bug then 👍
