### ISSUE TITLE
There seems to be a syntax error in the 'lib/web/fetch/util.js' file, causing a compilation error.

### ISSUE THREAD

**Issue by woohyun1031** [nodejs/undici#2923]
## Bug Description

I upgraded to undici version 6.7.0 in a specific library I'm using, and I encountered a compilation error. 
While tracing the issue, I found that it originated from the file 'lib/web/fetch/util.js'. 
And the file is being compiled through the SWC loader in Next.js.
Of course, it could be a different error, but I'm curious if the exception handling within the `FastIterableIterator` class in the `createIterator` function in that file is correct.

``` javascript
class FastIterableIterator {
    /** @type {any} */
    #target;
...
    next() {
...
        if (typeof this !== 'object' || this === null || !(#target in this)) {
          throw new TypeError(
            `'next' called on an object that does not implement the iterator interface.`
          );
        }
...
    }
...
```
I'm curious whether the part where the exception handling is performed on line 776 should be changed from `!(#target in this)` to `!(this.#target in this)`.

## Logs & Screenshots
![스크린샷 2024-03-05 오후 1 04 41](https://github.com/nodejs/undici/assets/94066263/c82e4653-4318-4c0d-8d50-c1a914ac2eee)

## Environment

Mac M1 Pro
Next.js 14.0.1
Node v20.10.0

**Comment by tsctx** [comment]
I think it is a swc issue.

**Comment by KhafraDev** [comment]
`#prop in this` is valid syntax. This is not an issue in undici.

**Comment by fersan96** [comment]
@woohyun1031  Hello, I hope you are doing well, I would like to know if you solved this problem?

**Comment by woohyun1031** [comment]
@fersan96 Hello, Unfortunately, I couldn't resolve the issue. I had to downgrade the version of undici. 
but it seems like Next.js parser issue. Check this #2954. It might be helpful to you

**Comment by jamespdaubert** [comment]
I added 'cheerio' here in next config, and it resolved issue:

```
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['cheerio'],
  },
```
