### ISSUE TITLE
undici npm package has no readme 

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2930]
Visit https://www.npmjs.com/package/undici?activeTab=readme

@Ethan-Arrowood 
Symlinking does not work for npm.

**Comment by Ethan-Arrowood** [comment]
Ah silly npm. Looks like this issue is long standing (latest I can find is here: https://github.com/npm/cli/issues/6746) 

Recommended fix is to include a `prepublish` or `prepack` script that copies the readme

**Comment by Uzlopak** [comment]
or maybe when building docs copy readme md into docs folder?
