### ISSUE TITLE
tests failing in node 21

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2931]
https://github.com/nodejs/undici/actions/runs/8179418041/job/22365444520
https://github.com/nodejs/undici/actions/runs/8179418041/job/22365444256

**Comment by Uzlopak** [comment]
`after` is for some reason broken in node v. 21.7.0 

We could rewrite it to not use after.... but i doubt that this is the way to got

**Comment by metcoder95** [comment]
Waiting for: https://github.com/nodejs/node/pull/51998

**Comment by Uzlopak** [comment]
v21.7.1 got released.
