### ISSUE TITLE
Wasm SIMD unsupported

### ISSUE THREAD

**Issue by Simkav** [nodejs/undici#2934]
## Bug Description

When using last version 6.7.0 on request\fetch getting error

 node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368]

## Reproducible By

npm i undici
call request or fetch function

## Expected Behavior

Expect to get response)

## Logs & Screenshots
![undici](https://github.com/nodejs/undici/assets/46397494/3762b317-bf5a-412a-bf31-0fe26a13b57d)

## Environment

Ubuntu 22.04.1 LTS
Node 20.11.1 || 18.7.0
undici 6.7.0 

## Additional context

If using previos version 6.6.2 everything work

**Comment by Uzlopak** [comment]
What CPU do you have?

**Comment by Simkav** [comment]
> What CPU do you have?

AMD Athlon(tm) II X3 455 Processor

**Comment by Uzlopak** [comment]
@mcollina 

We dropped in #2871 the non-simd version of wasm. Now @Simkav is reporting an issue, because his 14 year old processor does not work with wasm simd. 

Should we revert #2871?
Should we say it is a breaking change and apply the idea of #2871 to next and with undici v7 we have to tell devs like Simkav, that they basically should get new hardware?

**Comment by mcollina** [comment]
I think we would need to revert #2871, and possibly ship in v7.

@nodejs/build is there a minimum requirement for the CPU of Node.js? Can we expect simd to be there?

**Comment by targos** [comment]
I guess it's the same issue as https://github.com/nodejs/citgm/issues/1050 ?

**Comment by targos** [comment]
power8 platform is under Tier 2 support: https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list

**Comment by richardlau** [comment]
> I think we would need to revert #2871, and possibly ship in v7.
> 
> @nodejs/build is there a minimum requirement for the CPU of Node.js? Can we expect simd to be there?

Generally there's been no minimum requirement -- in the past it's probably been more dictated by V8. I think Power is the only architecture we currently specify the version for. There's obviously a balancing act around the hardware we have access to in Build and what is obtainable.

**Comment by mhdawson** [comment]
To add to the discussion, another factor is which versions customer still use and are supported by distros, Power 8 is still in enough use that shipping distros support it and we want Node.js to support it.

**Comment by mcollina** [comment]
we had that option and we removed it thinking most CPU in use had SIMD, given than V8 had WASM support for SIMD. We were mistaken.
