### ISSUE TITLE
EventSource properties are not configured properly

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2948]
```js
'use strict'

const { test } = require('node:test')
const assert = require('node:assert')
const { EventSource } = require('../..') // assuming the test is in test/eventsource/

test('EventSource.prototype properties are configured correctly', () => {
    const props = Object.entries(Object.getOwnPropertyDescriptors(EventSource.prototype))

    for (const [key, value] of props) {
        if (key !== 'constructor') {
            assert(value.enumerable, `${key} is not enumerable`)
        }
    }
})
```

**Comment by Uzlopak** [comment]
We dont have a bot. We also have a no cookie licking policy. If you want to provide a PR, then just provide it.

**Comment by Ayush9026** [comment]
Thanks @Uzlopak for telling i will raise PR.

**Comment by mertcanaltin** [comment]
If you need any help at all, please don't hesitate @Ayush9026 :rocket:

**Comment by MattBidewell** [comment]
Out of curiosity and probably a silly question! - why do we want the fields to be enumerable?

Just raised a PR here - https://github.com/nodejs/undici/pull/2987 

Let me know if I've missed anything off, I've assumed no documentation changes are needed.

**Comment by KhafraDev** [comment]
> Out of curiosity and probably a silly question! - why do we want the fields to be enumerable?

It's part of the webidl spec that's a little too complex for me to give an easy answer for.
