### ISSUE TITLE
interceptors does not have any exported type

### ISSUE THREAD

**Issue by acommodari** [nodejs/undici#2972]
## Bug Description

when you try to import `interceptors` in TS it complains

## Reproducible By

`import {interceptors} from "undici"`

within a TypeScript project

## Expected Behavior

You should be able to import `interceptors` and use `redirect`/`retry` in TS

## Logs & Screenshots

![Screenshot 2024-03-18 at 4 09 13 PM](https://github.com/nodejs/undici/assets/14224801/c286e6ed-7392-475a-a78f-d24ca4772d88)

## Environment

macOS Ventura 13.2.1
node 20.11.1
undici 6.9.0

**Comment by metcoder95** [comment]
We already have a PR for fixing that: #2967

**Comment by filipforro** [comment]
I'm still unable to import `interceptors` and I'm currently on [v6.13.0](https://github.com/nodejs/undici/releases/tag/v6.13.0)

`npm list`
![image](https://github.com/withthegrid/teleport/assets/37069624/5e5e45e2-f892-4c27-9c2d-f7f0e0525df2)

`package.json`
![image](https://github.com/withthegrid/teleport/assets/37069624/ea78f8ad-1cb9-4442-b55b-1e56e2eef262)

![image](https://github.com/nodejs/undici/assets/37069624/06511a67-0b1e-4ef9-9067-31db568f4ffd)

**Comment by Uzlopak** [comment]
Use Dispatcher and not Interceptors.

**Comment by everhardt** [comment]
@Uzlopak Is [the example in the docs about the retry interceptor](https://undici.nodejs.org/#/docs/api/Dispatcher?id=retry) outdated?

**Comment by Uzlopak** [comment]
Hmm. You are right.

https://github.com/nodejs/undici/blob/f90c16155d8c87c0d8cc1bdf46b553e8aef144a5/index.js#L39

I dont find the corresponding types.

**Comment by metcoder95** [comment]
This will be close with #3118
