### ISSUE TITLE
[TS] Signature method of Interceptor using Dispatcher#compose

### ISSUE THREAD

**Issue by clovis-guillemot** [nodejs/undici#2982]
##  Bug Description

Cannot define a custom Interceptor for Dispatcher#compose using TS

## Reproducible By

N/A

## Expected Behavior

No change when migrate from interceptors to compose : 
From 
```Typescript
const client = new Client(url, {
        interceptors: {
            Client: [hawkInterceptor],
        },
})
```

To : 
```Typescript
const client = new Client(url).compose(hawkInterceptor)
```

## Logs & Screenshots

```Typescript
const client = new Client(url).compose(hawkInterceptor)
```

```Typescript
import * as Hawk from 'hawk'
import {type Dispatcher} from 'undici'

import {getConfig} from '#/utils'
import {getCurrentUniverseUrl} from '#/utils/urls'

export const hawkInterceptor = (dispatch: Dispatcher['dispatch']) => {
    return function HawhAuthorizationHeader(
        opts: Dispatcher.DispatchOptions,
        handler: Dispatcher.DispatchHandlers
    ) {
        const authConfig = getConfig('auth')
        const {header: authorization} = Hawk.client.header(
            `${getCurrentUniverseUrl()}${opts.path}`,
            opts.method,
            {
                credentials: {
                    algorithm: 'sha256',
                    ...authConfig.hawk,
                },
            }
        )
        if (!opts.headers) opts.headers = {}
        if (authorization) {
            opts.headers = {...opts.headers, authorization}
        }
        return dispatch(opts, handler)
    }
}
```
<img width="764" alt="Capture d’écran 2024-03-22 à 10 08 34" src="https://github.com/nodejs/undici/assets/11499838/4a49a950-11d4-43b2-b9d4-1c7190759d23">

## Environment

Node 20 
Undici : ^6.10.0 (6.10.1)

**Comment by metcoder95** [comment]
I see the problem, the types define that it expects a dispatch as argument, not a curried function that returns a dispatch. 

Would you like to send a PR?

https://github.com/nodejs/undici/blob/fcbf6def1fa511dbe2f06863c3e6210889640dcc/types/dispatcher.d.ts#L23

**Comment by clovis-guillemot** [comment]
> I see the problem, the types define that it expects a dispatch as argument, not a curried function that returns a dispatch.
> 
> Would you like to send a PR?
> 
> https://github.com/nodejs/undici/blob/fcbf6def1fa511dbe2f06863c3e6210889640dcc/types/dispatcher.d.ts#L23

Yes I can send a PR for that.

**Comment by clovis-guillemot** [comment]
can you approve workflows on my PR @metcoder95 , please ?

**Comment by clovis-guillemot** [comment]
[Codecov](https://github.com/nodejs/undici/pull/2983#issuecomment-2014842497) report seems OK ✅
