### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by Probabilities** [nodejs/undici#2989]
## Bug Description

I get an error when using a proxy. I cannot catch the error so it crashes my app.

My code:
```js
    try{
        const req = await request('https://discord.com/api/v9/invites/discord', {
            query: {
                inputValue: 'discord',
                with_counts: true,
                with_expiration: true
            },
            dispatcher: agent
        })

        const data = await req.body.json()

        return data
    }catch{
        console.log('An error occurred.')
        return false
    }
```

## Reproducible By

I sent lots of requests with my proxy and on the odd chance it will throw this error

## Expected Behavior

Error should be caught.

## Environment

OS: Windows 11
Node Version: 18.13.0

### Additional context

I can restart my app and the whole process will happen again. I just want to catch the error lol so I can handle it.

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that isolates the issue you are describing?

**Comment by ronag** [comment]
What is the error? msg? stack?

**Comment by metcoder95** [comment]
Sorry but that's not enough to reproduce your use case, you mentioned proxy so maybe there might be the root cause as the request works accordingly.

Any stack, error, message?
