### ISSUE TITLE
Link to Contributing guide from the README

### ISSUE THREAD

**Issue by FatumaA** [nodejs/undici#3000]
## This would solve...
This makes it simpler for interested contributors to start interacting with the project.

## The implementation should look like...

The README should link to the CONTRIBUTING.md file either as a line closer to the top or as a section like "How to contribute/get started/get involved".

## Additional context
Here is a screenshot from Supabase github README: 

![Screenshot 2024-03-27 at 11 47 23](https://github.com/nodejs/undici/assets/67555014/4954a29f-b8c2-4cd5-9cba-131f502226ec)

I would like to raise the PR for this issue.

**Comment by metcoder95** [comment]
We actually miss that within the `README`, so sgtm 👍

**Comment by FatumaA** [comment]
> We actually miss that within the `README`, so sgtm 👍

Great. I'll go ahead and make the PR then :)
