### ISSUE TITLE
Undici cannot be required in --without-intl Node.js

### ISSUE THREAD

**Issue by panva** [nodejs/undici#3002]
## Bug Description

Undici cannot be required in --without-intl Node.js

## Reproducible By

```
# in nodejs/node
./configure --node-builtin-modules-path $(pwd) --without-intl --ninja
make

# in a project with undici
cat package.json | jq '.dependencies.undici'
"^6.10.1"
../node/node -e "require('undici')"

node:internal/encoding:487
          throw new ERR_NO_ICU('"fatal" option');
          ^

TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
    at new TextDecoder (node:internal/encoding:487:17)
    at Object.<anonymous> (/repo/node_modules/undici/lib/web/websocket/util.js:71:21)
    at Module._compile (node:internal/modules/cjs/loader:1421:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1499:10)
    at Module.load (node:internal/modules/cjs/loader:1232:32)
    at Module._load (node:internal/modules/cjs/loader:1048:12)
    at Module.require (node:internal/modules/cjs/loader:1257:19)
    at require (node:internal/modules/helpers:188:18)
    at Object.<anonymous> (/repo/node_modules/undici/lib/web/websocket/websocket.js:24:5)
    at Module._compile (node:internal/modules/cjs/loader:1421:14) {
  code: 'ERR_NO_ICU'
}
```

## Expected Behavior

Undici CI also tests on Node.js without ICU so that releases that cannot be merged to Node.js don't happen

## See

- https://github.com/nodejs/node/pull/52175#issuecomment-2020665559
- https://github.com/nodejs/undici/pull/2863#issuecomment-2020746531

**Comment by KhafraDev** [comment]
this is a recurring issue, we should run tests on builds without icu

cc @mweberxyz @Uzlopak

**Comment by mweberxyz** [comment]
👀 

@KhafraDev Do you happen to know of any other repos within nodejs/ building binaries `--without-intl`? I can work on a workflow that builds (and caches) a non-icu build just for undici's use, but better to not have to reinvent the wheel if it is already being done.

**Comment by KhafraDev** [comment]
I don't sorry, I thought it'd be similar to the nightly workflow 😅

**Comment by mweberxyz** [comment]
I also asked around in the #nodejs-build channel in OpenJS foundation. My intuition is no, I am going to have to build Node in this repo's actions.

I think we can do it in the PR workflow (as opposed to the nightly) to make sure we catch regressions before they even merge to main.

**Comment by mweberxyz** [comment]
Can this issue be closed?

https://github.com/nodejs/undici/pull/2999 fixes the particular regression and https://github.com/nodejs/undici/pull/3015 attempts to prevent future regressions.

The only remaining open questions surround the tests excluded from CI and broken websocket functionality when Node is built `--without-intl`.
