### ISSUE TITLE
Wrong information in docs README file

### ISSUE THREAD

**Issue by FatumaA** [nodejs/undici#3004]
## Bug Description

The README file in the docs folder appears to be a replica of the README in the root of the project. It does not offer any information on how to run the docs locally.

## Reproducible By

1. Go into the docs folder from within the Undici project structure
2. Open the README file in the docs folder
3. Notice it does not give any specific docs related information and it is a replica of the README at the root of the project

## Expected Behavior

1. The README in the docs folder should hold information on how to run the docs locally

## Logs & Screenshots

![Group 11](https://github.com/nodejs/undici/assets/67555014/185908d2-b2e9-40c6-96d2-e6ef92624670)

### Additional context

It appears that the codebase is a Monorepo with the benchmarks and docs being their own separate projects within the main one. I think the contributing guide should be updated to reflect this and it should also show clearly the general architecture of the project so contributors can know where to go to run specific parts. 

Perhaps the benchmarks folder should have it's own README?

I would like to raise the PR for this issue. And I'd be happy to create the other issues if it makes sense.

**Comment by mcollina** [comment]
The README in the docs folder is what get's published in our website, so we can't change that.

Maybe we should include how to visualize the docs in the CONTRIBUTING.md file.

**Comment by FatumaA** [comment]
> The README in the docs folder is what get's published in our website, so we can't change that.
> 
> Maybe we should include how to visualize the docs in the CONTRIBUTING.md file.

Yeah we can put the necesssry info (how the codebase is structured, how to run the different sections of the app) in the main contributing guide.

Or we can add contributing guides to the say benchmarks and docs and have the main contributing guide link to them.

What are your thoughts?

**Comment by mcollina** [comment]
Sure thing, that works.

**Comment by FatumaA** [comment]
On it then, thanks
