### ISSUE TITLE
OpenSSF scorecard "Token-permissions" score zero

### ISSUE THREAD

**Issue by fraxken** [nodejs/undici#3012]
Hello there :wave:,

Today in the Node.js security meeting we discussed that the undici project score had dropped due to a change in the workflows. This seems to be related to the following [commit](https://github.com/nodejs/undici/commit/3be7ec9bcc4679a827199a2aea3f0f1bfbdaf325).

![image](https://github.com/nodejs/undici/assets/4438263/ec1d6e60-4240-44f9-bfc2-8bd993b10aad)

[Full report here](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/undici/compare/dae31826560112ccf1244172e398fc7d2fce075d/7485cd9b4cf9a86cb76b1597df527eba15755bfc)

1. [nightly.yml](https://github.com/nodejs/undici/blob/main/.github/workflows/nightly.yml) and [test.yml](https://github.com/nodejs/undici/blob/main/.github/workflows/test.yml) seems to lack global permissions

```yml
permissions:
  contents: read
```

2. In **nodejs.yml** we have warnings to reviews the following permission.

https://github.com/nodejs/undici/blob/d3d24e2722046733f4f78a273423f10d0107e74f/.github/workflows/nodejs.yml#L102-L105

[Github Action Merge Dependabot](https://github.com/fastify/github-action-merge-dependabot?tab=readme-ov-file#usage) require `pull-requests` and `contents` (not sure if `actions` is required). These warnings are **perhaps to be ignored**.

@nodejs/security-wg

**Comment by metcoder95** [comment]
#3013 closes this issue?

**Comment by fraxken** [comment]
> #3013 closes this issue?

Not yet. I'm working on nodejs workflow. If everything ok I will close myself (else I will open another PR).

**Comment by mweberxyz** [comment]
My bad on that change. The GHA documentation is a bit bare on permissions, by not setting the global permissions does it essentially issue a full read-write token to the workflow?

Also just to confirm: Are job-level permissions additive to workflow-level?

For example, in nightly at the workflow level we now have:
```
permissions:
  contents: read
```
then the report-failure job within that workflow:
```
  report-failure:
    permissions:
      issues: write
``` 
So there's no need to explicitly set `contents: read` in the report-failure?

**Comment by fraxken** [comment]
> My bad on that change. The GHA documentation is a bit bare on permissions, by not setting the global permissions does it essentially issue a full read-write token to the workflow?

I think it depend on the Github permission setting (but by default yes it has read-write almost everywhere).

> Also just to confirm: Are job-level permissions additive to workflow-level?

Yes. The basic idea is to set read at the root and then assign the right permission by jobs.

You can read more [here](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) about how OpenSSF scorecard build the score (there is also some tips and links).
