### ISSUE TITLE
`Request` and `Response` types don't match messages sent to `diagnostics_channel`

### ISSUE THREAD

**Issue by dreamorosi** [nodejs/undici#3014]
## Bug Description

Undici types for `Request` and `Response` seem to not be aligned with the objects sent by `undici` in the diagnostics channels.

For example, the `Request` type [here](https://github.com/nodejs/undici/blob/d3d24e2722046733f4f78a273423f10d0107e74f/types/fetch.d.ts#L155) doesn't contain the `origin` attribute which is instead present in the [actual object sent](https://github.com/nodejs/undici/blob/d3d24e2722046733f4f78a273423f10d0107e74f/lib/core/request.js#L190) to the `undici:request:create` channel.

Likewise, for the `Response` object [here](https://github.com/nodejs/undici/blob/d3d24e2722046733f4f78a273423f10d0107e74f/types/fetch.d.ts#L192) both the `status` and `headers` properties seem to be incorrect since the [actual object sent](https://github.com/nodejs/undici/blob/d3d24e2722046733f4f78a273423f10d0107e74f/lib/core/request.js#L239) to the `undici:request:headers` channel instead uses `statusText` and has a different type for `headers` (`Uint8Array[]` vs `Headers`).

## Reproducible By

```ts
import { subscribe } from "node:diagnostics_channel";
import type { Request, Response } from "undici-types";

const onRequestStart = (message: unknown) => {
  const { request } = message as { request: Request };
  const {
    method,
    // @ts-expect-error - origin is not a property of Request
    origin,
  } = request;

  console.log("origin", origin);
};

const onResponse = (message: unknown) => {
  const { response } = message as { response: Response };
  const {
    // @ts-expect-error - statusCode is not a property of Response
    statusCode,
    headers,
  } = response;

  console.log("statusCode", statusCode);
  console.log("headers", headers);

  // This will cause a runtime error because headers is not an instance of Headers but Array<Uint8Array>
  const contentType = response.headers.get("content-type");
};

subscribe("undici:request:create", onRequestStart);
subscribe("undici:request:headers", onResponse);

(async () => {
  await fetch("https://httpbin.org/get");
})();
```

Find the [repo here](https://github.com/dreamorosi/repro-fetch-types).

After installing with `npm ci`, run `npx tsx index.ts` to see the logs.

## Expected Behavior

The types in `undici-types` should align with the actual shape of the object. If instead it's a different object, new types for the different object should be provided.

## Logs & Screenshots

You can clone this minimal reproducible example and observe the issue: https://github.com/dreamorosi/repro-fetch-types

As you can see, the attributes are not present in their respective types:
<img width="508" alt="image" src="https://github.com/nodejs/undici/assets/7353869/e8c7812e-f56f-4922-b516-2976f6362b16">

<img width="587" alt="image" src="https://github.com/nodejs/undici/assets/7353869/587d6e2e-89b4-4c30-b6fe-043cd8193af6">

But at runtime, printing the actual values, they are indeed present:
<img width="790" alt="image" src="https://github.com/nodejs/undici/assets/7353869/0821d151-a9e8-420d-83d4-d6fa81f619a7">

Likewise, the `headers` field is not an instance of `Headers` but an array of `Uint8Array` values (see error being thrown).

## Environment

Node.js v20.9.0

### Additional context

N/A

I am more than open to contribute a fix provided that the issue is verified and any of the maintainer can give me some guidance on which direction to take (i.e. modify the types or create a specific type for the objects sent via `diagnostics_channel`).

**Comment by metcoder95** [comment]
A PR is more than welcomed 👍

**Comment by dreamorosi** [comment]
Hi @metcoder95, should I modify the existing `Request` and `Response` types or create new ones specifically for the `message`s sent to the diagnostic channel?

I don't know if modifying the existing ones will break elsewhere.

**Comment by metcoder95** [comment]
To keep it within minor let’s create a new one and adjust the original ones in a next major

**Comment by dreamorosi** [comment]
> Request/Response types shouldn't be touched

Agreed, I'll open a PR with dedicated types for the objects sent to the diagnostics channel.

**Comment by dreamorosi** [comment]
After starting to work on the PR I found that the types are present, just under a different namespace (`DiagnosticsChannel`) [here](https://github.com/nodejs/undici/blob/2d5cbdfcf091922ed9b2ce35d7a769cd3f76014d/types/diagnostics-channel.d.ts#L6).

Closing.
