### ISSUE TITLE
nodejs/undici H1 scope ?

### ISSUE THREAD

**Issue by Sim4n6** [nodejs/undici#3018]
Quick question, does nodejs/undici repository covered by the scope of https://hackerone.com/nodejs?type=team
Thank you in advance for the information

**Comment by KhafraDev** [comment]
Yes, if you have found a security issue you can follow the instructions in https://github.com/nodejs/node/blob/HEAD/SECURITY.md to report it.

**Comment by Sim4n6** [comment]
You mean eligible for a bounty?

**Comment by Sim4n6** [comment]
It always depends ... if it was explicitly within the eligible scope, it would be mentioned in https://hackerone.com/nodejs/policy_scopes 

Thank you
