### ISSUE TITLE
`ProxyAgent` will cause customized `host` to reset

### ISSUE THREAD

**Issue by 1zilc** [nodejs/undici#3019]
## Bug Description
`ProxyAgent` causes `headers.host` to be forcibly reset in undici.request

## Reproducible By
```typescript
undici.request('http://127.0.0.1:8000', {
  headers: {
    host: 'test.com',
  },
  dispatcher: new ProxyAgent({
    uri: 'http://127.0.0.1:1087',
  }),
});
```

## Expected Behavior
`request.headers.host` should be `test.com` instead of `127.0.0.1:8000`

## Logs & Screenshots
<img width="425" alt="image" src="https://github.com/nodejs/undici/assets/44715458/23f471b1-ecad-4760-9c93-54627987f251">

## Environment
macOS 14.4.0
node v20.11.0
undici 6.10.2

### Additional context
without proxy
```typescript
undici.request('http://127.0.0.1:8000', {
  headers: {
    host: 'test.com',
  },
});
```
<img width="367" alt="image" src="https://github.com/nodejs/undici/assets/44715458/492dde97-1445-4d10-b9be-c2db2d8e97c8">

**Comment by metcoder95** [comment]
Thanks for the report, would you like to submit a PR for it?

**Comment by 1zilc** [comment]
I'd love to try and fix it.
