### ISSUE TITLE
Benchmark accuracy

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#302]
I'm getting a lot of variance even when running on a dedicated servers... is there any way to improve accuracy? More runs? I can't see any option that would allow that...

**Comment by ronag** [comment]
@szmarczak

**Comment by mcollina** [comment]
We need to use a similar approach to what we are using in Node.js core to compute improvements. Look at https://github.com/mcollina/autocannon-compare for an idea on what we could do.

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/89669648-1d0ebb00-d8e0-11ea-8c83-881d1791a144.png)

Try setting `minSamples` to `200` and see if that fixes it.

**Comment by ronag** [comment]
Implemented @szmarczak [suggestion](https://github.com/mcollina/undici/issues/302#issuecomment-670614218).

Help wanted with:

> We need to use a similar approach to what we are using in Node.js core to compute improvements. Look at https://github.com/mcollina/autocannon-compare for an idea on what we could do.
