### ISSUE TITLE
http2 onHeaders calls with header object instead of array

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#3023]
onHeaders should receive a raw headers array, in h2 it doesn't...

**Comment by ronag** [comment]
@metcoder95

**Comment by metcoder95** [comment]
SGTM 👍

**Comment by metcoder95** [comment]
`next` needs some rebase to cope with the project structure refactor

**Comment by ronag** [comment]
Yea I don't know how to handle the next branch. Will discuss with @mcollina next week.

**Comment by ronag** [comment]
@metcoder95 I would consider this a bug fix and not semver major, h1 will send an array and h2 will send an object atm.

**Comment by metcoder95** [comment]
Well, true; but if there are implementations already depending on h2 headers as `object`, we might break them, although we mark them as experimental so maybe not that bad.

I'll open a PR to main we take it from there 👍

**Comment by mcollina** [comment]
h2 is experimental.
