### ISSUE TITLE
main branch history overwritten

### ISSUE THREAD

**Issue by mweberxyz** [nodejs/undici#3033]
Looks like all merged PRs after #3001 was merged and prior to #3025 are gone.

**Comment by KhafraDev** [comment]
@mcollina @ronag

**Comment by ronag** [comment]
I'm confused as to what has happened

**Comment by ronag** [comment]
https://github.com/nodejs/undici/commit/845c713535bd1e8cfe1687332dcc8d8c2c580804
https://github.com/nodejs/undici/commit/fa5bcb4597cf662af28e6f9a30f6afbdc5c5381a
https://github.com/nodejs/undici/commit/d3d24e2722046733f4f78a273423f10d0107e74f
https://github.com/nodejs/undici/commit/9278de9cd9d5f31001f0b3600d663a3e691dbf29
https://github.com/nodejs/undici/commit/74bd88e4105ee3d69ab24d5268d4e275f92732b0
https://github.com/nodejs/undici/commit/ad4a5e58a681189e004cbfb492b9fe4e5faaf086
https://github.com/nodejs/undici/commit/9b744a39c251be529c08903d591f281c55278cb7

**Comment by mcollina** [comment]
I've limited force pushing

**Comment by mcollina** [comment]
Done
