### ISSUE TITLE
automate releases

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#3042]
as titled, we should automate our releases so we can avoid incidents like #3040

**Comment by bizob2828** [comment]
does this mean 6.11.0 is in a broken state? The New Relic Node.js agent tests are failing with 6.11.0

**Comment by mcollina** [comment]
@bizob2828 if we broke something, we can always revert. Please open an issue about the breakage.

**Comment by mcollina** [comment]
Unfortunately this is not compatible with protected branches. I've reverted the script.

Basically we need a _more complex_ workflow, which I don't have time to develop atm.

Ideas would be welcomed at this point... I'm not entirely sure how to work around this.
A possible flow could be:

1. action creates a PR
2. human approves and merge the PR
3. action releases to GH and NPM

**Comment by mweberxyz** [comment]
I can take a look.

**Comment by mcollina** [comment]
thx
