### ISSUE TITLE
addHeader removed in Undici request

### ISSUE THREAD

**Issue by bizob2828** [nodejs/undici#3043]
## Bug Description

Looks like addHeader was removed in https://github.com/nodejs/undici/pull/3024/files. The New Relic Node.js agent relies on this to propagate headers in our instrumentation.

## Reproducible By

```js
const requestHooks = diagnosticsChannel.channel('undici:request:create')
requestHook.subscribe(function requestCreate({ request }) {
  request.addHeader('test-header', 'value')
})
```

## Expected Behavior

Adds `test-header` with value of `value`

## Logs & Screenshots

```sh
TypeError: request.addHeader is not a function
    at addDTHeaders (undici.js:104:13)
    at requestCreateHook (undici.js:162:5)
    at Channel.publish (node:diagnostics_channel:142:9)
    at new Request (request.js:192:23)
    at Client.[dispatch] (client.js:304:21)
    at Intercept (redirect-interceptor.js:11:16)
    at Client.[Intercepted Dispatch] (dispatcher-base.js:158:12)
    at Client.dispatch (dispatcher-base.js:179:40)
    at Pool.[dispatch] (pool-base.js:143:28)
```

## Environment

Any, undici 6.11.0

**Comment by ronag** [comment]
That method is unsafe and pretty much undefined in terms of behavior. A request object should not be mutated once queued. 

What are you trying to achieve? Maybe we can find a better way to deal with it.

**Comment by bizob2828** [comment]
Our agent needs to propagate some headers before making an outbound request.  This was a documented use case and removed in a minor release

**Comment by ronag** [comment]
> This was a documented use case and removed in a minor release

Diagnostics channels are experimental. Hence any breaking change to them is not qualitifed as semver major. I'm not opposed to deferring it as such but it was in this case decided that it's not necessary.

**Comment by ronag** [comment]
> Our agent needs to propagate some headers before making an outbound request. 

And you can't achieve that with a dispatcher? Can you provide me with a full example?

**Comment by bizob2828** [comment]
This propagation use case is a [W3C standard](https://www.w3.org/TR/trace-context/). These were the [docs](https://github.com/nodejs/undici/pull/3024/files#diff-50ca564f113850a3161bf3fff1e979a1700b7ed0279ef4bacee11b67c9b0ee6d) I'm referring to as how to achieve this.

**Comment by bizob2828** [comment]
> And you can't achieve that with a dispatcher?

**Comment by bizob2828** [comment]
Looking at dispatchers, it's not the appropriate use case as we're an agent. The diagnostics channel seems more apropos for this use case

**Comment by bizob2828** [comment]
I can fix our instrumentation to just do `request.headers.push(<key>, <value>)`

**Comment by ronag** [comment]
We are having a meetup in London this week and I'll bring your use case up for discussion.

**Comment by bizob2828** [comment]
@ronag why don't you suggest pushing headers, it works just fine and looking at the request code, that's what is happening? we also cannot wait for a meeting next week. We have 100s of customers relying on this instrumentation.

**Comment by bizob2828** [comment]
> Diagnostic channels should not mutate the request state.

if that's the thinking, then it needs to be revisited. That's a major use case for observability vendors

**Comment by mcollina** [comment]
Let's revert this. I guess we should not have been done that to begin with and modifying headers is a valid use case.

**Comment by mcollina** [comment]
@ronag the use case of APMs is to be able to do these kind of manipulations.

**Comment by bizob2828** [comment]
Thanks @mcollina 🙏
