### ISSUE TITLE
QUIC support

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#305]
We have experimental QUIC support in node. Would be interesting to try HTTP 1.1 over QUIC.

**Comment by ronag** [comment]
@jasnell: Will quic sockets support the consume/unconsume API that net/tls sockets support?

**Comment by ronag** [comment]
What is the protocol name of quic in an url? e.g. `quic://localhost:3000`?

**Comment by jasnell** [comment]
Not sure which consume/unconsume API you mean

**Comment by ronag** [comment]
The node core HTTPParser has a [`consume` method](https://github.com/nodejs/node/blob/master/src/node_http_parser.cc#L589) that can take a socket handle. See, https://github.com/mcollina/undici/blob/master/lib/client.js#L719-L725.

**Comment by jasnell** [comment]
Ah... Yeah totally different model. It will fully consume a UDPWrap but the model is completely different in terms of how it does so

**Comment by ronag** [comment]
Then I guess the native-js-native roundtrip is the only way.

**Comment by jasnell** [comment]
No, in quic, all of the actual data flow is at the native layer. Data only comes to js via a QuicStream.

**Comment by ronag** [comment]
Yes, I mean we will have to go from quic native layer -> js -> native http parser

**Comment by jasnell** [comment]
Ah for http1... Well, not necessarily. We could actually implement an Http1Application in core that could engage the native parser at that level, before data flows into js

**Comment by jasnell** [comment]
As the implementation evolves, I plan to make it possible for native add-ons to create and register their own QuicApplication impls
