### ISSUE TITLE
library for assertions that are removed in production mode?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#306]
Does anyone have any experience with invariant/assertion libraries where the checks are either remove during transpilation or optimized out during runtime?

I think having more assertion would be a good complement to test and also documenting code. However, adding too many can currently have a negative perf impact.

Something like https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.contract?view=netcore-3.1 is even able to generate tests based on contract annotations.

**Comment by mcollina** [comment]
Unfortunately not :/. I would love this for node core as well.

**Comment by shobhitchittora** [comment]
@ronag you might want to take a look at [babel-macros](https://github.com/kentcdodds/babel-plugin-macros), where you can maybe define these assertions and remove them on for your final deployment ( runtime ).
Also as @mcollina said, it'd be and awesome value-add to the core itself.
