### ISSUE TITLE
Change "Body is unusable" error to something more helpful

### ISSUE THREAD

**Issue by nzakas** [nodejs/undici#3097]
## This would solve...

Unidici throws an error with the message "Body is unusable" when the body of a response is non-null and the stream is either locked or disturbed. In most cases, this situation occurs because someone has attempted to ready the body twice, such as:

```js
const response = await fetch(url);
console.log(await response.text());
const body = await response.json();  // throws "Body is unusable"
```

The message "Body is unusable" is opaque and requires searching to understand what it means and what the problem is. A more descriptive message would save developers a lot of time.

## The implementation should look like...

Changing the string on this line: https://github.com/nodejs/undici/blob/fe44b9b36718ff2c171568fc4a239ecb8eba038d/lib/web/fetch/body.js#L411

Suggestion: "Body is unusable: Body is either null or the stream has already been read."

The spec only specifies that a `TypeError` must be thrown, but it does not specify the text contained within that error, so it seems like changing the message would still be in-line with the spec.

## I have also considered...

Not filing this issue. :smile:

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mertcanaltin** [comment]
```throw new TypeError('Body is unusable: Body is either null or the stream has already been read.')```
Is this a good look or would it be better to added it in errors.js and get it?

**Comment by nzakas** [comment]
@mcollina happy to! :tada:

**Comment by nzakas** [comment]
@KhafraDev ah gotcha, I see that [`bodyUsable()` returns `false` if body is `null`](https://github.com/nodejs/undici/blob/fe44b9b36718ff2c171568fc4a239ecb8eba038d/lib/web/fetch/body.js#L448-L453). 👍 So maybe just "Body is unusable: The stream has already been read."?

**Comment by KhafraDev** [comment]
That message isn't much better, it assumes that you have some knowledge of fetch internals (that the body mixin methods are helper methods for consuming .body, which is a ReadableStream).

This example doesn't use any streams outwardly:
```js
const response = await fetch('https://www.google.com')
res.text()
res.text() // TypeError: Body is unusable
```

I don't think "read" is the correct verbiage here either as it might imply that the entire body has been read, which also may not be true. Also, "read" is something you can do to a ReadableStream so it may confuse people who do not directly access .body.

```js
const response = await fetch('https://www.goolge.com')
const reader = response.body.getReader()

await reader.read() // a single chunk

reader.releaseLock()

await response.text() // TypeError: Body is unusable
```

Instead, it should be something along the lines of "Body has already been consumed". Still, I don't necessarily think that the message is entirely clear and I suspect people will still have to look up what it actually means. Suggestions are welcome.

**Comment by nzakas** [comment]
Honestly, anything in addition to "Body is unusable" would have saved me a ton of time. I've opened a PR. Happy to workshop the wording over there.
