### ISSUE TITLE
`Response.body` is type of `PassThrough` instead of `ReadableStream`

### ISSUE THREAD

**Issue by flakey5** [nodejs/undici#3114]
## Bug Description

Under some specific circumstances, the `body` property in a `Response` object is of type `PassThrough` and not `ReadableStream`. From what I've gathered from docs ([MDN ref](https://developer.mozilla.org/en-US/docs/Web/API/Response/body)) and the types, this property should only be a `ReadableStream`.

## Reproducible By

I haven't been able to reproduce this outside of the project I'm seeing this on. It's unfortunately not open sourced yet, but I will update when it is. The setup, however:

 * E2E test for an endpoint that returns Server Sent Events
 * This same test is ran 4 times under different configurations. This issue is only present on two of the configurations
 * Switching the order that the configurations are ran in fixes the issue (putting the configs that experience this in between the tests that don't)
 * The issue is consistent when present, not flaky
 * The expected stream chunks are still in the `PassThrough`

## Expected Behavior

The `body` property is of type `ReadableStream`

## Logs & Screenshots

![image](https://github.com/nodejs/undici/assets/73616808/13c3c833-303c-4402-a233-a0e7adc1d209)
![image](https://github.com/nodejs/undici/assets/73616808/0d9e1d76-a065-4101-a966-00141d5f620d)

## Environment

* Windows
* Node v20.12.2
* Undici v6.8.0 (dependency of a dependency, upgrading doesn't fix the issue)
* Node test runner
* Tsx module loader

**Comment by Uzlopak** [comment]
PassThrough Stream is a Duplex Stream, which also implements a ReadableStream. But maybe it is not a Webstream

Does it happen when using deflate/inflate as compression?

**Comment by flakey5** [comment]
I don't believe there's compression happening. The transfer encoding is `chunked`

**Comment by KhafraDev** [comment]
Would you be able to share what dependency is using undici? It's unlikely to be an issue here.

**Comment by flakey5** [comment]
Aghh I've figured out the problem and it's not Undici. We utilize an api client to contact another service. Upon importing it, it checks if it's in a browser. If it's not, it overrides the global fetch to be `node-fetch`. Only one of the configurations causes us to use this client and we dynamically import it then. Since the tests and the service are running within the same Node instance, that means the calls to `fetch()` in the tests started using `node-fetch`'s implementation after we tested that configuration. So, the order of things was basically:

 * Configuration A endpoint test
   * `globalThis.fetch` is still Undici
   * Test passes just fine
 * Configuration B endpoint test
   * `globalThis.fetch` is still Undici
   * Api client is imported
   * `globalThis.fetch` is now `node-fetch`
   * Test passes just fine _somehow_?
 * Configuration C & D endpoint tests
   * `globalThis.fetch` is `node-fetch`
   * Tests fail, mocks aren't present, this issue pops up, etc.

In retrospect this probably should've been a bit more obvious to me haha 😅 

Closing now, thank y'all for your assistance!
