### ISSUE TITLE
Is there a plan to add options for setting HTTP headers on EventSource?

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#3115]
### Discussed in https://github.com/nodejs/undici/discussions/3112

<div type='discussions-op-text'>

<sup>Originally posted by **zbinlin** April 13, 2024</sup>
Likes Websocket, we can adds a `dispatcher` option to `EventSource` constructor.</div>

**Comment by Uzlopak** [comment]
@KhafraDev 

Your opinion on this request?

**Comment by KhafraDev** [comment]
we should add it

**Comment by mertcanaltin** [comment]
I added a dispatcher, how should I manage it, do we have certain rules?

**Comment by KhafraDev** [comment]
The same way fetch and websocket implement it https://github.com/nodejs/undici?tab=readme-ov-file#undicifetchinput-init-promise

**Comment by mertcanaltin** [comment]
I wonder if that's a good method 
https://github.com/mertcanaltin/undici/commit/8f6cf8bd1af22792f17b952f96b8876fb08abf31

**Comment by KhafraDev** [comment]
No, dispatcher should be added as an optional property in the eventsource options (second parameter) and I'm not sure if we need to add custom headers since it can be done with Agent. Also there is no step 11 that adds custom headers in the spec so all of those changes to comments should be undone.
