### ISSUE TITLE
Module parse failed: Unexpected token (874:57) undici/lib/web/fetch/util.js

### ISSUE THREAD

**Issue by neysimoes** [nodejs/undici#3122]
## Bug Description

```
 ⨯ ./node_modules/undici/lib/web/fetch/util.js
Module parse failed: Unexpected token (874:57)
|       // 5. If object is not a default iterator object for interface,
|       //    then throw a TypeError.
>       if (typeof this !== 'object' || this === null || !(#target in this)) {
|         throw new TypeError(
|           `'next' called on an object that does not implement interface ${name} Iterator.`
```

## Reproducible By

```
import { setGlobalDispatcher, ProxyAgent } from "undici";

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
const dispatcher =  new ProxyAgent('http://test.com');
setGlobalDispatcher(dispatcher);
```

## Environment
Ubuntu 22.04 LTS
Node v20.12.1

**Comment by Uzlopak** [comment]
Duplicate of #3122

**Comment by neysimoes** [comment]
> Duplicate of #3122

#3122 is this.

**Comment by ronag** [comment]
@KhafraDev should we fix this?

**Comment by KhafraDev** [comment]
No strong opinion. I don't think we should be providing workarounds for libraries that don't understand valid syntax, but this will throw a TypeError regardless if the private prop is accessed if `this` is bound to something else.

**Comment by KhafraDev** [comment]
>  I update the NextJS version to "14.2.1" and solve the problem.

Actually, I don't think we should fix it. It only happens on an outdated version of nextjs, seems like it's already been fixed upstream.

---

This is actually a duplicate of #2923.

**Comment by AdityaParashar24** [comment]
@neysimoes I am facing the same issue. Can you please explain a bit in detail as to how you fixed it? My code is almost the same as you wrote and error message is also the same. 

NextJS version: 14.1.4
Node version: 20.11.0

**Comment by Rolando-Barbella** [comment]
This is still not fix in NexJs, but the problem relies on undici

**Comment by KhafraDev** [comment]
There is fundamentally nothing for us to fix in undici.

https://github.com/vercel/next.js/discussions/30174#discussioncomment-8793544

**Comment by ContrapunctusII** [comment]
Same issue here. I cannot use cheerio.

**Comment by Uzlopak** [comment]
Again, this is not an issue in undici. This is valid syntax.

**Comment by Ethan-Arrowood** [comment]
FWIW, when you have issues with dependencies and Next.js, it is almost always not the dependencies issue. Next.js does a lot of automatic _magic_ including transpiling, bundling, and more. 

Use the Next.js config to exclude non-compatible dependencies either via fields like https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages or modifying the webpack config https://nextjs.org/docs/app/api-reference/next-config-js/webpack

**Comment by truca** [comment]
If you have this issue, you can force the undici version to be 5.28.4 to solve this issue, as mentioned here: https://github.com/nodejs/undici/discussions/3010#discussioncomment-9581353

**Comment by sayedhasan7** [comment]
if you are using firebase then shift to latest version these fix my issue . if not downgrade the version I think is the best solution
