### ISSUE TITLE
Invalid URL error when browser process it successfully

### ISSUE THREAD

**Issue by panchopoliti** [nodejs/undici#3130]
## Bug Description
I am having problems to make requests with a certain type of URL.

It seems that the issue is related with the hyphens (-) in the URL.

When I try the same url in the browser, automatically takes me to the place I want to go. With undici, it throws an error as an invalid url.

What am I missing?

## Reproducible By
````
## undici version 5.28.2 
import { request } from 'undici';

const url = 'https://xn--domain-test20888.activehosted.com'

const { statusCode, headers, trailers, body } = await request(url, {});
console.log(statusCode)

````
## Expected Behavior
Not throwing an error and being able to log the status code.

## Logs & Screenshots
TypeError: Invalid URL

## Environment
macOS 13.3.1 - Node v16.19.0

### Additional context

Thank you!

**Comment by ronag** [comment]
Not undici related.

```js
new URL('https://xn--domain-test20888.activehosted.com')
```

@anonrig

**Comment by panchopoliti** [comment]
Thanks for the answer @ronag.

By the way, I keep receiving the same error when adding
````new URL('https://xn--domain-test20888.activehosted.com')````

Any idea why?

**Comment by ronag** [comment]
I think the issue you linked explains the situation.
