### ISSUE TITLE
Type 'string' is not assignable to type 'HttpMethod'.ts(2345)

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#3168]
Can we change the type of `method` to just regular string? I keep getting this ts warning.

**Comment by Uzlopak** [comment]
This is actually a bug in your implementation and not of undici tylings. Meaning that you are not narrowing down the type to an intersection of HTTPmethod. You  have to typecast it to any, or typecast it to HTTPMethod, or the interface were you defined method as string to HTTPMethod.

If we set it to string, it would mean we accept any method name, even custom ones, like `ronag` method or `aras` method. Are we doing that? If so, then there is a special notation to keep the code completion ability and allow any string value.
If not I would highly recommend to consider it a bug in userland.
