### ISSUE TITLE
Fetching headers of small files causes node process to terminate after 8 seconds since GHSA-9f24-jqhm-jfcw

### ISSUE THREAD

**Issue by unilynx** [nodejs/undici#3230]
## Bug Description

Since undici 6.6.1, which fixes https://github.com/nodejs/undici/security/advisories/GHSA-9f24-jqhm-jfcw), a process fetching a small file but not fetching the body does not terminate until 8 seconds have passed. 

Before 6.6.1, the process would terminate immediately. 

I wonder if this is indeed a bug or intentional behavior caused by the fix and I need to work around it myself

(The advisory mentioned that fetching the body is a workaround for the security issue, so I would assume that undici^6.6.1 wouldnt require fetching bodies)

## Reproducible By
test.js:

```
const { fetch } = require ("undici");
async function main() {
  const x = await fetch (process.argv[2]);
  console.log(x);
}
main()
```

running it:
```
npm i undici@6.6.0
node test.js http://cms6-sites.webhare.com/test-arnold/empty-40kb.docx  # works, process terminates immediately
node test.js http://cms6-sites.webhare.com/test-arnold/empty-160kb.docx. # works, process terminates immediately

npm i undici@6.6.1
node test.js http://cms6-sites.webhare.com/test-arnold/empty-40kb.docx  # FAILS: process hangs for 8 seconds
node test.js http://cms6-sites.webhare.com/test-arnold/empty-160kb.docx. # works, process terminates immediately
```

Reproduction will probably depend on your latency to Amsterdam.

Locally I found the cutoff point to be between 91kb and 92kb (more details here https://github.com/nodejs/node/issues/52909)

The issue still exists in undici@6.16.0. It also affects the fetch currently shipped in nodejs v2.13.0 (nodejs v2.12.2 worked fine)

Actually fetching the body (await x.arrayBuffer()) fixes the issue.

## Expected Behavior
I would expect the process to be allowed to terminate even if I don't fetch the body

## Environment
Docker container node:20.13.0 (reproduced on both arm64 and x86_64)

**Comment by mcollina** [comment]
Can you try to assemble a server to reproduce locally?

**Comment by Uzlopak** [comment]
Strange. Under node 22 it works without any issue but with node 20 not.

**Comment by unilynx** [comment]
> Can you try to assemble a server to reproduce locally?

I tried that in may but couldn't reproduce it with a local http server, and didn't spot anything obvious in tcpdump or MTU related to trigger the issue. Didn't find the time to investigate it further back then unfortunately

> Strange. Under node 22 it works without any issue but with node 20 not.

Same here. node:22 works for me with both the shipped undici (6.19.2 judging by the changelogs) AND undici 6.6.1. Node 20 fails.

The node:22.0 docker container also works, but node:21 still fails.

**Comment by Uzlopak** [comment]
It is not missing a minimal reproduction. 

I bisected this issue in our code and can acknowledge this bug. I think this is a bug in node core itself. It seems like a  resource is not released, thus the node instance is not terminating.

I guess somewhere it was fixed main-branch but in the node 22-branch is not backported.

@metcoder95 
There is a minimal reproduction in the entry post. 

```js
'use strict'

const { fetch } = require (".");
async function main() {
    await fetch ('http://cms6-sites.webhare.com/test-arnold/empty-40kb.docx');
}
main()
```

node 18 is broken, node 20 is broken, only node 22 works

**Comment by mcollina** [comment]
> It is not missing a minimal reproduction.

It does. It needs a server.

---

> I guess somewhere it was fixed main-branch but in the node 22-branch is not backported.

This is somewhat related to a change in Node.js that landed in v22 but not on v20 and v18.

Let's move this to Node.js core, then. Hopefully, somebody could do a bisect and find out which commit fixed it.

**Comment by unilynx** [comment]
I've bisected it to https://github.com/nodejs/node/commit/1abff073921bcb0631602032aef0135bccfaee0d - interestingly this commit makes an exception for win32. I don't have easy access to that platform so I'm curious if the bug is still there (or never was)

I originally posted this issue as https://github.com/nodejs/node/issues/52909 so I'll just add the recent information here there.

**Comment by Uzlopak** [comment]
So basically if we remove the high watermark it should work again?!

**Comment by climba03003** [comment]
> I've bisected it to https://github.com/nodejs/node/commit/1abff073921bcb0631602032aef0135bccfaee0d - interestingly this commit makes an exception for win32. I don't have easy access to that platform so I'm curious if the bug is still there (or never was)

It works only because it consumed the whole payload based on the hwm.
I don't think it means to solve the underlying issue.

Here is the simple script using `node` as the server instead of `nginx`.
I disabled the `keep-alive` to simulate the problem, you can also change to `75` which match the nginx default.

You can see that it never been able to close without consuming the payload, or early than the keep-alive timeout.
From your case, the `160kb` seems to works because the payload is split into two part (by nginx). So, the content never received by fetch and actually considered as consumed all payload (status code and headers).
the `40kb` case is that the status, headers and payload is inside a single chunk. So, `fetch` requires to consume the later part of it.

```js
import { createServer } from 'http';
import { setDefaultHighWaterMark } from 'stream';
import { fetch } from 'undici';
const start = performance.now()

setDefaultHighWaterMark(false, 16 * 1024)
const kb = new Array(1024).fill('0').join('')

const server = createServer((request, response) => {
  response.setHeader('content-type', 'text/plain')
  switch (request.url) {
    case '/40kb.txt': {
      response.setHeader('content-length', '40960')
      for (let i = 0; i < 40; i++) {
        response.write(kb)
      }
      break
    }
    case '/160kb.txt': {
      response.setHeader('content-length', '163840')
      for (let i = 0; i < 40; i++) {
        response.write(kb)
      }
      break
    }
  }
  response.end()
})
server.keepAliveTimeout = 0
server.listen(3000, '127.0.0.1')

// 40kb
await fetch(`http://127.0.0.1:3000/40kb.txt`);
// 160kb
// await fetch(`http://127.0.0.1:3000/160kb.txt`);
server.close()

process.on('beforeExit', () => {
  const end = performance.now()
  console.log(`Script ended in %s ms`, end - start)
})
```

**Comment by mcollina** [comment]
Did somebody test this with latest undici? I think this case might be more or less be handled by the FinalizationRegistry logic, as the body should be cancelled after the `Response` goes out of scope.

Otherwise, I don't think there is much to do here.

**Comment by Uzlopak** [comment]
It doesnt work with latest undici and latest node 20.

**Comment by metcoder95** [comment]
I couldn't reproduce it with latest `undici` (`main`) and node `v22` nor `v20`.

With `v20`
- `Script ended in 66.89474999999999 ms`

With `v22`
- `Script ended in 11.864208000000005 ms`
