### ISSUE TITLE
running autobahn test suite

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#3249]
We cannot move WebSocket out from experimental until we run the autobahn test suite.

https://github.com/crossbario/autobahn-testsuite

**Comment by Uzlopak** [comment]
Maybe we can adapt it from this?

https://github.com/search?q=repo%3Atheturtle32%2FWebSocket-Node%20autobahn&type=code

I think we should do it in two steps.
1. Add autobahn test suite and make it run via an npm script like npm run test:autobahn
2. Fix errors thrown by autobahn incrementally
3. If all tests pass, add it as part of the test:websocket npm script

**Comment by KhafraDev** [comment]
@Uzlopak thanks for the link, but I'd probably use ws' autobahn client script; a lot of what's implemented in Websocket-node is just a basic setup that the autobahn suite instructs us on how to setup already.

autobahn tests don't exit out, it generates a report with passed/failed tests as an html file. We would instead publish the report on the docs site (for example).

running the tests is relatively easy, but making a reproducible testing suite is the hard part. Also, the tests don't give information on what failed and we have to replicate each test in js which makes it hard.

**Comment by KhafraDev** [comment]
https://github.com/websockets/ws/blob/master/test/autobahn.js

**Comment by KhafraDev** [comment]
[index.txt](https://github.com/nodejs/undici/files/15287449/index.txt)

Here are the results. (rename to index.html, github wouldn't let me upload an html file...)
