### ISSUE TITLE
do not encode with encodeURIComponent if query with method GET passed.

### ISSUE THREAD

**Issue by masoudesm** [nodejs/undici#3287]
I have studied the source code and saw this file `lib/core/util.js` which there is a function called `buildURL` and it is using node's querystring which by default is doing `encodeURIComponent` causing a third party backend that I'm calling to be broken, as I can not ask them to change, so preferably, it would be much nicer in undici we can have a option to disable `encodeURIComponent` or enable it.

**Comment by masoudesm** [comment]
I can do it, if it is possible.

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that outlines the behaviour that is leading to the failures?

**Comment by masoudesm** [comment]
for example:

API CALL:
` await request('https://jsonplaceholder.typicode.com/comments', {
  method: 'GET',
  query: {
    id: 1,
    postId: 1,
    date: '12-10-2024T12:12:40'
  }
})`

EXPECTED URL GENERATED:
`https://jsonplaceholder.typicode.com/comments?id=1&postId=1&date=12-10-2024T12:12:40`

WHAT DEBUG MODE SHOWS:
`UNDICI 13726: connecting to jsonplaceholder.typicode.com using https:undefined
UNDICI 13726: connected to jsonplaceholder.typicode.com using https:h1
UNDICI 13726: sending request to GET https://jsonplaceholder.typicode.com//comments?id=1&postId=1&date=12-10-2024T12%3A12%3A40
UNDICI 13726: received response to GET https://jsonplaceholder.typicode.com//comments?id=1&postId=1&date=12-10-2024T12%3A12%3A40 - HTTP 200
UNDICI 13726: trailers received from GET https://jsonplaceholder.typicode.com//comments?id=1&postId=1&date=12-10-2024T12%3A12%3A40`

as you see it is encoded, this example will work but some server rest implementation (which I would call them bad designed) they don't accept encodedURIComponent in the query string.

**Comment by ronag** [comment]
If you build the whole url yourself and don't user `query` you should already be able to do this

**Comment by masoudesm** [comment]
Yes I know, but I would prefer to not, when the library is doing it, I was wondering if there could be an option that could be passed to not encode the url?

**Comment by Uzlopak** [comment]
Maybe we should consider to pass a queryparser as an option?

**Comment by ronag** [comment]
> I was wondering if there could be an option that could be passed to not encode the url?

I don't think we want to maintain special code for bad behaving servers. You will need to do this "hack" in user space.
