### ISSUE TITLE
publish autobahn test results on the docs site

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#3312]
The autobahn report generates a couple hundred html files as a report, having this published without having to run the suite for oneself could be useful IMO.

**Comment by KhafraDev** [comment]
cc @Ethan-Arrowood

**Comment by mcollina** [comment]
I'm +1. How can we generate it? Is there an npm script?

**Comment by KhafraDev** [comment]
1. run the server with `docker run -it --rm     -v "${PWD}/config:/config"     -v "${PWD}/reports:/reports"     -p 9001:9001     --name fuzzingserver     crossbario/autobahn-testsuite`
2. `node test/autobahn/client.js`

**Comment by mcollina** [comment]
How to get the report then?

**Comment by KhafraDev** [comment]
after the node script finishes it generates the report automatically in test/autobahn/reports/clients/

**Comment by KhafraDev** [comment]
I've published the results onto my own .github.io site https://khafradev.github.io/autobahn/clients/index.html
