### ISSUE TITLE
Improve support for pre-shared sessions (PSK)

### ISSUE THREAD

**Issue by tastypackets** [nodejs/undici#3315]
## This would solve...

Simplify Undici for environments that use pre-shared sessions.

The biggest limitation I ran into was pool creating the session automatically. It looks to me like my only option to control the session is pass my own connect function and reimplement most of what's in `buildConnector`.

https://github.com/nodejs/undici/blob/250c863ce22a12223217c2d5cb2841b99c40b8c1/lib/dispatcher/pool.js#L55

## The implementation should look like...

Some ideas:
- If a session is passed have `buildConnector` respect / prioritize it, [currently it's overwritten](https://github.com/nodejs/undici/blob/250c863ce22a12223217c2d5cb2841b99c40b8c1/lib/core/connect.js#L102). On the surface this seems like the easiest and best option to me, but would like to hear some feedback.
  - Is there a reason we spread these options first instead of last? I'd expect the module should prioritize the passed settings over anything internal by default in most cases.
- Make extending `buildConnector` easy, for example if this was a class it'd be easy to extend and overwrite just the session method. The new custom connect builder could then be used to pass connect to the pool, so developers don't need to reimplement everything in build connector.
- We could also build something specific for pre-shared sessions, but that feels like a burden on this module and for implementors to learn. I think I'd favor something minimal that keeps the implementor on the hook for connecting in their pre-shared sessions as needed since this is likely the minority of Undici users.

## I have also considered...

For now I'll likely pass my own connect function

**Comment by tastypackets** [comment]
I don't mind opening a PR for this, but think it first needs some discussion/review to make sure we are aligned on the path forward.

**Comment by mcollina** [comment]
> Is there a reason we spread these options first instead of last? I'd expect the module should prioritize the passed settings over anything internal by default in most cases.

as you can see, in that example, we are reading the session from the cache. I guess this was added without thinking of the preshared key.

A PR that improves this would be great.

**Comment by tastypackets** [comment]
@mcollina opened a draft PR to simply spread options at the bottom, so anything can be overriden. Do you think this is okay or was it intentional somethings like `socket` and `ALPNProtocols` are set by the module?
