### ISSUE TITLE
Request constructor: Failed to parse URL from ___

### ISSUE THREAD

**Issue by rwaldron** [nodejs/undici#3319]
## Bug Description

The `Request` constructor is currently not interoperable with the web: 

| Code | Undici | The Web |
| --- | --- | --- |
| `new Request('')` | ❌  | ✅ |
| `new Request('/x')` | ❌  | ✅ |

## Reproducible By

| Code | Undici | The Web |
| --- | --- | --- |
| `new Request('')` | ❌  | ✅ |
| `new Request('/x')` | ❌  | ✅ |

## Expected Behavior

| Code | Undici | The Web |
| --- | --- | --- |
| `new Request('')` | ✅  | ✅ |
| `new Request('/x')` | ✅  | ✅ |

## Logs & Screenshots

Undici: 

![image](https://github.com/nodejs/undici/assets/27985/ca2abe67-d31c-48d6-82e4-24c94245548f)

![image](https://github.com/nodejs/undici/assets/27985/d1b0c471-1f51-478a-8dad-d858cc801c2e)

The web: 

![image](https://github.com/nodejs/undici/assets/27985/bedaa753-5b95-4186-92e2-4ae9fc49c81e)

**Comment by rwaldron** [comment]
A bit of a revision here: the issue is actually coming from `URL`, as it gets used here: https://github.com/nodejs/undici/blob/250c863ce22a12223217c2d5cb2841b99c40b8c1/lib/web/fetch/request.js#L113-L118

**Comment by KhafraDev** [comment]
The web has a concept of an origin, which is the base url used for Request. Node does not, and therefore cannot by default parse the url. With undici, you can set a global origin with [setGlobalOrigin](https://github.com/nodejs/undici?tab=readme-ov-file#undicisetglobaloriginorigin) which will be used in specs undici implements.
