### ISSUE TITLE
Ability to externalize WASM was broken

### ISSUE THREAD

**Issue by mhdawson** [nodejs/undici#3345]
## Bug Description

This PR introduced the ability to externalize WASM, which is needed by distros to be able to rebuild all components shipped: https://github.com/nodejs/undici/pull/2643

PR https://github.com/nodejs/undici/pull/3074 broke this by removing some of the implementation needed.

## Reproducible By
Build as specified in the undici CONTRIBUTING.md - https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md#building-for-externally-shared-node-builtins

and validate that the wasm is not in the expected place

## Expected Behavior

After building as described in the undici CONTRIBUTING.md - https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md#building-for-externally-shared-node-builtins

the wasm binary should be in the expected place

**Comment by ronag** [comment]
@Uzlopak

**Comment by mhdawson** [comment]
There is some discussion in the issue,  goal is to add back the parts that were removed but still needed while keeping what was optimized in https://github.com/nodejs/undici/pull/3074

**Comment by Uzlopak** [comment]
Yes, we discussed this, I kind of lost track of it.

**Comment by mcollina** [comment]
Should we revert?

@mhdawson how can we test for this in a meaningful way so we don't regress?

**Comment by mhdawson** [comment]
I was talking about that a bit with Richard. I don't know the undici tests well enough to know off the top of my head, but building with the option enabled and validating that the wasm file is were it's expected afterwards was what we thought might work.

**Comment by mcollina** [comment]
@mhdawson if any of you can drop a PR for this, it would be very useful to prevent further issues.

**Comment by Uzlopak** [comment]
Actually it just needs like 5 more lines, I promise I will provide a PR tonight at latest midnight (German Time),

**Comment by mhdawson** [comment]
@Uzlopak do you mean you will include the testing in your PR?

**Comment by Uzlopak** [comment]
I will also provide a test.

**Comment by khardix** [comment]
@Uzlopak Any updates?

**Comment by mhdawson** [comment]
@Uzlopak just wondering if there is something I can do to help this along?  If you have the right way in mind to fix but just don't have time maybe we can get together to do some knowledge transfer and either myself or @richardlau can help out?

**Comment by richardlau** [comment]
I'm working on this and should be able to open a PR either later today or tomorrow (trying to get a working GitHub Actions flow in place so future regressions can be detected).

**Comment by richardlau** [comment]
PR: https://github.com/nodejs/undici/pull/3421
