### ISSUE TITLE
Measure request latency 

### ISSUE THREAD

**Issue by artur-ma** [nodejs/undici#3347]
I would like to measure total request execution time (connect, write payload, wait on a socket, reading headers, reading payload)

There are three possible ways to do it right now:

1. Diagnostic channel - I do not want to use it, since it will measure any undici usage, in any package, I just want to measure my requests
2. Request Handler / Interceptor - Using `onConect` , `onComplete` and `onError` methods, it would be greate, but I do not have any common "context" object between all this methods, to find the start time of a request from `onComplete` method

Lets say I have this code

```ts
class MyHandler {
  constructor(..) {
     ...
  }
  
  onConnect(abort) {
     // let say I call here `performance.now()` where should I assign it?
  }
  
  onComplete(trailers) {
     // How do I get the start time of my exact request that just finished?
  }
}
```

3. I can use an interceptor

```ts
function createMetricsInterceptor() {
  return async (dispatch) => {
    return (opts, handler) => {
      const start = performance.now();
      const res = await dispatch(opts, handler);
      const totalTime = performance.now() - start
      
      return res
    };
  };
```

But this method, will **include the retries**, and also will **not include the "read from socket"** since undici is not reading from socket by default, it should be "consumed"

So am I missing something? Is there another way to measure?

Thanks

**Comment by metcoder95** [comment]
👋 
You should think about each `handler` as map to single request, so whatever state is attached to it, unless stored in another wider scope state, it will be tight to the lifecycle of the request.

For instance, you can have a class that preserves the state and flushes the metrics upon errored or completion:

```
{
  state: {
    start: 0,
    end: 0,
    errored: false,
  },
  onConnect() {
    this.start = Date.now()
  },
  onBodySent() {},
  onHeaders(status, _rawHeaders, resume, _statusMessage) {
    const timestamp = Date.now();
    console.log('headers took', timestamp - this.start, 'ms', 'errored:', this.state.errored)
  },
  onData(chunk) {},
  onComplete() {
    this.end = Date.now();
    console.log('Request took', this.end - this.start, 'ms', 'errored:', this.state.errored)
  },
  onError(err) {
    this.end = Date.now();
    console.log('Request took', this.end - this.start, 'ms', 'errored:', this.state.errored)
  },
}```

Just to ilustrate.

**Comment by fatal10110** [comment]
Oh, 
So in the interceptor we create a new dispatcher, that actually creates new handler instance on each dispatch


ok thanks!

**Comment by metcoder95** [comment]
Yes, exactly

Closing as resolved
