### ISSUE TITLE
Cannot convert argument to a ByteString because the character at index 46 has a value of 65286 which is greater than 255

### ISSUE THREAD

**Issue by xiaoqianghaochi** [nodejs/undici#3352]
## Bug Description

Cannot convert argument to a ByteString because the character at index 46 has a value of 65286 which is greater than 255

## Expected Behavior
UA contains the @ symbol

user_agent: **scaninfo@paloaltonetworks.com

## Environment

node: v20.11.1

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by tsctx** [comment]
This is not a bug. You are using invalid characters in the header that are not allowed by the spec.
