### ISSUE TITLE
Undici.Request and AbortController doesn't work well

### ISSUE THREAD

**Issue by fawazahmed0** [nodejs/undici#3353]
## Bug Description

Sometimes Aborting Undici.Request causes whole program to stop, even though everything is wrapped around try catch.

## Reproducible By

~~I don't have minimal reproducible example, as my code is larger in size.~~ But Undici.Fetch doesn't have this issue.

Here is minimal reproducible example:
```js
const undici = require('undici')

async function testUndici() {
    const controller = new AbortController()
    const {statusCode,headers,trailers,body} = await undici.request("https://github.com/fawazahmed0/tiger/releases/download/v2/pipetocsv.7z", { signal: controller.signal }).catch(console.error)
    setTimeout(()=>controller.abort(), 500)
}
testUndici()
```

## Expected Behavior

Undici.Request and AbortController should work

## Logs & Screenshots

```
node:events:498
      throw er; // Unhandled 'error' event
      ^
DOMException [AbortError]: This operation was aborted
    at new DOMException (node:internal/per_context/domexception:53:5)
    at AbortController.abort (node:internal/abort_controller:395:18)
    at Timeout._onTimeout (T:\xx\other scripts\undici-debug.js:7:31)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on BodyReadable instance at:
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v22.3.0
```

## Environment

Ubuntu 24.04 & Windows 11
Node v22.3.0
Undici 6.19.1

**Comment by Gigioliva** [comment]
I am having the same problem. The bug was introduced in `6.16.0`. I think the problem is in this #3209. In case of  [onComplete](https://github.com/nodejs/undici/blob/9134ee653af1ac933df975d76883fefd92bc23c2/lib/api/api-request.js#L156) we don't remove the listener from the signal

**Comment by Gigioliva** [comment]
Adding this in `api-request.js` fixes the issue

<img width="385" alt="Screenshot 2024-06-21 alle 21 38 51" src="https://github.com/nodejs/undici/assets/26747867/270e4895-288a-4012-b2f9-6ad6f70242cf">

**Comment by mcollina** [comment]
@Gigioliva Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Gigioliva** [comment]
👍🏼 I will do

**Comment by Gigioliva** [comment]
@mcollina https://github.com/nodejs/undici/pull/3354

**Comment by ronag** [comment]
The problem is that you are not cleaning up / destroying / consuming the body of returned response object which keep the signal handler referenced.

```js
    while (!response?.ok) {
        await response?.body.dump()
        response = await undici.fetch(link, { signal: controller?.signal, cache: "no-store"})
    }
```

**Comment by Gigioliva** [comment]
@ronag In my case I was consuming the response 🤔 `await result.body.text()`

**Comment by ronag** [comment]
Not between iterations of the while loop

**Comment by Gigioliva** [comment]
Yes. within the loop. My code is something like:
```ts
class MyClass {
  readonly #pool: Agent;

  constructor() {
    this.#pool = new Agent({ connections: MAX_CONCURRENCY });
  }

  async runFetch(urls: string[]): Promise<string[]> {
    return await Promise.all(urls.map((url) => this.doGet(url)));
  }

  private async doGet(url: string) {
    const result = await this.#pool.request({
      origin: url,
      path: "/foo",
      method: "GET",
      signal: AbortSignal.timeout(1_000),
    });
    const text = await result.body.text();
    console.log(text);
    return text;
  }
}
```

**Comment by ronag** [comment]
Do you have a repro then? Because your other repro was incorrect.

**Comment by Gigioliva** [comment]
Yup. I can reproduce it in my tool tests. I will try to extract the test and share with you

**Comment by ronag** [comment]
You are not consuming the body of the undici.request response object between loop iterations.

**Comment by Gigioliva** [comment]
@ronag looking better at the code, a specific status code (`204`) I don't consume the body. This however in my opinion is a bug. Why should I necessarily consume the body?

**Comment by ronag** [comment]
That's how it was designed and is clearly documented.

We can discuss that in a separate issue if you wish.

**Comment by ronag** [comment]
request returns a body: Stream which gets destroyed if an abort error and emits an error that you are not handling and therefore the process crashes with an unhandled exception. This is normal nodejs behavior. Feel free to open a PR if you think that needs to be explicitly documented by undici.

**Comment by Gigioliva** [comment]
Is this considered "correct"?
```ts
const pool = new Agent()

try {
    const result = await this.#pool.request({
          origin: url.origin,
          path: url.pathname,
          method: "GET",
          signal: AbortSignal.timeout(1000),
        });

   if(result.statusCode === 204){
       // log and DON'T consume the body
   } else {
      // call await result.body.text()
   }

   // Manually close the body to avoid this bug
   result.body.emit("close");

} catch(err) {
    // Handle connection errors
}



```

**Comment by ronag** [comment]
No that is not correct. You should not be emitting events yourself.

```
const pool = new Agent()

try {
    const result = await this.#pool.request({
          origin: url.origin,
          path: url.pathname,
          method: "GET",
          signal: AbortSignal.timeout(1000),
        });

   if(result.statusCode === 204){
       // log and DON'T consume the body
   } else {
      // call await result.body.text()
   }

   // Consume the body
   await result.body.dump() // or result.body.on('error', () => {}).destroy()
} catch(err) {
    // Handle connection errors
}
```

**Comment by ronag** [comment]
There is nothing to fix. It works as designed.

**Comment by uriva** [comment]
@titanism I'm still seeing this issue on nodejs 23.1.0

the code in question is https://github.com/webtorrent/bittorrent-tracker/blob/master/lib/client/http-tracker.js#L147

I'm getting the `DOMException` from the line where the `AbortController` is created, that is outside the try/catch

Any idea?

Thanks

**Comment by ggoodman** [comment]
Hi team, we got bitten by this issue in production like others in this thread.

I think that while `Readable` and `undici` are each working as intended, the combination of the two leads to an API that is unnecessarily hostile for a user.

In our case, the issue manifested because we're holding onto a reference to `clientRes` to pipe into a subsequent bit of work. However, after obtaining a reference to `clientRes` and before calling `pipeline(clientRes.body, nextConsumer, { signal })`, we call `signal.throwIfAborted()`.

This leads to a whole-program crash despite the whole sequence above being orchestrated in an `async function`, attempting idiomatic use of `AbortSignal`.

The fix, in our case is the following, which I believe is indicative of the dangerous nature of this interaction:

```js
async function criticalPath() {
  clientRes = await performUndiciRequest(signal);
  
  // This is the fix.
  clientRes.body.on('error', () => {
    // Ignore the error so that we don't get uncaught exceptions and crash.
  });
  
  // ... do some async work
  
  signal.throwIfAborted();
  
  // ... consume the body
  
  await pipeline([clientRes.body, targetStream], { signal });
}
```

**Comment by ggoodman** [comment]
> how do you safely do cleanup and destroy the stream after? otherwise you will encounter 100% cpu usage

@titanism my understanding is that the problematic behaviour with CPU usage is limited to `fetch` and Web streams. In our case, we're using `undici` as a lower-overhead http/1.1 client for some high-volume, low-latency reverse proxying.

Is there evidence that `import('node:stream').Readable` also suffers from this footgun?

**Comment by ronag** [comment]
I don't see a problem here. You are mostly mis-using the api... The `signal.throwIfAborted()` is not necessary.

**Comment by ronag** [comment]
@titanism That does not seem relateed to this issue, please create a new one

**Comment by ggoodman** [comment]
@ronag I think I see where you're coming from now. This appears to be the precedent for all Node.js Streams produced with a supplied signal (https://github.com/nodejs/node/blob/f17b9a4c7838f37022255f4dcee09a083686018e/lib/internal/streams/add-abort-signal.js#L41-L60). At least, that's the precedent for synchronous APIs returning streams.

I think the surprising thing here is that this is a hybrid promise / stream API. Both the initial promise for getting the `Response` object AND the stream are governed by the `signal`. I suppose that I was only expecting the initial Promise for the headers to be controlled by the signal. I was already controlling the consumption of the body stream using the `signal` via `pipeline()`. I expected any possible failure modes to result in promise rejections instead of this subtle interaction with node's emitter-based legacy.

**Comment by ronag** [comment]
> I think the surprising thing here is that this is a hybrid promise / stream API. Both the initial promise for getting the Response object AND the stream are governed by the signal. I suppose that I was only expecting the initial Promise for the headers to be controlled by the signal. I was already controlling the consumption of the body stream using the signal via pipeline(). I expected any possible failure modes to result in promise rejections instead of this subtle interaction with node's emitter-based legacy.

@mcollina wdyt?
