### ISSUE TITLE
`UND_ERR_CONNECT_TIMEOUT` errors thrown when there is CPU intensive code on the event loop

### ISSUE THREAD

**Issue by mknichel** [nodejs/undici#3410]
## Bug Description

Work on the event loop can interrupt the Undici lifecycle for making requests, causing errors to be thrown even when there is no problem with the underlying connection. For example, if a fetch request is started and then work on the event loop takes more than 10 seconds (default connect timeout), Undici will throw a `UND_ERR_CONNECT_TIMEOUT` error even if the connection could be established very quickly.

I believe what is happening is:

1. When the fetch request is started, Undici starts the work to make a connection. Undici calls `setTimeout` with the value of the `connectTimeoutMs` to throw an error and cancel the connection if it takes too long (https://github.com/nodejs/undici/blob/main/lib/core/connect.js). It makes a call to `GetAddrInfoReqWrap` (https://github.com/nodejs/node/blob/main/lib/dns.js#L221), but this is asynchronous and processing of the callback will be delayed until the next event loop.
2. User tasks block the event loop for a long period of time.
3. The `onConnectTimeout` timer is run because the previous task took longer than the timeout. `onConnectTimeout` calls `setImmediate` with a function to destroy the socket and throw the error. https://github.com/nodejs/undici/blob/main/lib/core/connect.js
4. The `GetAddrInfoReq` lookup callback (`emitLookup` in `node:net`) is run. This code begins the TCP connection (`internalConnect` is called in https://github.com/nodejs/node/blob/main/lib/net.js#L1032) but that is also asynchronous, so it won't finish in this round of the event loop.
5. The `setImmediate` function is run in the next phase which destroys the socket and throws the `UND_ERR_CONNECT_TIMEOUT` error.
6. Undici never gets a chance to handle the TCP connection response.

Internally at Vercel, we have been seeing a high number of these `UND_ERR_CONNECT_TIMEOUT` issues while pre-rendering pages in our Next.js application. I can't run this task on my local machine so it's harder to debug, but it's a CPU intensive task and moving fetch requests to a worker thread eliminated the Undici errors. We tried other suggestions (like `--dns-result-order=ipv4first` and verified that we were not seeing any packet loss) that did not resolve the issue. Increasing the connect timeout resolves the issue in the reproduction but _not_ the issue in our Next.js build (which I can't explain).

## Reproducible By

A minimal reproduction is available at https://github.com/mknichel/undici-connect-timeout-errors.

We can reproduce the behavior on Node 18.x and 20.x and with the `5.24.0` and the latest version of Undici (`6.19.2`)

## Expected Behavior

The Undici request lifecycle could operate on a separate thread that does not get blocked by user code. By separating it out from the user code, this would remove impact of any user code on requests.

To test this theory, we created a dispatcher that proxied the fetch request to a dedicated worker thread (`new Worker` from `worker_threads`). This eliminated all the Undici errors that we were seeing in our Next.js build.

## Logs & Screenshots

In the minimal reproduction, the error is:

```
TypeError: fetch failed
    at fetch (/Users/mknichel/code/tmp/undici-connect-timeout-errors/node_modules/.pnpm/undici@6.19.2/node_modules/undici/index.js:112:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchExample (/Users/mknichel/code/tmp/undici-connect-timeout-errors/index.ts:21:20)
    at main (/Users/mknichel/code/tmp/undici-connect-timeout-errors/index.ts:66:3) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/Users/mknichel/code/tmp/undici-connect-timeout-errors/node_modules/.pnpm/undici@6.19.2/node_modules/undici/lib/core/connect.js:190:24)
      at /Users/mknichel/code/tmp/undici-connect-timeout-errors/node_modules/.pnpm/undici@6.19.2/node_modules/undici/lib/core/connect.js:133:46
      at Immediate._onImmediate (/Users/mknichel/code/tmp/undici-connect-timeout-errors/node_modules/.pnpm/undici@6.19.2/node_modules/undici/lib/core/connect.js:174:9)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
```

In our Next.js builds, the error is:

```
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async s (elided path)
    at async elided path {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7760:28)
      at node:internal/deps/undici/undici:7716:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7748:13)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```

## Environment

The reproduction repo was erroring for me on Mac OS 14.4, while internally we are seeing issues on AWS EC2 Intel machines.

### Additional context

Vercel/Next.js users have reported `UND_ERR_CONNECT_TIMEOUT` issues to us:

- https://github.com/vercel/vercel/issues/11692
- https://github.com/vercel/next.js/issues/66373

**Comment by ronag** [comment]
I think something like this would also do the trick:

```js
diff --git a/lib/util/timers.js b/lib/util/timers.js
index d0091cc1..fa56be8b 100644
--- a/lib/util/timers.js
+++ b/lib/util/timers.js
@@ -2,13 +2,13 @@
 
 const TICK_MS = 499
 
-let fastNow = Date.now()
+let fastNow = 0
 let fastNowTimeout
 
 const fastTimers = []
 
 function onTimeout () {
-  fastNow = Date.now()
+  fastNow += TICK_MS
 
   let len = fastTimers.length
   let idx = 0
```

Though it needs some time to rewrite all the tests.

**Comment by dipesh112** [comment]
@mknichel any progress or updates on this one? My Vercel/Next.js based projects are facing bad experiences.

**Comment by Uzlopak** [comment]
I am currently working on this

**Comment by thisislvca** [comment]
Awesome! Been waiting for this for a while...

**Comment by thisislvca** [comment]
Any updates?

**Comment by Uzlopak** [comment]
I am on it ;)

**Comment by Uzlopak** [comment]
this bug is potentially still existing. we need more investigating.

**Comment by philipsolarz** [comment]
Hi, I've been getting the UND_ERR_CONNECT_TIMEOUT for a few months now. For my use case I have a default Next.js 14 App, using next-auth@beta with GitHub as provider. I go to http://localhost:3000/api/auth/signin and attempt to sign in.

1. npm run dev (Fail)
2. npm run build && npm run start (Fail)
3. docker build **(Success)** using: https://nextjs.org/docs/pages/building-your-application/deploying#docker-image
4. same image running in k8s (Fail)

Code: https://github.com/philipsolarz/my-next-app/

Any ideas or hints?

**Comment by Uzlopak** [comment]
ah, a new reproduction. let me check it

**Comment by Uzlopak** [comment]
@philipsolarz 

I dont see how i can provoke the issue. Do you have discord? twitter? something were we could chat?

**Comment by Uzlopak** [comment]
@philipsolarz 
I added you on linkedin. Maybe we can chat there?

**Comment by thisislvca** [comment]
> Hi, I've been getting the UND_ERR_CONNECT_TIMEOUT for a few months now. For my use case I have a default Next.js 14 App, using next-auth@beta with GitHub as provider. I go to http://localhost:3000/api/auth/signin and attempt to sign in.
> 
> 1. npm run dev (Fail)
> 2. npm run build && npm run start (Fail)
> 3. docker build **(Success)** using: https://nextjs.org/docs/pages/building-your-application/deploying#docker-image
> 4. same image running in k8s (Fail)

What OS are you running & what's your hardware configuration? I've been having the issue in prod for the past three-ish months, but never had it locally...

**Comment by kaitok** [comment]
I also got same issue.
node uses ipv6 by default, I specified ipv4 in next.config.js and it didn't solve the problem.

MacOS
Next.js version: 14.0.1

```
const dns = require('dns')
dns.setDefaultResultOrder('ipv4first')
```

**Comment by Uzlopak** [comment]
It is not because of ipv6 or ipv4

**Comment by 2-fly-4-ai** [comment]
Same issue here.

**Comment by 2-fly-4-ai** [comment]
> It is not because of ipv6 or ipv4

Has anyone figured out how to solve this issue yet?

**Comment by LikeDreamwalker** [comment]
I can reproduce this issue sometimes when I am trying to update next itself or installed some new dependencies.
So if you are facing this issue and you sure that your network and service are fine, you could try to remove the `node_modules` and `.next` folders content, to re-install and re-build again.
That works for me and I can be sure that this issue is not related to next itself, so you won't need to worry that if your updates on next cause some break issues on your server request.

**Comment by nykula** [comment]
I notice that in Node v20, there are more details about the error, such as attempted address and timeout. It would be better if even more error specifics were mentioned, such as which part of the connection failed. In my production deployment, the exact same error message (bringing a Next.js app down and making it impossible to rebuild), searching for which leads me to this issue, turned out to appear due to Google DNS rate limiting, which in practice looks like an infinite timeout. I found the cause accidentally when trying a curl request from bash rather than Node - the curl binary told me that resolving the hostname failed. Due to how the Undici error message is worded, we were investigating the wrong possible reason of the problem at first, we thought our backend server was discarding connections under load.
