### ISSUE TITLE
MockAgent not compatible with ProxyAgent,EnvHttpProxyAgent,RetryAgent

### ISSUE THREAD

**Issue by urugator** [nodejs/undici#3444]
## Bug Description

`ProxyAgent`, `EnvHttpProxyAgent`, `RetryAgent` can't be passed to `new MockAgent({ agent })`, because they're missing `closed` and `destroyed` props.

## Environment

Win 10, Node v20.13.1

### Additional context

Not sure if I am approching this correctly, but I would like to handle non-itercepted requests exactly the same way as they would be by the app. So my assumption is that I am supposed to pass an agent used by my application to `MockAgent` and it will be used for non-intercepted requests.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment]
Could reproduce it... provided potential fix in #3497
