### ISSUE TITLE
I do not receive set-cookie in response.headers.getSetCookie()

### ISSUE THREAD

**Issue by fancy45daddy** [nodejs/undici#3448]
## Bug Description
I do not receive set-cookie in response.headers.getSetCookie()

## Reproducible By
const login = await globalThis.fetch('https://huggingface.co/chat/login', {method:'post', headers:{'accept':'text/html', 'origin':'https://huggingface.co/chat', 'content-type':'application/x-www-form-urlencoded'}})
console.log(login.headers.getSetCookie, login.url)

But when I use http toolkit to monitor the fetch
I can see there is
set-cookie:
hf-chat=fb2586eb-4777-4ca9-b3a7-009d797c6d15; Path=/; Expires=Mon, 26 Aug 2024 14:28:33 GMT; HttpOnly; Secure; SameSite=None

but login.headers.getSetCookie() return [], why login.headers.getSetCookie() not return the hf-chat cookie?

## Expected Behavior
login.headers.getSetCookie() return hf-chat cookie

## Environment
node v22.6.0

**Comment by Ethan-Arrowood** [comment]
Undici's fetch implementation is spec compliant and behaves the same as the browser does. This means the set-cookie header is remove from any user facing interfaces. See the warning here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie for more information.

I recommend switching to `undici.request()` for server-side based requests.

**Comment by KhafraDev** [comment]
There could be a few reasons:
- undici has no cookie jar, you have to manage cookies yourself. For example, if you're making a request prior to that one that sends a `set-cookie`, you have to set the `cookie` header in every subsequent request.
- The server might be trying to prevent malicious requests (I'm assuming this is not meant to be a public api).

**Comment by fancy45daddy** [comment]
> Undici's fetch implementation is spec compliant and behaves the same as the browser does. This means the set-cookie header is remove from any user facing interfaces. See the warning here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie for more information.
> 
> I recommend switching to `undici.request()` for server-side based requests.

no, if i use other api on the same website. i can get the cooki

**Comment by fancy45daddy** [comment]
> > Undici's fetch implementation is spec compliant and behaves the same as the browser does. This means the set-cookie header is remove from any user facing interfaces. See the warning here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie for more information.
> > I recommend switching to `undici.request()` for server-side based requests.
> 
> no, if i use other api on the same website. i can get the cooki



> There could be a few reasons:
> 
> * undici has no cookie jar, you have to manage cookies yourself. For example, if you're making a request prior to that one that sends a `set-cookie`, you have to set the `cookie` header in every subsequent request.
> * The server might be trying to prevent malicious requests (I'm assuming this is not meant to be a public api).

do you actually test my code? I know the theory. I want to know why the theory not working in my specific case

**Comment by KhafraDev** [comment]
We are not employees at huggingface.co.
