### ISSUE TITLE
Missing bytes() mixin in response.body from request method

### ISSUE THREAD

**Issue by Hamper** [nodejs/undici#3449]
## Bug Description

The response.body object returned from the request method is missing the bytes() mixin that is supposed to be present according to the documentation.

## Reproducible By

```js
import { request } from 'undici'; 
const res = await request('some url');
await res.body.bytes() // no bytes method here
```

**Comment by KhafraDev** [comment]
It was added in https://github.com/nodejs/undici/commit/db8e6422f3f3d4ff2dfd4742a0e39974618bdd8b
