### ISSUE TITLE
how to use maxRedirections in fetch api

### ISSUE THREAD

**Issue by fancy45daddy** [nodejs/undici#3452]
I have a request to control the number of fetch.

the request will be redirect 4 times. If I use {redirect:'manual'}, it just jump to the next direct. If I do not set redirect, I jump to the last redirect. My I need to go to the the third redirect to receive set-cookie. I see there is an argument maxRedirections, but where this argument should go to?

await globalThis.fetch(url, {maxRedirections:2}) is not working. It just goes to the last redirect.
I also try
globalThis.fetch(url, {dispatcher:new globalThis[globalThis.Symbol.for('undici.globalDispatcher.1')].constructor({maxRedirections:2}))}) still not working. It just goes to the last redirect.

**Comment by KhafraDev** [comment]
fetch does not rely on the underlying undici logic for handling redirects, instead it follows the [fetch](https://fetch.spec.whatwg.org/#http-redirect-fetch) standard which does not allow setting the maximum number of redirects (which is 20).

You can use undici.request as an alternative.
