### ISSUE TITLE
ProxyAgent ignore & skip & rewrite "connect" parameter 

### ISSUE THREAD

**Issue by professrr** [nodejs/undici#3481]
## Bug Description

When I pass `new ProxyAgent({ uri, connect })` to `dispatcher` option of `undici.request` the connect parameter ignored in ProxyAgent

## Reproducible By

```js
undici.request(url, {
        bodyTimeout,
        body,
        headers,
        headersTimeout,
        method,
        query,
        throwOnError: true,
        dispatcher:
            new ProxyAgent({
              uri: proxy.uri,
              /** This entire connect will be skipped and ignored: */
              connect: {
                signal: AbortSignal.timeout(1000),
                timeout: bodyTimeout,
              },
              headers: {
                'Proxy-Authorization': `Basic ${Buffer.from(
                  `${proxy.username}:${proxy.password}`,
                ).toString('base64')}`,
              },
            })
      });
```

## Expected Behavior

It's necessary to pass `connect.signal`  option to ProxyAgent to use AbortSignal.timeout(1000) and do not wait 30 seconds every time when failed request

## Logs & Screenshots

That's how I perform request:

<img width="704" alt="Screencapture" src="https://github.com/user-attachments/assets/6535e427-14c0-487a-9456-988bec4cacba">

## Environment

MacOS 14.1.1 (23B81) Sonoma,
Node v21.6.2

### Additional context

I found the issue. Look to 60-70 lines in proxy-agent.js . When we set `this[kAgent] = new Agent({...opts, connect: () => {}})` the `opts.connect` will be ignored and rewrited by `connect: () => {}`

<img width="538" alt="Screencapture" src="https://github.com/user-attachments/assets/039006ed-24b9-4293-9fdb-9aca26a1adaf">

**Comment by Uzlopak** [comment]
Seems like you need to set the options into proxyTls and requestTls

![image](https://github.com/user-attachments/assets/4b55f4f4-393f-4135-858b-b4000e270bc5)

**Comment by Uzlopak** [comment]
Closing as it is actually documented accordingly.
