### ISSUE TITLE
how to disable globaldispatcher? potential source of error in our unit tests

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#3517]
I was testing #3495 with the undici repo and in node 18 and 20 the test passed. but in node 22 the test failed, by pointing to the core version of undici. Of course the global dispatcher should be globally active. But in this case it actually could mean, that we wont see regressions because we use the global dispatcher of core and not the dispatcher from our package/ repo. 

We need to ensure, that our tests not use the globaldipsatcher from core.

**Comment by metcoder95** [comment]
Just to confirm I'm getting it right; do you mean that we should ensure `fetch` tests from core uses the actual intended dispatcher and not the global?

**Comment by Uzlopak** [comment]
Ok, i tested it with a modified borp and could not find any obvious bug. As a result I have created some PRs, but the most important one is #3684
