### ISSUE TITLE
Unable to access base `Event` properties from `CloseEvent`, `ErrorEvent` & `MessageEvent` for WebSocket

### ISSUE THREAD

**Issue by eXhumer** [nodejs/undici#3524]
## Bug Description

[`MessageEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent) inherits [`Event`](https://developer.mozilla.org/en-US/docs/Web/API/Event) and is supposed to provide the properties of `Event` such as `Event.type` and `Event.timeStamp` to `MessageEvent`. However, any class inheriting `Event` (`CloseEvent`, `ErrorEvent` & `MessageEvent`) fails to make any of the base properties accessible and causes the typescript compiler to fail unless `MessageEvent` type gets replaced by `any` when trying to access the base event properties.

## Reproducible By

The following code is successfully compiled by tsc compiler.

```
const ws = new WebSocket('ws://localhost:8080');

ws.onmessage = (ev) => {
  const e = ev as any;
  console.log(e.type);
  console.log(e.defaultPrevented);
  console.log(e.cancelable);
  console.log(e.timeStamp);
};
```

The following code will throw an error while trying to compile with tsc due to `Property '' does not exist on type MessageEvent<any>`.

```
const ws = new WebSocket('ws://localhost:8080');

ws.onmessage = (e) => {
  console.log(e.type);
  console.log(e.defaultPrevented);
  console.log(e.cancelable);
  console.log(e.timeStamp);
};
```

## Expected Behavior

Base properties of `Event` class accessible from inherited classes.

## Logs & Screenshots

_None_

## Environment

macOS 15.1 Beta (24B5035e), node v22.6.0, undici v6.19.8

**Comment by mcollina** [comment]
@KhafraDev @Uzlopak @panva wdyt?

**Comment by panva** [comment]
I don't follow, the types are set up to inherit from `Event` all the same.

https://github.com/nodejs/undici/blob/cab60114da8bf9acc6628daff2ab58f06856bbc9/types/websocket.d.ts#L85-L89

https://github.com/nodejs/undici/blob/cab60114da8bf9acc6628daff2ab58f06856bbc9/types/websocket.d.ts#L135-L141

https://github.com/nodejs/undici/blob/cab60114da8bf9acc6628daff2ab58f06856bbc9/types/websocket.d.ts#L104-L120

**Comment by eXhumer** [comment]
I think the problem lies in `undici/types/patch.d.ts`, where the Event type is defined with the following.

https://github.com/nodejs/undici/blob/5f81898e1dc3e6ac50c85c2e17ba8f1f04f5057d/types/patch.d.ts#L25-L26

The `{ Event: infer T }` infers the type as `any`.

**Comment by KhafraDev** [comment]
Some history of why it was added: https://github.com/nodejs/undici/issues/1740

Is there an easy workaround? Is this even needed anymore? @Ethan-Arrowood @andrewbranch

**Comment by eXhumer** [comment]
I did a bit more digging, I think I figured out what the exact issue is. With the type inference being used, typescript infers the following `Event` type from `node_modules/typescript/lib/lib.dom.d.ts` instead of the correct type from `node_modules/@types/node/dom-events.d.ts`.

```typescript
declare var Event: {
    prototype: Event;
    new(type: string, eventInitDict?: EventInit): Event;
    readonly NONE: 0;
    readonly CAPTURING_PHASE: 1;
    readonly AT_TARGET: 2;
    readonly BUBBLING_PHASE: 3;
};
```

If you try accessing the readonly values, typescript will incorrectly think they are actually there and not complain when trying to access a non-existent property.

```typescript
import { WebSocket } from 'undici';
import { WebSocketServer } from 'ws';

const wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.send('something');
});

const ws = new WebSocket('ws://localhost:8080');

ws.onmessage = e => {
  console.log('e.NONE', e.NONE);
  console.log('e.CAPTURING_PHASE', e.CAPTURING_PHASE);
  console.log('e.AT_TARGET', e.AT_TARGET);
  console.log('e.BUBBLING_PHASE', e.BUBBLING_PHASE);
  console.log('e.data', e.data);
};

process.on('SIGINT', () => {
  console.log('Closing WebSocket server');
  wss.close();
  process.exit();
});
```

Console output

```
➜  node-network-app git:(main) ✗ yarn tsc
yarn run v1.22.22
$ /Users/exhumer/Projects/node-network-app/node_modules/.bin/tsc
✨  Done in 0.75s.
➜  node-network-app git:(main) ✗ yarn ts-node src/index.ts
yarn run v1.22.22
$ /Users/exhumer/Projects/node-network-app/node_modules/.bin/ts-node src/index.ts
e.NONE undefined
e.CAPTURING_PHASE undefined
e.AT_TARGET undefined
e.BUBBLING_PHASE undefined
e.data something
^CClosing WebSocket server
```

**Comment by eXhumer** [comment]
I have found a fix by first getting rid of the default DOM types provided by typescript with setting `{"lib": ["ES2016"]}` in `typescript.json`. And then getting rid of the contents of`Event` type provided in `patch.d.ts`. typescript now correctly imports the DOM `Event` type from `@types/node`. VSCode provides the correct typehints and the tsc compiler works as expected.

**Comment by eXhumer** [comment]
undici is currently at [`node@>=18.17`](https://github.com/nodejs/undici/blob/9639f180d62c47d081fc931f9d60185256184af6/package.json#L128) after support for [`node@<18.17` was dropped with the following commit](https://github.com/nodejs/undici/commit/f90c16155d8c87c0d8cc1bdf46b553e8aef144a5). Based on the comments from @KhafraDev [here](https://github.com/nodejs/undici/issues/1740#issuecomment-1306082678), this patched `Event` type seems to have been added for support for node@16, which is no longer supported. I am not sure if there is any point in the patched `Event` type at the very least.

`patch.d.ts` was added in as a part of [this commit](https://github.com/nodejs/undici/commit/93fd794d3925fba56818350387d0729ebe148826) when the supported engine was [`node@>=12.18`](https://github.com/nodejs/undici/blob/93fd794d3925fba56818350387d0729ebe148826/package.json#L101).

**Comment by eXhumer** [comment]
Looking into PR #1690, there was a lengthy discussion with SimenB and other members about the `DOMException` type and it's availability.

After which a new PR (#1762) was later opened which added the `patch.d.ts` as part of a type fix.

**Comment by eXhumer** [comment]
Confirmed issue to be fixed with the `Event` & `EventTarget` removed from `patch.d.ts`.
