### ISSUE TITLE
option to disable keepAlive

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#353]
Add a `keepAlive: Boolean` option to `Client` which disables keep alive behavior and always sets `[kReset]: true`.

**Comment by szmarczak** [comment]
@ronag What's the thinking behind this? I thought that forcing `keepAlive` to `true` was a good solution.

**Comment by ronag** [comment]
>  I thought that forcing keepAlive to true was a good solution.

I don't follow? You might have cases where you don't want a keep alive connection e.g. due to known issue with the target server.

**Comment by szmarczak** [comment]
https://github.com/nodejs/undici/tree/v1.0.0#new-undiciclienturl-opts

> Keepalive is enabled by default, and it cannot be turned off.

> You might have cases where you don't want a keep alive connection e.g. due to known issue with the target server.

Apart from the HEAD request issues, what would those be? I'm just trying to understand your reasoning :)

**Comment by ronag** [comment]
> Keepalive is enabled by default, and it cannot be turned off.

yea, that's confusing

> I'm just trying to understand your reasoning :)

Fair question. I don't have a good answer other than what I gave.

**Comment by szmarczak** [comment]
> yea, that's confusing

I mean that was version v1.0.0

> I don't have a good answer other than what I gave.

Well, TBH I don't mind having an option that defaults to `true`.

**Comment by ronag** [comment]
> Well, TBH I don't mind having an option that defaults to true.

That's the current way. So I guess we are good 😄.

**Comment by delvedor** [comment]
My fault, I forgot to update that part of the docs 😅
