### ISSUE TITLE
Support 407 status

### ISSUE THREAD

**Issue by zdm** [nodejs/undici#3539]
## Bug Description

When server replies with `407 Proxy Authentication Required` undici replaces it with `500 Internal Server Error`.

Need to show real status and reason.

**Comment by eXhumer** [comment]
You have repro? I am getting 407 as expected on my end.

`server.js`
```javascript
const http = require('http');

const port = 3000;

const server = http.createServer((req, res) => {
  // Set the status code to 407
  res.writeHead(407, {'Content-Type': 'text/plain'});
  
  // Write a message in the response body
  res.end('407 Proxy Authentication Required');
});

server.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
});

process.on('SIGINT', () => {
  server.close(() => {
    console.log('Server closed');
    process.exit(0);
  });
});
```

`client.js`
```javascript
const undici = require('undici');

const port = 3000;

undici
  .request(`http://localhost:${port}`)
  .then(async res => {
    console.log('statusCode', res.statusCode);
    console.log(res.headers);
    for await (const data of res.body) {}
  });
```

Client console output
```
➜  test-issue git:(main) ✗ node client.js
statusCode 407
{
  'content-type': 'text/plain',
  date: 'Tue, 03 Sep 2024 03:40:49 GMT',
  connection: 'keep-alive',
  'keep-alive': 'timeout=5',
  'transfer-encoding': 'chunked'
}
```

**Comment by zdm** [comment]
Yes. It throws an error on 407. Why?

```
import net from "node:net";

const server = new net.Server();

server.on( "connection", socket => {
    socket.end( "HTTP/1.1 407 Proxy Authentication Required\r\n\r\n" );
} );

server.listen( 80, "127.0.0.1" );

const res = await fetch( "http://127.0.0.1/" );

console.log( res.status );

```

**Comment by eXhumer** [comment]
Appears to be `fetch` specific issue. The error is thrown with the following.

https://github.com/nodejs/undici/blob/8d28413b33019f80847faed1a37976e70dc6c78e/lib/web/fetch/index.js#L1620-L1625

**Comment by zdm** [comment]
Is it correct, how we should know, that auth is required?

**Comment by zdm** [comment]
What is `request.window`?

**Comment by eXhumer** [comment]
This appears to first throw a normal `Error` out, which for some reason seems to get picked up as a `TypeError`, preventing access to the original network `Error`.

```
TypeError: fetch failed
    at Object.fetch (/Users/exhumer/Projects/test-issue/node_modules/undici/index.js:112:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  [cause]: Error
      at makeNetworkError (/Users/exhumer/Projects/test-issue/node_modules/undici/lib/web/fetch/response.js:348:9)
      at httpNetworkOrCacheFetch (/Users/exhumer/Projects/test-issue/node_modules/undici/lib/web/fetch/index.js:1624:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async httpFetch (/Users/exhumer/Projects/test-issue/node_modules/undici/lib/web/fetch/index.js:1139:33)
      at async /Users/exhumer/Projects/test-issue/node_modules/undici/lib/web/fetch/index.js:591:16
      at async mainFetch (/Users/exhumer/Projects/test-issue/node_modules/undici/lib/web/fetch/index.js:575:16)
}
```

My best suggestion is to wait for someone from undici's maintainer to reply as they have better understanding of the implementation.

**Comment by eXhumer** [comment]
`request.window` initially appears to be set to `client`, which is later modified with the following to `no-window`.

https://github.com/nodejs/undici/blob/8d28413b33019f80847faed1a37976e70dc6c78e/lib/web/fetch/index.js#L433-L442

Is there any specific reason why an network error reason is not provided with `request.window === 'no-window'` with status code 407 handling?

**Comment by eXhumer** [comment]
To my knowledge, this is the fetch standard working as expected. My best suggestion is to use [`undici.ProxyAgent`](https://undici.nodejs.org/#/docs/api/ProxyAgent) for proxy handling.

It's just odd that the fetch spec just tells to return a generic error with `request.window === 'no-window' && response.status === 407`

**Comment by zdm** [comment]
I am using proxy agent, but need to know the reason of the error.

Ok. if this is a fetch standard - we can't change it and this issue can be closed.

**Comment by KhafraDev** [comment]
> It's just odd that the fetch spec just tells to return a generic error with request.window === 'no-window' && response.status === 407

Browsers will show a login box for the user to enter their creds and then retry the request. Node can't do this because there's no gui (or a "window"). There isn't a good alternative way of handling this in a node app.
