### ISSUE TITLE
Failed to load url undici/types/readable

### ISSUE THREAD

**Issue by sgohlke** [nodejs/undici#3555]
## Bug Description

I tried to create a new class that extends `BodyReadable`. When I try to run a vitest test I get the following error:
`Error: Failed to load url undici/types/readable (resolved id: undici/types/readable) in .../undici-issue/src/index.ts. Does the file exist?` 

Implementation:
```typescript
import { BodyMixin } from "undici";
import BodyReadable from "undici/types/readable";

export class TestResponseBody extends BodyReadable implements BodyMixin {
    declare body: never
    constructor(bodyAsString: string) {
        super()
        this.push(bodyAsString)
    }
}
```

## Reproducible By

Repo for this issue: https://github.com/sgohlke/undici-issue

1. Checkout repo and install dependencies
2. Run tests (npm run test)

## Expected Behavior

Import for `BodyReadable` should be working.

## Environment

Windows 11 Home 23H2, Node v20.17.0, undici@6.19.8

**Comment by Uzlopak** [comment]
Why is the file extension missing?  Set it to .js and it should work.

**Comment by Uzlopak** [comment]
Why do you load types? Load from the right folder. But i dont think you can load it, because it is cjs. But you can try. It is in lib/api/readable.js.
