### ISSUE TITLE
Invalid keepAliveInitialDelay default value

### ISSUE THREAD

**Issue by zdm** [nodejs/undici#3611]
## Bug Description

In documentation default value for `keepAliveInitialDelay` is `60000`, but in `buildConnector` code is `60e3`.

**Comment by Uzlopak** [comment]
![image](https://github.com/user-attachments/assets/6a70c887-adf8-4b01-99fa-5995e64976b9)

**Comment by zdm** [comment]
Ah, sorry, i thought it 60`8`3
