### ISSUE TITLE
Undici throws timeout errors related to the number of connections

### ISSUE THREAD

**Issue by juanibiapina** [nodejs/undici#3617]
## Bug Description

Undici throws timeout errors related to the number of connections.

## Reproducible By

I was able to reduce the code to this:

```js
import { fetch, Agent } from 'undici';

async function main () {
  const url = 'https://via.placeholder.com/150';
  const agent = new Agent({
    connections: 1000, // Number of connections set here
  });
  const numberOfRequests = 5000;

  for (let i = 0; i < numberOfRequests; i++) {
    fetch(url, { dispatcher: agent })
      .then(async response => {
        // I also have a version with the following line when the URL is JSON
        // await response.json();
        console.log("done");
      });
  }
};

main();
```

## Expected Behavior

I expect this to work, but instead I get a connect timeout error:
```
TypeError: fetch failed
    at fetch (/home/juan/workspace/juanibiapina/sandbox/node_modules/undici/index.js:112:13)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at runNextTicks (node:internal/process/task_queues:69:3)
    at process.processImmediate (node:internal/timers:459:9) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/home/juan/workspace/juanibiapina/sandbox/node_modules/undici/lib/core/connect.js:190:24)
      at /home/juan/workspace/juanibiapina/sandbox/node_modules/undici/lib/core/connect.js:133:46
      at Immediate._onImmediate (/home/juan/workspace/juanibiapina/sandbox/node_modules/undici/lib/core/connect.js:174:9)
      at process.processImmediate (node:internal/timers:491:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

Node.js v22.8.0
```

## Environment

- NixOS: works up to 10 connections, fails consistently beyond 12
- MacOS: works up to around 500 connections, fails beyond that

Both computers are running on the same network, and kernel limits and other things are all very high. I think I've correctly ruled out IPv4 VS IPv6 issues as well.

### Additional context

When I set a high connect timeout, everything works as expected. However, my understanding is that I shouldn't need to adjust the connect timeout manually if Undici is managing the connection pool. In fact, when connections is 1, I don't get a timeout even though the script takes a long time to finish and many connections must be certainly waiting. Could you confirm if I’m interpreting this correctly?

Cheers

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that isolates the problem?

I'm trying to reproduce it without any luck.

If you are facing a connect timeout, most likely is the server throttling your connections (possibly load shedding, depending on the network layer).

Depending on what API are you using from `undici`, you are correct in assuming the connection pool is handled by undici.
Here really seems a networking issue rather than undici's one

**Comment by juanibiapina** [comment]
@metcoder95 Thanks for trying to reproduce it! I've now updated the code block to make fail consistently on all systems I've tried. I'll have access to more systems and a different network soon to continue testing.

**Comment by metcoder95** [comment]
If is possible to isolate it by providing the server code as well that help us reproduce it, that will be the best.

I've tried once more without luck. My only guess is that there's some throttling happening at either host or network level that might be affecting the connection and leads to the timeout, but cannot say truly without being able to reproduce it

**Comment by Uzlopak** [comment]
so far, with external server

```js
'use strict'

const { tspl } = require('@matteo.collina/tspl')
const { describe, test, after } = require('node:test')
const { Agent, fetch } = require('..')

describe('https://github.com/nodejs/undici/issues/3617', () => {
  test('FastTimers', async (t) => {
    t = tspl(t, { plan: 5000 })

    const url = 'https://via.placeholder.com/150';
    const agent = new Agent({
      connections: 1000, // Number of connections set here
    });
    const numberOfRequests = 5000;
  
    for (let i = 0; i < numberOfRequests; i++) {
      fetch(url, { dispatcher: agent })
        .then(async response => {
          // I also have a version with the following line when the URL is JSON
          // await response.json();
        })
        .catch(err => {
          console.error(err);
        });
    }

    await t.completed
  })

})

```

**Comment by juanibiapina** [comment]
Thank you for your effort. I tested it on a different network and could no longer reproduce the issue, so I'm fine with closing this for now.

For reference, my next hypothesis is that the DNS server might be causing the problem. The logs suggest that it's resolving the address for every request, which could potentially lead to the issue.

**Comment by tjoseph-ltg** [comment]
Hi guys, 

What's the process of finding out what version of Node.js this or any other fix related to `UND_ERR_CONNECT_TIMEOUT` would be in?
