### ISSUE TITLE
dns tests fail out of the box

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#3646]
I have a freshly installed setup.  And it seems that the tests expect ipV6 for localhost but i have ipv4?

@metcoder95

**Comment by metcoder95** [comment]
I remember having troubles with it, I believe was Windows or Ubuntu, the order of the DNS results is the culprit; in which platform are you having the issue?

**Comment by Uzlopak** [comment]
Ubuntu 24.04 and latest nodejs 22.9.0.

**Comment by Uzlopak** [comment]
nevermind. it fails on old node 18 versions, here 18.19.1
