### ISSUE TITLE
client[kMaxHeadersSize] is undefined, fetch failed in NW.js

### ISSUE THREAD

**Issue by skylarmt** [nodejs/undici#3652]
## Bug Description

When running NW.js, the Node context can't fetch.  I've traced the error back to [this line](https://github.com/nodejs/undici/blob/ae18f0e7dade688849a15e1c331a2d0c8e252ca1/lib/dispatcher/client-h1.js#L204), where an `assert` fails because `client[kMaxHeadersSize]` is undefined.  Commenting out this assertion in the Chromium devtools sources tab causes fetch to work normally.

## Reproducible By

1. Download and unpack the NW.js SDK runtime from https://nwjs.io.
2. Create a `package.json` file in the runtime folder with the contents `{"name": "test", "main": "index.html"}`.
3. Create a `index.html` file with any content (such as `<h1>Hello world</h1>`).
4. Run `nw` from the runtime.
5. Right-click in the window that appears, click `Inspect background page`.
6. In the console, run `fetch("any-url-here")`.  It will fail.
7. In the console stack trace, click the link in `at new Parser (node:internal/deps/undici/undici:7214:9)`.
8. Comment out the `assert`, press Ctrl-S.
9. Re-run step 6.  The fetch succeeds without error.

## Expected Behavior

It should work.

## Environment

Ubuntu 22.04.4, NW.js 0.89

**Comment by metcoder95** [comment]
This seems an issue related to `NW.js`. I'd suggest to open an issue with them.

If not `maxHeaderSize` passed through the configuration options, we fallback to `node:http` default; if this still `undefined` after that check, it means `NW.js` might not be supporting the `node:http` module.

**Comment by skylarmt** [comment]
Perhaps if the fallback to `node:http` fails, it could fall back to a sane default value for `maxHeaderSize` instead of crashing.  This seems like an easy fix that would increase compatibility.

**Comment by metcoder95** [comment]
The fact that its in sync with `node:http` maxHeaderSize value, allows the implementer to manage this value as well through [`--http-max-header-size`](https://nodejs.org/api/cli.html#--max-http-header-sizesize) cli flag.

I'd say that is something that should also be flagged on NW.js, as again, is not really an `undici` issue but rather `NW.js` bug.
