### ISSUE TITLE
Instructions on proper cleanup when using fetch()

### ISSUE THREAD

**Issue by laurisvan** [nodejs/undici#3653]
## This would solve...

Undici documentation could be more exact on the cleanup of resources allocated by `fetch()`. The documentation mentions [Specification Compliance regarding garbage collection](https://undici.nodejs.org/#/?id=garbage-collection) that Undici expects the response body to be consumed but no mentioning on how to best consume them in different cases. This leaves uncertainty on how to best cleanup body and if there might be other resources to be cleaned up (and how) in case of 1) successful responses, 2) HTTP errors (e.g. responses with non-200 status codes) and 3) in cases fetch throws an error. 

## The implementation should look like...

A simple snippet on proper cleanup of resources would build confidence that we have done the cleanup properly.

## Additional context

In our cases, specifically, connected services may return garbled responses with fully valid status codes. Therefore we would not like to consume the body at all, but cancel it with `await response.body?.cancel()`. This seems to work alright, but it still leaves us questions whether some cleanup would be needed in case fetch throws an error. There might be some other cases, as well, that we are unaware of.

**Comment by mcollina** [comment]
Only for 1 it's needed, and in latest versions it should not be needed at all. However by consuming the body you make undici job easier, so your application will be faster.
