### ISSUE TITLE
WebSocket: "close" is not emitted on error

### ISSUE THREAD

**Issue by kettanaito** [nodejs/undici#3697]
## Bug Description

When a WebSocket connection is closed due to an error, the `close` event doesn't get emitted. 

## Reproducible By

Run this in Node.js REPL (assumes `undici` is installed):

```js
const { WebSocket } = require('undici')

let ws = new WebSocket('wss://example.com/non-existing-url')
ws.onerror = () => console.log('ERROR!')
ws.onclose = () => console.log('CLOSE!')
```

## Expected Behavior

The WebSocket instance must dispatch two events in the following order:

```
ERROR!
CLOSE!
```

## Actual behavior

It doesn't. Only the error event gets dispatched. The close event never gets dispatched, which I believe to be incorrect. 

```
ERROR!
```

## Logs & Screenshots

I can also verify that the browser implementation of WebSocket behaves correctly:

![Screenshot 2024-10-07 at 11 38 33](https://github.com/user-attachments/assets/40de2924-4cf7-4c07-a8cd-19b1707c09e4)

## Environment

I believe the environment is irrelevant here. 

- undici 6.6.2

### Additional context

- [WHATWG WebSocket standard: Closing connections](https://websockets.spec.whatwg.org/#closeWebSocket)
- [WebSocket `error` event on MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/error_event):

> The `error` event is fired when a connection with a WebSocket has been closed due to an error (some data couldn't be sent for example).

**Comment by Uzlopak** [comment]
@KhafraDev

**Comment by kettanaito** [comment]
I'm also open to contributing a fix to this if we conclude that it's indeed an issue! Would appreciate guidance with tests during the code review.

**Comment by Uzlopak** [comment]
@kettanaito 

Imho it was already fixed by @KhafraDev  via #3628 and #3651 .

**Comment by kettanaito** [comment]
Oh, that sounds nice! I'm trying that on Node.js v18, I believe. I'd love to have a backport to that version.

**Comment by KhafraDev** [comment]
backporting to v6 will be difficult because websocket has had significant rewrites

**Comment by kettanaito** [comment]
@KhafraDev, understandable. Is v22 the minimal to use to get this fix then? (Undici v7)

**Comment by KhafraDev** [comment]
@fawazahmed0 I have opened a PR with a fix, thanks.
