### ISSUE TITLE
error in Request constructor does not cleanup body argument

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#370]
Not sure what the correct error mode is. But currently if e.g. an invalid header causes an error to be thrown in the passed body is not destroyed.

Error mode needs to be either fixed or documented.

**Comment by ronag** [comment]
```js
const body = new Readable()
client.stream({ body }, (err) => {
  // UND_ERR_INVALID_ARG
})
```

@mcollina in your opinion where does the responsibility lie in terms of ensuring `destroy()` is called on `body` in the above example?

**Comment by ronag** [comment]
I'm leaning towards making it the users responsibility to cleanup body and any other resource passed as argument upon failure.

**Comment by mcollina** [comment]
I'm not convinced. I think it's safest to destroy it regardless.
