### ISSUE TITLE
onConnectTimeout bug

### ISSUE THREAD

**Issue by zabranskiy** [nodejs/undici#3752]
## Bug Description

`[error] uncaughtException TypeError: Cannot read properties of undefined (reading 'autoSelectFamilyAttemptedAddresses')
    at onConnectTimeout (/usr/lib/node_modules/.../node_modules/undici/lib/core/connect.js:224:28)
    at Immediate.<anonymous> (/usr/lib/node_modules/.../node_modules/undici/lib/core/connect.js:206:11)
    at process.processImmediate (node:internal/timers:491:21)`

undici/lib/core/connect.js file has function onConnectTimeout:

```node
function onConnectTimeout (socket, opts) {
  let message = 'Connect Timeout Error'
  if (Array.isArray(socket.autoSelectFamilyAttemptedAddresses)) { <-- bug in this line
  ...
}
```

socket is undefined when the garbage collector has already freed the WeakRef, which leads to TypeError.

## Reproducible By

It happens rarely on our prod.

## Expected Behavior

No error.

## Environment

Debian 12
nodejs 22.9.0
undici 6.20.0

**Comment by murrayee** [comment]
+1
Is there a solution?

**Comment by murrayee** [comment]
or how do I catch it？

**Comment by KhafraDev** [comment]
@murrayee do you have a reproducible sample of code?

**Comment by SolT31** [comment]
Faced the same issue. Created a [MR](https://github.com/nodejs/undici/pull/3825).
