### ISSUE TITLE
FormData body throws if request is redirected

### ISSUE THREAD

**Issue by DTrombett** [nodejs/undici#3803]
## Bug Description

When sending a `FormData` as body with `request` or `stream`, the request fails if redirected with the following `TypeError`: `The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array`

## Reproducible By

In the following example a `POST` request is made to `http://github.com`, which automatically redirects to `https://github.com`. The issue is reproducible with any other url that triggers a redirect.
```js
import { FormData, request } from "undici";

const body = new FormData();

body.append("hello", "world");
await request("http://github.com", {
	body,
	method: "POST",
	maxRedirections: 1,
});
```

## Expected Behavior

Not sure about the specs but the body should be either redirected or discarded based on the redirect type, without any errors.

## Logs & Screenshots

```shell
node:buffer:776
    throw new ERR_INVALID_ARG_TYPE(
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array
    at Function.byteLength (node:buffer:776:11)
    at AsyncWriter.write (D:\test\node_modules\undici\lib\dispatcher\client-h1.js:1259:24)
    at writeIterable (D:\test\node_modules\undici\lib\dispatcher\client-h1.js:1219:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

## Environment

Windows 11 Home, Node v22.11.0

### Additional context

Tested with various redirect urls and the issue is always reproducible

**Comment by KhafraDev** [comment]
What version of undici are you using?

**Comment by DTrombett** [comment]
I'm pretty sure it's the latest because I had just upgraded but I'll let you know asap

**Comment by KhafraDev** [comment]
This is a bug in v6 that is patched in v7 ([7.0.0-alpha.3](https://www.npmjs.com/package/undici/v/7.0.0-alpha.3)).

**Comment by DTrombett** [comment]
I see, I'll try updating to alpha, thanks!

**Comment by mcollina** [comment]
@KhafraDev do you know which PR?

**Comment by DTrombett** [comment]
It seems that using the alpha the redirect is not followed at all? Not sure if I'm doing something wrong but I'll try to send an example

**Comment by DTrombett** [comment]
```ts
import { request } from "undici";

const data = await request("http://github.com", { maxRedirections: 8 });

console.log(data.statusCode, data.headers.location);```

This logs `301 https://github.com/` while it should log `200 undefined`

**Comment by DTrombett** [comment]
Manually using the RedirectHandler works

**Comment by DTrombett** [comment]
So, as I said above, `maxRedirections` doesn't redirect the request in the latest alpha version so it's impossible to test the same code, but using a `RedirectHandler` I can confirm that the issue is still present

**Comment by KhafraDev** [comment]
`maxRedirections` is ignored unless you are using the redirect interceptor.

**Comment by DTrombett** [comment]
The patch seems not to work with h2:
```js
import { Agent, FormData, interceptors, request } from "undici";

const body = new FormData();

body.append("hello", "world");
await request("http://github.com", {
	dispatcher: new Agent({ allowH2: true }).compose(
		interceptors.redirect({ maxRedirections: 1 }),
	),
	body,
	method: "POST",
});
```
```shell
      throw new ERR_INVALID_ARG_TYPE(
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
    at _write (node:internal/streams/writable:482:13)
    at Writable.write (node:internal/streams/writable:510:10)
    at writeIterable (D:\-\node_modules\undici\lib\dispatcher\client-h2.js:740:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
