### ISSUE TITLE
Use primordials when built for Node.js (e.g. global.WebAssembly)

### ISSUE THREAD

**Issue by tlhunter** [nodejs/undici#3812]
I'm going to try solving this on my own but I figured I'd create an issue to track it. Suggestions for making the change are appreciated!

## This would solve...

I'm working on a side project and one of the things it does is to delete a bunch of globals, such as `global.WebAssembly`. This is fine for all of the internal Node.js modules since they make use of primordials which is essentially caching of JavaScript globals before user code runs.

However the Undici bundled within Node.js throws an error.

Ideally it would be possible to delete most of the globals and Undici would be as stable as the other Node.js internal modules.

## The implementation should look like...

Matteo suggested this change could be made as part of the build step when building Undici for Node.js. I think it can be solved with dependency injection. `WebAssembly` and any other globals that Undici depends on can be passed in. Perhaps the Undici code can be wrapped in a function like what Node.js does to inject `__filename` into CJS files. Maybe like this:

```js
function primordialInjectionWrapper(WebAssembly, Foo, Bar) {
  // existing Undici code
}
primordialInjectionWrapper(primordials.WebAssembly, primordials.Foo, primordials.Bar);
```

## I have also considered...

I suppose I could not delete all the globals in my silly side project. And notably this is not an issue with real applications. And I don't think there is any security benefits as one could still mutate `WebAssembly` later even if Undici is using a version that is pulled from the global early on.

## Additional context

Here's a repro:

```
$ cat undici-primordial.js
delete global.WebAssembly
void Request;
$ node undici-primordial.js
node:internal/deps/undici/undici:5771
        mod = await WebAssembly.compile(llhttpWasmData || require_llhttp_wasm());
        ^

ReferenceError: WebAssembly is not defined
    at lazyllhttp (node:internal/deps/undici/undici:5771:9)
    at lib/dispatcher/client-h1.js (node:internal/deps/undici/undici:5817:25)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/dispatcher/client.js (node:internal/deps/undici/undici:7507:21)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/dispatcher/pool.js (node:internal/deps/undici/undici:7968:18)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/dispatcher/agent.js (node:internal/deps/undici/undici:8051:16)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/global.js (node:internal/deps/undici/undici:8151:17)

Node.js v23.1.0
```

**Comment by KhafraDev** [comment]
It might fix deleting globals, but someone could still `delete Array.prototype.push` and break undici? I am not sure what this would solve.

**Comment by ronag** [comment]
I don't see what this solves

**Comment by tlhunter** [comment]
I suppose it's mostly just an interesting inconsistency that when deleting globals the only internal Node.js module that has errors seems to be Undici / fetch. Presumably there's a reason the other internal Node.js modules avoided the issue with the use of primordials and that reason might also apply to Undici.

> It might fix deleting globals, but someone could still delete Array.prototype.push and break undici? I am not sure what this would solve.

I think the primordials concept takes care of that by caching many of the methods available on built-ins such as Array:

https://github.com/nodejs/node/blob/a094a8166cd772f89e92b5deef168e5e599fa815/lib/internal/per_context/primordials.js#L41
https://github.com/nodejs/node/blob/a094a8166cd772f89e92b5deef168e5e599fa815/doc/contributing/primordials.md?plain=1#L55-L92

E.g.
```js
const array = [1, 2, 3];
ArrayPrototypePush(array, 4);
```

That said, while injecting the globals via a wrapper function might be straightforward, coming up with a tool to transform `array.push(1)` into `ArrayPrototypePush(array, 1)` during the build process might be impossible.

**Comment by tlhunter** [comment]
> Fortunately, undici can't use primordial since it's not developed in core.

Here's an example of how primordials could be injected: https://github.com/nodejs/node/pull/55783

**Comment by ronag** [comment]
Primordials in undici won't happen. Sorry. Feel free to fork if you think it's important.

**Comment by tlhunter** [comment]
So far it looks like this can all be done on the Node.js side so I'll close this issue.
