### ISSUE TITLE
Accept HTTP/2 headers

### ISSUE THREAD

**Issue by benmccann** [nodejs/undici#3818]
## This would solve...

HTTP/2 requests to SvelteKit can fail with errors like `":method" is an invalid header name.` We take the incoming request (which may be of varying shapes depending on the platform - node, bun, cloudflare, vercel, netlify, etc.) and put it into an undici `Request` with `new Request`. This `Request` isn't being used to issue a `fetch`, but is being used as the `Request`/`Response` interface for users build SvelteKit applications.

Eventually HTTP/2 request headers will have to be accepted by `undici` when implementing support for `h2c`, etc. It would be helpful to update which headers `new Request` accepts now in order to both make that eventual support one step closer to being implemented and to solve this usecase.

## The implementation should look like...

Probably modify the code here:

https://github.com/nodejs/undici/blob/a2f63e7ca606c733998e7477a5074d93202e9f7f/lib/core/util.js#L724-L765

## I have also considered...

We are currently forcing HTTP/2 requests to be downgraded to HTTP 1.1 in many contexts. However, we're not able to apply this everywhere and there are edge cases where requests are broken.

We cannot use a different API because `Request` is the standard that's being implemented by all web platforms and frameworks. It would be incredibly expensive for us to re-implement `Request` in our own project

## Additional context

Issue in the SvelteKit repo: https://github.com/sveltejs/kit/issues/11365

**Comment by KhafraDev** [comment]
> We cannot use a different API because Request is the standard

The standard is why this header isn't accepted. If another platform accepts http2 header names, then they aren't.

**Comment by benmccann** [comment]
Thanks for taking the time to reply. I'm not quite sure I understand though. Can't web browsers make HTTP/2 `fetch` requests? In what way would HTTP/2 headers violate the spec?

**Comment by KhafraDev** [comment]
I am not entirely sure what the issue is; undici (and fetch) supports http2, but follows the spec in regards to what is considered a valid [header name](https://fetch.spec.whatwg.org/#header-name). If the issue is to simply support http2, there is a PR that will soon enable it by default, #3814, but it can also be enabled manually by using the dispatcher api.

```js
import { Agent, setGlobalDispatcher } from 'undici'

const agent = new Agent({ allowH2: true })
setGlobalDispatcher(agent)

// works with both the global fetch and fetch imported from undici
await fetch('...')

// or set it per-request
await fetch('...', { dispatcher: agent })
```

**Comment by ronag** [comment]
@benmccann donyiu have a repro that works in a browser but doesn't work with undici fetch?

**Comment by benmccann** [comment]
Hmm, I guess this API does work as in the browser.

The browser does send a `fetch` request with headers containing `:`

![Screenshot from 2024-11-08 21-00-56](https://github.com/user-attachments/assets/8692ef9a-3d51-4837-a6bb-72be2141a540)

But it seems you can't specify those yourself and only the browser can fill them in. E.g. you get an exception trying to do this:
```
new Request('/', { headers: { ':method': 'POST' }});
```

So I guess I understand where y'all are coming from

Thanks for taking the time to provide the pointers and feedback!

**Comment by dominikg** [comment]
How are you going to plan to support h2c if you don't allow it's pseudo-headers that are defined in an RFC https://www.rfc-editor.org/rfc/rfc9113.html#name-request-pseudo-header-field ?

I am not sure i follow the reasoning behind limiting undici to what current browsers allow on the clientside. most (all?) of the time undici is on the other end, so isn't it natural that a few limitations don't apply/are different?

you could even look into exposing a different Request implementation depending on the `browser` condition if you want to avoid server only features from creeping out.

What do you suggest servers/frameworks do to support h2c if they want to modify incoming requests before passing them along?

**Comment by ronag** [comment]
fetch is a browser spec. Use the non-browser api's if you want non browser behavior.

**Comment by KhafraDev** [comment]
incoming headers: use the interceptor api
outgoing headers: [use the dispatcher api](https://gist.github.com/KhafraDev/af69d9652e93f4e28e139853c818f46b)

**Comment by KhafraDev** [comment]
> What do you suggest servers/frameworks do to support h2c if they want to modify incoming requests before passing them along?

You can use undici's interceptor API along with the dispatcher API similar to what I did above to modify incoming and outgoing headers. The docs are practically non-existent, but one of the [built-in](https://github.com/nodejs/undici/tree/main/lib/interceptor) interceptors should make it easy to understand.
