### ISSUE TITLE
RetryAgent does not support throwOnError: false

### ISSUE THREAD

**Issue by golyshevd** [nodejs/undici#3837]
## Bug Description

`RetryAgent` does not support  `throwOnError: false` option, it always throws `UND_ERR_REQ_RETRY` on retries limit exceeded

## Reproducible By

```ts
import { createServer } from 'node:http';

import { Agent, RetryAgent } from 'undici';

export const retryAgentBug = async (): Promise<void> => {
  const port = 3210;

  await new Promise<void>((accept, reject) => {
    const server = createServer((req, res) => {
      res.statusCode = 500;
      res.setHeader('content-type', 'text/plain');
      res.write('Internal Server Error');
      res.end();
    });

    server.once('error', reject);
    server.listen(port, accept).unref();
  });

  const dispatcher = new RetryAgent(new Agent());

  await dispatcher.request({
    method: 'GET',
    origin: `http://localhost:${port}`,
    path: '/',
    // `UND_ERR_REQ_RETRY` will still be thrown
    throwOnError: false,
  });
};

void retryAgentBug();
```

## Expected Behavior

Expecting `RetryAgent` to support `throwOnError` option as descendant of of `Dispatcher`.
Expecting `RetryAgent.request` to still return `Dispatcher.ResponseData` even if retries limit exceeded

## Logs & Screenshots

<img width="345" alt="image" src="https://github.com/user-attachments/assets/f75c3093-201a-4b62-9173-6f19cbc021e3">

## Environment

Mac OS Sonoma, Node.js v18.18.2, undici@6.20.1

### Additional context

Faced this issue when tried to know how to get backend response's body after N unsuccessful retries.
It could be natively possible if `RetryAgent` was taking into account `throwOnError`

**Comment by golyshevd** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Yes I would. I think I have a solution. But right now I am trying to run tests

Idk why many tests fail even without my changes (on main branch) like that:

<img width="522" alt="image" src="https://github.com/user-attachments/assets/340e9a1d-fe65-4489-bff3-88225d4138a0">

Maybe I did not set something up yet? Exactly these 76 tests fail stable for me

**Comment by mcollina** [comment]
What version are running?

**Comment by golyshevd** [comment]
> What Node.js version are you running, what OSS are you in? Tests are passing here?

```sh
node -v
v18.18.2
```

Tried v22 - tests passed )
Just wrongly assumed that `package.engines.node` is also fine for development

**Comment by golyshevd** [comment]
In main branch (version: 7.0.0-alpha.3) `throwOnError` option was dropped :D 
Now undici never throws http errors

Does it mean now that `RetryAgent` should also never throw an error even if http "error" was retried `maxRetries` times?

I think the issue is not a bug now, but feature request. I still need to get response after retries did not lead to success

**Comment by golyshevd** [comment]
Self closing as incorrect
