### ISSUE TITLE
Support all the `cache` options in `fetch()`

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#3847]
Ref https://developer.mozilla.org/en-US/docs/Web/API/Request/cache.

I _think_ we could add some support for this.

**Comment by mcollina** [comment]
cc @flakey5 @KhafraDev

**Comment by KhafraDev** [comment]
+1 to adding it, but it will not work with the current caching interceptor logic. Pasting part of my comment from [here](https://github.com/nodejs/undici/pull/3842#issuecomment-2484530817):

> In the fetch spec, the http cache is built a layer above fetch, whereas in undici it's a layer below [in the interceptor api]. For example, in multiple parts of the spec we are meant to query the cache directly (see [http-network-or-cache-fetch](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch)). There are multiple situations where headers may get added to requests/responses, or the internal request is modified in some way that will cause bugs or deviate from browser behavior.

**Comment by mcollina** [comment]
https://fetch.spec.whatwg.org/#concept-request-cache-mode doens't imply it's implemented on top. I'm specifically _not_ talking about `CacheStorage`.

> There are multiple situations where headers may get added to requests/responses, or the internal request is modified in some way that will cause bugs or deviate from browser behavior.

Can you clarify this? Why can't we go update the underlining cache?

**Comment by KhafraDev** [comment]
> doens't imply it's implemented on top. I'm specifically not talking about CacheStorage.

I know, but think about it from this perspective - currently the cache is built into the interceptor itself; it accepts an array of buffers as headers and a node stream for its body. To cache fetch responses, you have to store the headers (a HeadersList), a body (web readable), and the internal response state.

The fetch spec calls implementations to update, insert, and delete responses from the cache in the spec itself. If we leave this to the interceptor, there are a number of places where internal response state may be modified, headers get added, etc. that will change how the response is received.

> Can you clarify this? Why can't we go update the underlining cache?

The interceptor cache does not take internal response state into account, and that internal state is also modified between where we are meant to update/insert/delete from the cache and where we are currently doing it (the dispatch). Without taking this into account, things like `referer` headers, etc. will subtly break). AFAIK the cache is tied to the interceptor api currently, and isn't shared outside of it (and if it can, it still leads to the issue of checking the cache in fetch, and then having to re-check it again in the interceptors).

**Comment by mcollina** [comment]
> To cache fetch responses, you have to store the headers (a HeadersList), a body (web readable), and the internal response state.

This is not how I read the spec in https://fetch.spec.whatwg.org/#concept-request-cache-mode. There is no real connection to `HeadersList` and `Readable`, but every object is freshly created.

**Comment by KhafraDev** [comment]
> There is no real connection to HeadersList and Readable

Of course you can convert the HeadersList to and from an array of buffers and web readables to node readables (and vice versa), but what I'm getting at is that fetch has different requirements to cache than the interceptor api.

**Comment by mcollina** [comment]
> ...but what I'm getting at is that fetch has different requirements to cache than the interceptor api.

I can only see fetch having _additional_ requirements, not _different_. If they were different, it would mean that the fetch() spec does not follow RFC 9111, which sound highly unlikely.

**Comment by metcoder95** [comment]
Do you have something in mind in specific @KhafraDev?
Or what are you proposing to achieve it?

**Comment by KhafraDev** [comment]
> I can only see fetch having additional requirements, not different.

Maybe my phrasing wasn't the best 😄.

> Or what are you proposing to achieve it?

We need the following:
- an interface to insert, update, and delete cache entries directly (not through an interceptor -- similar to MemoryCacheStore). the issue is that it currently only works for node streams and undici headers (arrays of buffers). currently MemoryCacheStore has no way to update, .get(...) return a new object.
- discuss the cache store we use by default in fetch. An in-memory cache is likely a poor choice, browsers typically store the cache on disk. Do we make it configurable, and if so, how?
- discuss how we handle using the cache option with the cache interceptor (should it throw? there may be options that contradict each other)
- do we use a shared cache store for fetch and the interceptor?

**Comment by KhafraDev** [comment]
> The reusability was one of my concerns when designing the API of the current cache store, but definitely can revisit (maybe create a separate one if we made the work after the cut off for v7).

I think it's 95% fine and just missing a little extra that we need. We can convert fetch Headers to raw headers and web streams to node ones easily, so not much of a concern there. Honestly someone would need to start implementing it to see exactly what's missing/lacking. I don't have the time or motivation to do so currently. :(

An example of one of my bullet points above, does this cache the response? Which takes precedence? Will we allow this? My other points are straightforward IMO so examples aren't needed.

```js

const agent = new Agent().compose(interceptors.cache())

await fetch('...', {
  cache: 'no-store',
  dispatcher: agent
})

```

**Comment by mcollina** [comment]
@metcoder95 I don't think you meant to close this.

**Comment by metcoder95** [comment]
oh sorry. my bad 😞
