### ISSUE TITLE
New Hooks API

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#3874]
I am doing another iteration on this. The primary goal is to support pre-parsed headers in handlers. However, just doing that seems a bit wasteful and I'm hoping to take the interface one step forward:

I am thinking of something the following lines:

```ts
interface Controller {
  pause () : void;
  resume () : void;
  abort(err: Error) : void;
  get aborted () : boolean;
  get reason() : Error;
}

type Headers = Record<string, string | string[]>;
type Trailers = Record<string, string | string[]>;

interface Handler {
  onRequestStart(controller: Controller): void;
  // onRequestHeaders(controller: Controller, headers: Headers): Headers;
  // onRequestData(controller: Controller: chunk: Buffer): Buffer;
  // onRequestTrailers(controller: Controller: chunk, trailers: Trailers): Trailers;
  // onRequestEnd(controller: Controller): void;
  // onRequestError(controller: Controller, error: Error): void;
  onResponseStart(controller: Controller, statusCode: number, statusMessage?: string) : void;
  onResponseHeaders(controller: Controller, headers: Headers): void;
  onResponseData(controller: Controller, chunk: Buffer): void;
  onResponseTrailers(controller: Controller, trailers: Trailers): void;
  onResponseEnd(controller: Controller): void;
  onResponseError(controller: Controller, err: Error): void;
}
```

**Comment by ronag** [comment]
@mcollina @flakey5 @ShogunPanda @metcoder95

**Comment by metcoder95** [comment]
Wouldn't be enough to pass the controller in a similar manner as we pass abort on the `onConnect` hook?
Or are we planning to made most of these hooks optional?

What use-cases do you have in mind for most of the `onRequest` hooks (excepting `start` one)?
and, for the request hooks, we are planning to add them before or after the lifecycle happened? (this can maybe open the door for mutating the pieces before actually doing any step of the request).

For the Response ones, lgtm

**Comment by ronag** [comment]
https://github.com/nodejs/undici/pull/3878
