### ISSUE TITLE
with custom agent mockPool.intercepts body is asyncGenerator

### ISSUE THREAD

**Issue by smoebody** [nodejs/undici#3887]
## Bug Description

When setting a custom agent as option for `MockAgent` the `body` property is of type `asyncGenerator` and therefore never matches my source body

## Reproducible By

A minimal example follows
```ts
import { Agent, fetch, setGlobalDispatcher } from "undici";
import { MockAgent } from "undici";

const agent = new Agent();
const mockAgent = new MockAgent({ agent });
const mockPool = mockAgent.get("http://localhost");
setGlobalDispatcher(mockAgent)

mockPool
  .intercept({
    path: "/test",
    method: "POST",
    body: (body) => {
      console.log(body);
      return true;
    },
  })
  .reply(204);

(async () => {
  await fetch("http://localhost/test", {
    dispatcher: agent,
    method: "POST",
    body: "test",
  });
})().then(() => {
  process.exit()
})
```
The output is 

```
Object [AsyncGenerator] {}
Object [AsyncGenerator] {}
```

## Expected Behavior

The output should be 

```
test
```

when removing the `dispatcher` property from the `fetch` call it works as intended (i guess, although `test` is printed twice)

## Environment

Docker-Image: node:22-alpine
Kernel: 6.11.8-300.fc41.x86_64 x86_64 Linux
Node: v22.11.0
undici: 6.21.0

**Comment by KhafraDev** [comment]
A little bit of both:

https://github.com/nodejs/undici/blob/1cfe0949053aac6267f11b919cee9315a27f1fd6/lib/web/fetch/index.js#L2065

We can't detect if an agent is a MockAgent without degrading performance, and the agent passed doesn't have an `isMockActive` property, unlike MockAgent.

**Comment by KhafraDev** [comment]
Ignore my previous answer, fetch's `dispatcher` option takes precedence over the global dispatcher.

```js
await fetch("http://localhost/test", {
    dispatcher: agent,
    method: "POST",
    body: "test",
  });
```

The dispatcher has to be `mockAgent` in this case, or the option has to be unset, in which case it'll fallback to the global dispatcher (being mockAgent).
