### ISSUE TITLE
v7 FormData change causing issue in express app

### ISSUE THREAD

**Issue by xconverge** [nodejs/undici#3896]
## Bug Description

I am receiving a `415: unsupported media type text/plain; charset=utf-8` in my express app when receiving a multipart POST request from undici, this was working fine in v6

This is what my test is sending:

```
  const logoPath = "./data/unittest/logo.png"
  const logoMetadata: ILogoMetadata = { test: 123 }
  const logoBlob = await openAsBlob(logoPath)

  const formData = new FormData()
  formData.append("image", logoBlob)
  formData.append("metadata", JSON.stringify(logoMetadata))

  const addLogoResult = await fetchHelper<IMessage>(
    fetch(`test/logo`, {
      method: "post",
      headers: {
        authorization: xyz,
      },
      body: formData,
    }),
  )
```

Is there anything else I can log/share/show for this?

I also tried 

```
  const logoData = await fs.readFile(logoPath)
  const logoBlob = new Blob([logoData], { type: "image/png" })
```
instead of 
```
const logoBlob = await openAsBlob(logoPath)
```

## Reproducible By

Sending formdata as formatted above

## Expected Behavior

I am not sure what changed but there is something different in the formdata

## Environment

macOS and Ubuntu, node 22

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by xconverge** [comment]
Thank you, you are certainly correct @DTrombett , I was able to see the error with tsc when I ran it on the file manually, I will look into why my project/vscode are not reporting it correctly
