### ISSUE TITLE
Do we need `Pool/Client.close()`

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#391]
I haven't really had a case where I find this useful. Is it worth keeping and maintaining?

**Comment by ronag** [comment]
@mcollina @szmarczak

**Comment by szmarczak** [comment]
Yes, for example when testing. We don't want to run out of ports.

**Comment by ronag** [comment]
@szmarczak We can use `.destroy()` for that?

**Comment by szmarczak** [comment]
Ah, then you're right. Not sure if there's any valid use case for `client.close()`.

**Comment by mcollina** [comment]
The use case is a soft-close vs an hard-close.
In a soft-close state we want the current requests to finish and not error, while not accepting new ones.

This is needed for most graceful shutdown situations.

**Comment by ronag** [comment]
Fair enough.
