### ISSUE TITLE
`destroy(err)` semantics

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#393]
The semantics of `destroy(err)` with `err` is a little bit undefined. What should happen with the error?

Currently only running requests *might* receive the error while pending requests will fail with `ClientDestroyedError`. While in `Pool` pending requests will fail with `err`. It's a bit of a mess.

I'm considering removing the signature with `err` and just have everything fail with `ClientDestroyedError`. Alternatively need to spend some effort and ensure *all* requests fail with the passed `err`.

Thoughts? @mcollina @szmarczak @delvedor

**Comment by szmarczak** [comment]
I'd go for the custom errors approach.

**Comment by ronag** [comment]
> I'd go for the custom errors approach.

Sorry. Which one is that 😄 ? Propagate `err` to all requests properly?

**Comment by ronag** [comment]
Fixed in #392

**Comment by szmarczak** [comment]
> Keep err signature and propagate err to all requests properly?

:+1:
