### ISSUE TITLE
dns interceptor doesn't set port in host header

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#3937]
https://github.com/nodejs/undici/blob/503ad7679118530d8ecdf0f202aad298aab4ec47/lib/interceptor/dns.js#L361

I believe this should be using `host` instead of `hostname`... otherwise we will strip the port...

**Comment by ronag** [comment]
@metcoder95

**Comment by metcoder95** [comment]
Agree, missed that completely 👍
