### ISSUE TITLE
Throwing in `'drain'` handler doesn't always lead to unhandled exception

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#394]

**Comment by zhangwinning** [comment]
could you explanation the question by example,  I'll try to polish the patch and submit a fix PR.

**Comment by ronag** [comment]
So:

```js
const client = new Client(...)

client.on('drain', () => {
  throw new Error() // should always lead to unhandled exception
})
```

Depending on the call stack during `.emit('drain')` the thrown exception might or might not cause a unhandled exception.

**Comment by mcollina** [comment]
It seems Zalgo is here and we have a missing nextTick somewhere.

**Comment by mcollina** [comment]
In other terms, we should not support throwing in event handlers, and it should always go in uncaughtException.

**Comment by zhangwinning** [comment]
> So:
> 
> ```js
> const client = new Client(...)
> 
> client.on('drain', () => {
>   throw new Error() // should always lead to unhandled exception
> })
> ```
> 
> Depending on the call stack during `.emit('drain')` the thrown exception might or might not cause a unhandled exception.
> 
> Alternatively we catch the error and emit `'error'` on the client object or something else. We might also have the same issue with the `'connect'` and `'disconnect'` events.
> 
> The important thing is that the behavior is consistent and documented.
> 
> @mcollina: Wdyt? How should we handle users throwing in event handlers?

Hi @ronag, I think the below code must thrown exception, not throw exception which it ？ 
```
const { Client } = require('.')

const { createServer } = require('http')

let server = createServer((req, res) => {
  res.end('ok')
}).listen(0)

const client = new Client(`http://localhost:${server.address().port}`)

client.on('drain', () => {
  throw new Error()
})

client.emit('drain')

```

**Comment by ronag** [comment]
Sorry I don't understand the question.
