### ISSUE TITLE
Undici requests are suddenly 2x slower.

### ISSUE THREAD

**Issue by nrathi** [nodejs/undici#3943]
## Bug Description

About 48 hours ago, all of our requests via Undici suddenly got 2x slower. We did not redeploy the application, nor actively change anything else. One thing to note is we have a very high volume of requests, to the point where we had to set up dnsmasq about a year ago. This issue reminds me of that one, in the sense that it feels sneakily related to scale. The difference is - once it started, it never stopped - I am not seeing the issue get better in slower periods. 

## Reproducible By

I wish I knew. This is what I've had for months now:
`fetch({...req, dispatcher: new ProxyAgent(proxyUrl), signal: AbortSignal.timeout(PROXY_TIMEOUT)});`

When the error started, I tried to play around with the connections and timeouts. I tried variations of: 

```
    const agent = new ProxyAgent({
      uri: proxyUrl,
      autoSelectFamily: true, // Tried true and false
      connections: 500, // Tried 50, 100, 500
      keepAliveTimeout: 60 * 1000, // Tried 120s
      bodyTimeout: 45 * 1000, // Tried 30s
      headersTimeout: 45 * 1000, // Tried 15s
      allowH2: true, // Tried true and false
      proxyTls: {
        allowH2: true, // Tried true and false
        keepAlive: true, // Tried setting this to true
        timeout: 45 * 1000, // Tried 15s
      },
      requestTls: {,
        allowH2: true, // Tried true and false
        keepAlive: true, // Tried setting this to true
        timeout: 45 * 1000, // Tried 15s
      },
    });
````

I didn't see any impact from any of these changes. I did confirm that my agents are cached properly (I have 2000 proxies), and that the sockets are reused.

## Environment

On my Linux EC2, which Is running Node 21.7.3, I tried both Undici 6.19.8 (old) and 7.1.0 (new). Everything is fast on my Macbook (running the same version of Node & using the same proxies). 

Any advice would be appreciated. I have been banging my head against a wall for 48 hours. 

## Other notes

It is worth noting that I have four integrations: 

One uses Undici + custom proxy => got slower
Two use Undici + third-party proxy => got slower
Last one does not use Undici => no change in speed (fast)

**Comment by nrathi** [comment]
Yes exactly. The third one looks like `fetch(customProxyUrl, body: payloadToUnpack)`, so there's no ProxyAgent. 

My p90 graph is so strange. I have four lines (one per integration), and right around 12/9 2:30pm Eastern, three of them shoot up.

**Comment by nrathi** [comment]
Yeah I did read that request was faster, but I wasn't clear on the limitations. I also wasn't sure about pipelining despite reading a lot about it. 

I'll give that a go. Meanwhile, does this help spark ideas? 

# curl -v -x http://xxx:yyy@p.webshare.io:80 https://httpbin.org/get
*   Trying 00.00.000.000:80...
* Connected to (nil) (00.00.00.000) port 80 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to [httpbin.org:443](http://httpbin.org:443/)
* Proxy auth using Basic with user 'xxx'
> CONNECT [httpbin.org:443](http://httpbin.org:443/) HTTP/1.1
> Host: [httpbin.org:443](http://httpbin.org:443/)
> Proxy-Authorization: Basic yyy
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 200 OK
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate St

This is a curl, using my third-party proxy, and shows the most time is spent in TLS handshaking.

**Comment by nrathi** [comment]
Could there be something in how Undici handles TLS that would be particularly sensitive to EC2 crypto performance?

**Comment by metcoder95** [comment]
If you haven't updated `undici` in the lsat 48hrs is most likely some configuration issue regarding one of your proxies (which seems to be possibly related with TLS negotiation, but hard to guess).

As @PandaWorker stated, without a 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) is a bit hard to help out; nevertheless I'm convinced the problem does not roots to `undici`.

**Comment by nrathi** [comment]
Thanks both. You were right, I tried switching proxy providers and that did the trick. Appreciate your quick response and it was great to learn about configuration options that may help me in the future!
