### ISSUE TITLE
coverage badge

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#397]
Would be nice to have a badge for coverage since we do often land stuff that does not maintain 100 coverage. I usually try to ensure 100 coverage just before a release.

**Comment by RocktimSaikia** [comment]
@ronag Hi, I would like to work on it. If it's open for others!

**Comment by dnlup** [comment]
What service do you prefer? What about https://coveralls.io/?

**Comment by mcollina** [comment]
Note that we need to ask the TSC to add external services. I'm happy to use coveralls if somebody else set it up: unfortunately I have too many repos and my account cannot be opened anymore (that's also a good reason to not use them).

**Comment by dnlup** [comment]
Of course, thank you. I have seen that Node is using https://codecov.io/, maybe they would be more inclined to use that service? Or maybe there could be a way to just add a badge using Actions.

**Comment by mcollina** [comment]
I'm inclined to use codecov as well :).

**Comment by dnlup** [comment]
> I'm inclined to use codecov as well :).

Sorry, you're right 😁

**Comment by dnlup** [comment]
I have a working branch using codecov [here](https://github.com/dnlup/undici/tree/coverage_badge). Is it safe to open a PR?

**Comment by dnlup** [comment]
Link to a report of the same branch:

https://codecov.io/gh/dnlup/undici/branch/coverage_badge

**Comment by mcollina** [comment]
Nice! What would you need to enable this here? Could you just PR it?

**Comment by dnlup** [comment]
> Nice! What would you need to enable this here? Could you just PR it?

To enable just the coverage report with the badge I think it should work just by opening the PR. To enable the full integration it should be installed at the org level I think, but that can be done anytime, if necessary. The full integration should provide comments in PRs.

**Comment by dnlup** [comment]
I'll open a PR
