### ISSUE TITLE
Client.dispatch headers argument as array

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#404]
Allow passing an array as `headers` (i.e. the same format as the output from `dispatch({ onHeaders })`.

e.g.

```js
client.request({
 headers: ['key', 'value', 'key2', 'value2']
})
```

**Comment by ronag** [comment]
@Ethan-Arrowood maybe something for you?

**Comment by Ethan-Arrowood** [comment]
Thank you @ronag! I'd be happy to work on this 😄
