### ISSUE TITLE
Benchmark does not have parallelism

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#405]
The benchmarks don't seem to run any requests in parallel, thus there is no pipelining.

i.e. the results we are getting at the moment are without pipelining.

**Comment by ronag** [comment]
@szmarczak @mcollina

**Comment by szmarczak** [comment]
I don't know of any library that would benchmark concurrently. I guess we need to create a different file for pipeline tests.

**Comment by ronag** [comment]
> I don't know of any library that would benchmark concurrently.

Yea I couldn't find one either :/

**Comment by ronag** [comment]
I tried making the benchmark parallel but I believe there are several problems with how it's implemented. In particular running batches does not provide a realistic result.¨

See, https://github.com/nodejs/undici/issues/467
