### ISSUE TITLE
Unhandled exception on pool.destroy() in 2.0.0

### ISSUE THREAD

**Issue by Lalem001** [nodejs/undici#412]
Sample code: https://runkit.com/embed/fjc3coliu5jk

The above sample is the simplest code I can think of that replicates my scenario. I have tried many variations and I cannot catch the error that occurs. It is breaking my unit tests that were working fine pre 2.0.0.

**Comment by Lalem001** [comment]
Also note that `destroy resolved/rejected` is never shown. The promise appears to hang after `pool.destroy()`. However, I am not able to reproduce this hang in local testing.

**Comment by ronag** [comment]
You need to add a `'error'` handle on the response `body`.

**Comment by ronag** [comment]
```js
await pool
  .request({ method: 'GET', path: '/undici' })
  .then(({ body }) => {
     console.log('hello')
     body.on('error', (err) => console.error(err))
  })
  .catch(console.error)
  .then(() => pool.destroy())
  .then(() => console.log('destroy resolved'))
  .catch(() => console.log('destroy rejected'));
```

**Comment by ronag** [comment]
> Also note that destroy resolved/rejected is never shown. The promise appears to hang after pool.destroy(). However, I am not able to reproduce this hang in local testing.

If you have an unhandled exception it will crash and now show anything further

**Comment by Lalem001** [comment]
> You need to add a `'error'` handle on the response `body`.

Fair enough.

I want to mention that the module I am building is similar to `fastify-reply-from` which was recently upgraded to use Undici 2.0.0. I do not see any effort to attach an error handler to body in its source so I can only presume there will be an unhandled error when Fastify closes.

fastify-reply-from buildRequest: https://github.com/fastify/fastify-reply-from/blob/master/lib/request.js#L56-L64
fastify-reply-from handleUndici: https://github.com/fastify/fastify-reply-from/blob/master/lib/request.js#L95-L116
fastify-reply-from onClose: https://github.com/fastify/fastify-reply-from/blob/master/index.js#L136-L141

**Comment by Lalem001** [comment]
Is there an alternative to destroy for tear down? Should I not tear down at all? As mentioned above my module is pattered after `fastify-reply-from` which is why I was using destroy in the first place.

**Comment by ronag** [comment]
> > You need to add a `'error'` handle on the response `body`.
> 
> Fair enough.
> 
> I want to mention that the module I am building is similar to `fastify-reply-from` which was recently upgraded to use Undici 2.0.0. I do not see any effort to attach an error handler to body in its source so I can only presume there could be an unhandled error when Fastify closes.
> 
> fastify-reply-from buildRequest: [fastify/fastify-reply-from@`master`/lib/request.js#L56-L64](https://github.com/fastify/fastify-reply-from/blob/master/lib/request.js?rgh-link-date=2020-09-11T17%3A45%3A50Z#L56-L64)
> fastify-reply-from handleUndici: [fastify/fastify-reply-from@`master`/lib/request.js#L95-L116](https://github.com/fastify/fastify-reply-from/blob/master/lib/request.js?rgh-link-date=2020-09-11T17%3A45%3A50Z#L95-L116)
> fastify-reply-from onClose: [fastify/fastify-reply-from@`master`/index.js#L136-L141](https://github.com/fastify/fastify-reply-from/blob/master/index.js?rgh-link-date=2020-09-11T17%3A45%3A50Z#L136-L141)

I suspect the code that consumes buildRequest will attach an error handler...

**Comment by ronag** [comment]
> Is there an alternative to destroy for tear down? Should I not tear down at all? As mentioned above my module is similar to`fastify-reply-from` which is why I was using destroy in the first place.

You should tearndown and you should attach an error handler.

**Comment by Lalem001** [comment]
> I suspect the code that consumes buildRequest will attach an error handler...

Technically it doesn't, but the consumer does send the body to fastify to handle, which inevitably does add an error handler.

Thank you for your time.
