### ISSUE TITLE
Header set to `null` validation

### ISSUE THREAD

**Issue by dnlup** [nodejs/undici#416]
I have a use case where I get a header set to `null` and [this](https://github.com/nodejs/undici/blob/9365968fd3cbcbf13c83c6b62e691bdd57c5e163/lib/core/request.js#L159) check fails. Can `null` be considered as `undefined` so that this check can be modified, or should I handle this separately? My gut tells me probably it's better separately, maybe because of streams behavior.

**Comment by ronag** [comment]
PR welcome!

**Comment by dnlup** [comment]
I'll work on it, thanks!
