### ISSUE TITLE
Caching support

### ISSUE THREAD

**Issue by talentlessguy** [nodejs/undici#417]
Hello, I'd like to suggest a feature of adding caching to undici.

The simplest implementation is using a folder to save responses, similar to [node-fetch-cache](https://github.com/mistval/node-fetch-cache)

I don't know if it is Undici job, or a separate package should do that.

as for other HTTP clients, [ky](https://github.com/sindresorhus/ky#readme) support caching via Redis.

if it's not planned to add caching support to Undici, feel free to close this issue :D

**Comment by ronag** [comment]
> I don't know if it is Undici job, or a separate package should do that.

Yea, I think that's unfortunately out of scope of this project.

> if it's not planned to add caching support to Undici, feel free to close this issue :D

Cheers!
