### ISSUE TITLE
Undici tries to reconnect indefenitely on `ECONNRFUSED`

### ISSUE THREAD

**Issue by dnlup** [nodejs/undici#418]
Sorry to bother again :pray: .

I noticed that on `ECONNREFUSED` the client keeps on trying to reconnect.

Steps to reproduce:

```js
const { Client } = require('undici')

const client = new Client('http://localhost:3000') // no server is listening on this port

client.request({ path: '/', method: 'GET' }).then(console.log).catch(console.error)
```

On version `1.3.1` the call fails with a `Socket Timeout` error.
 
Is this behavior by design on version 2?

I might be wrong, but It looks like there is a connection `retryTimeout`, but not a maximum number of attempts.

These are the parts that I have seen handling the socket connection:

* https://github.com/nodejs/undici/blob/9365968fd3cbcbf13c83c6b62e691bdd57c5e163/lib/core/client.js#L710

* https://github.com/nodejs/undici/blob/9365968fd3cbcbf13c83c6b62e691bdd57c5e163/lib/core/client.js#L851

Particularly the socket error handler

* https://github.com/nodejs/undici/blob/9365968fd3cbcbf13c83c6b62e691bdd57c5e163/lib/core/client.js#L619

**Comment by ronag** [comment]
This is by design. There is no maximum retry. How would you like it to behave and why?

**Comment by ronag** [comment]
Does your example no fail at all? That is something we should probably resolve.

**Comment by dnlup** [comment]
> Does your example not fail at all?

It hangs, I would say indefinitely or for a very long time. Before version 2 it would have failed after the default 30 seconds of `requestTimeout` or a similar timeout.

**Comment by ronag** [comment]
> It hangs, I would say indefinitely or for a very long time. 

I don't think this is right but I'm unsure what would be the appropriate behavior. Some kind of timeout somewhere should apply.

**Comment by dnlup** [comment]
> This is by design. There is no maximum retry. How would you like it to behave and why?

Well, the fact that this is by design makes me think. I understand your point of view. I had a test suite that was simulating network errors and one of the codes I was using was ECONNREFUSED.

I am a bit unsure too, the only thing that I am certain of is that undici should tell something to the user. WDYT @ronag ?

> Some kind of timeout somewhere should apply.

Do you prefer this approach over the number of attempt? I don't have a particular preference, just curious.

**Comment by ronag** [comment]
> Do you prefer this approach over the number of attempt? I don't have a particular preference, just curious.

Yes, I prefer a timeout.

**Comment by ronag** [comment]
Another alternative is to always error all pending requests on socket error.
