### ISSUE TITLE
Feature request: allow a custom dns lookup function to be supplied

### ISSUE THREAD

**Issue by JakeChampion** [nodejs/undici#421]
The `http` built-in module can have a [custom `lookup` function defined](https://nodejs.org/api/http.html#http_http_request_url_options_callback), which is great as it enables applications to decide if they want to implement a dns-caching system or something else.

Do we think it is a good idea to also implement such a feature for undici?

**Comment by mcollina** [comment]
Sure, would you like to send a PR?

**Comment by JakeChampion** [comment]
Would this be the correct change?

Make these `net.connect` calls take a custom lookup function and default to dns.lookup otherwise?
https://github.com/nodejs/undici/blob/master/lib/core/client.js#L732

Are these other places that would need to be updated also?

**Comment by ronag** [comment]
I think this could be resolved through https://github.com/nodejs/undici/issues/852

**Comment by GeoffreyBooth** [comment]
I’m running into this issue as well. My use case is an app that needs to connect to a server that can be accessed over the public internet but not within the virtual network where my app is running. In an older app with the same need, I wrote this code to patch DNS resolution for requests to use a public DNS server as a fallback when the internal lookup failed:

```js
import { lookup } from 'node:dns'
import http from 'node:http'
import https from 'node:https'

export async function patchDnsResolution() {
	http.globalAgent = new http.Agent({
		keepAlive: true,
		lookup: customLookup,
	})
	https.globalAgent = new https.Agent({
		keepAlive: true,
		lookup: customLookup,
	})
}

function customLookup(hostname, _family, callback) {
	lookup(hostname, 4, (lookupError, address, family) => {
		if (hostname === 'localhost') {
			return callback(undefined, '127.0.0.1', 4)
		}

		if (lookupError) {
			console.log(`Using public DNS resolver to look up ${hostname}`)
			// https://developers.cloudflare.com/1.1.1.1/encrypted-dns/dns-over-https/make-api-requests
			fetchWithTimeout(`https://1.1.1.1/dns-query?name=${encodeURIComponent(hostname)}`, {
				headers: {
					accept: 'application/dns-json',
				},
			})
				.then(response => response.json())
				.then(response => {
					if (response?.Answer) {
						// https://developers.cloudflare.com/1.1.1.1/encrypted-dns/dns-over-https/make-api-requests/dns-json
						// Find the first IPv4 or IPv6 address; https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4
						const { data: address, type } = response.Answer.find(({ type }) => type === 1 || type === 28)
						family = type === 1 ? 4 : 6 // IPv4 type is 1, IPv6 type is 28
						callback(undefined, address, family)
					} else {
						callback(new Error(`Public DNS resolver unrecognized response: ${response}`))
					}
				}).catch(error => {
					console.error(`Public DNS resolver error: ${error}`)
				})
		} else {
			callback(undefined, address, family)
		}
	})
}

async function fetchWithTimeout(resource, options = {timeout: 2000}) {
	const { timeout } = options
	const controller = new AbortController()
	const id = setTimeout(() => controller.abort(), timeout)
	const response = await fetch(resource, {
		...options,
		signal: controller.signal
	})
	clearTimeout(id)
	return response
}
```

In my new app, one of its dependencies uses Node’s global `fetch` to make a call to this unreachable server. The above code doesn’t patch the DNS resolution of global `fetch`, but there doesn’t appear to be a way to do an equivalent for Undici or global `fetch`.

**Comment by mcollina** [comment]
@ronag @GeoffreyBooth shouldn't this be solved by using the `connect()` option?

**Comment by ronag** [comment]
The connect option solves this.

**Comment by GeoffreyBooth** [comment]
> The connect option solves this.

Can you provide a working example?

**Comment by michael-braun** [comment]
I think I've got it working by using an Agent-instance with the connect-option. I don't know whether this is the preferred option, but it seems to work:

```javascript
import { Agent } from 'undici';

await fetch('https://example.com', {
  dispatcher: new Agent({
    connect: {
      lookup: (hostname, options, callback) => {
        return dns.lookup(hostname, options, callback);
      },
    },
  }),
});
```

Alternatively, the Agent can be registered globally using the `setGlobalDispatcher` function from the undici package.

**Comment by Chadzzz1** [comment]
[****](url)
