### ISSUE TITLE
Return body as async iterator

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#422]
Briefly discussed at todays webserver-framework meeting. Would be interesting to see how returning an async iterable as body would work out.

Not sure how we would do it API wise. Basically it would be a `client.request` which returns an async iterable instead of a stream.

Should we have another API or should it be an option? @mcollina wdyt?

```js
const { body } = await client.request(...)
for await (const chunk of body) {
}
```

**Comment by ronag** [comment]
Maybe something @Ethan-Arrowood would like to work on once we've figured out how the API would look?

**Comment by Ethan-Arrowood** [comment]
Yeah would love to take a crack at this! Thank you!

**Comment by ronag** [comment]
`Readable` is already async iterable. However, it does not provide the most optimal performance.
