### ISSUE TITLE
InvalidArgumentException due to Connection header

### ISSUE THREAD

**Issue by DBain07** [nodejs/undici#428]
I am curious as to why is an error (InvalidArgumentException ) is thrown when the Connection general header is sent with the request? What is the purpose for doing this?

**Comment by szmarczak** [comment]
`undici` handles this for you. Why would you need to set `Connection` on your own?

**Comment by DBain07** [comment]
Yes that makes sense, I figured that was the case. I was mainly asking since if someone hitting the server is unaware of this fact, their request will be refused and I was wondering if there was a way to avoid this (I use undici with fast-proxy to relay requests to api's not exposed to the public).

**Comment by szmarczak** [comment]
> I was wondering if there was a way to avoid this

Yes, the fix is simple. Just don't send the Connection header :smile: 

> I use undici with fast-proxy to relay requests to api's not exposed to the public

So you're not calling `undici` directly?

**Comment by DBain07** [comment]
Lol yea that would do it. No, I'm not calling undici directly, it is called through a library called Fast-Proxy. I should be good now though, just found out that Fast-Proxy has a method called rewriteRequestHeaders where I can ensure I remove the connnection header before proceeding, thus preventing any issues on undici's end. Thanks again for your help.

**Comment by szmarczak** [comment]
Please consider opening an issue in `fast-proxy` in case it's a bug.
