### ISSUE TITLE
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by yohay-ma** [nodejs/undici#430]
hi,

I'm using:
    "fastify": "^3.4.1",
    "fastify-http-proxy": "^4.0.4",
resolved undici version: "2.0.2"

When I run load test on my node I've stated to see the following debug messages:
```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at Socket.addListener (events.js:406:10)
    at Socket.Readable.on (_stream_readable.js:871:35)
    at write (/app/node_modules/undici/lib/core/client.js:1168:8)
    at _resume (/app/node_modules/undici/lib/core/client.js:920:9)
    at resume (/app/node_modules/undici/lib/core/client.js:771:3)
    at Parser.3 (/app/node_modules/undici/lib/core/client.js:597:7)
```

I'm using node (docker) version node:12.18.4-alpine
```
exec node --trace-warnings app.js
```

I have attached flamegraph.log, please rename to flamegraph.html to view the report

[flamegraph.log](https://github.com/nodejs/undici/files/5269984/flamegraph.log)

**Comment by ronag** [comment]
Can you provide a fully reproducible example?

**Comment by ronag** [comment]
nevermind found the issue

**Comment by yohay-ma** [comment]
@ronag please let me know if you need more information.
This happens when load testing with POST request. (I think that the stream is not closed/end properly)

**Comment by ronag** [comment]
It’s been fixed and a new release has been published.
