### ISSUE TITLE
Leaking array buffers

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#434]
Not sure if this is a user, undici, node or V8 bug but I have case where I have lot's of ArrayBuffers allocated and never freed in our Node based proxy:

```
{rss: 4519784448, heapTotal: 25522176, heapUsed: 20927688, external: 722839852, arrayBuffers: 721332770}
```

@mcollina @addaleax any hints on how to debug this?

**Comment by mcollina** [comment]
Have you got a repro? You can possibly find them using heapdump.
If you need something programmatic to run on servers, use https://github.com/nearform/heap-profiler.

**Comment by szmarczak** [comment]
@ronag I remember there was a bug in Node.js 12 related to TLS sockets. What Node.js version are you running?

**Comment by ronag** [comment]
14.8

Happens at multiple locations with different node versions.

I see that V8 recently did something with GC of ArrayBuffers. Maybe coincidence...

**Comment by ronag** [comment]
I’ll have to continue digging on Monday.

**Comment by ronag** [comment]
> Have you got a repro? You can possibly find them using heapdump.
> If you need something programmatic to run on servers, use https://github.com/nearform/heap-profiler.

Does that work with cluster?

**Comment by mcollina** [comment]
It might work given some adaptation.

**Comment by ronag** [comment]
Seem to have the same problem on a totally different service which recently started to use undici

**Comment by ronag** [comment]
Been trying to create a repro without success 😞

**Comment by szmarczak** [comment]
@ronag How does the `undici` call look like? What function is used?

**Comment by ronag** [comment]
`Client.request``

I think it might be broken back pressure.

**Comment by ronag** [comment]
My current guess it that it has something to do with pause/resume multiple times. This seems to be growing arrayBuffer usage infinitiely:

```js
'use strict'

const { Client } = require('..')
const { createServer } = require('http')
const { Readable } = require('stream')

const requests = 128

const server = createServer()

const limit = 1e9

server.on('request', (req, res) => {
  let bytesWritten = 0

  const interval = setInterval(() => {
    console.log(process.memoryUsage().arrayBuffers / 1e6, bytesWritten, bytesWritten / limit)
  }, 1e3)

  const buf = Buffer.allocUnsafe(16384)
  new Readable({
    read () {
      bytesWritten += buf.length
      this.push(buf)
      if (bytesWritten >= limit) {
        clearInterval(interval)
        this.push(null)
      }
    }
  }).pipe(res)
})

server.listen(0, () => {
  const client = new Client(`http://localhost:${server.address().port}`, {
    pipelining: 1
  })

  for (let n = 0; n < requests; ++n) {
    client.request({ path: '/', method: 'GET', opaque: 'asd' }, (err, data) => {
      if (err) {
        console.error(err)
      }
      data.body
        .resume()
        .on('data', () => {
          data.body.pause()
          setTimeout(() => data.body.resume(), 1e3)
        })
    })
  }
})

```

**Comment by ronag** [comment]
I have no idea though where these buffers are hiding at the moment.

**Comment by ronag** [comment]
Could it be that `socket.pause()` does not work in `consume()` mode?

**Comment by ronag** [comment]
Yep, that's the problem.

**Comment by szmarczak** [comment]
@ronag Is it possible to pause a response using `client.dispatch`?

**Comment by ronag** [comment]
> @ronag Is it possible to pause a response using client.dispatch?

Return false in `onBody`.
