### ISSUE TITLE
Proxy Example Could Not Connect to A nodejs ws Server(upgrade)

### ISSUE THREAD

**Issue by Test-mycode** [nodejs/undici#437]
os: win10 x64
node: 14.12.0
the error message :
{
  "name": "SocketError",
  "code": "UND_ERR_SOCKET"
}

**Comment by ronag** [comment]
Could you provide a reproducible example?

**Comment by Test-mycode** [comment]
here is the reproducer https://github.com/Test-mycode/proxy_ws_reproducer.git
![image](https://user-images.githubusercontent.com/66617605/94266984-6e950700-ff6d-11ea-9e27-d719901a8576.png)

**Comment by Test-mycode** [comment]
@ronag

**Comment by Test-mycode** [comment]
2.0.6 still not work. any progress? @ronag

**Comment by ronag** [comment]
Ah sorry. I forgot about this. Will dig into it over the weekend.

**Comment by ronag** [comment]
@Test-mycode sorry but could you create a repro in javascript? I don't know typescript.

**Comment by ronag** [comment]
You don't seem to be using the latest version of the examaple: https://github.com/nodejs/undici/blob/master/examples/proxy/proxy.js

**Comment by Test-mycode** [comment]
reproducer updated to pure javascript. @ronag

**Comment by ronag** [comment]
2.0.7 published

**Comment by Test-mycode** [comment]
thinkyou it worked
