### ISSUE TITLE
socket timeout

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#439]
Not sure if user land bug but after https://github.com/nodejs/undici/pull/435 I'm getting some timeouts. Maybe those timeouts not occurring was a bug before.

Needs further investigating to determine whether we've introduced a new bug or not.

**Comment by szmarczak** [comment]
What do you think about integrating https://github.com/sindresorhus/got/blob/master/source/core/utils/timed-out.ts into undici? Or should that be left as another module?

**Comment by ronag** [comment]
Problem probably in userland and related to https://github.com/nodejs/node/issues/35341.

**Comment by ronag** [comment]
> What do you think about integrating [https://github.com/sindresorhus/got/blob/master/source/core/utils/timed-out.ts](https://github.com/sindresorhus/got/blob/master/source/core/utils/timed-out.ts?rgh-link-date=2020-09-25T15%3A36%3A08Z) into undici? Or should that be left as another module?
> 
> The end user API looks like [sindresorhus/got#timeout](https://github.com/sindresorhus/got#timeout)

That looks very intersting! I'll dig into it next week.
