### ISSUE TITLE
Custom abort signal event

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#445]
It would be nice to be able to specify what event on the passed event emitter should cause abort, e.g. in some cases it would make sense to just pass an object that emits `'close'` instead of having to wrap in additional event emitter, e.g.

```js
return client.stream({
  ...options,
  opaque: res,
  signal: [res, 'close'] // when res emits 'close', abort request.
}, ({ opaque }) => opaque)
```

Instead of:

```js
const signal = new EE()
res.on('close', () => signal.emit('abort'))
return client.stream({
  ...options,
  opaque: res,
  signal
}, ({ opaque }) => opaque)

```

**Comment by ronag** [comment]
@mcollina @szmarczak wdyt?

**Comment by ronag** [comment]
@jasnell might also have some input since he worked on the abort signal stuff in core.

**Comment by mcollina** [comment]
I would keep using `'abort'`, is a bit more standard. Also, a stream emit `'close'` and I would try not to tie the two things together. Overall I don't mind either way, so go with what you prefer!

**Comment by ronag** [comment]
I'm mostly going back to the proxy example where this would provide a little more convenience and performance. Though I'm unsure if the semantics make sense.

**Comment by szmarczak** [comment]
I'm good with both. The first approach looks a bit cleaner though.

**Comment by StarpTech** [comment]
Will it be possible to pass the signal of an `AbortController`?

**Comment by ronag** [comment]
> Will it be possible to pass the signal of an `AbortController`?

It's already possible?

**Comment by StarpTech** [comment]
Nice! ⭐
