### ISSUE TITLE
HTTP response mocking use case

### ISSUE THREAD

**Issue by bengl** [nodejs/undici#450]
I recently started porting a codebase over to using `undici`, but the tests for this codebase make heavy use of [`nock`](http://npm.im/nock). Since `undici` does not use `require('http')`, a lot of what `nock` does is useless with `undici`. From what I can tell, most other HTTP response mocking libraries do something similar.

I see two paths forward here:

1. Mocking instead at the `net` layer using something like https://www.npmjs.com/package/net-interceptor, or just doing it manually. 
2. Building out something either within `undici` or alongside it to help in HTTP response mocks, doing it at `undici`'s API surface.

I'm leaning toward option 2.

**Comment by mcollina** [comment]
I think option 2 would be best. Adding mocking as a built-in concept would make sure it does not break over time. Moreover, this is extremely useful.

**Comment by ronag** [comment]
@mcollina can we close this?

**Comment by mcollina** [comment]
Shipped!
