### ISSUE TITLE
Missing results on benchmarks in Node 10 and 12

### ISSUE THREAD

**Issue by dnlup** [nodejs/undici#456]
Hi :wave: :smile: 

I am getting timeout errors when running benchmarks on Node 12 and 10, resulting in a premature exit without results. This doesn't happen on Node 14. Switching to the use of the `finish` event instead of `close` fixes this issue. Is this behavior wanted?

**Comment by mcollina** [comment]
Given the test suite pass on all versions, it seems ok to assume that is a problem in the benchmarks... could you send a PR to fix?

**Comment by dnlup** [comment]
Yes, thanks :D
