### ISSUE TITLE
"bad" Pool scheduling performance under low pressure

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#467]
In https://github.com/nodejs/undici/pull/466 I've made the benchmarks parametric. I also added the ability to run the server with a timeout, which in this case is set top 10ms.

The following cases are _not_ saturating benchmarks, e.g. both the client and server have _plenty_. of spare CPU capacity.

```
$ PORT=3000 CONNECTIONS=5 PARALLEL=10 PIPELINING=10 node benchmarks/index.js
http - no agent  x 85.57 ops/sec ±0.96% (43 runs sampled)
http - keepalive x 86.13 ops/sec ±0.74% (43 runs sampled)
http - keepalive - multiple sockets x 373 ops/sec ±1.33% (61 runs sampled)
undici - pipeline x 176 ops/sec ±0.91% (45 runs sampled)
undici - request x 180 ops/sec ±0.84% (80 runs sampled)
undici - pool - request - multiple sockets x 180 ops/sec ±0.70% (33 runs sampled)
undici - stream x 182 ops/sec ±0.72% (33 runs sampled)
undici - dispatch x 182 ops/sec ±0.67% (81 runs sampled)
undici - noop x 186 ops/sec ±0.46% (82 runs sampled)
```

As you can see, the clients are not saturated, but the throughput is essentially the one of 1 socket.
This is essentially a low pressure scenario because PARALLEL < CONNECTIONS * PIPELINING.

If we remove pipelining, we can still see some improvement.

```
$ PORT=3000 CONNECTIONS=5 PARALLEL=10 PIPELINING=1 node benchmarks/index.js
http - no agent  x 83.88 ops/sec ±0.86% (42 runs sampled)
http - keepalive x 85.33 ops/sec ±0.70% (43 runs sampled)
http - keepalive - multiple sockets x 377 ops/sec ±1.43% (59 runs sampled)
undici - pipeline x 88.54 ops/sec ±1.16% (45 runs sampled)
undici - request x 89.27 ops/sec ±0.63% (45 runs sampled)
undici - pool - request - multiple sockets x 403 ops/sec ±0.98% (62 runs sampled)
undici - stream x 91.53 ops/sec ±0.57% (46 runs sampled)
undici - dispatch x 90.92 ops/sec ±0.39% (45 runs sampled)
undici - noop x 92.51 ops/sec ±0.56% (46 runs sampled
```

If we increase load so that match PARALLEL = CONNECTIONS * PIPELINING:

```
$ PORT=3000 CONNECTIONS=5 PARALLEL=50 PIPELINING=10 node benchmarks/index.js
http - no agent  x 85.65 ops/sec ±1.60% (13 runs sampled)
http - keepalive x 85.78 ops/sec ±1.22% (13 runs sampled)
http - keepalive - multiple sockets x 411 ops/sec ±0.94% (42 runs sampled)
undici - pipeline x 480 ops/sec ±1.09% (48 runs sampled)
undici - request x 501 ops/sec ±0.64% (49 runs sampled)
undici - pool - request - multiple sockets x 831 ops/sec ±1.25% (74 runs sampled)
undici - stream x 506 ops/sec ±0.76% (50 runs sampled)
undici - dispatch x 517 ops/sec ±0.66% (51 runs sampled)
undici - noop x 525 ops/sec ±0.46% (52 runs sampled)
```

Last case where PARALLEL > CONNECTIONS * PIPELINING:

```
$ PORT=3000 CONNECTIONS=5 PARALLEL=500 PIPELINING=10 node benchmarks/index.js
http - no agent  x 87.28 ops/sec ±1.28% (5 runs sampled)
http - keepalive x 88.06 ops/sec ±1.72% (5 runs sampled)
http - keepalive - multiple sockets x 434 ops/sec ±1.06% (9 runs sampled)
undici - pipeline x 829 ops/sec ±1.07% (13 runs sampled)
undici - request x 851 ops/sec ±0.54% (13 runs sampled)
undici - pool - request - multiple sockets x 2,998 ops/sec ±0.95% (32 runs sampled)
undici - stream x 853 ops/sec ±0.60% (13 runs sampled)
undici - dispatch x 858 ops/sec ±0.52% (13 runs sampled)
undici - noop x 859 ops/sec ±0.24% (13 runs sampled)
```

---

I think we should change the scheduling algorithm so that the case where PARALLEL < CONNECTIONS * PIPELINING is handled properly. Have you got any pointers @ronag?

**Comment by ronag** [comment]
I think this goes back to the depth first vs breadth first conversation?

**Comment by ronag** [comment]
https://github.com/nodejs/undici/issues/73#issuecomment-626141009

**Comment by ronag** [comment]
Breadth first might have a performance advantage from request parallelism.

**Comment by ronag** [comment]
You might also want to have the server with cluster to make it more realistic and where more connections might have even more advantage.

**Comment by ronag** [comment]
> If we remove pipelining, we can still see some improvement.

This is interesting. Not sure where the dead time might occur. Would be interesting to try against a different server such as h2o or nginx.

**Comment by ronag** [comment]
I think the benchmarks are a little suboptimal in terms of benchmarking parallelism since it does it in batches of 10 (which is probably why you don't see 100% cpu) but I don't know how to make them better given how the benchmark model works.

**Comment by mcollina** [comment]
> I think this goes back to the depth first vs breadth first conversation?

I think so. We might want to implement breadth-first instead - possibly with an option. I don't necessarily get how `client.busy` is calculated - would I need to change that if I wanted to add this option?

--- 

It's not really a server problem, the server load is _minimum_. If the client _could_ send more throughput, the server will handle it, it never goes above 10% on my machine.

**Comment by ronag** [comment]
> I think so. We might want to implement breadth-first instead - possibly with an option. I don't necessarily get how client.busy is calculated - would I need to change that if I wanted to add this option?

No change needed for `.busy` you only need to update `Pool` so that it always tries to grab the client with least number of requests.

**Comment by ronag** [comment]
```js
const nextClient = clients.sort((a, b) => a.size - b.size)[0]
```

**Comment by ronag** [comment]
> I don't necessarily get how client.busy is calculated

`busy` false means that additional requests won't get directly dispatched on socket if enqueued.

**Comment by ronag** [comment]
```js
const nextClient = clients.sort((a, b) => {
  if (a.busy !== b.busy) return b.busy ? -1 : 1
  if (a.size !== b.size) return a.size - b.size
  return 0
})[0]
```

**Comment by mcollina** [comment]
Moving from depth-first to breadth-first does not change the measurement. It succeeds in spreading more evenly the requests on the sockets. The CPU is at 20% and there is plenty of capacity to send more. Might it be that it is waiting for some event in Client? Maybe `'drain'` is too late or `.busy` is too eager?

**Comment by ronag** [comment]
> The CPU is at 20% and there is plenty of capacity to send more.

How do you measure this? What bench params are you running?

**Comment by ronag** [comment]
I also think the benchmark might not be optimal for measuring parallel performance...

**Comment by ronag** [comment]
What happens if you remove the busy check and also always emit drain if ´!pending` (i.e. without the nextTick logic).

**Comment by mcollina** [comment]
> What happens if you remove the busy check and also always emit drain if ´!pending` (i.e. without the nextTick logic).

I checked and it didn't work :/

**Comment by ronag** [comment]
I suspect you are seeing an issue with the benchmark.

**Comment by ronag** [comment]
I would suggest closing this with a reference to https://github.com/nodejs/undici/issues/405
