### ISSUE TITLE
How to trigger headersTimeout and bodyTimeout

### ISSUE THREAD

**Issue by luddd3** [nodejs/undici#474]
Hi,

I'm currently evaluating this library for my use cases and I'm wondering how headersTimeout and and bodyTimeout is supposed to work.

Server:
```javascript
const http = require('http')
const { promisify } = require('util')
const delay = promisify(setTimeout)

const server = http.createServer(async (req, res) => {
  await delay(2e3)
  res.setHeader('Content-Type', 'application/json')
  res.writeHead(200)
  await delay(2e3)
  res.end('{}')
})
server.listen(8080)
```

Client:
```javascript
const undici = require('undici')
async function main () {
  const client = new undici.Client('http://localhost:8080')
  const { body } = await client.request({
    path: '/',
    method: 'GET',
    headersTimeout: 1e3 // I have also tested with bodyTimeout
  })
  for await (const b of body) {
    console.log(String(b))
  }
}
main()
```

If I start the server first and then run the client i expect the client to get an unhandled promise rejection, but instead it logs "{}". Have I completely misunderstood how these timeouts are supposed to work? 

I ran these tests using using node v12.14.0

**Comment by ronag** [comment]
What version of undici?

**Comment by luddd3** [comment]
2.1.1

**Comment by ronag** [comment]
Look at the documento on for the 2.x branch. Master is not yet released.

**Comment by luddd3** [comment]
Ah sorry, I missed that the current npm version was in another branch.

I switched to current master (#9a1e9af) and reran my test. It fails as expected for headersTimeout, but I cannot trigger bodyTimeout. I used the same server and replaced headersTimeout with bodyTimeout in the client.

Am I doing it wrong or is it a work in progress?

**Comment by ronag** [comment]
@luddd3 can you provide an example?

**Comment by luddd3** [comment]
I use the code in my first post. First start server.js in one terminal and then start client.js in another.

For undici #9a1e9af I get the following expected error message from the client process:
```bash
(node:1693338) UnhandledPromiseRejectionWarning: HeadersTimeoutError: Headers Timeout Error
    at Timeout.<anonymous> (/home/mathias/workspace/undici-test/node_modules/undici/lib/core/request.js:123:22)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1693338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1693338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is expected since `headersTimeout` is set to 1 second and the server starts writing the headers after 2 seconds. When I run the same code on, e.g. #f083cc0 (latest commit on master), no error is printed.

Another example is to replace `headersTimeout` with `bodyTimeout` in client.js. Then I expect an error to occur since there is a 2 second delay to "res.end" in server.js

Depending on how you have defined bodyTimeout to work, I guess that it should trigger in one of these cases:
  1. time between headers and first body packet too long
  2. time between first and last packet of body too long
  3. time between any two packets of body too long

**Comment by ronag** [comment]
The expected behavior is 1 and 3

**Comment by luddd3** [comment]
@ronag Thank you
