### ISSUE TITLE
Support HTTP 103

### ISSUE THREAD

**Issue by zekth** [nodejs/undici#481]
I implemented a plugin for HTTP 103 early hints in fastify : https://github.com/zekth/fastify-early-hints
I wanted to introduce undici as part of the test stack because currently i use `curl` as a subprocress and parse the stdout for it.

The problem currently with undici are those lines : https://github.com/nodejs/undici/blob/f083cc025353c1fc0cbd81fea8797a9b033ecb5d/lib/client-request.js#L88-L90

Indeed it skips the `information` part of the raw HTTP message. I concede that HTTP 103 is experimental for now, but if it's possible to implement it i'd suggest to add those informations in the response of the request like:

```js
client.request({
  path: '/',
  method: 'GET'
}, function (err, data) {
  if (err) {
    // handle this in some way!
    return
  }

  const {
    statusCode,
    headers,
    body,
    info
  } = data
```

Because of the RFC the structure of the `info` would be something like:
```js
{
  raw: [
    [
      ['Link: </main.css>; rel=preload; as=style'],
      ['Link: </script.js>; rel=preload; as=script'],
    ],
    [
      ['Link: </style.css>; rel=preload; as=style']
    ],
  ],
  compiled: [
      ['Link: </main.css>; rel=preload; as=style'],
      ['Link: </script.js>; rel=preload; as=script'],
      ['Link: </style.css>; rel=preload; as=style']
  ]
}
```

ref:
- https://httpwg.org/specs/rfc8297.html
- https://chromium.googlesource.com/chromium/src/+/master/docs/early-hints.md
- https://www.fastly.com/blog/beyond-server-push-experimenting-with-the-103-early-hints-status-code

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ronag** [comment]
The point of info messages is that they arrive before the response headers. The API you suggest kind of breaks that.

We would need an api which allow listening to those events before the response headers.

I don’t know how that would look and is why we haven’t implemented it yet.

**Comment by zekth** [comment]
a solution would be to emit event on Information headers like:
```js
client.on('info', handler)
```
Also do we want to have the whole http transite compiled into `request` like i proposed or not?
I surely can try to implement it in a PR.
