### ISSUE TITLE
Rewrite in Typescript?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#485]
I wouldn't mind having undici written entirely in Typescript. Thoughts?

**Comment by ronag** [comment]
@mcollina

**Comment by ronag** [comment]
Would make life a bit easier with keep the type definitions correct.

**Comment by mcollina** [comment]
Rewriting this in TypeScript would make me unable to contribute effectively. Moreover it would be a blocker if our goal is to land it in core eventually.

**Comment by ronag** [comment]
> Rewriting this in TypeScript would make me unable to contribute effectively. Moreover it would be a blocker if our goal is to land it in core eventually.

Ok. Then it sounds like a bad idea.
