### ISSUE TITLE
`servername` option not documented

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#486]

**Comment by timdp** [comment]
I wanted to pick this up to familiarize myself with the codebase but I'm wondering if it _should_ be documented by Undici itself.

The `servername` option is part of the `tls.TlsOptions` passed to a `Client`. Those are [documented here](https://github.com/nodejs/undici/blob/0c920947c62ae43284ce2dbf2fc8a6579a7cfe38/docs/api/Client.md#parameter-clientoptions). The current documentation states that the options object is handed off to the linked [`tls.connect()`](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback), which in turn explains its purpose:

> Server name for the SNI (Server Name Indication) TLS extension. It is the name of the host being connected to, and must be a host name, and not an IP address.

I don't see a lot of value in rewording that, or in further clarifying it, but I suppose we could copy it if we think people are going to be thrown off by the link. However, then we should probably document _all_ the relevant bits of `tls.TlsOptions`?

**Comment by ronag** [comment]
Good point. I would prefer if we actually moved relevant settings to undici and not just directly pass any option to `net.connect`. But that's a different issue.

Closing this.

Thanks @timdp!
