### ISSUE TITLE
Generate docs from type definitions or vice versa?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#487]
Is this possible? @Ethan-Arrowood

**Comment by Ethan-Arrowood** [comment]
Yes if we use inline JS docs we can generate types from those

**Comment by Ethan-Arrowood** [comment]
If I find some time I'll try experimenting with this. I've seen some other projects do this successfully. node-fetch uses this feature quite well.

**Comment by Ethan-Arrowood** [comment]
Been playing with this today. This article is really great about covering a lot of the details of using JSDoc for types: https://gils-blog.tayar.org/posts/jsdoc-typings-all-the-benefits-none-of-the-drawbacks/

**Comment by Ethan-Arrowood** [comment]
And this page of the handbook helps a lot too: https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

**Comment by Ethan-Arrowood** [comment]
Type Checking hits a wall pretty fast: https://github.com/microsoft/TypeScript/issues/41996

But we could potentially still use JSDoc to generate types... its just tough to do one with the other (type checking with jsdoc vs. generating types with jsdoc)
