### ISSUE TITLE
doc: fix typo in abort request

### ISSUE THREAD

**Issue by Sirius79** [nodejs/undici#494]
There seems to be a typo in the first line of abort request [here](https://github.com/nodejs/undici#aborting-a-request).

It says `A request can may be aborted using either an AbortController or an EventEmitter.`

Should I send a PR to fix this to `A request can be aborted using either an AbortController or an EventEmitter.`?

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
