### ISSUE TITLE
WeakRef support

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#501]
We should test that a `WeakRef`:d `Pool` or `Client` does not get garbage collected while there is an active socket.

So basically if the pool/client has no pending request and idle/keepalive timeout has expired it should be garbage collected, otherwise not.

I think this already works but needs a regression test.

`Client` has a ref to `Pool` through `onDrain` listener and `Socket` has a ref to `Client` through `[kClient]`.

I think sockets are GC roots so I believe they will never be GC:d while there is still an active connection.

**Comment by ronag** [comment]
@Ethan-Arrowood @dnlup Maybe? This can be fun if you want to get more familiar with weak refs.

**Comment by dnlup** [comment]
To test if it has been garbage collected, we could use [`deref`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/deref), right? As for keeping the socket active, is it sufficient to work just with the keepalive timeout, or is it better to send some data (in this case, I don't know how to do it without referencing the Client/Pool atm)? I can try to put something together.

**Comment by ronag** [comment]
I think you can use finalization registry as well to check for gc

**Comment by ronag** [comment]
> I don't know how to do it without referencing the Client/Pool

I mean you can write something and then null the refs?

**Comment by dnlup** [comment]
Yup, thanks for the pointers
