### ISSUE TITLE
dispatchFromAgent opts.path

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#513]
How should we handle if path is passed through `opts.path` to e.g. `undici.request`?

1. Always throw invalid arg?
2. Throw invalid arg if url doesn't have path?
3. Join url path and opts.path?
4. Prioritize one over the other?

**Comment by ronag** [comment]
@Ethan-Arrowood @dnlup

**Comment by ronag** [comment]
Right now the docs say that `opts` is the same as `client.request.opts` so we have a conflict here.

**Comment by ronag** [comment]
@mcollina wdyt

**Comment by mcollina** [comment]
> Always throw invalid arg?

Yes.
