### ISSUE TITLE
gc test fails on darwin

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#515]
https://github.com/nodejs/undici/commit/0ff9cf22e16bd03dea41b7698f8d77c9089bf29d

**Comment by ronag** [comment]
@dnlup

**Comment by dnlup** [comment]
Yup, I know. I guess it's not flaky but fails consistently on that platform. Unfortunately, I don't know how to fix it atm, so the best thing is to disable it as you did.

**Comment by ronag** [comment]
I can recreate it locally so I'll look into it eventually if no one beats me to it.

**Comment by mcollina** [comment]
is this fixed?

**Comment by ronag** [comment]
no
