### ISSUE TITLE
Agent is missing close and destroy methods.

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#520]
Agent is missing close and destroy methods.

**Comment by Ethan-Arrowood** [comment]
I may be misunderstanding how the current Agent implementation works.

Does the GC cleanup not automatically close the pool when it is no longer referenced?

**Comment by ronag** [comment]
> Does the GC cleanup not automatically close the pool when it is no longer referenced?

The socket references it until timeout.

**Comment by Ethan-Arrowood** [comment]
> The socket references it until timeout.

I see. And so, if there is no timeout, the pool never closes.

**Comment by Ethan-Arrowood** [comment]
(Copying over some ideas I had from undici-fetch thread

I can think of two auto-close scenarios:

- Long running process (such as an REST API) - should close unused pools after some time if a new request comes through that uses a previous origin, that pool needs to be reopened (or just reinstantiated). Maybe we could consider a compounding timeout here where every time the pool timesout and is then asked for again, the following timeout time is increased.
- Short running process (such as a CLI command) - let the OS destroy it when the process ends execution (is this safe?). these should also have a timeout in case the "short" process runs for a long time, but we could set that timeout for a very long time and also integrate an auto-reset feature if it is reused after self-closing

**Comment by ronag** [comment]
Sockets are GC roots.

**Comment by Ethan-Arrowood** [comment]
Is it safe to not close a pool if the process is short running?

**Comment by ronag** [comment]
> Is it safe to not close a pool if the process is short running?

Yes.

**Comment by ronag** [comment]
I don't think sockets keep the process alive.

**Comment by Ethan-Arrowood** [comment]
> I don't think sockets keep the process alive. 

I'd like to try and test / confirm this to be certain.

---

So i think then adding a close and destroy method are useful for those who want to use it, but then also maybe integrating my previous ideas at the undici-fetch level might be useful

**Comment by ronag** [comment]
> but then also maybe integrating my previous ideas at the undici-fetch level might be useful

But this is already working in undici? I'm confused.

**Comment by Ethan-Arrowood** [comment]
> But this is already working in undici? I'm confused.

Yes, sorry. I mean implement these timeout ideas for the Agent itself -- this way users never have to call `.close()`.

> You still need close in order for the tests to properly finish.

Yes 100% we need to add `close()` and `destroy()` so that this Agent can be properly tested and used in **all** scenarios
