### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jsumners** [nodejs/undici#553]
I am evaluating using this library since `got` is planned to be ESM only by end of 2021 and I am encountering a few questions:

1. Under what conditions does `client.request` return an error? Is it only for operational errors? Or will it return an error if the remote host returns a `404` response? If the later, is it any `4xx` or `5xx`?
2. Does `client.request` follow redirects?
3. Does `client.request` automatically retry under any circumstances? For example, `got` by default will retry a `500` three times before giving up and returning an error.
4. If `undici.Client` accepts an instance of `URL`, why would it reject paths and query parameters (#552)? Since it accepts a `URL` instance, I assumed it would create a client specific to that URL and `client.request` wouldn't require any further configuration to make a request.

I'm sure I have other questions if I dig further, but these are the primary questions I have after a few minutes of trial.

**Comment by ronag** [comment]
undici is a low level client not comparable to got. got could be built on top of undici.

1. No
2. No
3. No
4. Because the client is just a connection to a server, query parameters are for requests.

**Comment by ShogunPanda** [comment]
What do you think about a PR for the n.2? 

I'm thinking like adding a `maxRedirects: number` option in `undici.Client`, overridable in `client.request`.

If not provided, then undici will behave as today, for backwards compatibility.

If provided, it is the number of redirects to follow, with `0` meaning `infinite` and undici will follow the redirects according to RFCs.

If any redirects is following, a `redirects` array will be provided in callback data as well.

If this spec looks fine to you I'll try to work on a PR as soon as I can.

**Comment by ronag** [comment]
I'm not sure I think adding redirect support is a good idea.

**Comment by ShogunPanda** [comment]
Can you elaborate? So we can find a suitable solution. I had the same issue as @jsumners so I think this might be a common concern.

**Comment by ronag** [comment]
undici is supposed to be a low level client which is correct and simple to maintain. I'm concerned that adding redirect support will increase complexity. It also could easily live in a separate npm package as a decorator.

Looking at https://www.npmjs.com/package/follow-redirects I'm quite concerned about complexity.

**Comment by ronag** [comment]
If you think you can implement it in a simple and elegant way that is spec compliant feel free to open a PR but I can't promise we merge it. If not then maybe we can create a separate npm package based on that PR?

**Comment by ronag** [comment]
@mcollina wdyt?

**Comment by ShogunPanda** [comment]
A separate package might work as well. Let me explore PR first and if doesn't feel appealing l'll go for the separate package one.

**Comment by ShogunPanda** [comment]
Ok, I've explored the PR way and I immediately found out it makes little sense. Since undici works on a single host, following redirects (which usually change it) it will involve maintaining different clients all together.
And this goes way beyond the scope of this package.

I'll write a extension package, like `undici-with-redirects` which achieves this maintaining several clients internally.
Thanks for the support.

**Comment by mcollina** [comment]
I think it might be possible to write a `RedirectAgent` that can follow a request through hops. It might be a separate module or something internal - it won't touch any of the exiting codebase.

(I think having it internally might simplify discovery and usability).

**Comment by ShogunPanda** [comment]
I also thought the same.
My only concern is: how should I handle external hops? 

Let's say we have this:

```
const fastify = require('fastify')()

fastify.get('/', function (request, reply) {
  reply.redirect('https://somewhere.com/resource', 302)
})

await fastify.listen(3000)

const client = new undici.Client('http://localhost:3000', opts)
client.request({path: '/resource', method: 'GET'})
```

How should I handle the clients? Internal hidden clients to the new server? Also, should I forward opts?

**Comment by mcollina** [comment]
I was thinking something like:

```js
import { request, RedirectAgent, setGlobalAgent } from 'undici'

setGlobalAgent(new RedirectAgent())

const {
  statusCode,
  headers,
  trailers,
  body
} = await request('http://localhost:3000/foo')

console.log('response received', statusCode)
console.log('headers', headers)

for await (const data of body) {
  console.log('data', data)
}

console.log('trailers', trailers)
```

**Comment by ShogunPanda** [comment]
Ok, I was able to implement it using a RedirectAgent as @mcollina suggested.

Please see: https://github.com/nodejs/undici/pull/597/files
