### ISSUE TITLE
Unknow error when Client is created.

### ISSUE THREAD

**Issue by NawafSwe** [nodejs/undici#557]
I am trying to creating Client object to call another local server on my mahcine but it gives me the following error:  **InvalidArgumentError: invalid url**

my code is: 
`
const {Client} = require('undici');
const BASE_URL = 'http://127.0.0.1:8000/';
 const options = {method: 'POST', body: {endpoint: url}};
// here throws the error;
 const client = new Client(BASE_URL);
      
`

**Comment by aayushmau5** [comment]
Can you check again? I tried the same code and it's working for me.

**Comment by NawafSwe** [comment]
Still not working I am trying to call django server locally is this allowed? I tried it with axios and it was just fine with the same url.

**Comment by ronag** [comment]
That should work. I suspect you are doing something else than your example above.

**Comment by NawafSwe** [comment]
I tried the request with `get` request and its works fine with get endpoints, 
still cannot use client to do post request.

**Comment by mcollina** [comment]
Can you please include an example we can run for both the client and the server?

**Comment by NawafSwe** [comment]
Okay
**using request for get requests**
`    import {request} from 'undici';
    // using request
        const {body} = await request(endpoint);
        return body;`
      **works just fine and perfect returns a valid body**

---------------------------------------------------------------------------------
     **but using client instead for post requests it wont work for the below code**
        const Client = require('undici');
        const options = {method:'POST', body:{dummy:'dummy'}};
        const client = new Client(endpoint); // ----> here it throws an error :  **InvalidArgumentError: invalid url**
        const {data} = await client.request(options);
       return data;
     it works just fine with the same url using **axios** so idk what is the issue with the post method.
     thank you for your work and time.

**Comment by ronag** [comment]
Client does not take url with path or query

**Comment by ronag** [comment]
See the docs:

> url can be a string or a URL object. It should only include the protocol, hostname, and port.

**Comment by NawafSwe** [comment]
okay got it now thanks 👍🏻👍🏻
