### ISSUE TITLE
[Docs] Pool options types states 100 connections by default, docs state 10

### ISSUE THREAD

**Issue by ctolkien** [nodejs/undici#563]
See:

![image](https://user-images.githubusercontent.com/515955/108930887-c6f63f00-769a-11eb-86e0-411ab0d3ead0.png)

vs

![image](https://user-images.githubusercontent.com/515955/108930930-e1c8b380-769a-11eb-9ad3-b5c61ba6cb8d.png)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by Ethan-Arrowood** [comment]
And I think the current API defaults to 1 @ronag -- fwiw i'm fixing this in my upcoming docs PR adding the pool.md file ~ should be up tomorrow

**Comment by ronag** [comment]
Current default is 10.

**Comment by Ethan-Arrowood** [comment]
closed by #582 ?
