### ISSUE TITLE
How to send a POST request? (example)

### ISSUE THREAD

**Issue by frzsombor** [nodejs/undici#570]
Hi! Can someone please provide a working POST request example?
I've been struggling with sending a simple POST request with undici for hours.
Tried adding post data to `body` several ways, but the server is not getting it.
Tested with https://postman-echo.com/ too, native POST request succeeds, but undici is not.

Is there anything wrong with this code?
```javascript
const { Client } = require('undici');
const client = new Client(`https://example.com`);
const qs  = require('querystring');

client.request({
  path: '/path/to/post',
  method: 'POST',
  headers: {
    myheader: 'value'
  },
  body: qs.stringify({
    data1: true,
    data2: 'asd'
  })
}, function (err, data) {
  //...
})
```

**Comment by Ethan-Arrowood** [comment]
Hi @frzsombor this might be an issue with your server. Here is an example I coded up that successfully posts a string to a native Node.js http server

```js
'use strict'
const { createServer } = require('http')
const { Client } = require('undici')

const server = createServer((request, response) => {
  request.setEncoding('utf8')
  request.on('data', console.log)

  response.end('undici')
})

server.listen(() => {
  const client = new Client(`http://localhost:${server.address().port}`)

  client.request({
    path: '/',
    method: 'POST',
    headers: {
      myHeader: 'value'
    },
    body: '?data1=true&data2=asd'
  }, (err, data) => {
    const { body } = data
    body.setEncoding('utf8')
    body.on('data', console.log)
  })
})
```

**Comment by frzsombor** [comment]
Thanks for the quick, detailed help! I haven't had time to test it yet, but I already noticed that I've missed the first question mark '?' character from the beginning of the data string, maybe that caused the issue. I've modified the title of the issue to be more search friendly for those who are looking for a POST example.
