### ISSUE TITLE
Turn into mono repo?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#573]
Discussed with @Ethan-Arrowood. Would be nice if we could split undici into a mono repo that publishes multiple packages. In particular undici-core that only contains Client (and dispatch). So that other packages such as undici-fetch has a minimal dependency.

**Comment by ronag** [comment]
@mcollina wdyt?

**Comment by ronag** [comment]
A bit similar to how pouchdb does it.

**Comment by mcollina** [comment]
I don't see the benefit of it. It's faster to download and install a bigger module than 2 small modules of equal sizes :/.

I would add fetch() to undici instead.

**Comment by Ethan-Arrowood** [comment]
> I don't see the benefit of it. It's faster to download and install a bigger module than 2 small modules of equal sizes :/.
> 
> I would add fetch() to undici instead.

One additional note I'd make is that users would only ever have to install the part they need. I.e. request or fetch or stream or whatever. They'd all depend on "core". + if a library like Got or Axios wanted to base their APIS on undici they'd only have to install "core" We could also still export and publish a "undici" which exposes all of the available things.

**Comment by mcollina** [comment]
Let's revisit when such a use case shows up. I've received praise for undici not having dependencies for example.
