### ISSUE TITLE
Charterining Undici as a full working group

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#580]
I think it's time we charter Undici as a Node.js Working group, and maybe start having a biweekly or monthly sync to track development. There is a lot of progess being done in a short amount of time, which is amazing.

**Comment by mcollina** [comment]
cc @Ethan-Arrowood @dnlup @ronag

**Comment by Ethan-Arrowood** [comment]
I'd love this - happy to help charter as well.

**Comment by dnlup** [comment]
Sounds good to me 💪

**Comment by Ethan-Arrowood** [comment]
I'm going to start on the process detailed [here](https://github.com/nodejs/TSC/blob/main/WORKING_GROUPS.md) now

**Comment by ronag** [comment]
SGTM

**Comment by Ethan-Arrowood** [comment]
🚀

**Comment by delvedor** [comment]
I don't have a lot of time, but I would love to help!

**Comment by Ethan-Arrowood** [comment]
@ronag & @mcollina can the folks in this thread all be added to Undici as collaborators so we can help out with issue and pr management?

**Comment by mcollina** [comment]
done!
