### ISSUE TITLE
Feature: ability to ignore errors (strict: false)

### ISSUE THREAD

**Issue by csvan** [nodejs/undici#581]
We are seeing some errors from Undici which do not occur under any other client, e.g.

```
code: "UND_ERR_CONTENT_LENGTH_MISMATCH"
error: "Internal Server Error"
message: "Request body length does not match content-length header"
statusCode: 500
```

I have been told Undici is stricter with regard to the HTTP spec than other clients, and I think that's great. However, for the sake of compatibility with existing ecosystems, it would be great to be able to configure undici to ignore some (or all) such errors. This would let organisations make a gradual migration, or handle edge cases where these errors are not meaningful.

**Comment by mcollina** [comment]
If it's possible, I think we should do it (as long as it is disabled by default). The more popularity Undici gains the more these kind of issues will appear.

**Comment by ronag** [comment]
So basically something like a `strict: false` options? PR welcome.

**Comment by simoneb** [comment]
How would this work?

- identify which errors should be turned into warnings when strict: false
- check the value of the strict option when such an error is about to be thrown
- turn it into a warning if strict: false
- use process.emitWarning in Node and console.warn in the browser

Thoughts?

**Comment by mcollina** [comment]
I think we can just adopt a simple strategy for this:

1) Identify when `UND_ERR_CONTENT_LENGTH_MISMATCH` is being generated
2) Write a test for a new option `strictContentLength`: it can be `true` or `false`, default `true`. When this option is `false`, the error should not be generated.
3) Make the test pass.

(Undici does not support browsers).

**Comment by csvan** [comment]
From the perspective of a developer which uses Undici but isn't familiar with the internals, I imagine something like:

`strict: false` - do not throw on any of the errors specified in https://github.com/nodejs/undici#undicierrors, but (optionally) log a warning.

```
strict: [ 'UND_ERR_CONTENT_LENGTH_MISMATCH', 'UND_ERR_TRAILER_MISMATCH' ]
```

^ throw on the listed errors, optionally log a warning for all the other ones.

**Comment by simoneb** [comment]
@csvan I agree with the approach with the exception (sorry for the pun) that I don't believe that all those errors qualify as possible warnings. e.g. `NotSupportedError` will (I assume) prevent undici from working altogether

**Comment by csvan** [comment]
@simoneb I see, I wasn't familiar with all of them or what they signified unfortunately. Allowing the developer to ignore a subset of them would still be very helpful.

**Comment by simoneb** [comment]
Working on this in https://github.com/nodejs/undici/pull/586

**Comment by simoneb** [comment]
> I think we can just adopt a simple strategy for this:
> 
> 1. Identify when `UND_ERR_CONTENT_LENGTH_MISMATCH` is being generated
> 2. Write a test for a new option `strictContentLength`: it can be `true` or `false`, default `true`. When this option is `false`, the error should not be generated.
> 3. Make the test pass.
> 
> (Undici does not support browsers).

@mcollina this is what I've done in #586 and there's one thing I could use some input on. I basically copied the tests from the existing test file which was testing that an error was generated when content-length mistmatches. There are 2 tests which are streaming data and sending 2 requests. With `strictContentLength` disabled the second request always fails anyway. If I keep the two requests in the same file the second fail, if I split them into 2 tests and execute them individually, both succeed. It seems that the two requests executed on the same client are interacting with each other in unexpected ways. 

It's quite likely I'm missing something, but this may be a bug too.

**Comment by mcollina** [comment]
> There are 2 tests which are streaming data and sending 2 requests. With strictContentLength disabled the second request always fails anyway. If I keep the two requests in the same test the second fails, if I split them into 2 tests and execute them individually, both succeed. It seems that the two requests executed on the same client are interacting with each other in unexpected ways. See here and the following test. They're the same, just with the two requests swapped (one commented, the other not).

This is the reason why we ended up creating an error for the request. Some other changes will be needed.

**Comment by simoneb** [comment]
> This is the reason why we ended up creating an error for the request. Some other changes will be needed.

Makes sense, thanks for confirming. I'll have a closer look
