### ISSUE TITLE
🧹 repo housekeeping 

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/undici#584]
Now that we have an @nodejs/undici team we should probably put some effort into cleaning up this repo. Some general things that come to mind include:

- [x] issue templates
- [x] pr templates
- [x] enable discussions (for help requests)
- [x] update labels
- [x] groom existing issue list
- [x] is LICENSE, CONTRIBUTING, and CODE_OF_CONDUCT all up to date? ~(docs intentionally omitted since thats a WIP change)~
- [ ] (optional) establish recurring team meetings
- [x] (optional) establish projects/milestone for undici major releases

Anything else I'm missing?

**Comment by mcollina** [comment]
Put the names of everybody in the README.

**Comment by Ethan-Arrowood** [comment]
Should we have a community space like Discord? Or will GitHub discussions suffice to start?

**Comment by mcollina** [comment]
We can have a channel in the Node.js slack or the Open.js slack :)

**Comment by Ethan-Arrowood** [comment]
> We can have a channel in the Node.js slack or the Open.js slack :)

We should link these - I think I'm only in the OpenJS Foundation slack

**Comment by joesepi** [comment]
I created a Slack channel in OpenJS Slack: #nodejs-undici

For those who want to join OpenJS Slack: https://slack-invite.openjsf.org/

The benefit of using OpenJS Slack is that it is paid and does not have message limits. ✌️

**Comment by dnlup** [comment]
thanks @joesepi

**Comment by Nytelife26** [comment]
Would it be prevalent to have an IRC as well as slack? IRC is a lot more accessible, especially to those that have opted against using slack and other similar modern stacks for various reasons.

Just a thought :) I can also PR in various templates. I'm not a member and so unsure of what the team would ideally like this to look like, however I can make a start.

**Comment by mcollina** [comment]
I'm in the node-undici channel on FreeNode.

Thanks for taking a stab to the templates!

**Comment by Nytelife26** [comment]
I wasn't aware there was an undici freenode channel, nice, I'll join later :)

And, no worries! Proofreading and writing is a large part of what I do (mostly documentation usually) so I'm happy to put that forward. As I'm just starting out here but have great interest in this project I'll help in any way possible.

**Comment by mcollina** [comment]
> I wasn't aware there was an undici freenode channel, nice, I'll join later :)

I just created it now, lol.

**Comment by ronag** [comment]
Can't we stick with slack? There is too many places now :/.

**Comment by mcollina** [comment]
Slack's ok.

**Comment by Ethan-Arrowood** [comment]
Closing since I think we've completed everything in the existing list. I think the issue list could use another scan. We might want to enable something like stale-bot so we can start auto closing stale issues. Great work everyone looking forward to the success of the v4 release!
