### ISSUE TITLE
dispatch semver major change ideas

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#590]
This is just a list of ideas for optimizing dispatch by changing the API. Mostly enabled by https://github.com/nodejs/undici/pull/575/files.

- `onBody` buffer must be handled synchronously or copied.
- `rawHeaders` is an array of buffers instead of strings.
- Add `onHeader` (s) which must be handled synchronously or copied? Remove headers argument from `onHeaders` and `onComplete`. Rename `onHeaders` to `onStatus` (or something).

**Comment by mcollina** [comment]
I would go with whatever increase the throughput. The only caveat is not have a regression in `request` and the others.
