### ISSUE TITLE
Best practice for following redirects?

### ISSUE THREAD

**Issue by viglucci** [nodejs/undici#591]
What is the best practice for following redirects when using `undici`?

I don't seem to see anything in the README about following redirects, is that correct, or have I missed something?

If there is no direct support for following redirects then I am thinking that following a redirect is a higher-level concern than a concern of `undici`, in that it would be expected that a consumer of `undici` would inspect the response and if it contains a `location` header perform their own subsequent request. Is that understanding correct of how redirects would be expected to be handled?

**Comment by ronag** [comment]
Redirects is something we currently expect to be handled on a higher level.

**Comment by viglucci** [comment]
Thanks for the quick response! It would be great to see `unidici` support following redirects directly but I also understand that it may go against the focus and nature of the library.

I'll close this issue as my question has been answered.
