### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/undici#594]
Refs: https://github.com/nodejs/node/issues/33864

I don't think the rename will have much of an effect on the ongoing work, and I don't think there are external dependencies on this repo/branch name.

Any concerns with me updating the primary branch to main ?

**Comment by delvedor** [comment]
Guide from GitHub on how to do it: https://github.com/github/renaming

**Comment by mcollina** [comment]
> Any concerns with me updating the primary branch to main ?

Not at all! Ship it.

**Comment by mhdawson** [comment]
Done
