### ISSUE TITLE
`Agent` is missing closed and destroyed properties

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#607]
`Agent` should provide the `closed` and `destroyed` properties similar to `Client`.

**Comment by yashshah1** [comment]
I'd like to work on this 👋

**Comment by mcollina** [comment]
go for it!

**Comment by yashshah1** [comment]
I have one quick question, might be quite trivial, so bear with me.
Do we want the `Agent` class in `lib/agent.js` to expose the `closed` and `destroyed` properties from `this[kFactory]` (which is either an instance of `Client` or `Pool`), or do we want to re-implement these properties?

**Comment by ronag** [comment]
the closed/destroyed is totally unrelated to this[kFactory].

**Comment by yashshah1** [comment]
My editor has been making a lot of changes because of my prettier config, the major contributor being the lack of semi-colons. Two questions:
- Why not enforce semi-colons?
- Is there a project-wide formatting setting that I can import to avoid this from happening?
