### ISSUE TITLE
`Agent` `destroy` and `close` should have same signature as `Client`

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#609]
`Agent.destroy()` should be `Agent.destroy(err[, callback])`
`Agent.close()` should be `Agent.destroy([callback])`

Basically the same as for `Client` and `Pool`

**Comment by sharat9211** [comment]
` close (callback) {
    const closePromises = []
    for (const pool of this[kCache].values()) {
      closePromises.push(pool.close())
    }
    if (callback === undefined) {
      return Promise.all(closePromises)
    }
    if (typeof callback !== 'function') {
      throw new InvalidArgumentError('callback must be a function')
    }
    Promise.all(closePromises)
      .then(() => callback())
      .catch((err) => callback(err))
  }`
  I hope something like this is what we are looking at.

**Comment by ronag** [comment]
Fixed
