### ISSUE TITLE
Move undici global methods out of Agent docs

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#610]
They don't really have anything to do with Agent per say and it would be nice if this is the page that most users start with and don't have to worry about the other  details.

i.e. a page with:

```
# undici.request
# undici.stream
# undici.pipeline
# undici.upgrade
# undici.connect
```

is the only thing I think 90% of users need. Maybe should be the index page?

**Comment by mcollina** [comment]
I agree.

**Comment by Ethan-Arrowood** [comment]
Good idea!

**Comment by ShogunPanda** [comment]
I can confirm it was mess for me to follow docs when starting using undici.

**Comment by Ethan-Arrowood** [comment]
I noticed these got added to the main readme - closing this issue now
