### ISSUE TITLE
Agent connect/disconnect ambiguous

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#612]
The connect and disconnect  events are a little weird at the moment.

They both pass a "client" argument but it's unclear what exactly this is, e.g. in the case of `Agent` is it a `Pool` instance of `Client` instance? i.e. inner or outer? 

Also makes it a little hard to reason about. 

I think the current behavior is not correct since it passes a client instance instead of pool.

**Comment by ronag** [comment]
@nodejs/undici

**Comment by mcollina** [comment]
> I think the current behavior is not correct since it passes a client instance instead of pool.

The behavior is somewhat correct because in `Agent.prototype.get()` we can return either a Client or a Pool depending on `connections`. The signature of the event is the same because they try to be identical.

---

These events are useful for debugging and diagnosing what's happening. The do not have a real use case in mind so it's a bit hard to refactor them.

**Comment by ronag** [comment]
> The behavior is somewhat correct because in Agent.prototype.get() we can return either a Client or a Pool depending on connections. The signature of the event is the same because they try to be identical.

But in the current case the connect/disconnect events will always emit the inner most client, i.e. not the Pool.

**Comment by dnlup** [comment]
I think the problem is that the `Pool` is just forwarding `Clients` events:

* https://github.com/nodejs/undici/blob/c604e172fda9f11d1908e0cd6ebfad43c889f3e8/lib/client-pool.js#L82

Maybe we should emit a `disconnect` event only when all clients have disconnected? Or use a custom event?

**Comment by ronag** [comment]
> I think the problem is that the Pool is just forwarding Clients events:

Whether it's a problem or not depends a little on how we expect it to work. Which is what I'm unsure about.

**Comment by dnlup** [comment]
> > I think the problem is that the Pool is just forwarding Clients events:
> 
> Whether it's a problem or not depends a little on how we expect it to work. Which is what I'm unsure about.

How are you using this event now? Why is it confusing for you? Do you have do access the `Pool` instance when this event is emitted?

**Comment by ronag** [comment]
> How are you using this event now? Why is it confusing for you? Do you have do access the Pool instance when this event is emitted?

I'm using it to log connections/disconnections (per socket/Client). However, @mcollina seems to expect it to emit `Pool` instances.

**Comment by ronag** [comment]
If it's to ambiguous/confusing I would even prefer removing it.

**Comment by mcollina** [comment]
> I'm using it to log connections/disconnections (per socket/Client). However, @mcollina seems to expect it to emit Pool instances (which it doesn't).

I didn't state that. I clarified that the reason why it has the client as the first parameter is because it's emitted by `Pool` as well and `Agent.prototype.get()` can return either of them.

I think maintaining this is useful. I would not change this until we have clearer requirements.

**Comment by ronag** [comment]
Ok. Then we are happy with the behavior? I seem to have misunderstood Mattea.

**Comment by dnlup** [comment]
I am ok with keeping things as they are.

**Comment by ronag** [comment]
I'm re-opening this as I want to give it some more thought-
