### ISSUE TITLE
Docs site should correspond to latest version published to npm

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#630]

**Comment by ronag** [comment]
@dnlup 

> This could be mitigated if we used another branch maybe (although there would be an additional manual step to push the docs on that branch for now). Just thinking out loud

**Comment by ronag** [comment]
@Ethan-Arrowood wdyt?

**Comment by Ethan-Arrowood** [comment]
Yeah I agree; I think what would be easier is if we could keep the `main` branch as the source of truth for the API. It should match NPM. Any in-progress work or next major work should have its own branch (like `v4` or `dev`)

**Comment by mcollina** [comment]
I agree with @Ethan-Arrowood!

**Comment by ronag** [comment]
@mcollina Would you mind doing this? I'm fine with whatever you decide in terms of naming etc.

**Comment by mcollina** [comment]
> @mcollina Would you be ok with doing this? I'm fine with whatever you decide in terms of naming etc.

The best approach is to ship v4 asap and then do semver-major changes off the next branch.
