### ISSUE TITLE
agent can leak clients

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#631]
```js
      if (this.connected === 0 && this.size === 0) {
        this.off('disconnect', agent[kOnDisconnect])
        agent[kClients].delete(this.origin)
      }
```

Is not correct unfortunately. A client can disconnect due to an error and then reconnect. However, in that case the agent will incorrectly remove the client from it's own pool.

**Comment by ronag** [comment]
TBH I think the best and easiest option is going back to the `WeakRef` implementation. @mcollina @dnlup wdyt?

**Comment by ronag** [comment]
Probably not a problem.

**Comment by mcollina** [comment]
It's a bug but not a leak.

**Comment by dnlup** [comment]
> ```js
>       if (this.connected === 0 && this.size === 0) {
>         this.off('disconnect', agent[kOnDisconnect])
>         agent[kClients].delete(this.origin)
>       }
> ```
> 
> Is not correct unfortunately. A client can disconnect due to an error and then reconnect. However, in that case the agent will incorrectly remove the client from it's own pool.

Would a check on `pending` or `busy` help? Otherwise, can we expose something that signals that the disconnection should, let's say, ignored?
