### ISSUE TITLE
Could we use https://github.com/node-ffi-napi/weak-napi for Node < 14?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#632]
Would be nice to be able to use `WeakRef` in Node. Now that we are dropping Node 10 support it would be possible to use them we use https://github.com/node-ffi-napi/weak-napi as a fallback for Node 12.

Would this be ok? Or something we want to avoid?

It's not that important but it would make some state management easier and less bug prone.

**Comment by ronag** [comment]
@mcollina

**Comment by mcollina** [comment]
I would prefer not to have any binary dependency.
