### ISSUE TITLE
Be more stricter in regards to URLs

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#643]
Currently, passing `'https://example.com/%AA'` doesn't throw. A `decodeURI(string)` can fix that - but I guess it might have a performance impact.

**Comment by ronag** [comment]
Won't the server error?

**Comment by szmarczak** [comment]
It depends on the server.

**Comment by dnlup** [comment]
That's a valid point. Does `fetch` do that by default (I am looking into it, but if someone already knows, it helps)? I am not sure if I would enable this strict validation by default if there are performance impacts and `fetch` doesn't provide it. We could measure the impact in the meantime. FWIW, the agent uses `URL` to parse atm if I am not mistaken:

* https://github.com/nodejs/undici/blob/main/index.js#L34
* https://github.com/nodejs/undici/blob/main/lib/core/util.js#L26

**Comment by ronag** [comment]
Actually just the global methods use URL parsing and Agent but only when redirecting.

**Comment by ronag** [comment]
I'm not that worried about adding more parsing to the global methods. Since they are more for convenience and there are faster alternatives.

**Comment by dnlup** [comment]
> Actually just the global methods use URL parsing and Agent but only when redirecting.

Yes, that's true. I thought that's was the scope we were discussing, sorry.

**Comment by szmarczak** [comment]
`fetch` doesn't throw, so I guess `undici` should neither.

**Comment by ronag** [comment]
What does fetch do?

**Comment by ronag** [comment]
I'm personally fine with adding this to the global api. But it does bring some perf and consistency overhead.

**Comment by szmarczak** [comment]
> What does fetch do?

The request goes through.

**Comment by ronag** [comment]
@szmarczak Current thoughts on this issue?

**Comment by szmarczak** [comment]
I think we should skip this one.
