### ISSUE TITLE
dns lookup origin before picking Pool?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#644]
Let's say I have two different dns names pointing to the same server:

```
await undici.request('http://mydomain1.com') // 192.168.0.11
await undici.request('http://mydomain2.com') // 192.168.0.11
```

Currently this will unnecessarily create two different pools duplicating the connections.

Is this worth spending time on?

**Comment by ronag** [comment]
Leave it for later.

**Comment by szmarczak** [comment]
I'm not sure if this is worth doing. Most of the servers are HTTPS now which require `servername` and the server may choose to send a certificate for the subdomain only.
