### ISSUE TITLE
Fix type definitions

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#651]
4.0 has some api changes that are not reflect in type definitions

**Comment by ronag** [comment]
@Ethan-Arrowood Any chance you will have to look at this? I think we could be ~1-2 week away from a 4.0 release.

**Comment by Ethan-Arrowood** [comment]
@ronag happy to take a pass on this tonight. Do you see any more large API changes coming before v4? 

FWIW I'll be completely offline Friday 9th -> Friday 16th

**Comment by ronag** [comment]
I don’t see any more major changes

**Comment by Ethan-Arrowood** [comment]
I didn't see any discrepancies in my review. Validated the type tests and everything seems okay. Types generally don't follow semver anyways so when 4.0 launches and there are issues discovered with the types, have folks submit fixes and then you just have to bump the patch. Of course, I'll be back in a weeks time and can help on anything uncovered 😄
