### ISSUE TITLE
Docs need cleanup and fixes

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#652]
Broken links and misc cleanup and formatting.

**Comment by ronag** [comment]
@Ethan-Arrowood Any chance you will have to look at this? I think we could be ~1-2 week away from a 4.0 release.

@dnlup Maybe we should also try and help out here? I'll get to it once I'm done with https://github.com/nodejs/undici/pull/689.

**Comment by Ethan-Arrowood** [comment]
Similar to TypeScript issue, yes happy to take a pass at this today/tomorrow now that it seems the largest API changes are completed.

**Comment by Ethan-Arrowood** [comment]
👀 i didn't realize just how much the API grew in the last couple weeks. I mean i knew we were adding things but looking at all the code all together -- whew its a lot!

**Comment by mcollina** [comment]
There are many people working on this release. You might not have noticed, but this repo is _the most active_ in the entire org.
