### ISSUE TITLE
Favicon is missing on https://undici.nodejs.org/#/

### ISSUE THREAD

**Issue by dgonzalez** [nodejs/undici#657]
## Bug Description

Favicon is missing on https://undici.nodejs.org/#/

**Comment by mcollina** [comment]
What should we put in there? I would just use what Node.js uses. Could you set it up?

**Comment by ronag** [comment]
PR welcome

**Comment by delivey** [comment]
Opened PR. https://github.com/nodejs/undici/pull/758

**Comment by delivey** [comment]
PR merged and favicon is on the live site. This issue should be closed.
