### ISSUE TITLE
does not provide an export named 'Agent'

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#671]
When running test locally on Node 15.13 I get the following error:

```js
test/esm-wrapper.js 2> SyntaxError: The requested module 'file:///Users/ronagy/GitHub/public/undici/index.js' does not provide an export named 'Agent'
test/esm-wrapper.js 2>     at processImmediate (node:internal/timers:464:21)
 FAIL  test/esm-wrapper.js 573.635ms
  command: /Users/ronagy/.nvm/versions/node/v15.13.0/bin/node
  args:
    - -r
    - /Users/ronagy/GitHub/public/undici/node_modules/esm/esm.js
    - --expose-gc
    - test/esm-wrapper.js
  exitCode: 1
  signal: null
```

However, it is not a problem on CI. I'm a little confused by the error since it **does** export `Agent`. What's going on?

**Comment by ronag** [comment]
@Ethan-Arrowood any ideas?

**Comment by Ethan-Arrowood** [comment]
Hm I'm not sure, this might be an esm issue

**Comment by jarrodconnolly** [comment]
I also ran into this. It took an `npm install` to fix, as it was happening when still running tap 14. I missed running that when the package was upgraded to tap 15.

**Comment by ronag** [comment]
That was it. Thanks!
