### ISSUE TITLE
Investigate if we can use fuzzying

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#677]
https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/jsfuzz

**Comment by ronag** [comment]
Maybe @jonnydgreen?

**Comment by jonnydgreen** [comment]
Yep, very happy to do some investigating on this - I can make a start tomorrow :)

**Comment by jonnydgreen** [comment]
Just wanted to say that I haven't forgotten about this - I was on holiday for the second half of last week :) I've been running some basic investigations here and getting familiar with the jsfuzz API https://github.com/jonnydgreen/undici-fuzzing and will write up my experiences and anything I found in this issue

**Comment by ronag** [comment]
@jonnydgreen this is an issue that would have been nice to catch through fuzzing https://github.com/nodejs/undici/pull/738

**Comment by jonnydgreen** [comment]
Cool, understood - I will look into that as well!

**Comment by ronag** [comment]
@jonnydgreen did you get anywhere with this?

**Comment by jonnydgreen** [comment]
My apologies, this dropped off my radar. I will block out some time this weekend to make some significant progress but completely understand if you wanted to work on this yourself!

**Comment by ronag** [comment]
I don't have any plans working on it. Was just curious if you came to any conclusion in regards to whether it's feasible or not.

**Comment by jonnydgreen** [comment]
I did have some initial thoughts so far and will expand on the feasibility of these this weekend:
 - Automating in the CI would be tricky as the tool runs indefinitely, so it might need to run manually like the benchmarks. However, if can make it gracefully terminate (if there are no unexpected errors) after a short amount of time this could be run in a scheduled GH action if we wanted to automate this.
 - For constructing fuzzing scenarios, we'll probably need to provide some util functions to make constructing different fuzzing scenarios easier.

**Comment by jonnydgreen** [comment]
Quick update! I've been looking into this this weekend with a main focus on creating a generic solution for different fuzzing examples as well as trying to improve the creation of different flows depending on the input buffer - I'll continue this exploration this week :) I'm pausing the CI side of things for now while I look at the raw functionality and get the key bits nailed down

**Comment by jonnydgreen** [comment]
I think I have some key bits of functionality sorted with hopefully a nice way running a series of different functions within the fuzzer, I'll push up the code once I've tidied it up a bit and with my analysis to go with this!

**Comment by jonnydgreen** [comment]
Hi! :) Here is my latest exploration if you wanted to take a look: https://github.com/jonnydgreen/undici-fuzzing/blob/master/Analysis.md

In summary, I think `jsfuzz` is pretty good and could provide all the core bits required for fuzzing in undici. I've also pushed up some example code here: https://github.com/jonnydgreen/undici-fuzzing. I've tried to keep things simple so not to distract from the core exploration

Most of the core questions that I had have been answered (although I still have a couple of open questions). I was not able to generically create tests that would've caught the issue you mentioned above, but I think I've found a middle ground (by being slightly more specific with the fuzz functions and splitting into client and server functions) in my test repo that should cast a wide net over potential issues if they exist

**Comment by ronag** [comment]
Cool I'll take a look as soon as I have time. Might be a week or so though.

**Comment by jonnydgreen** [comment]
No problem and for sure! :) I'm fairly busy this week, but can make a start next Monday if that works for you?

**Comment by jonnydgreen** [comment]
Quick update, still working on a PR with some basic fuzzing that I started today - ran into a couple of issues which I've just smoothed out so will aim to get it in tomorrow evening so we can continue improving! :)

**Comment by jonnydgreen** [comment]
@ronag Do you reckon we can close this now that this PR has been merged? https://github.com/nodejs/undici/pull/821
