### ISSUE TITLE
Can we use llhttp_pause instead of the queue hack in Client?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#681]
Basically we would like to be able to stop llhttp from invoking further callbacks. Currently we achieve this by using a somewhat hacky solution with `Parser.queue`.

Can we call `llhttp_pause` from inside `wasm_on_headers_complete` and `wasm_on_body`? Or maybe it's possible to just return `constants.ERROR.PAUSED`?

**Comment by ronag** [comment]
@dnlup

**Comment by dnlup** [comment]
It should be sufficient just to return `HPE_PAUSED` in the user's callbacks:

https://github.com/nodejs/llhttp/blob/a620012f3fd1b64ace16d31c52cd57b97ee7174c/src/native/api.h#L151

Then we should resume as needed calling `llhttp_resume`

**Comment by ronag** [comment]
How does that work with e.g. `kOnHeadersComplete` which needs to return 2,1,0 depending on upgrade, ignore or normal?

**Comment by ronag** [comment]
I think I know.
