### ISSUE TITLE
parser error reason reading is not safe

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#684]
If execute e.g. returns `HPE_PAUSED` then the logic for reading the reason string goes crazy.

This can be reproduced by making `kOnBody` return `21` at the end and running `npm run test`.

```
Invalid EOF statePausedHPE_OKHPE_INTERNALHPE_STRICTHPE_LF_EXPECTEDHPE_UNEXPECTED_CONTENT_LENGTHHPE_CLOSED_CONNECTIONHPE_INVALID_METHODHPE_INVALID_URLHPE_INVALID_CONSTANTHPE_INVALID_VERSIONHPE_INVALID_HEADER_TOKENHPE_INVALID_CONTENT_LENGTHHPE_INVALID_CHUNK_SIZEHPE_INVALID_STATUSHPE_INVALID_EOF_STATEHPE_INVALID_TRANSFER_ENCODINGHPE_CB_MESSAGE_BEGINHPE_CB_HEADERS_COMPLETEHPE_CB_MESSAGE_COMPLETEHPE_CB_CHUNK_HEADERHPE_CB_CHUNK_COMPLETEHPE_PAUSEDHPE_PAUSED_UPGRADEHPE_USERDELETEGETHEADPOSTPUTCONNECTOPTIONSTRACECOPYLOCKMKCOLMOVEPROPFINDPROPPATCHSEARCHUNLOCKBINDREBINDUNBINDACLREPORTMKACTIVITYCHECKOUTMERGEM-SEARCHNOTIFYSUBSCRIBEUNSUBSCRIBEPATCHPURGEMKCALENDARLINKUNLINKSOURCEPRIDESCRIBEANNOUNCESETUPPLAYPAUSETEARDOWNGET_PARAMETERSET_PARAMETERREDIRECTRECORDFLUSHQXep������4K^t�����
                                                                                                                                                            (/38=AIQW\aglu����������������"+16<ESajqPause on CONNECT/Upgradeloseeep-aliveContent-Length overflowInvalid character in Content-Lengthchunked
                                                          
> 180 |       return new HTTPParserError(message, code)                                                          
```

**Comment by ronag** [comment]
@dnlup

**Comment by dnlup** [comment]
Has this happened with only `HPE_PAUSED`?

**Comment by ronag** [comment]
I've only tried with HPE_PAUSED. But there are other return codes that might or might not suffer from the same problem.

**Comment by dnlup** [comment]
I think `HPE_PAUSED` should be explicitly handled, in Node the error reason is set accordingly when pausing:

* https://github.com/nodejs/node/blob/master/src/node_http_parser.cc#L921

Just thinking out loud, I have to work on it. I think this is related to the work in https://github.com/nodejs/undici/pull/683 , right?

**Comment by ronag** [comment]
I think the correct way here is to determine whether a reason is available or not and not guess whether there is a reason or not.

**Comment by dnlup** [comment]
Is this still an issue after meging #683 ?

**Comment by ronag** [comment]
It's a minor issue. I still think we should be able to check if there is a reason and have a safe way to read it.

**Comment by dnlup** [comment]
> It's a minor issue. I still think we should be able to check if there is a reason and have a safe way to read it. Doesn't get_reason return null or something if there is no reason available?

I'll check and see what we can do.

**Comment by ronag** [comment]
Is it enough to check if the value returned from get_reason is `null`?

**Comment by dnlup** [comment]
> Is it enough to check if the value returned from get_reason is `null`?

I am not sure it returns `null`. In C I am sure it does, but from the tests, I see it always has a numeric value. I can't reproduce this issue with the latest changes, though. That could be the main reason.

**Comment by dnlup** [comment]
I think we should check for `0`

**Comment by ronag** [comment]
Check for falsy?
