### ISSUE TITLE
`TestExclude is not a constructor`

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#685]
When running `npm run coverage` I get the following error:

```
TestExclude is not a constructor
```

**Comment by ronag** [comment]
Does anyone else have this error? Any ideas what might cause it? @dnlup @Ethan-Arrowood

**Comment by dnlup** [comment]
No, I don't this error.

```bash
undici@3.3.1
└── tap@15.0.2 
```
```bash
$ node -v
v14.6.0
```

What's your env?

**Comment by ronag** [comment]
v15.13.0

**Comment by dnlup** [comment]
> v15.13.0, main branch

I tried this version locally, installed it with `volta`, and still no errors. I'll try to compile the latest one. I suspect it is something involving Istanbul.

**Comment by dnlup** [comment]
I know it's silly, but have you tried to re-install all the deps from scratch already?

**Comment by ronag** [comment]
Full re-install helped! Sorry to waste your time.

**Comment by dnlup** [comment]
> Full re-install helped! Sorry to waste your time.

No worries, happy you resolved 😉
