### ISSUE TITLE
Upgrade llhttp

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#690]
v5.1.0 is released.

Could we also write some docs as to how we update llhttp in undici?

**Comment by dnlup** [comment]
> Could we also write some docs as to how we update llhttp in undici?

That shouldn't go into the user's docs, right? I think it should be something related to a `CONTRIBUTING` section.

**Comment by mcollina** [comment]
> > Could we also write some docs as to how we update llhttp in undici?
> 
> 
> 
> That shouldn't go into the user's docs, right? I think it should be something related to a `CONTRIBUTING` section.

Yes!
