### ISSUE TITLE
Weird test flakiness

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#710]
I sometimes get weird errors when running tests... e.g.

```
 FAIL  test/client-upgrade.js
 ✖ should be equivalent

  test/client-upgrade.js              
  103 |     })                        
  104 |                               
> 105 |     t.same(headers, {         
      | ------^                       
  106 |       hello: 'world',         
  107 |       connection: 'upgrade',  
  108 |       upgrade: 'websocket'    

  --- expected                
  +++ actual                  
  @@ -1,5 +1,5 @@             
   Object {                   
  +  "grade": "upgra",        
     "connection": "upgrade", 
     "upgrade": "websocket",  
  -  "hello": "world",        
   }                          

  test: test/client-upgrade.js basic upgrade promise
  stack: |
    Server.<anonymous> (test/client-upgrade.js:105:7)
```

**Comment by ronag** [comment]
Notice

`+"grade": "upgra"`
`-"hello": "world",``

"grade" and "upgra" are of the correct length, but either the `memory.buffer` or the `at` seems corrupted :/.

**Comment by ronag** [comment]
@indutny do you have any ideas as to what could be happening here?

**Comment by ronag** [comment]
I don't really see that we could be doing something here. The `wasm_on_header_field` and `wasm_on_header_value` are rather trivial.

**Comment by ronag** [comment]
I've seen this kind of error several times while running tests locally. Not this exact variant but similar in the sense of weird values.

**Comment by ronag** [comment]
> Notice
> 
> `+"grade": "upgra"`
> `-"hello": "world"`
> 
> `"grade"` and `"upgra"` are of the correct length, but either the `memory.buffer` or the `at` seems corrupted :/.

Consider a buffer that looks like this:

`"upgrade",\n"upgrade": "websocket"`

The relative indices corresponds with:

`"hello" : "world"`

**Comment by indutny** [comment]
Could it be memory pointing to some buffer that gets overwritten?

**Comment by indutny** [comment]
Yeah, looks like you don't copy the data that you get in `onHeader` and just use `Buffer.from` to create a view over that part of memory. This can go wrong when memory gets overwritten.

**Comment by ronag** [comment]
Ah! Buffer.from doesn’t copy?

**Comment by indutny** [comment]
Not if its argument is `ArrayBuffer`: https://nodejs.org/api/buffer.html#buffer_static_method_buffer_from_arraybuffer_byteoffset_length
