### ISSUE TITLE
Tree-Shaking

### ISSUE THREAD

**Issue by tbnritzdoge** [nodejs/undici#721]
## Bug Description

On the latest commit on master it is impossible to tree shake and reduce bundle size in my library due to the wasm files.

### Additional context

This is paramount to any project seeking to use undici as the underlying wrapper as tree shaking is the only way to keep the size down as undici is a fairly large library.

**Comment by ronag** [comment]
Why would the wasm make tree shaking impossible? Sounds more like a problem with your bundled. Also why are you tree shaking a backend application?

**Comment by mcollina** [comment]
What's your use case?

**Comment by Nytelife26** [comment]
> Why would the wasm make tree shaking impossible? Sounds more like a problem with your bundler.

You have to bundle the WASM build with the library to make it work since the library functions will not work without the WASM build present. Tree shaking does not become impossible, but very difficult without needing to bundle the WASM build, which drastically increases bundle size. It is also currently impossible to tree-shake WASM, since very few packages allow for it to be bundled at all (Parcel being the main one), and those are not currently capable of tree shaking it.

> What's your use case?

This applies to any library using undici and tree shaking/bundling instead of using it as a raw dependency.

**Comment by tbnritzdoge** [comment]
> What's your use case?

We wrap undici and a more simple to use library which fits the spec of the library we already used in our codebase (centra).

**Comment by ronag** [comment]
I’m still confused what the problem here is and what you suggest we do about it?

Are you developing universal (back + front) code and you expect tree shaking to totally remove undici for the front end? And for some reason the wasm interferes with that?

**Comment by Nytelife26** [comment]
> Are you developing universal (back + front) code and you expect tree shaking to totally remove undici for the front end? And for some reason the wasm interferes with that?

No. We're using tree shaking to reduce the bundle size of the library and not require undici as a raw dependency. WASM interferes with that because we must package the WASM with the library and WASM is not currently tree-shakeable.

**Comment by mcollina** [comment]
It's not exactly clear what's the ask. We can't remove the wasm part as it's needed to parse the HTTP headers, and node core asked us to not use internal and unsafe C++ objects to do ao.

**Comment by tbnritzdoge** [comment]
> It's not exactly clear what's the ask. We can't remove the wasm part as it's needed to parse the HTTP headers, and node core asked us to not use internal and unsafe C++ objects to do so.

We were hoping that the WASM can be removed. Although that is obviously not going to happen we probably will be able to work around it with some fancy bundling stuff. Thanks for the help and keep up the great work.
