### ISSUE TITLE
test/client-pipeline.js 2> Assertion failed

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#732]
When running test I get a `test/client-pipeline.js 2> Assertion failed` message in console.

**Comment by ronag** [comment]
I have no idea where this might be coming from. @dnlup any ideas?

**Comment by dnlup** [comment]
> I have no idea where this might be coming from. @dnlup @mcollina any ideas?

Not atm, I saw this too a while ago. I thought I missed something in the process.
