### ISSUE TITLE
Change benchmarking framework

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#736]
As @ronag posted in https://github.com/nodejs/undici/pull/729#issuecomment-818261572, a significant part of the benchmarks is spent __inside the `benchmark` library__, making our benchmarks less useful: 

![Screenshot 2021-04-13 at 11 05 48](https://user-images.githubusercontent.com/52195/114527369-35da2800-9c48-11eb-9b94-871bd28f7fc7.png)

In the past where we had similar issues, we used https://www.npmjs.com/package/cronometro from @ShogunPanda which we developed for another _really fast_ library (https://github.com/nearform/fast-jwt).

**Comment by ronag** [comment]
Also would be nice to have results relative to a baseline (e.g. http) so that the computer performance for any specific run is less of a factor when comparing results.

**Comment by ronag** [comment]
@ShogunPanda Would you be interested in looking into this?

**Comment by ShogunPanda** [comment]
@ronag Sure, absolutely. I'll send a PR in the next few days.

**Comment by ronag** [comment]
Related https://github.com/nodejs/undici/issues/715

**Comment by ShogunPanda** [comment]
Done. See #751.
