### ISSUE TITLE
MockCLient not a constructor

### ISSUE THREAD

**Issue by kas-akram** [nodejs/undici#739]

**Comment by kas-akram** [comment]
![image](https://user-images.githubusercontent.com/79639000/114670327-81600500-9d20-11eb-8b8d-837b6489f966.png)

**Comment by ronag** [comment]
How do I reproduce?

**Comment by kas-akram** [comment]
"undici": "^3.3.3"



const { MockClient } = require("undici");
const client = new MockClient("https://www.nodejs.org");

client.intercept({
  path: "/",
  method: "GET",
}).reply(200, { "foo": "bar"});

**Comment by ronag** [comment]
MockClient was added in undici 4

**Comment by kas-akram** [comment]
Any other way i can mock for version 3?

**Comment by ronag** [comment]
Sorry, no.
