### ISSUE TITLE
Expected /HTTP

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#741]
Flaky test :/ 

```js
 FAIL  test/client-stream.js
 ✖ Expected HTTP/

  test/client-stream.js                    
  314 |       return pt                    
  315 |     }, (err) => {                  
> 316 |       t.error(err)                 
      | --------^                          
  317 |       t.equal(pt.destroyed, true)  
  318 |     })                             
  319 |   })                               

  test: test/client-stream.js stream destroy if not readable
  stack: |
    test/client-stream.js:316:9
    lib/api/api-stream.js:150:14

  Error Origin:

      }
      util.destroy(socket, new HTTPParserError(message, constants.ERROR[ret]))
---------------------------^
    }
  }

  at:
    line: 564
    column: 28
    file: lib/client.js
    function: Parser.execute
  stack: |
    Parser.execute (lib/client.js:564:28)
  type: HTTPParserError
  code: HPE_INVALID_CONSTANT
  message: Expected HTTP/

```

**Comment by ronag** [comment]
Added more info to parser error to easier debug this https://github.com/nodejs/undici/commit/7a750ba998cbc4c125f747876536655c2f7b7c02.

**Comment by ronag** [comment]
@dnlup FYI

**Comment by ronag** [comment]
Looks like some kind of interference between `Client` instances. There is no special payload here.

**Comment by dnlup** [comment]
Just out of curiosity, can we try to avoid the usage of the `currentParser`  technique and go back to the previous implementation? What do you think?

**Comment by dnlup** [comment]
We are either modifying memory regions we shouldn't or maybe using the wrong parser pointer?

**Comment by szmarczak** [comment]
I can have a look a this. Just give me a few minutes.

**Comment by dnlup** [comment]
Thank yo @szmarczak

**Comment by szmarczak** [comment]
Are you able to reproduce this or it throws randomly?

**Comment by dnlup** [comment]
> Are you able to reproduce this or it throws randomly?

It is random, and apparently, it is happening only in the CI if I am not mistaken. There is work going on to introduce fuzzing, which should help. I can't find it atm 😢

**Comment by ronag** [comment]
This one happened locally for me. But haven’t been able to repro since.

**Comment by ronag** [comment]
> Just out of curiosity, can we try to avoid the usage of the `currentParser` technique and go back to the previous implementation? What do you think?

Let’s try to go back to the Map but check benchmarks. @dnlup can you try that?

**Comment by dnlup** [comment]
I'll be able to tomorrow morning, is that ok?

**Comment by ronag** [comment]
I might have a go at it tonight. I’ll give you a status update for the morning.

**Comment by szmarczak** [comment]
> it is happening only in the CI

Can I have a link please?

**Comment by dnlup** [comment]
Maybe this one:

* https://github.com/nodejs/undici/runs/2279575903?check_suite_focus=true#step:5:9313

cc @ronag

**Comment by ronag** [comment]
> Maybe this one:
> 
> * https://github.com/nodejs/undici/runs/2279575903?check_suite_focus=true#step:5:9313
> 
> cc @ronag

Nope. Not that one. I don't remember if/when I saw it on CI last time. As I said this issue was created when it happened locally.

**Comment by ronag** [comment]
Could it be related to throwing exception across the js -> wasm -> js border?

**Comment by dnlup** [comment]
> Could it be related to throwing exception across the js -> wasm -> js border?

Not sure, why do you think that?

**Comment by ronag** [comment]
> > Could it be related to throwing exception across the js -> wasm -> js border?
> 
> Not sure, why do you think that?

I have no good reason. I'm just grasping at straws.

**Comment by ronag** [comment]
I don't think we do actually throw anything across so its not relevant.

**Comment by ronag** [comment]
Could it be some kind of keep alive thing? What if the last buffer contains message eof **and** the start of the next message

**Comment by szmarczak** [comment]
> What if the last buffer contains message eof and the start of the next message?

Tested it. No error.

**Comment by szmarczak** [comment]
I wonder if the error happens after the headers have been read or before they have been read.

**Comment by szmarczak** [comment]
> There is no special payload here.

Do you mean `data` is empty?

**Comment by ronag** [comment]
> > There is no special payload here.
> 
> Do you mean `data` is empty?

Yea.

**Comment by szmarczak** [comment]
Dang, it makes no sense. I think it could be an error inside `llhttp`, but I'm not so sure.

**Comment by ronag** [comment]
I'm not sure what more we can do at the moment. I've added the `data´ argument to the parser error so if the error occurs again we might have a bit more info.

**Comment by ronag** [comment]
Maybe would be nice if there was a meaningful way to dump the llhttp state? @indutny

**Comment by indutny** [comment]
There's a way, actually. You just have to generate `llhttp` sources with `LLPARSE_DEBUG=on make` :wink:

**Comment by ronag** [comment]
Haven't seen this for a while now.
