### ISSUE TITLE
get error reason unsafe

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#748]
Somehow managed to get the following error:

```js
test/client-stream.js 1>     not ok 4 - Start offset 1768710445 is outside the bounds of the buffer
test/client-stream.js 1>       ---
test/client-stream.js 1>       stack: |
test/client-stream.js 1>         new Uint8Array (<anonymous>)
test/client-stream.js 1>         Parser.execute (lib/client.js:533:21)
test/client-stream.js 1>         Socket.onSocketData (lib/client.js:876:12)
test/client-stream.js 1>       type: RangeError
test/client-stream.js 1>       tapCaught: uncaughtException
test/client-stream.js 1>       test: stream promise get
```

This line:

```
        const len = new Uint8Array(llhttp.exports.memory.buffer, ptr).indexOf(0)
```

**Comment by ronag** [comment]
https://github.com/nodejs/undici/compare/err?expand=1

```js
tap test/client.js
```

**Comment by dnlup** [comment]
I'll try to reproduce it locally.

**Comment by dnlup** [comment]
I think this could be happening:

1. A custom error has happened
2. No custom error was set (withset_error_reason)
3. The pointer might point to a random place

We could:
1. Be sure that we set the error reason on user errors
2. Be extra safe ad wrap that block in a `try`/`catch`

This is the affected part:

```js
 } else if (ret !== constants.ERROR.OK) {
      const ptr = llhttp.exports.llhttp_get_error_reason(this.ptr)
      let message = ''
      if (ptr) {
        const len = new Uint8Array(llhttp.exports.memory.buffer, ptr).indexOf(0)
        message = Buffer.from(llhttp.exports.memory.buffer, ptr, len).toString()
      }
      util.destroy(socket, new HTTPParserError(message, constants.ERROR[ret], data))
    }
```

(Line 533 in `lib/client.js`)

Does that make sense to you?

**Comment by dnlup** [comment]
I couldn't reproduce it locally, though.

**Comment by ronag** [comment]
Now i can't repro either... is there any reasonable way to validate the value `ptr`? Do we know its valid bounds?

**Comment by ronag** [comment]
> Do we know its valid bounds?

Nope

**Comment by ronag** [comment]
Maybe just let's hope it was a fluke

**Comment by dnlup** [comment]
> Maybe just let's hope it was a fluke

We could wrap it in a try/catch, or is it too much of a hack?

**Comment by ronag** [comment]
> We could wrap it in a try/catch, or is it too much of a hack?

Yea... I would rather check the `memory.buffer` bounds in that case.

**Comment by dnlup** [comment]
Do you see anything that the Node parser does here?

https://github.com/nodejs/node/blob/master/src/node_http_parser.cc#L790

**Comment by ronag** [comment]
> Do you see anything that the Node parser does here?
> 
> https://github.com/nodejs/node/blob/master/src/node_http_parser.cc#L790

Nope, they seem to assume it always returns valid string 😕
