### ISSUE TITLE
types: index.d.ts is not exported

### ISSUE THREAD

**Issue by Anish-Shobith** [nodejs/undici#757]
## Bug Description

From what i see in the `package.json` under `files` there is option to include `.d.ts` file but unfortunately the dist or the code in npm does not include `index.d.ts`, which forces us to types from directly from the types folder which shouldn't be the case.

https://github.com/nodejs/undici/blob/29682079eeeb918a35b02a6ef06156cb8f74b2d1/package.json#L25

## Reproducible By

The way to check if `index.d.ts` is included or not by running a dry run test 
`npm publish --dry-run`

## Expected Behavior

`index.d.ts` should be exported.

https://github.com/nodejs/undici/blob/29682079eeeb918a35b02a6ef06156cb8f74b2d1/package.json#L24-L29
Fix: 
```diff
+ "*.d.ts",
+ "index.js",
- "index.(js|.d.ts)"
```

```json
  "files": [
    "*.d.ts",
    "index.(js|.d.ts)",
    "lib",
    "types",
    "docs"
  ],
```

## Logs & Screenshots

Console Logs: 

Output of log without including `index.d.ts` : https://sourceb.in/AVrVZ2g12h

![image](https://user-images.githubusercontent.com/38991749/115514863-2f7c2980-a2a2-11eb-8c74-ae433ca18b10.png)

Output of log with including `index.d.ts` : https://sourceb.in/XAbWszsZ0M
![image](https://user-images.githubusercontent.com/38991749/115515424-bcbf7e00-a2a2-11eb-905f-c95f5d6fc410.png)

## Environment

N/A

### Additional context

None

**Comment by ronag** [comment]
@Ethan-Arrowood

**Comment by ronag** [comment]
PR welcome
