### ISSUE TITLE
host header and SNI

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#764]
At the moment we currently [always override the SNI servername to what is passed in the request host header.](https://github.com/nodejs/undici/blob/main/lib/client.js#L1125-L1131) The main reason we do this is because that's what Node does. However, I'm unsure if we have to do this? Is there are any spec that defines this behavior?

I'm mostly asking because this logic adds some complexity which would be nice to avoid.

**Comment by ronag** [comment]
@szmarczak @ShogunPanda

**Comment by szmarczak** [comment]
I have never encountered an example where the servername would be different than the host.

https://tools.ietf.org/html/rfc2818#section-3

**Comment by mcollina** [comment]
Let's keep doing what node does.
