### ISSUE TITLE
client can emit disconnect without a preceding connect

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#766]
It should not be possible to emit `'disconnect'` without `'connect'`. However, it then becomes a problem of how to make connection errors visible... do we need another event? i.e. what do we do with socket errors that occur before `'connect'`.

**Comment by ronag** [comment]
Ideas? @szmarczak @dnlup @ShogunPanda

**Comment by dnlup** [comment]
I think maybe we could expose an error event.

**Comment by ronag** [comment]
> I think maybe we could expose an error event.

Problem with that is that forces user to listen to it.

**Comment by dnlup** [comment]
> > I think maybe we could expose an error event.
> 
> Problem with that is that forces user to listen to it.

That's true. This could happen anyway If we don't use disconnect and opt for another approach (being another event or a callback passed to `connect`).

**Comment by dnlup** [comment]
The big problem that I see with the `error` event is the potential uncaught exception (or maybe that's what you meant and I didn't get it)

**Comment by ronag** [comment]
Another solution is to emit connect when we start connecting.

**Comment by dnlup** [comment]
> Another solution is to emit connect when we start connecting.

If it doesn't create confusion on timing, sounds good to me.

**Comment by szmarczak** [comment]
I'm good with anything. The current solution seems fine to me.

**Comment by ronag** [comment]
It is a problem for users that use the connect/disconnect events to count the number of active connection.

**Comment by ShogunPanda** [comment]
I also second @dnlup - Let's emit error, being careful to emit only if there are listeners present.

**Comment by ronag** [comment]
@mcollina wdyt?

**Comment by mcollina** [comment]
+1
