### ISSUE TITLE
UND_ERR_ABORTED vs core AbortError?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#778]
Should we be using `AbortError` instead of `UND_ERR_ABORTED`. Node core doesn't expose `AbortError` but it's easy to shim.

I'm a little unsure how to think about this...

**Comment by ronag** [comment]
Another option is to set the `name` of `UND_ERR_ABORTED` to `AbortError`. That might give sufficient compat?

**Comment by ronag** [comment]
I'm primarily concerned with this kind of code:

```js
try {
  await doSomething()
} catch (err) {
  if (err.name === 'AbortError' || err.code === 'UND_ERR_ABORTED') {
  } else {
  }
}

```

**Comment by mcollina** [comment]
I don't mind either way.

**Comment by Ethan-Arrowood** [comment]
https://nodejs.org/api/errors.html#errors_abort_err was only added in v15 so we probably need to support both for now?
