### ISSUE TITLE
Not matching mocks are hard to debug

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#787]
## Bug Description

When a mock does not match (and net.connect is disabled), we error with a generic:

```
Unable to find mock dispatch and real dispatches are disabled for XYZ
```

However, we are likely setting up a mock for this URL - so there might be something that is not matching.

We should provide better error messages.

**Comment by mcollina** [comment]
cc @jonnydgreen

**Comment by jonnydgreen** [comment]
Makes sense, I can get started on a solution for this this evening for improving the mock errors!

**Comment by mcollina** [comment]
Thanks!

**Comment by jonnydgreen** [comment]
No problem at all! :)

**Comment by jonnydgreen** [comment]
Thinking of something like this which indicates exactly what the issue is and offers a solution as well:

```js
...
if (netConnect === false) {
  throw new MockNotMatchedError(`Request to ${origin} does not match any registered mock dispatches and net.connect is disabled. Please register a mock dispatch for this origin.`)
}
throw new MockNotMatchedError(`Request to ${origin} does not match any registered mock dispatches and net.connect is not enabled for this origin. Please register a mock dispatch for this origin or add this origin to your MockAgent.enableNetConnect matchers.`)
...
```

What do you reckon?

**Comment by mcollina** [comment]
It would work but it needs to be more nuanced. For example, express that there was a body or header or XYZ mismatch.

**Comment by jonnydgreen** [comment]
Ah okay, no problem - I'll get right on that and try and think of other situations that need more info as well!
