### ISSUE TITLE
Mocks should match headers

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#791]
Currently we do not match the headers when doing intercepts:

```js
mockPool.intercept({
  path: '/foo',
  method: 'GET',
  headers: {
     'User-Agent': 'undici' // requests with different or missing user agent would not be matched.
  }
}).reply(200, 'foo')
````

I would only consider an header as a requirement if included. So passing (or not passing) an `Accept` header would not make a difference for this interceptor.

**Comment by mcollina** [comment]
cc @jonnydgreen

**Comment by mcollina** [comment]
@ronag this must be fixed before the v4 release.

**Comment by jonnydgreen** [comment]
I'll get a PR sorted for this this weekend :)
