### ISSUE TITLE
SSE 4.2

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#801]
I notice in llhttp.c there are some `__SSE4_2__` guards. Is this something that our `msimd128` build is able to enable?

**Comment by ronag** [comment]
@dnlup

**Comment by dnlup** [comment]
I am not sure. From quick research:

* https://github.com/WebAssembly/simd/blob/main/proposals/simd/ImplementationStatus.md
* https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile
* https://github.com/linbox-team/fflas-ffpack/issues/184

I think it should be something that is enabled by the compiler if it's supported on the target platform. It is still not 100% clear to me if wasm has full support, and if just the `msimd128` flag is sufficient.
