### ISSUE TITLE
Response body ends prematurely

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#803]
~~Haven't had time to check but I suspect we might have a problem with body sizes larger than 31 bit.~~

undici will complete without error before reading entire response body.

**Comment by ronag** [comment]
It just works. This might be a wasm thing.

**Comment by dnlup** [comment]
[Inspecting](https://github.com/nodejs/undici/blob/main/deps/llhttp/include/llhttp.h#L30) `llhttp` I see content-length is an unsigned int of 64 bits. That should exclude some issues in the parser native side.

**Comment by indutny** [comment]
Isn't wasm memory space limited to 2gb? I think you need to split up the data before passing it into llhttp.

**Comment by ronag** [comment]
The data is split?

**Comment by indutny** [comment]
Looking. Completely unrelated, you should probably use `parseInt(..., 10)` instead of just `parseInt()` (Yes, JS is weird: `parseInt('0x1f') === 0x1f`)

**Comment by indutny** [comment]
llhttp itself appears to work fine: https://gist.github.com/indutny/818e4428eeadb17bb541a668e653e2a9 . Whenever I execute it - I get back exactly the same amount of bytes that passed to execute.

I strongly suspect that it is either an issue with wasm build or the wrapping around it.

**Comment by ronag** [comment]
@indutny Thanks for confirming. Much appreciated.

**Comment by ronag** [comment]
@indutny I ported your test into our WebASsembly and was able to reproduce the issue: https://gist.github.com/ronag/3e316e78931f8b49f1138460a77a258a

**Comment by indutny** [comment]
Added a bunch of logging and looks like `uint64_t` subtraction doesn't work:

```
parser.content_length=0x100028c68 on_body_len=65536 read_total=1605238784
parser.content_length=0x100018c68 on_body_len=65536 read_total=1605304320
parser.content_length=0x100008c68 on_body_len=65536 read_total=1605369856
parser.content_length=0x0 on_body_len=35944 read_total=1605405800
```

As you might have guessed 35944 is `0x8c68` in hex. So it subtracts 0x8c68 from 0x100008c68 and gets 0x0.

**Comment by indutny** [comment]
FWIW, here's the code that I've added to `wasm_on_body` to extract this:

```js
      const _cl = new Uint32Array(llhttp.exports.memory.buffer, p + 8 * 4, 2);
      const _remaining = _cl[1] * 0x100000000 + _cl[0];
      console.log('parser.content_length=0x%s on_body_len=%d read_total=%d', _remaining.toString(16), len, _total += len);
```

**Comment by indutny** [comment]
What's the best way to view the contents of the wasm file?

**Comment by indutny** [comment]
Sounds like `wasm2wat`

**Comment by ronag** [comment]
> What's the best way to view the contents of the wasm file?

Maybe https://webassembly.studio?

**Comment by indutny** [comment]
I know what's going on. Could you find `s_n_llhttp__internal__n_consume_content_length` replace `size_t`s with `uint64_t`s right after it and try recompiling and running the test?

**Comment by ronag** [comment]
hm, didnt seem to help.

**Comment by ronag** [comment]
That fixed it!

**Comment by indutny** [comment]
Alright, working on the real fix. Thanks for trying it.

**Comment by indutny** [comment]
Fix: https://github.com/nodejs/llparse/pull/44 .

@ronag could you try `llhttp.c` from the attachment and see if it still works?

[llhttp.c.zip](https://github.com/nodejs/undici/files/6463901/llhttp.c.zip)

**Comment by ronag** [comment]
> Fix: [nodejs/llparse#44](https://github.com/nodejs/llparse/pull/44) .
> 
> @ronag could you try `llhttp.c` from the attachment and see if it still works?
> 
> [llhttp.c.zip](https://github.com/nodejs/undici/files/6463901/llhttp.c.zip)

All good!

**Comment by dnlup** [comment]
Thank you for the help @indutny !

**Comment by indutny** [comment]
No worries. Always glad to fix my own mess ups 😂

**Comment by indutny** [comment]
Created a new release: https://github.com/nodejs/llhttp/releases/tag/release%2Fv6.0.2
