### ISSUE TITLE
Response latency of express server is increasing when using undici as http client

### ISSUE THREAD

**Issue by smehta91** [nodejs/undici#808]
## Bug Description

I am trying to integrate undici as HTTP client on my express project. But after integrating we found that server response latency has increased drastically. Could someone please review what I am doing wrong here https://github.com/smehta91/node-GQL-flash/pull/1/files.

**Comment by mcollina** [comment]
You are using a single `Client` to send multiple HTTP requests, while a single Client wraps a single socket. You need to use a `Pool` or an `Agent`, so that you can use multiple sockets.

I would recommend to update to v4.0.0-rc.4 and use the top-level `request()` method.
