### ISSUE TITLE
Invalid body doesn't error

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#810]
```js
test('https://github.com/mcollina/undici/issues/807', (t) => {
  t.plan(2)

  const server = net.createServer(socket => {
    socket.write('HTTP/1.1 200 OK\r\n')
    socket.write('Content-Length: 1\r\n\r\n')
    socket.write('11111\r\n')
  })
  t.teardown(server.close.bind(server))

  server.listen(0, () => {
    const client = new Client(`http://localhost:${server.address().port}`)
    t.teardown(client.destroy.bind(client))

    client.request({
      path: '/',
      method: 'GET'
    }, (err, data) => {
      t.error(err)
      data.body.resume().on('end', () => {
        t.fail()
      })
    })
  })
})
```

I think the above request should fail. The body is longer than content-length.

**Comment by ronag** [comment]
@indutny isn't llhttp a bit too lenient here?

**Comment by mcollina** [comment]
> I think the above request should fail. The body is longer than content-length.

I think we should handle this ourselves.

**Comment by ronag** [comment]
> > I think the above request should fail. The body is longer than content-length.
> 
> I think we should handle this ourselves.

Why? Then we need to start parsing packages in undici? I think this makes more sense to handle in llhttp.

**Comment by mcollina** [comment]
Why this needs to go in Undici and not on our users code?

Node http does not handle this either.

**Comment by ronag** [comment]
> Why this needs to go in Undici and not on our users code?

Because users can't detect it.

**Comment by mcollina** [comment]
I think we should handle this here and it should not be part of llhttp.

**Comment by ronag** [comment]
> I think we should handle this here and it should not be part of llhttp.

I don't see why? It would be much easier to handle in llhttp. I'm unsure if we can handle it in undici in a reasonable way... if we get a message complete we somehow have to parse the last buffer passed to `execute` and figure out where in that buffer the relevant data is (i.e. on packet can contain multiple full messages).

**Comment by ronag** [comment]
Also in this case we actually need llhttp to parse the body until the termination in order to avoid corrupting other requests in the packet.

**Comment by mcollina** [comment]
> Also in this case we actually need llhttp to parse the body until the end of request (i.e. not just until content-length) in order to avoid corrupting other requests in the packet.

This is the reason why it should stay out of llhttp. We can handle it in Undici.

**Comment by ronag** [comment]
> This is the reason why it should stay out of llhttp. We can handle it in Undici.

But I don't see how we could handle it in undici. We pass `execute(buf)` where buf can contain multiple requests. There is nothing we can do in undici to handle it in that case.

**Comment by mcollina** [comment]
I mean, we could just throw in https://github.com/nodejs/undici/blob/main/lib/client.js#L814 if the content-length mismatch.

**Comment by ronag** [comment]
> I mean, we could just throw in https://github.com/nodejs/undici/blob/main/lib/client.js#L814 if the content-length mismatch.

One of us is missing something. If you look at my example above, as far as undici knows everything went well, since message complete is called as soon as content-length has been satisfied, i.e. it's not possible to catch whether there was extra data afterwards.

**Comment by mcollina** [comment]
> One of us is missing something. Not sure which one of us 😅. If you look at my example above, as far as undici knows everything went well, since message complete is called as soon as content-length has been satisfied, i.e. it's not possible to catch whether there was extra data afterwards.

Ah I understand the problem now.

I'll think about it for a bit.

**Comment by mcollina** [comment]
Here is my understanding of this problem, in the same tick:

1. `execute` https://github.com/nodejs/undici/blob/7d563c0297e23a1275fa263e47aa0d3ac6fbb23e/lib/client.js#L526 end up calling `onMessageComplete`.
2. it reaches an if-block at the end https://github.com/nodejs/undici/blob/7d563c0297e23a1275fa263e47aa0d3ac6fbb23e/lib/client.js#L538-L546, where we error the socket.

I think the solution to this is to defer `onMessageComplete` by a microtick and channel that error up to the Request.. and call `onError` instead.

Would that work @ronag?

**Comment by ronag** [comment]
I don’t think we ever get an error from llhttp for that request so I’m not sure how it would help.

**Comment by ronag** [comment]
I’ll make a llhttp specific test case and we can see what happens.

**Comment by mcollina** [comment]
> I don’t think we ever get an error from llhttp for that request so I’m not sure how it would help.

I have verified and we get an error as the response from execute.

**Comment by ronag** [comment]
> > I don’t think we ever get an error from llhttp for that request so I’m not sure how it would help.
> 
> I have verified and we get an error as the response from execute.

I think the error is from the next request which fails. I think the point here is that the next request shouldn’t fail.

I still think this is best handled in llhttp. @indutny I think we need your input here.

**Comment by mcollina** [comment]
> I think the error is from the next request which fails. I think the point here is that the next request shouldn’t fail.

It happens in the same microtick.

Node.js handles it with the same underlying library, we should be able to do the same?

**Comment by ronag** [comment]
I’ll have to do some test with multiple messages in same packet. But won’t we lose significant performance this way? I’m not sure Node.js actually handles this case...

**Comment by ronag** [comment]
Yea. I think you might be right. I’ll open a Pr.

**Comment by indutny** [comment]
I actually get:

```
off=0 message begin
off=13 len=2 span[status]="OK"
off=17 len=14 span[header_field]="Content-Length"
off=33 len=1 span[header_value]="1"
off=38 headers complete status=200 v=1/1 flags=20 content_length=1
off=38 len=1 span[body]="1"
off=39 message complete
off=39 message begin
off=39 error code=8 reason="Expected HTTP/"
```

when running the response from the issue description through llhttp's test suite in both strict and loose modes. Does llhttp return the same error code in unidici?

**Comment by indutny** [comment]
Oh sorry, looks like I've missed quite a lot of discussion and my previous comment is irrelevant. Let me know if you still need my help.

**Comment by mcollina** [comment]
> Yea. I think you might be right. I’ll open a Pr.

how are you doing?

**Comment by ronag** [comment]
> > Yea. I think you might be right. I’ll open a Pr.
> 
> how are you doing?

I've been working non stop with deploying a new system into production. I think I can have a PR by end of week.

**Comment by ronag** [comment]
I haven't forgotten and will get to this as soon as I can.
