### ISSUE TITLE
Client.request() ingnores maxRedirections

### ISSUE THREAD

**Issue by Sfinx** [nodejs/undici#815]
Trying to make proxyfied requests with redirection support with no success. Seems like Client.request() just ignoring maxRedirections.

The following code having always 301 statusCode

```
 let client = new Client('https://youtube.com')
 const { statusCode, headers, body, trailers } = await client.request({
   method: 'GET',
   path: '/',
   maxRedirections: 10
 })
 console.log(statusCode)
```

**Comment by mcollina** [comment]
which version are you using?

**Comment by Sfinx** [comment]
Latest release from npm repo: 3.3.6

**Comment by ronag** [comment]
> Latest release from npm repo: 3.3.6

maxRedirects was added in 4.x

**Comment by ronag** [comment]
> Oh, README.md at front page do not reflect this. Sorry

Yea sorry about that. Currently front page follows master. We intend to change this but since we think (thought?) 4.x is soon to be released we didn't prioritise it.
