### ISSUE TITLE
Upload progress callback

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#820]
## This would solve...

Currently there's no way to get upload progress other than passing a stream. What if we're passing a 10MB Buffer instead? `Readable.from(buffer)` and we're storing it twice, which is unfortunate. So for an application that handles 100MB at a time we would need 200MB. 

## The implementation should look like...

```js
  client.dispatch({
    path: '/',
    method: 'GET',
    headers: {
      'x-foo': 'bar'
    }
  }, {
...
    onUploadProgress: (bytes) => {
      console.log(`onUploadProgress : ${bytes} bytes in total`)
    },
...
  })
```

## I have also considered...

Reading the state from the underlying socket. It's not so nice.

**Comment by mcollina** [comment]
This would be a nice feature to add! I think we should make the callback arrive to https://github.com/nodejs/undici/blob/b33dffa76d34d31a7ee189ac72c5ace5ef75e7f3/lib/client.js#L1423 and call it afterwards (if it's present).

**Comment by gabrielcaires** [comment]
Can I get it as my first contribution?

**Comment by Linkgoron** [comment]
I'll try to take a stab at this. Any opinions regarding `onBodyChunkSent` or `onDataSent` (as opposed to the current `onData`)? I'll have the callback receive two parameters, the current chunk size and the total bytes written so far.

**Comment by mcollina** [comment]
I prefer `onBodyChunkSent`

**Comment by mcollina** [comment]
@szmarczak I don’t understand why wrapping a buffer in a Readable would duplicate the memory used by the app.

**Comment by szmarczak** [comment]
> I don’t understand why wrapping a buffer in a Readable would duplicate the memory used by the app.

In order to receive progress events we would have to disable object mode.

**Comment by mcollina** [comment]
I'm questioning a bit the use case.. I would not allocate a massive buffer in the first place.

**Comment by BobNobrain** [comment]
Not sure if this is the right place to ask, but is there any way to track *download* progress? Especially when using `stream` method

**Comment by axetroy** [comment]
The documentation for `undici` is so bad that you can't even find any example for this.

**Comment by viocha** [comment]
Has this feature been implemented or abandoned?

**Comment by metcoder95** [comment]
This should be doable as an interceptor, contributions are welcomed
