### ISSUE TITLE
just a question. what about server implementation?

### ISSUE THREAD

**Issue by muturgan** [nodejs/undici#838]
Hi dear team!
Thank you for this outstanding lib.

At the article at nodejs.medium.com you say that "There are certain bugs or performance bottlenecks [of node.js core http module] we cannot fix without breaking the majority of our users — both on the client and server implementations as they are deeply tied".

Well I see that I can use undici to solve my "client tasks".

But what you can recommend to use to solve some "server tasks" and to "listen some http port"?

Thank you.

**Comment by mcollina** [comment]
One thing at a time. At some point we will approach the server implementation.
The client was in a dire shape and it required a massive refactoring - the server implementation is less problematic and more stable.

**Comment by muturgan** [comment]
I see. Thank you.
