### ISSUE TITLE
client cert support

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#842]
### Discussed in https://github.com/nodejs/undici/discussions/841

<div type='discussions-op-text'>

<sup>Originally posted by **ledmirage** June 18, 2021</sup>
hi there,

this is an exciting module and i am looking forward to use it in my project.

one question tho, i check thru the documentation, i do not seem to see it supports client cert yet, is this true?

my use case requires 2 way SSL verification, so client cert support is required.

thanks
Tse
</div>

**Comment by mcollina** [comment]
@ledmirage 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by joaopedrocampos** [comment]
Hey @mcollina! If possible I would love to try this fix. Could you please give some directions of how start it?

**Comment by mcollina** [comment]
I think you should start adding those TLS options to the `Client`.

**Comment by jarrodconnolly** [comment]
I think this may already be possible, though there might be a case for convenience options.

Client already takes an option of `tls` in its constructor that gets passed to `makeConnect()` and on into `tls.connect()` in here:
https://github.com/nodejs/undici/blob/main/lib/core/connect.js#L34

`tls.connect()` allows options from `tls.createSecureContext()` to be passed directly to it. This appears to be where the settings for client cert are.
https://nodejs.org/dist/latest-v14.x/docs/api/tls.html#tls_tls_connect_options_callback
https://nodejs.org/dist/latest-v14.x/docs/api/tls.html#tls_tls_createsecurecontext_options

Probably need a test case to check it out.
```
const client = new Client(`https://localhost:${server.address().port}`, {
      tls: {
        cert: fs.readFileSync(certFile),
        key: fs.readFileSync(keyFile),
        rejectUnauthorized: false
      }
    })
```
As well as setting `requestCert: true` for the server.

**Comment by mcollina** [comment]
It's probably just adding some documentation and use through the Agent.

**Comment by ledmirage** [comment]
@jjarrodconnolly nice, so it seems this is already supported, just need some documentation.
will definitely try it out when i have the chance.

**Comment by Lalem001** [comment]
On the topic of TLS documentation, the type definitions for Client, and by extension Pool, do not allow for `options.tls`. Just ran into this discrepancy.

Further, the expected contents of `options.connect`, which CAN have `tls` within, is not listed in the type definitions either.

**Comment by ronag** [comment]
> On the topic of TLS documentation, the type definitions for Client, and by extension Pool, do not allow for `options.tls`. Just ran into this discrepancy.
> 
> Further, the expected contents of `options.connect`, which CAN have `tls` within, is not listed in the type definitions either.

The content of `connect` is forwarded directly so:

```js
connect: {
  rejectUnauthorized: false
}
``` 

PR is welcome.

**Comment by RaisinTen** [comment]
The docs and tests have been added in https://github.com/nodejs/undici/pull/890. Is this safe to close now?
