### ISSUE TITLE
Unable to detect invalid body

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#849]
This is a bit of an edge case which is improbable but possible.

Right now we detect if a server responses with a body larger than the content-length header by waiting until we parse the next message in a packet. If the server response is large than content-length then we will if we are lucky get an http parsing error.

```
Content-Length = 1
[xTHISISNOTPARSABLE]
```

The parser will first parse `x` and then try to parse  `THISISNOTPARSABLE` as a http response and fail.

However, there are 2 cases where this can fail:

1. `THISISNOTPARSABLE` looks like a valid HTTP message header.
2. If the body is split into two packets `[x], [THISISNOTPARSABLE]`,

undici has currently no way to detect this failure and would give a false success on the `[x]` message.

**Comment by ronag** [comment]
@mcollina @indutny thoughts?

**Comment by mcollina** [comment]
We assume we can trust the server, so case 1 is not a problem. However it's the basis of any http injection attack when servers receive an http connection.

Case 2 is trickier. However I don't think we can do anything in this case, minus erroring the socket.

**Comment by indutny** [comment]
Isn't this expected behavior with HTTP, though? I'm not sure if something meaningful could be done without compromising the security.
