### ISSUE TITLE
Make `kConnect` a public option

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#852]
We currently have a private option called `kConnect` used internally. This could also be make public if we add docs and tests accordingly.

**Comment by joaolucasl** [comment]
Hey @ronag ! I'm willing to work on this. Can you give me more insight on what `kConnect ` is supposed to do overall? 

I tried to look at the code, but I couldn't pin what's the purpose

**Comment by szmarczak** [comment]
@ronag This also should allows us to create a compatibility layer with the native Node.js agents?
