### ISSUE TITLE
Using HTTP Proxy with undici.dispatch bug

### ISSUE THREAD

**Issue by NN-Binary** [nodejs/undici#861]
## Bug Description

When using Dispatch with an HTTP Proxy, it seems to always redirect to the same URL (tho the problem isn't linked to the "redirect"), HTTP proxy is valid as I can browse with it on Firefox, I've enabled verbosity on the HTTP Proxy Server and I notice it's not using CONNECT and instead try to do: 
request: https://en.wikipedia.org/ which could explain the problem.

The problem seems to only happen with HTTPS only URLs. If I query the same exact way (with the same HTTP Proxy) with path: https://ipinfo.io/ then it WORKS. Only HTTPS only websites that auto-upgrade such as Wikipedia do an infinite circular redirect.

## Reproducible By

```js



 // WORKING CODE (create test.js) and node test.js and you'll see the problem with the circular redirect (as long as you specify a valid HTTP Proxy URL)
 
import { Client  } from 'undici';

let ProxyURL = 'http://127.0.0.1:8080/'; // Valid HTTP proxy - working with all other codes (except Undici) and even Firefox.

let HTTPClient = new Client(ProxyURL, {
    pipelining: 64,
    maxCachedSessions: 500
});

HTTPClient.dispatch({
    path: 'https://www.wikipedia.org/',
    method: 'GET',
    headers: {
        'Host': 'www.wikipedia.org',
        'Accept-Language': 'en-US,en;q=0.5',
        'User-Agent': 'Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/3.0 Chrome/59.0.3017.125 Safari/537.36'
   }
}, {

    onConnect: () => {
        // Connected - Here we could use that, it means basically for sure the server at least is replying!
   },

    onError: (ErrorMessage) => { },

    onUpgrade: () => { },

    onHeaders: (HTTPStatusCode, ReceivedHTTPResponseHeaders) => {

        let Headers = {};
        for (let i=0; i < ReceivedHTTPResponseHeaders.length; i+=2) {
            Headers[ReceivedHTTPResponseHeaders[i].toString().toLowerCase()] = ReceivedHTTPResponseHeaders[i + 1].toString();
        }
    
        console.log(Headers) // HERE IS THE PROBLEM - JUST CHECK THIS LOG

        
        
    },

    onData: (ChunkAsBuffer) => { },

    onComplete: (trailers) => { }
});

    
```

## Expected Behavior

It should show the homepage of Wikipedia (each listener is empty in my example but if I check onHeaders, I'll be receive a Header location to the same URL (Circular redirects)

## Logs & Screenshots

Response Headers:
![Screenshot from 2021-07-03 16-14-51](https://user-images.githubusercontent.com/47809005/124347970-d887be80-dc19-11eb-9770-8b5f53bcd482.png)

See here, it goes again to the same URL (Location: https://www.wikipedia.org/)

## Environment

Node 15 (Linux) but I've tried with different versions, it's not really Node related

### Additional context

Thanks for the help, I'm having strong difficulties using an HTTP proxy for HTTPS requests with Dispatch, I didn't try other methods such as undici.request because all our codebase is already done with dispatch, I'm simply trying to implement request going through the HTTP proxy but it's been almost 2 days and I can't seem to make it work.|

I've been searching for hours proper examples on how to use an HTTP proxy with Undici for any type of request (http/https...) but it seems I can't find any example working with .dispatch

**Comment by mcollina** [comment]
Just to clarify: have you tried with `client.request()` and it works?

**Comment by mcollina** [comment]
Also, I don't think we have any control on the `location` header the server send back.

**Comment by NN-Binary** [comment]
> Just to clarify: have you tried with `client.request()` and it works?

I've tried so many things and I think it doesn't, the problem is probably due to the fact that it doesn't use CONNECT but GET.
The location header is solely an example, you can also put startpage.com instead of wikipedia it's also gonna do "infinite redirects".

**Comment by NN-Binary** [comment]
Anyone tested to reproduce the bug?

**Comment by mcollina** [comment]
I don't think so. Most of us do not use proxies, so it might take a while.

Which proxy should we use to test? Could you also provide a way we can use to reproduce the problem locally without any remote resources?

**Comment by szmarczak** [comment]
I'll give this a try.

**Comment by szmarczak** [comment]
I can't reproduce this. I set up a simple web proxy server like this:

```js
const http = require('http');
const https = require('https');

const protocols = {
    'http:': http.request,
    'https:': https.request
};

http.createServer((request, response) => {
   try {
        const url = new URL(request.url[0] === '/' ? request.url.slice(1) : request.url);
        const fn = protocols[url.protocol];

        const req = fn(url, {
            method: request.method
        }).on('response', res => {
            for (const header in res.headers) {
                response.setHeader(header, res.headers[header]);
            }

            res.pipe(response);
        });

        request.pipe(req);

        req.once('error', () => {
            request.destroy();
        });
   } catch (error) {
       response.statusCode = 500;
       response.end(error.stack);
   }
}).listen(8080);
```

and used your code 1:1 and there's no `location` header.

**Comment by NN-Binary** [comment]
Thank you so much @szmarczak! It indeed work yeah, I've tried to implement your solution with Dispatch and I can't seem to make it work, any way you can provide me a working example with Dispatch? Would be so helpful to be honest

**Comment by szmarczak** [comment]
I have literally run your Dispatch code and it worked flawlessly. I haven't modified anything.

**Comment by NN-Binary** [comment]
Oh wait, you mean you've run my code in "Reproducible By" and it works?

**Comment by szmarczak** [comment]
Correct.
