### ISSUE TITLE
SOCKS4/5 Proxy Support

### ISSUE THREAD

**Issue by NN-Binary** [nodejs/undici#862]
## This would solve...

Ability to connect through SOCKS proxy, potentially with the help of this library:
https://github.com/TooTallNate/node-socks-proxy-agent

## I have also considered...

I have been using HTTP proxy with Undici (well, failing but apparently support is established)

## Additional context

SOCKS5 Proxy support would be great as it's the most common type of proxies we can find.

**Comment by mcollina** [comment]
This would be great to add! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by NN-Binary** [comment]
Actually I wish but I can't even seem to make HTTP Proxy implementation for Undici work (hence my other posted issue) so I'm not sure I'm the right candidate :(

**Comment by NN-Binary** [comment]
I would however be willing to sponsor the dev of this feature if it could be done quickly, as we need it in my company and none of our developers seems competent enough to implement it.

**Comment by mcollina** [comment]
@NN-Binary reach out to my email, we can possibly arrange something.

**Comment by skidman123** [comment]
> ## This would solve...
> Ability to connect through SOCKS proxy, potentially with the help of this library: https://github.com/TooTallNate/node-socks-proxy-agent
> 
> ## I have also considered...
> I have been using HTTP proxy with Undici (well, failing but apparently support is established)
> 
> ## Additional context
> SOCKS5 Proxy support would be great as it's the most common type of proxies we can find.

SOCKS5 support would be so useful

**Comment by dzcpy** [comment]
Any updates?

**Comment by Max98532** [comment]
How to connect SOCKS5? 

**Error invalid protocol with ProxyAgent**

**Comment by Kaciras** [comment]
@Max98532 Undici currently does not support SOCKS proxy. I have created a module [fetch-socks](https://github.com/Kaciras/fetch-socks) for that.

**Comment by mcollina** [comment]
I think we can close this as an implementation already exists. Wdyt @ronag @KhafraDev?
