### ISSUE TITLE
Small issue with the links on the docs website

### ISSUE THREAD

**Issue by pedroapfilho** [nodejs/undici#868]
There's an error in the documentation.

Whenever it loads for the first time, it adds a `/#/` at the end of the URL, so it's like: `https://undici.nodejs.org/#/`

When you go to the homepage and click on the `Example` link, it actually goes to `https://undici.nodejs.org/#/benchmarks/benchmark.js`, which is actually a `404` page. It should go to `https://undici.nodejs.org/benchmarks/benchmark.js`

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by pedroapfilho** [comment]
That's the thing! I would love to! At first, I thought it would be an easy fix, but then I saw this: https://github.com/docsifyjs/docsify/issues/235 and realized that it might not be.

I'll think about it on the weekend, run the project locally and see if I can make these links go without the `/#/`

Thanks for the awesome work @mcollina, I'll submit the PR by the end of next week!

**Comment by mcollina** [comment]
Thanks!

**Comment by joaopedrocampos** [comment]
@mcollina should we close this issue now the PR is merged? 🙏
