### ISSUE TITLE
How to get remote IP address?

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#870]
Currently it's not possible to get the remote IP address. In terms of `dispatcher.dispatch`, we could pass the entire socket in `onConnect`. Dunno for other methods.

**Comment by ronag** [comment]
You need post dns resolve? You could resolve the url yourself and pass the ip to undici?

**Comment by ronag** [comment]
Might be easier to do after we fix https://github.com/nodejs/undici/issues/852

**Comment by szmarczak** [comment]
That would do :) Looks like this issue is a duplicate then.
