### ISSUE TITLE
Aborting the request before `onConnect`

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#871]
When using `dispatcher.dispatch` there is no other way than to abort the request when the socket gets connected.

**Comment by ronag** [comment]
Unfortunately no. Why do you need this?

**Comment by szmarczak** [comment]
It's just a Got test case. Probably someone will report this in the future. I'm okay with waiting for connection though.

Makes sense as the connections are `keep-alive`. If it was HTTP/2 then the session would be created anyway, so you're right.

**Comment by szmarczak** [comment]
Ah it seems this was a duplicate of #386
