### ISSUE TITLE
Advanced timeouts

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#874]
Something like https://github.com/sindresorhus/got/blob/c0b5346433996e761bca15cdb942f2b740264118/source/core/timed-out.ts#L14-L23

**Comment by ronag** [comment]
We currently have:

- `connectTimeout`
- `headersTimeout`
- `bodyTimeout`

What else do you need?

**Comment by szmarczak** [comment]
- `secureConnectTimeout`
- `lookupTimeout`
- `uploadTimeout` (but that would require `chunkify`, so probably will be implemented on Got side)

The first two can be done via #852 as well

**Comment by ronag** [comment]
I'll leave it open until we have #852

**Comment by ronag** [comment]
I think `connectTimeout` actually is `secureConnectTimeout` for https.

**Comment by ronag** [comment]
Also please note that `bodyTimeout` is only for receiving data from server, if the client has paused the response body then it won't fire.

**Comment by joshxyzhimself** [comment]
> We currently have:
> 
> * `connectTimeout`
> * `headersTimeout`
> * `bodyTimeout`
> 
> What else do you need?

Hi, are those also available at `options` part of `undici.request(url, options)`?

**Comment by ronag** [comment]
> > We currently have:
> > 
> > * `connectTimeout`
> > * `headersTimeout`
> > * `bodyTimeout`
> > 
> > What else do you need?
> 
> Hi, are those also available at `options` part of `undici.request(url, options)`?

- `headersTimeout`
- `bodyTimeout`

Are. We need a PR to fix the docs.

**Comment by joshxyzhimself** [comment]
> > > We currently have:
> > > 
> > > * `connectTimeout`
> > > * `headersTimeout`
> > > * `bodyTimeout`
> > > 
> > > What else do you need?
> > 
> > 
> > Hi, are those also available at `options` part of `undici.request(url, options)`?
> 
> * `headersTimeout`
> * `bodyTimeout`
> 
> Are. We need a PR to fix the docs.

Hi thank you, found them here

https://github.com/nodejs/undici/blob/494201af4d95a1d9dbf8727bf4847b858e9f4707/lib/core/request.js#L20-L21

Maybe types too? No `headersTimeout` and `bodyTimeout` here, correct?

https://github.com/nodejs/undici/blob/main/types/dispatcher.d.ts

**Comment by ronag** [comment]
@szmarczak this should be possible to implement now with a custom `connect`.

**Comment by jiajianrong** [comment]
> 

I see headersTimeout and bodyTimeout params here [https://github.com/nodejs/undici/blob/main/docs/api/Dispatcher.md#parameter-dispatchoptions]

but where to set the connectTimeout? And I want to know if the connectTimeout is the identical to the options.timeout param in http.request(url, options), as below:
https://nodejs.org/docs/latest-v12.x/api/http.html#http_http_request_url_options_callback

> timeout [<number>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type): A number specifying the socket timeout in milliseconds. This will set the timeout before the socket is connected.


Thank you.
