### ISSUE TITLE
Change socket localAddress

### ISSUE THREAD

**Issue by RuralDependencies** [nodejs/undici#882]
Hi

Anyway of changing the localAddress in the socket? NodeJS NET module allows it but I'm not exactly sure of where to do that in Undici?

I would like to change my source localAddress when connecting anywhere. 

> socket.connect(options[, connectListener])
> port <number> Required. Port the socket should connect to.
> host <string> Host the socket should connect to. Default: 'localhost'.
> localAddress <string> Local address the socket should connect from.
> localPort <number> Local port the socket should connect from.
> family <number>: Version of IP stack. Must be 4, 6, or 0. The value 0 indicates that both IPv4 and IPv6 addresses are allowed. Default: 0.
> hints <number> Optional dns.lookup() hints.
> lookup <Function> Custom lookup function. Default: dns.lookup().

NodeJS allows localAddress and even localPort.

**Comment by ronag** [comment]
Once this lands https://github.com/nodejs/undici/pull/881

**Comment by ronag** [comment]
Maybe once this lands https://github.com/nodejs/undici/pull/881****
