### ISSUE TITLE
Can `undici` handle compression internally?

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#883]
Something like a `decompress` option or so.

**Comment by mcollina** [comment]
Not at this point and I'm not even sure we should include it. I think this would be better handled by upper-layer libraries.

**Comment by szmarczak** [comment]
In regards to `fetch`, both Google Chrome and Firefox handle compression:

```
accept-encoding: gzip, deflate, br
```

I took a quick look at the spec and found nothing whether the compression should be handled or not, so I guess it's up to the implementation.

**Comment by ronag** [comment]
I think we should aim for compat with browser if the intent is to help isomorphic use.

**Comment by ronag** [comment]
@szmarczak I believe we have landed this. Close?

**Comment by dzcpy** [comment]
If it doesn't support it, is there any examples? gzip is very widely used but I have issues using undici to decode it.

**Comment by joshxyzhimself** [comment]
just noticed this too.

- it doesn't send any accept-encoding header.
- if user sets accept-encoding header, content-encoding exists in response but unused
