### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#893]
1. We can provide `connect` function or `connect` options but not both. Why?
2. Why `options.origin` and not `options.protocol`, `options.host` and `options.port`?
3. https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/request.js#L100-L127 these checks are missing in [RedirectHandler](https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/handler/redirect.js#L9)
4. Isn't https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/request.js#L130 moot because https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/core/request.js#L77
5. nitpick: https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/client.js#L1096 is slower by ~20% than `hostname[0] === '['`
6. https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/client.js#L1397-L1399 can be removed because ee64b39b97e5c39369ba66a54ff8dffaa8cd3339?
7. Can we avoid object allocation somehow? I think that should improve the performance as well. I mean https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/client.js#L1439-L1449
8. https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/lib/handler/redirect.js#L28 this reassures us that there is no body sent on redirect
9. I wonder if https://github.com/nodejs/undici/blob/aebbb5df86d5584b03102cb9198aad8abae421f1/index.js#L40-L65 can be removed

**Comment by mcollina** [comment]
The vast majority of those are PRs that could be sent 🙏❤️

**Comment by ronag** [comment]
1. Because if you provide a method you can save all params in the closure. Thus you don't need both.
2. Simplicity I guess...
3. PR
4. `host` is set through `processHeader`
5. PR
6. PR
7. I think V8 might handle that already. Don't think it makes much of a diff.
8. PR
9. Why you think that?

**Comment by joaopedrocampos** [comment]
Hey guys, decided to try the fixes that @ronag said that needed a PR, in this case, the items 3 and 5

- Change `startsWith` for `[0] ===`
- Create an util function that validates `handler` (I am not sure if the solution I did is the best but I think this is a better discussion for the PR)

PR: https://github.com/nodejs/undici/pull/894

**Comment by szmarczak** [comment]
> 9. Why you think that?

Sorry, my bad. I thought the code was duplicated somewhere else.

> 4. host is set through processHeader

Right 👍🏼 

> 1. Because if you provide a method you can save all params in the closure. Thus you don't need both.

Hmm... makes sense.

Thanks for answering!
