### ISSUE TITLE
Pool.request: Incorrect type definition

### ISSUE THREAD

**Issue by delvedor** [nodejs/undici#900]
## Bug Description

The `Dispatcher.request` `origin` property should not be required in `Client.request` and `Pool.request`.

## Reproducible By

```ts
import { Pool } from 'undici'

const pool = new Pool('http://localhost:3000')
const response = await pool.request({ method: 'GET', path: '/' }) // missing required ‘origin’ property
```

## Expected Behavior

`origin` should not be required. This can be easily solved with a `@ts-expect-error`. Once you do it, the code works as expected.
I’m not sure how to solve this, as every `.request` method extends its options from `Dispatcher.request`.
Any suggestion @Ethan-Arrowood?

**Comment by szmarczak** [comment]
I think we can close this now
