### ISSUE TITLE
HTTP2 Basic Support

### ISSUE THREAD

**Issue by RuralDependencies** [nodejs/undici#902]
Hi Hi!

The library would be awesome with even basic HTTP2 support (even without pushes), any lead date?

**Comment by mcollina** [comment]
It'll be done when it will be done.. you can contribute to it!

**Comment by vegerot** [comment]
Has this been added yet?  Currently I only get

```
Missing ALPN Protocol, expected `h2` to be available.
If this is a HTTP request: The server was not configured with the `allowHTTP1` option or a listener for the `unknownProtocol` event.
```

when trying to fetch from an H2 server

**Comment by metcoder95** [comment]
This has been added under the flag `allowH2`, see https://undici.nodejs.org/#/docs/api/Client

**Comment by vegerot** [comment]
So I have to import `Client` from undici?  There's no way to do it just with Node builtins?

**Comment by metcoder95** [comment]
Yes, it stills experimental so it is disabled by default, hence the requirement to construct a `Client` with Undici

**Comment by vegerot** [comment]
Got it.  Thank you!
