### ISSUE TITLE
BodyMixin types are missing

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#910]
## Bug Description

The typings for request.body were not updated with v4.3.x so TypeScript users can't use it easily yet.

Right now `response.body` is a Readable stream type only

## Reproducible By

file.ts:
```ts
import { request } from 'undici';

const { body } = await request('https://www.google.com')
const html = await body.text();
                        ^ Property 'text' does not exist on type 'Readable'
```

### Additional context

https://github.com/nodejs/undici/blob/main/types/dispatcher.d.ts#L101
https://github.com/nodejs/undici/blob/main/types/dispatcher.d.ts#L110

these should be the only places it needs updating although I haven't looked for other instances.

```ts
// from here: https://fetch.spec.whatwg.org/#body-mixin
interface BodyMixin {
  readonly body?: never // throws on node v16.6.0
  readonly bodyUsed: boolean
  arrayBuffer(): Promise<ArrayBuffer>
  blob(): Promise<import('buffer').Blob> // requires nodejs v15.7.0+
  formData(): Promise<never> // not implemented
  json(): Promise<any>
  text(): Promise<string>
}

// ...
{
  body: Readable & BodyMixin
}
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by KhafraDev** [comment]
I will try :)
