### ISSUE TITLE
Should `undici` support `username` and `password` in URL?

### ISSUE THREAD

**Issue by szmarczak** [nodejs/undici#913]
Node.js does, while ~~almost~~ all `fetch` implementations don't.

**Comment by mcollina** [comment]
I think they almost always cause security issues. But I'm also ok in adding support for them.

**Comment by szmarczak** [comment]
What about `fetch`? The support could be enabled but the spec says it's off by default.

**Comment by mcollina** [comment]
I would say we should follow the standard.
