### ISSUE TITLE
Update LICENSE with undici-fetch

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#916]
We've now borrowed stuff from undici-fetch and should update our license accordingly.

**Comment by ronag** [comment]
@Ethan-Arrowood would you mind opening a PR so it's done in a way you are happy with?

**Comment by Ethan-Arrowood** [comment]
Will do - thank you!

**Comment by ronag** [comment]
Fixed in https://github.com/nodejs/undici/pull/928
