### ISSUE TITLE
Add spec comments to Header class

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/undici#933]
It is useful to add comment references to the relevant parts of the whatwg fetch spec for the Headers class.

**Comment by ronag** [comment]
Also improve spec conformance, e.g. the errors we throw do not follow spec.

**Comment by ronag** [comment]
Is `fill` too loose in relation to the spec? i.e. does it allow "init" to be things that browser fetch wouldn't accept?

**Comment by Ethan-Arrowood** [comment]
Yes, flat array is not spec compliant; this was a point of discussion in the Node core PR. 

It helps us support the raw header list we get from other Node http things as well as being faster than other header implementations

**Comment by ronag** [comment]
Can we explicitly document the differences?

**Comment by ronag** [comment]
I’m thinking if we could expose the non spec compliant things as exported helper functions. That way we don’t violate the spec.

**Comment by Ethan-Arrowood** [comment]
Now that we are going complete spec compliant, I agree.

**Comment by ronag** [comment]
I did some of this but there is still work to be done.

**Comment by ronag** [comment]
Also should probably remove the undici errors with e.g. `TypeError`s.
