### ISSUE TITLE
 Fix Request.clone

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#945]
node-fetch tests fail and are therefore disabled

**Comment by ronag** [comment]
@szmarczak would you like to have a go at this one?

**Comment by szmarczak** [comment]
Sure, I'll do this after 2h. Working atm.

**Comment by szmarczak** [comment]
https://github.com/nodejs/node/issues/39758

**Comment by ronag** [comment]
@szmarczak Fixed `Response.clone` now we just need to sort `Request.clone`.
