### ISSUE TITLE
Make node-fetch tests contribute to coverage report

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#946]
How do make node-fetch tests to be included in coverage report?

**Comment by ronag** [comment]
@szmarczak @mcollina any experience with this?

**Comment by szmarczak** [comment]
No experience, but I'll see and let you know in a few mins.

**Comment by szmarczak** [comment]
https://github.com/istanbuljs/nyc#combining-reports-from-multiple-runs

**Comment by szmarczak** [comment]
I'll send a PR
