### ISSUE TITLE
mark resource timing

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#952]
Does node have something similar to https://w3c.github.io/resource-timing/#dfn-mark-resource-timing which would make sense to report fetch info to?

https://github.com/nodejs/undici/blob/3d2dbc72470af39c887bec8a7a432cee6f35a150/lib/fetch/index.js#L207-L213

@nodejs/diagnostics @addaleax @jasnell

**Comment by Qard** [comment]
This would connect to perf_hooks but will need some additions. We have `PerformanceEntry` but no ` PerformanceResourceTiming` yet. I don't think it would be difficult to add though. 🤔

**Comment by jasnell** [comment]
It's certainly doable. We'll need to expose a public API for publishing custom performance entries. Not unreasonable at all.

**Comment by RafaelGSS** [comment]
I have been working in a sketch https://github.com/RafaelGSS/node/pull/1

**Comment by jasnell** [comment]
I should be able to carve out some time next week to see what we need in node.js to make this a bit more feasible.

**Comment by RafaelGSS** [comment]
FYI I'm working on that in Node.js core. Planning a PR in Node.js in the next coming days.

**Comment by RafaelGSS** [comment]
@Trott I think this issue doesn't need to be closed because `undici.fetch` doesn't use it yet.

**Comment by Trott** [comment]
> @Trott I think this issue doesn't need to be closed because `undici.fetch` doesn't use it yet.

I didn't manually close it. It got closed because of the "Fixes:" line in the commit message. Feel free to re-open or whatever you want to do with it. I have no opinion at all.

**Comment by qm3ster** [comment]
RIP https://github.com/oven-sh/bun/issues/8867
