### ISSUE TITLE
What is a "byte sequence"

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#956]
I'm trying to figure out what to do in [this](https://github.com/nodejs/undici/blob/v4.4.2/lib/fetch/index.js#L300-L302) step.

> 7. If request’s body is a byte sequence, then set request’s body to the first return value of safely extracting request’s body.

It refers to a "byte sequence" however it is unclear for me what that means in javascript.

If you look at https://fetch.spec.whatwg.org/#concept-bodyinit-extract you can see that it defines byte sequence separately from `BufferSource` and `scalar value string`. So my understanding is that it's neither a buffer nor a string, but then what is it?

**Comment by ronag** [comment]
@szmarczak @dominic @addaleax @szmarczak

**Comment by addaleax** [comment]
I think it’s just the abstract concept of a byte sequence, not necessarily tied to any specific implementation. For example, it could be backed by a ReadableStream or a Buffer.

**Comment by szmarczak** [comment]
I agree with @addaleax
