### ISSUE TITLE
is content-length match after decoding sufficient?

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#960]
Is a little unclear if we should check content-length against encoded or decoded byte length (or either?)

Refs: https://github.com/whatwg/fetch/issues/716

**Comment by szmarczak** [comment]
Decoded I think

**Comment by mcollina** [comment]
I'm unsure, I think some tests against nginx and co are needed. 
However, I would think Content-Length what is being sent on the wire.

In https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

> The content-coding is a characteristic of the entity identified by the Request-URI. Typically, the entity-body is stored with this encoding and is only decoded before rendering or analogous usage.

Note that it would not be possible to compute the content-length without decoding if a zipped file is stored on disk.

**Comment by ronag** [comment]
> However, I would think Content-Length what is being sent on the wire.

I think so as well. If strictly following the HTTP spec. Just not sure what chrome does.

**Comment by mcollina** [comment]
let's assume spec and iterate!

**Comment by szmarczak** [comment]
My assumption was wrong, @mcollina is right. I just checked and Chrome leaves `content-length` as it is:

> Content-Length what is being sent on the wire.

:+1:
