### ISSUE TITLE
Implement FormData parsing

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#964]
In https://github.com/nodejs/undici/pull/961 we add `FormData` parsing through https://www.npmjs.com/package/dicer. I would prefer if we could avoid this dependency.

**Comment by szmarczak** [comment]
Sorry I'm unable to help with this one, I'd love to but constantly either I'm working or solving other open source issues :(

**Comment by ronag** [comment]
Maybe @octet-stream?

**Comment by octet-stream** [comment]
Sorry, but I don't think I have enough free time to get dive into this :<
