### ISSUE TITLE
mac 16 CI is flaky

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#965]
Is this a problem on our side or GitHub actions?

**Comment by szmarczak** [comment]
Looks a race condition. https://node-tap.org/docs/api/parallel-tests/

**Comment by ronag** [comment]
Why only on mac 16?

**Comment by szmarczak** [comment]
No idea. We had these issues in Got as well. IIRC marking some tests to run serially fixed the issue.

**Comment by ronag** [comment]
I suspect that the coverage job runs much slower on Mac 16 for some reason and this is just a case of timeout. I've disabled coverage on CI.

**Comment by szmarczak** [comment]
Still flaky
