### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#968]
This is just a fun thought that I don't personally plan to spend much time on.

It should be in theory possible to run undici in the browser (especially the fetch parts) if one creates a `BrowserClient` implementation based on e.g. XMLHTTPRequest. That way we could in theory even act as an alternative to e.g. https://github.com/github/fetch fetch polyfill.

We have implemented some of the web stuff from the spec and there a clear TODOs ([examples](https://github.com/nodejs/undici/issues/958)) with references to spec for the missing parts. There are a few node specific stuff we make use of (e.g. Buffer) but those should be somewhat trivial to either replace or polyfill.

**Comment by ronag** [comment]
@JakeChampion just a friendly ping in case there is any room for collaboration with https://github.com/github/fetch.

**Comment by ronag** [comment]
A quick link to our work https://github.com/nodejs/undici/tree/main/lib/fetch

**Comment by jimmywarting** [comment]
Sounds fun but also pointless, XMLHttpRequest don't have any good streaming support 

also you would be importing a browserified version of `node:http` that includes `buffer`, `readable-stream` and many other other small sub packages like `inherit`. that alone is some few 170kb of [code](https://github.com/cross-js/cross-js) the amount code would be large

pretty much all browser ships fetch now days. so what would be the point?
