### ISSUE TITLE
Node extensions

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#975]
What extension to the spec (for a "non-strict" mode) do we believe makes sense for usage in node?

Some things I can think of:

- Accept `AsyncIterable` (including `stream.Readable`) and `Iterable` as `Request` body. (https://github.com/whatwg/fetch/issues/1291)
- Accept flat raw headers array for `Headers`. 
- Accept `EventEmitter` as `AbortSignal`.

**Comment by ronag** [comment]
@Ethan-Arrowood @szmarczak

**Comment by szmarczak** [comment]
> Accept AsyncIterable (including stream.Readable) and Iterable as Request body.

:+1:

> Accept flat raw headers array for Headers.

Why?

> Accept EventEmitter as AbortSignal.

Why?

**Comment by ronag** [comment]
> > Accept AsyncIterable (including stream.Readable) and Iterable as Request body.
> 
> 👍
> 
> > Accept flat raw headers array for Headers.
 
Performance

> > Accept EventEmitter as AbortSignal.
> 
> Why?

Not sure. A lot of node libs seems to do this. Maybe support for node versions without AbortSignal?

**Comment by szmarczak** [comment]
> Performance

Have you benchmarked this already? I don't think this will matter given the overhead...

> Maybe support for node versions without AbortSignal?

Isn't fetch already Node.js 16+?

**Comment by ronag** [comment]
> > Performance
> 
> Have you benchmarked this already? I don't think this will matter given the overhead...

@Ethan-Arrowood Did some work on this. It's mostly for the cases where the headers are already in that format, e.g. node core `rawHeaders` or headers from undici core api. So I guess it's not just perf it's also compat.

> 
> > Maybe support for node versions without AbortSignal?
> 
> Isn't fetch already Node.js 16+?

**Comment by szmarczak** [comment]
> It's mostly for the cases where the headers are already in that format

:+1:
