### ISSUE TITLE
CI fail Windows 16.7

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#979]
We have a failing test with Node 16.7 on Windows.

`destroy socket abruptly`

**Comment by ronag** [comment]
@szmarczak

**Comment by szmarczak** [comment]
Will check this now

**Comment by ronag** [comment]
I've disabled to test on win32 for now

**Comment by szmarczak** [comment]
```js
    if (process.platform === 'win32') {
      setTimeout(() => {
        setTimeout(() => {
          socket.destroy()
        })
      })
    } else {
      setImmediate(() => {
        socket.destroy()
      })
    }
```

You can try the fix above. This is definitely related to libuv and I'm not good at libuv (or any kernel-related) things... `setTimeout` just delays the function to be called at the beginning of the next event loop. Twice - as I understand it, that means the code is executed after two event loop iterations.

Or you can do `{ skip: process.platform === 'win32' }`.
