### ISSUE TITLE
toUSVString

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#981]
I notice node core is using `toUSVString`. I believe we should do the same. However, it's unclear what it's implementation is.... https://github.com/nodejs/node/blob/master/lib/internal/url.js#L144-L152

Also a little unclear in which places exactly we need to use it. Everywhere where we do `String(value)`?

**Comment by ronag** [comment]
@szmarczak

**Comment by szmarczak** [comment]
`process.binding('url').toUSVString` ?

**Comment by szmarczak** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/USVString

**Comment by ronag** [comment]
> `process.binding('url').toUSVString` ?

I think process.binding is deprecated
