### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#982]
We need to reach much higher on code coverage:

- [x] body.js
- [ ] file.js
- [ ] formdata.js
- [ ] headers.js
- [ ] index.js
- [ ] request.js
- [ ] response.js
- [ ] util.js

To see what lines need coverage just run `npm run coverage`

**Comment by ronag** [comment]
@Ethan-Arrowood if you have time could you take a look at headers and formdata?

**Comment by ronag** [comment]
https://app.codecov.io/gh/nodejs/undici

**Comment by Ethan-Arrowood** [comment]
Yep will do
