### ISSUE TITLE
RangeError: WebAssembly.Instance(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by janpio** [nodejs/undici#988]
## Bug Description

We have been happy users of `undici` at @prisma for quite a while and finally found the time to upgrade to 4.x. Fundamentally everything seems to be working fine (after making sure the `llhttp` binaries are copied into our builds as well), but a specific test suite is failing with this error:

```
    RangeError: WebAssembly.Instance(): Out of memory: wasm memory

      at Object.<anonymous> (../../node_modules/.pnpm/undici@4.4.5/node_modules/undici/lib/client.js:400:16)
      at Object.<anonymous> (../../node_modules/.pnpm/undici@4.4.5/node_modules/undici/index.js:3:16)
```

https://github.com/prisma/prisma/pull/8823
https://github.com/prisma/prisma/runs/3373629489#step:9:1284

It also does not fail all the time on all systems, but only reliably on GH Actions (it's fine locally or on BuildKite for example).

Any idea what we should look at here?

## Reproducible By

Our test suite on GH Actions is the only reproduction.

## Expected Behavior

No failure.

## Logs & Screenshots

See links above

## Environment

Ubuntu 20.04, Node 12.22.5 or Node 14.17.5

### Additional context

Possibly interesting: In the failing test, `undici` should not even really be used as we have two implementations: An Prisma Engine binary that starts a webserver which we talk to with `undici`, and one where we have a Node-API library which we talk to directly, no webserver and `undici` involved - and _THAT_ is the test run that is failing (which makes not sense!?).

**Comment by ronag** [comment]
@janpio Do you think you could try https://github.com/nodejs/undici/pull/989?

**Comment by janpio** [comment]
I did, and it indeed seems to solve the problem on our side!
https://github.com/prisma/prisma/pull/8831

Awesome!

(Although I am still confused why only the code path that does _not_ really use undici runs into this... something smells funny there.)
