### ISSUE TITLE
Fetch body streams are not full duplex

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#990]
The fetch spec doesn't seem to allow reading the response before the full request body has been transmitted. We are in violation with the spec here since we do allow this. Also we allow aborting the request body if the full response body has been read.

I think we should probably keep our current behavior. There doesn't seem any specific reason to why the fetch spec wouldn't allow it other than lack of resources. Just needs to add a section in docs describing it.

Refs: https://github.com/whatwg/fetch/issues/1254

**Comment by szmarczak** [comment]
I think it's full-duplex? https://github.com/whatwg/fetch/commit/3a41b6f04996d4aac13ecad5b38635827dcd0df3 https://github.com/web-platform-tests/wpt/issues/7693
