### ISSUE TITLE
Fetch and GC

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#998]
The fetch standard describes [quite aggressive garbage collection expectations](https://fetch.spec.whatwg.org/#garbage-collection) which are not possible to implement in pure JS. ~~I believe we would need to have access to the actual reference count and not simply wait for GC to occur like we do atm through `FinalizationRegistry`.~~

We should at least document this discrepancy.

I'm not even sure if this is possible to do in native code (@addaleax)?

**Comment by addaleax** [comment]
@ronag What’s the “actual reference count” here?

In native code, yes, I think this is possible, but since we’re talking about a mostly-JS implementation of fetch, that feels anything but trivial to implement.

**Comment by ronag** [comment]
> @ronag What’s the “actual reference count” here?

Whether or not the object is observable or not.

> In native code, yes, I think this is possible, but since we’re talking about a mostly-JS implementation of fetch, that feels anything but trivial to implement.

Yea, I was just assuming native code. We could maybe do it "properly" if/when we land fetch in core.

**Comment by addaleax** [comment]
> > @ronag What’s the “actual reference count” here?
> 
> Whether or not the object is observable or not.

But that’s what GC/FinalizationRegistry tells you, no?

I think, properly done, this does work without native code – e.g. you could detect when `res.body` is GC’ed, and make the assumption that nothing will start reading from it at that point if it hasn’t already.

**Comment by ronag** [comment]
> But that’s what GC/FinalizationRegistry tells you, no?

Yes, but it does it lazily. In theory it might never run or it could take a very long time before it runs. The way I read the fetch spec it's expected to release the connection pretty soon after it's no longer possible to observe it.

**Comment by ronag** [comment]
e.g. you might start a request every second, not consume the response body, the gc doesn't fire because memory pressure is low and you run out out socket handles or something.

**Comment by ronag** [comment]
@jasnell I think you might end up with similar requirements for `File`.

**Comment by ronag** [comment]
I don't know if `WeakRef.deref` returns undefined once an object is GC:d or when it's no longer observable. I would assume the former so that doesn't help either.

**Comment by addaleax** [comment]
> > But that’s what GC/FinalizationRegistry tells you, no?
> 
> Yes, but it does it lazily and in an indeterministic fashion. In theory it might never run or it could take a very long time before it runs. 

I mean, yeah, but that’s also true for any GC tracking – there’s no reason to expect that tracking on the native side would give us earlier or more reliable results.

> The way I read the fetch spec it's expected to release the connection pretty soon after it's no longer possible to observe it.

> e.g. you might start a request every second, not consume the response body (which is ok according to spec), the gc doesn't fire because memory pressure is low and you run out of socket handles or something (even you don't run out of handles you are not able to re-use connections).

Yeah, I understand the concern – but I don’t see a way to do that which doesn’t rely on GC, although I’m happy to be proven wrong there, of course. :) GC timing works a little differently in browsers anyway, I think, because rendering timing is more predictable and thus idle periods are as well.



> I don't know if `WeakRef.deref` returns undefined once an object is GC:d or when it's no longer observable. I would assume the former so that doesn't help either.

I assume the same thing, but either way, the two situations aren’t actually distinguishable in practice I would say.

**Comment by ronag** [comment]
> Yeah, I understand the concern – but I don’t see a way to do that which doesn’t rely on GC, although I’m happy to be proven wrong there, of course. :) GC timing works a little differently in browsers anyway, I think, because rendering timing is more predictable and thus idle periods are as well.

I don't see a solution either... do we have any possibility to tune the GC in node to better account for this? As it is now I think implementing fetch is not quite possible without adding the "you must consume or cancel the response body" constraints.

**Comment by addaleax** [comment]
> I don't see a solution either... do we have any possibility to tune the GC in node to better account for this? 

We’ve had conversations about that, but never came to a conclusion about *how* to do that. Browsers have predictable scheduling, Node.js doesn’t, and events can always happen at any time and there isn’t really something we can do about that in general.

> As it is now I think implementing fetch is not quite possible without adding the "you must consume or cancel the response body" constraints.

To be fair – the spec indicates that the user agent *may* terminate an ongoing fetch, not that it *must*. I would still consider an implementation that doesn’t do any GC tracking at all fully spec-compliant.

**Comment by ronag** [comment]
> To be fair – the spec indicates that the user agent may terminate an ongoing fetch, not that it must. I would still consider an implementation that doesn’t do any GC tracking at all fully spec-compliant.

I guess that's true. Though I'm not sure that's how users would use it (unless we add an explicit note about it).
